### ISSUE TITLE
click event can't resolve series for bar charts

### ISSUE THREAD

**Issue by PPPW** [plotly/plotly.js#1797] opened 2017-06-19 15:32 UTC
Dear Plotly.js,
For bar charts with multiple series, e.g., this one:
https://codepen.io/plotly/pen/79bf01113db127f234e92e5c535dbc43?editors=1011

I define the click event by using: 
`myPlot.on('plotly_click', function(data) { console.log(data); })`

Then if I click on a bar, both series are returned in the "points" of the event data. For example, if I click on the blue bar of "giraffes", in the event data, both blue and orange bars are there. Is it possible to make the events sensitive to series? Same for the stacked bar charts. Thank you! 

Best,

**Comment by etpinard** [comment] 2017-06-19 15:51
duplicate of https://github.com/plotly/plotly.js/issues/965

**Closed by etpinard** 2017-06-19 15:51 UTC
