### ISSUE TITLE
Sunburst long text is rotated when it is not fit within the sector

### ISSUE THREAD

**Issue by archmoj** [plotly/plotly.js#4381] opened 2019-11-22 19:52 UTC
[demo](https://codepen.io/MojtabaSamimi/pen/ExxJLKy?editors=0010)

**Comment by archmoj** [comment] 2019-12-06 18:38
Also please note that this is NOT a problem for `pie`. [Demo](https://codepen.io/MojtabaSamimi/pen/VwYvPKP?editors=0010)

**Comment by gvwilson** [comment] 2024-06-14 12:53
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-14 12:53 UTC
Labels: type: bug
