### ISSUE TITLE
[Feature Request] Show errors as absolute values

### ISSUE THREAD

**Issue by Batalex** [plotly/plotly.js#4067] opened 2019-07-22 12:42 UTC
Hi,

Errors in Plotly are shown upon hover as relative values. For example, in the following graph

```
data = {
    "type": "scatter",
    "y": [10, 11],
    "error_y": {
        "type": "data",
        "array": [1, 2],
        "arrayminus": [1, 2]
    }
}
```

the first data point is displayed as `10 +1 /-1`.

It would be interesting for some cases to display the absolute values as an interval `10 (9, 11)`. For example when plotting odds ratios it is preferable to read the confidence interval in a straightforward way rather than showing the spread. Even with `hovertemplate` I could not figure out how to properly set this behavior.

I think it could implemented with a new "display" key in `error_x`|`error_y` with the values "relative" (default) or "absolute"

**Comment by gvwilson** [comment] 2024-06-14 12:47
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-14 12:47 UTC
Labels: type: feature
