### ISSUE TITLE
Low performance of histogram relayout [drawing.pointStyle, drawing.singlePointStyle]

### ISSUE THREAD

**Issue by DaanyWaay** [plotly/plotly.js#4435] opened 2019-12-20 06:08 UTC
I prepared 2 codepens with almost identical data, with just one difference: the second plot has 2 extra bars and much wider X range:
A. https://codepen.io/DaanyWaay/pen/mddgrvo
B. https://codepen.io/DaanyWaay/pen/MWYpOjw

In A, the drawing.pointStyle finds 151 paths and call drawing.singlePointStyle for each of them.
In B, drawing.pointStyle finds 1751 paths and call drawing.singlePointStyle for each of them.

Where this difference comes from? I just added 10 more points to the data.

**Comment by etpinard** [comment] 2019-12-20 22:36
Thanks for pointing this out. The 151 and 1751 lengths you're mentioning correspond to the number of `gd.calcdata` items generated in 

https://github.com/plotly/plotly.js/blob/571ce6b5c87c667c1d2f278abdf5a9ecaa00c2ff/src/traces/histogram/calc.js#L160-L182

At the moment, we (unfortunately) draw all of them (you can see that by calling `d3.selectAll('.point').size()` in the console), so yeah we should try to optimize things in scenarios like the one you presented.

**Comment by gvwilson** [comment] 2024-06-14 12:54
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-14 12:54 UTC
Labels: type: performance
