### ISSUE TITLE
Alternating tick colors on axis

### ISSUE THREAD

**Issue by greengumby** [plotly/plotly.js#4281] opened 2019-10-17 09:44 UTC
Hi,

Wondering if there is a way to alternate the colors of the individual ticks on the axis?

Cheers,

**Comment by etpinard** [comment] 2019-10-25 20:00
Here's one way to do this: https://codepen.io/etpinard/pen/RwwgrwK?editors=1010

But perhaps we could extend the `tickfont` API to accept arrays e.g.:

```js
var layout = {
  xaxis: {
    tickfont: {
      color: ['red', 'blue']
    }
  }
}
```

which would imply alternating between red and blue.

**Comment by greengumby** [comment] 2019-10-28 03:04
Yes, extending the tickfont would be a clean approach that would benefit the product.

**Comment by gvwilson** [comment] 2024-06-14 12:51
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-14 12:51 UTC
Labels: type: feature
