### ISSUE TITLE
Prevent dragging legend out of plot div?

### ISSUE THREAD

**Issue by brian428** [plotly/plotly.js#2940] opened 2018-08-22 19:15 UTC
Currently, if a plot is editable and set to a constrained size, it's possible to drag the legend out of the plot div and permanently "lose" it. It would be nice if the drag behavior was changed to prevent this, or to provide a config option to turn on constraints on dragging the legend (or anything, really) out of the plot div.

**Comment by alexcjohnson** [comment] 2018-08-22 19:28
Can you demonstrate in a codepen? I can't figure out how to reproduce the effect you're describing. By default the margins expand to fit wherever you drag it, but if I turn that off (`margin.autoexpand: false`) it always seems to jump back onto the plot when I let go of it.
![legend-off-edge](https://user-images.githubusercontent.com/2678795/44485789-c1c65e00-a61f-11e8-96d7-0dade754d75e.gif)

**Comment by alexcjohnson** [comment] 2018-09-19 16:54
@brian428 we still have not been able to reproduce this. Can I close it or do you have a demonstration of the issue?

**Comment by alexcjohnson** [comment] 2018-09-20 19:57
Closing due to lack of activity. Feel free to reopen if anyone can reproduce.

**Closed by alexcjohnson** 2018-09-20 19:57 UTC
