### ISSUE TITLE
[feature request] Add Oceania as a geo scope

### ISSUE THREAD

**Issue by mbkupfer** [plotly/plotly.js#3823] opened 2019-04-30 21:43 UTC
How much effort would it be to add a new geo scope for 'Oceania'? 

Based on a google search, the layout longitude and latitude would be: 
```
lonaxis.range = [-54, 108]
lataxis.range = [114, -120]
```
This creates a significant inconvenience since it requires me to specify the axis ranges for every scope. I'd also be happy with the option of monkey patching the scope when creating my plotly build. Is that possible?

**Comment by etpinard** [comment] 2019-04-30 21:45
Duplicate of https://github.com/plotly/plotly.js/issues/3036

**Closed by etpinard** 2019-04-30 21:45 UTC

**Comment by etpinard** [comment] 2019-04-30 21:46
@mbkupfer see also https://github.com/etpinard/sane-topojson/pull/10

Picking "correct" longitude and latitude ranges for Oceania prove to be a little tricky, so that work staled.

**Comment by mbkupfer** [comment] 2019-04-30 21:56
My apologies for not noticing the duplicate. As for doing around type of monkey patch is there any way to define custom scopes to supplement the current scopes? This would be very useful

**Comment by etpinard** [comment] 2019-04-30 22:06
> My apologies for not noticing the duplicate

No worries! Searching through Github issue can be a pain. We understand.



> As for the monkey patch workaround, is there any way to define custom scopes to supplement the current scopes?

Not at the moment unfortunately.
