### ISSUE TITLE
ability to select text in a hover label / hover labels that don't disappear when you mouse over them

### ISSUE THREAD

**Issue by chriddyp** [plotly/plotly.js#2090] opened 2017-10-16 16:41 UTC
In some plots with rich hover text, you may want to highlight words in the hover label or click on links in the hover label. plotly.js removes the hover label as soon as your cursor leaves the point. Some other libraries allow you to mouse over the hover label itself by tracking directly from the marker to the lable. Here's an example:
![hover-links](https://user-images.githubusercontent.com/1280389/31624008-454f025e-b26f-11e7-8ed5-b3b432fb2b1f.gif)
And in comparison, here's our current behaviour:
![hover-links-plotly](https://user-images.githubusercontent.com/1280389/31624029-52607ce8-b26f-11e7-8d7e-56d9396f0541.gif)

**Comment by etpinard** [comment] 2017-10-16 16:56
Similar to and perhaps duplicate of https://github.com/plotly/plotly.js/issues/998

**Comment by etpinard** [comment] 2017-11-13 18:51
Merging with #998

**Closed by etpinard** 2017-11-13 18:51 UTC
