### ISSUE TITLE
auto move chart when adding data

### ISSUE THREAD

**Issue by Princezhm** [plotly/plotly.js#2084] opened 2017-10-12 13:41 UTC
Hello, 
using the [example](https://plot.ly/javascript/streaming/) of streaming data we can see that the chart is adding on the right side but on the left side everything is starting to squash, is there an easy way to follow the last added points of data? or move the selected range always to the left if it is pointing to the end?

Regards.

**Comment by etpinard** [comment] 2017-10-12 13:44
Duplicate of https://github.com/plotly/plotly.js/issues/387

**Closed by etpinard** 2017-10-12 13:44 UTC
