### ISSUE TITLE
Method plot shrink graphic in FF

### ISSUE THREAD

**Issue by tapinambur0508** [plotly/plotly.js#2446] opened 2018-03-06 12:48 UTC
Hello. I use plotly.js inside Angular Material mat-tab. In Chrome I have this result:
https://prnt.sc/inkxvg
In FF:
https://screenshots.firefox.com/6fybwYOQnymRjiEt/localhost.
Also graphics in Chrome not full-width
I use method plot to render graphic:
` Plotly.plot(element, data, laylot)`
where element is:
`const element = this.element.nativeElement`
Could you help me with it? Thank you

**Comment by etpinard** [comment] 2018-03-08 22:30
That will be a tough one to debug for us starting fron just the links you provided.

Would you mind trying to reproduce the issue in a small reproducible codepen / jsfiddle / jsbin to help us out?

**Comment by tapinambur0508** [comment] 2018-03-10 13:40
Hello. I created mini version of my real project. You can see that plot does not stretch of all available width. I use ASUS with 15.6 inch display and resilution of 1920x1080

**Comment by etpinard** [comment] 2018-03-13 20:53
Hmm. After navigating to https://prnt.sc/inkxvg

this is what I see in Chrome 65:

![image](https://user-images.githubusercontent.com/6675409/37369183-c40ab82a-26de-11e8-8794-6cf83a7481ec.png)

and this is what I see in FF58:

![image](https://user-images.githubusercontent.com/6675409/37369222-e0f81a2c-26de-11e8-8190-8ccf0a51e766.png)

--- 

Is anyone else affected by this bug?

**Comment by tapinambur0508** [comment] 2018-03-14 13:14
I do not like that the graph does not stretch to the whole width of the screen. I mean, inside red rectangle
![index](https://user-images.githubusercontent.com/17224522/37404368-54aebe60-279a-11e8-8a20-e63cd1903c41.png)

**Comment by etpinard** [comment] 2018-03-14 14:35
Ok I see. Now, can you share a reproducible example of how that graph div is created? 

`Plotly.plot(element, data, laylot)`
where element is:
`const element = this.element.nativeElement`

doesn't help us much. At the very least can you share what style properties that `element` has?

**Comment by tapinambur0508** [comment] 2018-03-15 14:54
Link on stackblitz - https://stackblitz.com/edit/angular-y1bhs3. I created chart in chart component. element - doesn't have any style

**Comment by etpinard** [comment] 2018-03-16 15:56
Thanks for the link! I don't much about AngularJS, so I can't really put a finger on the problem.

You might want to look into https://plot.ly/javascript/responsive-fluid-layout/ which might help your app resize your graphs properly.

**Comment by etpinard** [comment] 2018-03-16 15:57
... and you might want to try posting on https://community.plot.ly/c/plotly-js where another AngularJS users may have encounter the same issue.

**Comment by etpinard** [comment] 2018-04-13 16:46
Closing due to lack of recent activity.

**Closed by etpinard** 2018-04-13 16:46 UTC
