### ISSUE TITLE
Null island with plot_geo and add_segments

### ISSUE THREAD

**Issue by sw1sh** [plotly/plotly.js#983] opened 2016-09-27 15:17 UTC
You can see it right in the first example from https://plot.ly/r/lines-on-maps/. And I'm having the same result locally in RStudio and the github version of plotly.

First incorrectly posted the issue on [R version of plotly](https://github.com/ropensci/plotly/issues/731), but was redirected here.

[Null island](https://en.wikipedia.org/wiki/Null_Island)

**Comment by etpinard** [comment] 2016-09-27 15:23
duplicate of https://github.com/plotly/plotly.js/issues/963

**Closed by etpinard** 2016-09-27 15:23 UTC
Labels: type: duplicate
