### ISSUE TITLE
Customize fill-rule in selection and shape drawings

### ISSUE THREAD

**Issue by archmoj** [plotly/plotly.js#4592] opened 2020-02-19 20:45 UTC
Currently, the `fill-rule` applied in selection outline and shapes is `evenodd`.
It would be of interest to make this configurable.
https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/fill-rule

**Comment by gvwilson** [comment] 2024-06-14 12:57
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-14 12:57 UTC
Labels: type: feature
