### ISSUE TITLE
[feature] - add events to plotly_select

### ISSUE THREAD

**Issue by destradafilm** [plotly/plotly.js#4091] opened 2019-07-30 23:40 UTC
`plotly_click` has key events, `plotly_select` should too. I want to know if a user has `ctrl` or `meta` key clicked when they are selecting points. That way I can programmatically handle custom style options

*this request is for boxplot / violin / heatmap

**Comment by gvwilson** [comment] 2024-06-14 12:48
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-14 12:48 UTC
Labels: type: feature
