### ISSUE TITLE
Need to reset each Scattermapbox for it to show up properly

### ISSUE THREAD

**Issue by dimrizo** [plotly/plotly.js#3642] opened 2019-03-16 12:02 UTC
So I have created a minimal example of my issue. I just use Python, plotly and Mapbox to represent a set a marker with a few labels. Everything works fine but the map produced is not centered where I want and needs to reset it to show the proper markers and area. Also, the tiles take a while to load and won't fully load if I don't move the map. Please take a look at the code:

https://pyfiddle.io/fiddle/ca7b194f-dd0c-4a94-be7f-b03c42d1895f/?i=true

**Comment by etpinard** [comment] 2019-03-18 15:53
Thanks for reporting. Could someone attempt to convert this to JS to help us debug?

In the meantime, to solve


I _think_ you're looking for `layout.uirevision` as presented in:

**Comment by jonmmease** [comment] 2019-03-25 10:10
Here's a codepan: https://codepen.io/jonmmease/pen/vPPmVo

Here's the result.  Note that the tooltips work right away, but the markers don't show up until the "Home" button is clicked.  Also, the tiles don't fill in until you start panning around and they fill in everywhere around the points before the tile with the points is loaded.


![mapbox_update](https://user-images.githubusercontent.com/15064365/54911280-809f7080-4ec4-11e9-932f-2ec66ab641a1.gif)

**Comment by etpinard** [comment] 2019-03-25 13:45
![image](https://user-images.githubusercontent.com/6675409/54924432-bf442380-4ee2-11e9-9bbd-fdba58f421e9.png)

interesting.

**Comment by etpinard** [comment] 2019-03-25 13:51
Something looks off with `"mapbox://styles/dimrizo/cjt8m6l500onx1fo7nnag2cw8"`

Here's a plain mapbox-gl pen with that custom style: https://codepen.io/etpinard/pen/OqqZyv

Here's @jonmmease 's pen with stock style: https://codepen.io/etpinard/pen/wOOjWx

**Comment by etpinard** [comment] 2019-05-08 21:42
> Here's a plain mapbox-gl pen with that custom style: https://codepen.io/etpinard/pen/OqqZyv

Is still logging a bunch of errors in the console. So I strongly suspect the problem isn't related to plotly.js. Closing (for now).

**Closed by etpinard** 2019-05-08 21:42 UTC
