### ISSUE TITLE
This mesh won't render

### ISSUE THREAD

**Issue by etpinard** [plotly/plotly.js#1948] opened 2017-08-11 13:44 UTC
See https://codepen.io/etpinard/pen/PKjMgz?editors=0010

A mesh with:

```js
x: [1, 1, 1, 1]
y: [0, 1, 1, 0]
z: [0, 0, 1, 1]
```

fails to render. Note that perturbing `x` to `[1, 1, 0.99, 0.99]` makes it appear.

**Comment by alexcjohnson** [comment] 2017-08-15 21:53
all manner of interesting effects here...
`xb = [0.99, 1, 0.99, 1]`
<img width="381" alt="screen shot 2017-08-15 at 5 39 21 pm" src="https://user-images.githubusercontent.com/2678795/29337824-d3d11040-81e0-11e7-85da-21629997911e.png">
The issue is `delaunayaxis` - triangulation fails because everything is colinear in xy for the default `delaunayaxis='z'`, works fine if you change it to `'x'` - so dunno if we really want to consider this a bug, if we do we need to somehow automatically choose a `delaunayaxis`.

**Comment by maptopixel** [comment] 2017-08-16 07:58
Thank you for looking into this. For my situation I should be able to work with setting the delaunayaxis for certain surfaces.

On the wider issue, perhaps the triangulation should be 2D where vertices are collinear...  ;P

**Comment by alexcjohnson** [comment] 2017-08-16 18:29
That's exactly the issue, the triangulation *is* 2D, having ignored the `delaunayaxis` coordinate. Precisely colinear projected vertices are kind of a trivial edge case, so I suspect this is simply an issue we need to call out in the docs. Correctly inferring the intended axis from the data seems like it would be extremely difficult to do in any sort of a robust way.

Alternatively I suppose we could default to some other algorithm besides delaunay triangulation - though it seems like as we have it now these also do not appreciate completely coplanar points. This does not work (with `alphahull: 0` or `0.1` - anything on `(0,1.15]` seems equivalent, `>~1.16` everything disappears no matter what):
```js
var data=[
    {
      opacity:0.8,
      color:'rgb(300,100,200)',
      type: 'mesh3d',
      x: [1, 1, 1, 1],
      y: [0, 1, 1, 0],
      z: [0, 0, 1, 1],
      alphahull: 0
    }
];
```

but change to `x: [1, 1, 1, 0.99]` and you get a very thin tetrahedron. I doubt this is the generally desirable outcome (particularly in the case where `x` is NOT uniform, ie is representing some real data - there's a big difference between a hull and a layer), I think we should leave it as is and just deal with it as a documentation issue.

**Comment by sandrodiord** [comment] 2019-11-30 18:04
Dears,

first of all, congrats for the excellent job with the plotly library and thank you very much for this.

I also have the same problem with surface rendering, as you can see in the plot below. I trying create a web application in which I will use simple 3d models of civil engineering structures to illustrate how they are moving due natural vibrations (i.e, caused by traffic, wind, waves, etc.). I am using Scatter3d and Mesh3d but the vertical and horizontal surfaces will not render correctly as you can see in the figure bellow (note that only the front faces are rendered correctly). I have tried to set the `delaunayaxis` property to each surface, but the problem persisted. I wonder if the problem has to do with the fact that normal vector of each triangle is not taken into a account in the rendering, but only the vectors defined by coordinate system axes (i.e, x, y and z).
 
 ```
fig1 = go.Figure()
 if len(cfglines) != 0:
    for l in range(0, len(cfglines)):
        Inode = np.where(cfgnodes[:, 0] == cfglines[l, 0])
        Jnode = np.where(cfgnodes[:, 0] == cfglines[l, 1])
        Idl = np.array([Inode[0], Jnode[0]])
        xl = np.array(cfgnodes[Idl, 1]).squeeze()
        yl = np.array(cfgnodes[Idl, 2]).squeeze()
        zl = np.array(cfgnodes[Idl, 3]).squeeze()
        line = go.Scatter3d(x=(xl), y=(yl), z=(zl), mode="lines+markers", opacity=1.0, showlegend=False,
                 line=dict(width=3, color="blue"), marker=dict(size=3, color="black", symbol="circle"))
        fig1.add_trace(line)

if len(cfgsurfs) != 0:
    for s in range(0, 20):
        Inode = np.where(cfgnodes[:, 0] == cfgsurfs[int(s), 0])
        Jnode = np.where(cfgnodes[:, 0] == cfgsurfs[int(s), 1])
        Knode = np.where(cfgnodes[:, 0] == cfgsurfs[int(s), 2])
        Ids = np.array([Inode, Jnode, Knode])
        xs = np.array(cfgnodes[Ids, 1]).squeeze()
        ys = np.array(cfgnodes[Ids, 2]).squeeze()
        zs = np.array(cfgnodes[Ids, 3]).squeeze()
        surf = go.Mesh3d(x=(xs), y=(ys), z=(zs), opacity=0.4, color="blue", i=[0], j=[1], k=[2], delaunayaxis="z", flatshading=True)
        fig1.add_trace(surf)

fig1.update_layout(scene = dict(
                     xaxis = dict(nticks=4, range=[-10,50],),
                     yaxis = dict(nticks=4, range=[-10,40],),
                     zaxis = dict(nticks=4, range=[0,60],),),
                     width=800,
                     margin=dict(r=20, l=10, b=10, t=10))
fig1.show()
```

![newplot (1)](https://user-images.githubusercontent.com/58369580/69903790-a3145280-139e-11ea-81d5-dadb05c6784b.png)

**Comment by gvwilson** [comment] 2024-06-10 15:56
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson

**Closed by gvwilson** 2024-06-10 15:56 UTC
Labels: type: bug
