### ISSUE TITLE
Axis `nticks` description is wrong

### ISSUE THREAD

**Issue by yankev** [plotly/plotly.js#659] opened 2016-06-17 19:47 UTC
http://codepen.io/plotly/pen/92268ebeb73d75262fbebfdcd8e64450?editors=1010

In the example there are 18 data points, and nticks (for the x-axis) has to be set to 19 before there is one tick per bar.
Other values for tick < 19 result in other unexpected behaviour.

**Comment by etpinard** [comment] 2016-06-17 19:52
Same _issue_ as https://github.com/plotly/plotly.js/issues/614 

`nbins` and `nticks` (and `ncontours`) for that matter use the same algorithm.

This is the intended behaviour, not a bug.

We should change the description [here](https://github.com/plotly/plotly.js/blob/4f3b448035b538c6bc259d1e853944613bb7cff3/src/plots/cartesian/layout_attributes.js#L134-L135) though.

**Comment by cldougl** [comment] 2016-06-17 19:58
and [here](https://github.com/plotly/plotly.js/blob/27503920d1d3e98a002f7cb87a0eed1033f7eda7/src/traces/contour/attributes.js#L45) then as well

**Comment by etpinard** [comment] 2016-06-20 21:02
fixed in https://github.com/plotly/plotly.js/pull/662

**Closed by etpinard** 2016-06-20 21:02 UTC
Labels: type: documentation
