### ISSUE TITLE
time axis is not chronological

### ISSUE THREAD

**Issue by jwkvam** [plotly/plotly.js#1232] opened 2016-12-07 01:38 UTC
demo:
https://codepen.io/anon/pen/dOeWBw?editors=0010

In the example I have two traces. The second one has time points that precede the first trace. These extra time points get appended to the axis instead of being prepended like I was expecting.

I can work around this issue by first checking which trace has the earliest timestamps. I would rather not need to check for this if possible, thanks!

**Comment by etpinard** [comment] 2016-12-07 02:29
duplicate of https://github.com/plotly/plotly.js/issues/1003 

which will be fixed in the next release `v1.21.0`

**Closed by etpinard** 2016-12-07 02:29 UTC
