### ISSUE TITLE
How do I name png image snapshots?

### ISSUE THREAD

**Issue by mldangelo** [plotly/plotly.js#264] opened 2016-02-19 01:25 UTC
Plotly.js is awesome! I just started using it in one of my projects and have a question. I'm having trouble figuring out how to rename PNG snapshots from newplot.png to something else. I see [here](https://github.com/plotly/plotly.js/blob/34438d713f9eb806f8e3afafbc89b561bbd52529/src/components/modebar/buttons.js#L69) that the name can be set, but I have no idea how to do it. Can anyone help me out? Thanks so much.

**Comment by etpinard** [comment] 2016-02-19 13:51
Thanks for writing.

The feature you are describing is not exposed through any public method at the moment.

We are planning on bringing several to-image functionalities to the public realm in the near future.

Your issue overlaps somewhat https://github.com/plotly/plotly.js/issues/83 , so I'm going to close it.

Please follow https://github.com/plotly/plotly.js/issues/83 for the latest information. Cheers.

**Comment by etpinard** [comment] 2016-02-19 13:51
duplicate of https://github.com/plotly/plotly.js/issues/83

**Closed by etpinard** 2016-02-19 13:51 UTC

**Comment by etpinard** [comment] 2016-05-16 19:30
done in https://github.com/plotly/plotly.js/pull/446

**Comment by mldangelo** [comment] 2016-05-17 05:30
Thanks so much @etpinard!
