### ISSUE TITLE
'Click' events not working on 'Touch' in bar chart

### ISSUE THREAD

**Issue by tropys** [plotly/plotly.js#2639] opened 2018-05-16 08:43 UTC
'Click' and 'Touch' work fine for pie charts but, only 'Click' works for bar chart.
If 'Touch' is not supported why does it work for pie charts?

Tested using chrome and firefox, emulated and on a touch screen.

Pie vs Bar chart codepen: https://codepen.io/steph_curried/pen/RyYmxL

**Comment by alexcjohnson** [comment] 2018-05-16 14:01
Yes, that should work, thanks for the report! Seems like it should also show hover labels on the bar, wouldn't you think?

Even the pie has some behavior (on my phone anyway) that I wouldn't have expected: the first touch on a slice shows hover data and the *second* touch on that same slice makes a click event. @etpinard is that intentional? I guess I could imagine a rationale for that - otherwise there's no way to see the hover info without generating a click, which may be a stronger interaction than the user intended - but it still feels weird to me. Anyway, we should pick a behavior and have all trace/subplot types follow it.

**Comment by etpinard** [comment] 2018-05-16 14:04
> Anyway, we should pick a behavior and have all trace/subplot types follow it.

Right, picking the _right_ behavior isn't obvious to me. It would be nice to see what other graphing library are doing. See https://github.com/plotly/plotly.js/issues/1858

Related: https://github.com/plotly/plotly.js/issues/1967

**Comment by etpinard** [comment] 2018-09-14 13:53
The 'click on bars' part is essentially a duplicate of #1967 and will be in fixed in https://github.com/plotly/plotly.js/pull/2997

The single vs double touch click idea is now in https://github.com/plotly/plotly.js/issues/1858#issuecomment-421365483

**Closed by etpinard** 2018-09-14 13:53 UTC
Labels: type: bug
