### ISSUE TITLE
anchor shapes to map axes

### ISSUE THREAD

**Issue by archmoj** [plotly/plotly.js#4594] opened 2020-02-20 02:13 UTC
At the moment it is possible to draw shapes on top of maps using `paper` anchor.
However, there is no way to link with e.g. `mapbox` axes to draw shapes in data coordinates.

**Comment by etpinard** [comment] 2020-02-20 14:28
See https://github.com/plotly/plotly.js/pull/1638 for inspiration.

**Comment by archmoj** [comment] 2020-02-20 14:39
> See #1638 for inspiration.

@etpinard thanks!

**Comment by gvwilson** [comment] 2024-06-14 12:57
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-14 12:57 UTC
Labels: type: feature
