### ISSUE TITLE
Box-Plot group - line connecting | individual traces && box-plots

### ISSUE THREAD

**Issue by AdnanBoota** [plotly/plotly.js#4238] opened 2019-10-01 13:44 UTC
Hi Team Plotly @etpinard ,

Thanks for the great library!

I'm working with Box-Plots and some use-cases to implement with box-plots `boxmode: group`, but unfortunately, not able to produce the following use-cases:

1. Connect individual traces inside the same box-plot-group with their median values, and then connect multiple box-plot-groups with a line.
![box-plot-feature-1](https://user-images.githubusercontent.com/14972616/65969397-fdf40100-e464-11e9-8e4c-c6f5aa56f873.png)

2. Connect multiple box-plot group's individual related traces with a line:
![box-plot-feature-2](https://user-images.githubusercontent.com/14972616/65969411-04827880-e465-11e9-905b-52687ae39129.png)

Looks like, there is no option to connect individual traces with `boxmode: group`

Here is the rough implementation, but not able to achieve it. Please help me how can i achieve these use-cases with box-plots?
https://codepen.io/adnanboota-the-encoder/pen/NWKVQBa?editors=0010

Regards,
Adnan

**Comment by etpinard** [comment] 2019-10-02 17:53
Hi @AdnanBoota 

- Are you looking a way to add scatter-line traces with coordinates corresponding the the box positions?
- Or, are you making a feature request where we would expose a way to add "connectors" to box traces? 

If the former, please ask your question over at https://community.plot.ly/c/plotly-js, and I'll answer it there - where other plotly.js users will be able to benefit from the answer.

**Comment by AdnanBoota** [comment] 2019-10-03 13:05
Hi @etpinard,

Thanks for your reply. Sure i will also ask in https://community.plot.ly/c/plotly-js

I think this could be a good idea, as it will be the part of box-plots.

> - Or, are you making a feature request where we would expose a way to add "connectors" to box traces?

Thanks,
Adnan

**Comment by gvwilson** [comment] 2024-06-14 12:50
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-14 12:50 UTC
