### ISSUE TITLE
gl3d orthographic zoom using modebar button

### ISSUE THREAD

**Issue by colinbrownec** [plotly/plotly.js#4239] opened 2019-10-01 17:23 UTC
When viewing a 3d plot with the orthographic projection, you can zoom with the scroll wheel, but using the modebar zoom button causes the camera to clip the graph.

From previous discussions about orthographic zooming (#3588) and a merge fixing scroll wheel zooming (#3601) seem to imply this behavior is intentional.

I want to submit this behavior as a bug for the following reasons.

1. cannot zoom if the user does not have a scroll wheel
2. modebar behavior should be consistent between plots and projections
3. the current "slicing" behavior is a graphical bug, not a feature (ie. plot axis are also clipped)

I am including the [codepen](https://codepen.io/colinbrown/pen/yLBmBvZ) from 3601 and have updated plotly to use plotly-latest.js

**Comment by etpinard** [comment] 2019-10-02 18:21
Thanks very much posting @colinbrownec 

Here's a gif showing the current mouse-drag behaviour under `dragmode: 'zoom'` for orthographic projections:

![Peek 2019-10-02 14-19](https://user-images.githubusercontent.com/6675409/66070661-c1391000-e51f-11e9-8bed-5790d1504e91.gif)

**Comment by archmoj** [comment] 2019-10-25 13:55
The https://github.com/plotly/plotly.js/pull/4292 PR fixed relayouting issue related to `orthographic` scroll zoom. But to address this issue I would suggest adding a new modebar button (i.e. for both `perspective` and `orthographic` projections) for scaling the scene. Please note that tweaking the `aspectratios` for `perspective` projection can be also be of interest for scaling the 3d graph without changing the `camera.eye` position.

**Comment by etpinard** [comment] 2019-10-25 14:02
Hmm. I'm not sure adding a new modebar buttons is the way to go in the short term. The gl3d modebar is already pretty cluttered.

**Comment by gvwilson** [comment] 2024-06-14 12:51
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-14 12:51 UTC
Labels: type: feature
