### ISSUE TITLE
Scatter3D plot is rounding values 

### ISSUE THREAD

**Issue by boleslawmaliszewski** [plotly/plotly.js#4053] opened 2019-07-16 08:32 UTC
Hi,
I am trying to render some data from lidar on a Scatter3D graph and I encounter a strange problem. It looks like the data is somehow rounded...

Here is the code with the original, unchanged data:
https://codepen.io/bmaliszewski/pen/EBqaZJ
And here is the code where I subtract some constance value from X and Y:
X = X - 7541560
Y = Y - 5751100
The plot relatively should be looking the same, but its not:
https://codepen.io/bmaliszewski/pen/rEXOxw

**Comment by etpinard** [comment] 2019-07-17 21:07
Thanks very much for the report!

Hmm @archmoj any ideas on why this is happening? It might be related to https://github.com/plotly/plotly.js/issues/2646

**Comment by archmoj** [comment] 2019-07-17 21:22
Webgl 1 uses `float` numbers to draw numbers to the screen. And `float` numbers work best when the distribution of points are around the origin. 
On the other hand Lidar data namely those that are encoded in [LAZ](https://rapidlasso.com/2011/11/30/laszip-lossless-compression-of-lidar-data/) format are using `integer` numbers which could help in lossless compression.
@boleslawmaliszewski offsetting the numbers (as a pre-processing step) as you did is a good idea until we may possibly address this issue.

**Comment by archmoj** [comment] 2019-07-18 13:55
[This codepen](https://codepen.io/MojtabaSamimi/pen/JgjvVV) illustrates `scattergl` handles the raw data properly. 
For this `regl-scatter2d` uses [to-float32](https://www.npmjs.com/package/to-float32) module.

**Comment by gvwilson** [comment] 2024-06-14 12:47
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-14 12:47 UTC
Labels: type: bug
