### ISSUE TITLE
Inconsistency when setting `tickvals` and omitting `ticktext` in date axes

### ISSUE THREAD

**Issue by stakemura** [plotly/plotly.js#738] opened 2016-07-12 08:52 UTC
Please see https://jsfiddle.net/0cjprqgy/10/
All ticks of date axis display as "hh:mm:ss aN".

**Comment by etpinard** [comment] 2016-07-12 13:52
That's probably because your `tickvals` aren't valid date timestamps.

How did you get those values?

**Comment by stakemura** [comment] 2016-07-12 14:40
In real use case, I used programmaticaly-generated date timestamps.
However, all cases seemed to be failed.
OK. the following new sample use apparently valid timestamps.
How about https://jsfiddle.net/0cjprqgy/11/ ?

**Comment by etpinard** [comment] 2016-07-13 15:48
Looks like those weird tick labels are caused by you not providing a `ticktext` setting to accompany `tickvals`. Setting a proper `ticktext` makes your problem go away http://codepen.io/etpinard/pen/YWEdJX .

But, those weird labels do showcase an inconsistency between `linear` and `date` axis types. See http://codepen.io/etpinard/pen/rLYoqK here omitting to provide `ticktext` falls back to stringnified `tickvals` values - making this issue a _very low_ priority bug.

Maybe a better question to ask ourselves: _should we allow `tickmode: 'array'` when `tickvals` isn't provided?_ I'm changing the issue title to reflect this. Thanks.

**Comment by etpinard** [comment] 2016-07-13 18:00
> hover text won't be able to show date.

You mean it _only_ shows the hour? Interesting. Thanks for pointing this out. This is probably related to the inconsistency mentioned in https://github.com/plotly/plotly.js/issues/738#issuecomment-232398378

**Comment by stakemura** [comment] 2016-07-14 02:23
Without tickvals date axis shows date and time apparently.
Please check https://jsfiddle.net/0cjprqgy/12/ .

**Comment by etpinard** [comment] 2016-07-14 13:39
> Without tickvals date axis shows date and time apparently

Yeah I noticed that too. This should be resolved in the same patch as for https://github.com/plotly/plotly.js/issues/738#issuecomment-232398378

Thanks.

**Closed** 2016-11-23 15:05 UTC
Labels: type: bug, type: community
