### ISSUE TITLE
xaxis: the title (with standoff = 0) is misplaced when the tick labels are hidden

### ISSUE THREAD

**Issue by Nauss** [plotly/plotly.js#6576] opened 2023-04-20 08:42 UTC
This [pen](https://codepen.io/Nauss/pen/abRBZNj) is the [Set and Style Axes Title Labels and Ticks example](https://plotly.com/javascript/axes/#set-and-style-axes-title-labels-and-ticks) with the added standoff parameter on the title.

`title: { text: "AXIS TITLE", standoff: 0 }`

When changing the `showticklabels: true` to `showticklabels: false`, the xaxis' title "moves" at the top of the plot.

I have an easy workaround: when `showticklabels = false` I just set `standoff = undefined` and the tilte is back in its expected place.

Looks like a bug but I might be missing something ?
I also think it is a regression that came after 2.13.3...

**Comment by alexcjohnson** [comment] 2023-04-25 18:46
Duplicate of #6552 - thanks!

**Closed by alexcjohnson** 2023-04-25 18:46 UTC
