### ISSUE TITLE
SVG downloads in IE/Edge contain literal data URL

### ISSUE THREAD

**Issue by arbscht** [plotly/plotly.js#2063] opened 2017-10-06 02:33 UTC
When using `downloadImage` to save a SVG snapshot via MS IE or Edge, the saved file contains the literal data URL value rather than the decoded SVG source code.

I believe this is a consequence of https://github.com/plotly/plotly.js/commit/22d902ba00822496e7a9edbf1ce73689b78a37c1 before which `url` contained the raw SVG source. That commit is probably correct to only put URL values in `url`, but that means the URL should be decoded before constructing a Blob and saving as a file.

See my PR here for a fix: https://github.com/arbscht/plotly.js/pull/1

**Comment by alexcjohnson** [comment] 2017-10-06 13:58
possibly related to (or duplicate of even) #699 ?

**Comment by bpostlethwaite** [comment] 2017-10-06 16:40
cc @cldougl - looks like we have progress on this one

**Closed** 2017-10-10 14:26 UTC
