### ISSUE TITLE
import latency

### ISSUE THREAD

**Issue by Phillip-M-Feldman** [plotly/plotly.js#4564] opened 2020-02-10 04:09 UTC
When I import `plotly`, using Anaconda 2019.10 with Python 3.7, there is a latency of roughly 3 seconds.  (For comparison, on the same computer, it takes roughly half a second to import `matplotlib`).  Is there anything that can be done to reduce the `plotly` import latency?

**Comment by alexcjohnson** [comment] 2020-02-10 14:16
duplicate of https://github.com/plotly/plotly.py/issues/740

**Closed by alexcjohnson** 2020-02-10 14:16 UTC
