### ISSUE TITLE
Cannot keep consistent image size when using xref : axis

### ISSUE THREAD

**Issue by Matz13** [plotly/plotly.js#967] opened 2016-09-22 15:26 UTC
Hi,

I  am inserting png images on a timeseries. But the relative sizing make them super blurry. Is there a way to ignore sizing and use the real size of the image?
I also tried using a svg file and I got the same result, is there anything I am missing ?

Mat

**Comment by etpinard** [comment] 2016-09-22 15:28
Can you share a reproducible example? 

What browser are you using?

Thanks.

**Comment by Matz13** [comment] 2016-09-22 17:18
The bottom line is: I would like to use an image like an annotation.

Quick example here: https://plot.ly/~matz13/4/
The red image is a png, yellow is a svg (much sharper indeed)

I managed to get it to look not to bad by using `sizing : contains` and eyeballing a `sizey` value corresponding roughly to the real size and putting `sizex` as big as possible. This way, my `ysize` defines the images size.
This works for a static chart, but if the graph is resized passed a certain limit (as is needed in my case) it breaks. Same goes when zooming in vertically.
Proof is: when I built the chart I set it to 500x500px and the red images was fine. Once shared, it opens full page and the red image becomes too big and ugly.

It would be great to have the image retain the same size regardless of the `xref`

**Comment by etpinard** [comment] 2016-09-22 17:21
Looks like you'll need to find a bigger png image.

There's not much plotly.js can do here. Upscaling png `layout.images` is outside the scope of the library.

**Comment by Matz13** [comment] 2016-09-22 17:55
I agree on this point, this is why I am using svg files now. So the blurryness is solved. But this wouldn't have been an issue without the scaling. Maybe the title needs to be changed.

If the sizing reference was seperated from the position reference this would not be any issue anymore. something in the line of `sizeref(string)` taking parameters like x, y (coord), paper (%), fixed (px)
I would then be able to size my picture regardless of the positioning reference.
Do I make sense ?

**Comment by etpinard** [comment] 2016-09-22 18:03
That makes perfect sense. Thanks for clarifying. 

I'll add the `type: feature` label. Implementing this won't be a priority for us, but we'll gladly accept community PRs for it.

Sorry about the confusion. Thanks for posting.

**Comment by gvwilson** [comment] 2024-06-05 17:23
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson

**Closed by gvwilson** 2024-06-05 17:23 UTC
Labels: type: feature, type: community
