### ISSUE TITLE
HTML abbr Support

### ISSUE THREAD

**Issue by Kolano** [plotly/plotly.js#2515] opened 2018-03-30 22:20 UTC
Plotly supports [various HTML tags](https://help.plot.ly/adding-HTML-and-links-to-charts/) in text fields.  One useful omitted tag is abbr, used to provide explanations of abbreviated values / acronyms. For instance...
`title: "Top <abbr title='Internet Protocol Addresses'>IPs<abbr>"`
...which currently renders as plain text.

I work around this currently by overlaying separate HTML titles, but such are then absent from Plotly's PNG saves, which is not ideal.

**Comment by alexcjohnson** [comment] 2018-04-02 18:47
Seems like a nice feature, sure. Looks like we'd have to do this in javascript though, as I don't see an equivalent functionality built into SVG. The `<title>` tag *might* have allowed this but doesn't seem browsers have adopted this as a tooltip-like display.

**Comment by Kolano** [comment] 2018-04-02 18:54
Perhaps a [foreignObject](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/foreignObject) element would allow more direct support of HTML markup?

**Comment by alexcjohnson** [comment] 2018-04-02 19:21
Right, due to image exports, and the desire to export SVG itself for use by Illustrator etc, we have avoided `foreignObject` elements. Anyway I suspect replicating this in javascript will not be terribly difficult.

**Comment by gvwilson** [comment] 2024-06-11 17:04
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson

**Closed by gvwilson** 2024-06-11 17:04 UTC
Labels: type: feature
