### ISSUE TITLE
No Click event on category label (xticks) of bar chart

### ISSUE THREAD

**Issue by patilkun** [plotly/plotly.js#1751] opened 2017-06-01 14:45 UTC
I am not getting click event on click of category label (xticks) of bar chart. I am using 'plotly_click'.
Below is the code

**HTML -** 
```
<head>
  <!-- Plotly.js -->
  <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
</head>

<body>
  
  <div id="myDiv" style="width: 480px; height: 400px;"><!-- Plotly chart will be drawn inside this DIV --></div>
  <script>
    <!-- JAVASCRIPT CODE GOES HERE -->
  </script>
</body>
```

**Javascript -** 
```
var trace1 = {
  x: ['giraffes', 'orangutans', 'monkeys'], 
  y: [20, 14, 23], 
  name: 'SF Zoo', 
  type: 'bar'
};

var trace2 = {
  x: ['giraffes', 'orangutans', 'monkeys'], 
  y: [12, 18, 29], 
  name: 'LA Zoo', 
  type: 'bar'
};

var data = [trace1, trace2];

var layout = {barmode: 'group'};

Plotly.newPlot('myDiv', data, layout);
var myDiv = document.getElementById('myDiv');
myDiv.on('plotly_click', function(data){
    alert('chart clicked');
});
```

 
I am able to get click event on actual bars but I am looking for click event on category label under bar. 
In below image I am looking for click event on 'giraffes'. Thanks for the help in advance.
![image](https://cloud.githubusercontent.com/assets/6294305/26684723/d72eeac0-46b5-11e7-9c2b-0367399a4095.png)

**Comment by etpinard** [comment] 2017-06-01 14:49
That's the desired behavior. `plotly_` are only triggered within the plot area (i.e. inside the axes).

**Comment by patilkun** [comment] 2017-06-01 14:55
Thanks @etpinard for quick response. Is there any other event triggered on click of the labels?

**Comment by etpinard** [comment] 2017-06-01 15:09
> Is there any other event triggered on click of the labels?

Not at the moment. See https://github.com/plotly/plotly.js/issues/145 for more event proposals.

In any case, this is a duplicate of https://github.com/plotly/plotly.js/issues/65; closing this ticket.

**Closed by etpinard** 2017-06-01 15:09 UTC

**Comment by sardbaba** [comment] 2017-12-11 09:44
https://github.com/plotly/plotly.js/issues/65#issuecomment-350672387
