### ISSUE TITLE
Showing spikelines on Fx.hover and Fx.loneHover?

### ISSUE THREAD

**Issue by lnunno** [plotly/plotly.js#2517] opened 2018-04-03 15:24 UTC
I've made a [codepen as an example](https://codepen.io/lnunno/pen/OvwNqz). I would like the behavior to be that the effect of Fx.hover is the same as hovering over a single point manually, the spikelines are shown.

I would also like this behavior for scattergl plots, I had [posted an issue in react-plotly.js](https://github.com/plotly/react-plotly.js/issues/69), but maybe here is a more appropriate place, I have not seen of a way to resolve data's x, y pixel values without a mouse event, but the only solution in [this plotly forum thread was to have a mouse event](https://community.plot.ly/t/how-to-customize-plotly-tooltip/332/21) is it possible to do this another way?

**Comment by lnunno** [comment] 2018-04-03 17:06
Also: seeing problems with using the hover [when the xaxis is a string](https://codepen.io/lnunno/pen/QmBGZB).

**Comment by lnunno** [comment] 2018-04-03 18:30
This is [my latest codepen](https://codepen.io/lnunno/pen/WzKRme?editors=0010) that tries to use synchronized hover lines with a datetime x axis and getting Fx.hover warnings that hover failed. It seems to expect the values to be numeric or fails to retrieve them given the datetime string, I've also tried time in milliseconds since the epoch but with no success.

**Comment by alexcjohnson** [comment] 2018-04-04 04:38
> I would like the behavior to be that the effect of Fx.hover is the same as hovering over a single point manually, the spikelines are shown.

Yes, I agree that that should be the behavior. Seems like a bug that this isn't what happens.

> It seems to expect the values to be numeric or fails to retrieve them given the datetime string, I've also tried time in milliseconds since the epoch but with no success.

I'll have to look at this one in more detail, but in principle it *should* work using the date string. milliseconds are problematic and discouraged.

**Comment by etpinard** [comment] 2018-04-04 13:43
Referencing https://github.com/plotly/plotly.js/issues/1848 and https://github.com/plotly/plotly.js/issues/1963 

Personally, I don't think we should add more features to `Fx.hover`. The declarative hover analog to `selectedpoints` (I think we settle on `hoveredpoints`) will effectively replace `Fx.hover` (and `Fx.loneHover` - not sure how that one got into our docs :upside_down_face: )

**Comment by lnunno** [comment] 2018-04-04 17:54
I'm primarily using scattergl, so it may be an acceptable workaround for me to know how to retrieve the x, y points without an event handle so that I can use `Fx.loneHover` as an alternative, unless hoveredpoints is soon to be released.

**Comment by bfeist** [comment] 2018-09-12 14:14
Hi there. Any word on this? I'd love for my triggered hover labels to look the same as mouse rollover.

**Comment by slowkow** [comment] 2019-05-13 19:30
With Plotly 1.47.4, I tried to trigger a hover with `Plotly.Fx.hover()` and it didn't work because I'm using `scattergl` instead of `scatter`.

Could I please ask if you might be able to share an example with a workaround for this issue?

**Comment by Moerko** [comment] 2020-04-21 10:16
Any update on that or an alternative to Plotly.Fx.hover() ?

**Comment by gvwilson** [comment] 2024-06-11 17:04
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson

**Closed by gvwilson** 2024-06-11 17:04 UTC
Labels: type: bug
