### ISSUE TITLE
Box Select for Bar and Histogram

### ISSUE THREAD

**Issue by chriddyp** [plotly/plotly.js#1863] opened 2017-07-07 18:22 UTC
Another request from the Dash community: Box Select for Bar and Histogram. 

Right now, users are able to hack this support by drawing an invisible marker trace behind the bars and then manually updating the bar chart's colors. It would be nice if this was natively supported.

![selected-bars](https://user-images.githubusercontent.com/1280389/27971180-ab2c7eac-631f-11e7-840a-c4450e022afd.gif)

**Comment by etpinard** [comment] 2017-07-07 18:28
essentially a duplicate of https://github.com/plotly/plotly.js/issues/170

**Comment by etpinard** [comment] 2017-07-21 17:40
Closing in favor of #170

**Closed by etpinard** 2017-07-21 17:40 UTC
Labels: type: feature
