### ISSUE TITLE
addTraces upon plotly_selected event with scattergl not rendering correctly

### ISSUE THREAD

**Issue by cpsievert** [plotly/plotly.js#2298] opened 2018-01-25 22:53 UTC
https://codepen.io/cpsievert/pen/MrMMvj

Brush the blue marker. A red marker should appear at (1, 2), but it seems to be transparent.

cc @dfcreative

**Comment by dfcreative** [comment] 2018-02-01 20:41
@etpinard `scatter` mode adds a new trace without `selectedpoints` set on it. Ie. new trace looks like as if it's points are selected, but in fact it has no selection. Is that desired behavior? Or we better off showing new traces with all poins in `unselected` mode?

**Comment by etpinard** [comment] 2018-02-01 20:48
What does the svg `scatter` implementation do in this case?

**Comment by dfcreative** [comment] 2018-02-01 21:11
Should be fixed with #2311

**Comment by cpsievert** [comment] 2018-02-13 15:15
I modified the example slightly so the red marker should be placed directly on top of the blue marker, but again, the red marker isn't rendered.

May seem like a silly bug, but I need this fixed before I can update the R package...

**Comment by dfcreative** [comment] 2018-02-14 23:27
@cpsievert https://github.com/plotly/plotly.js/pull/2367 fixes that.
It swaps canvas order.
The initial guess was that selected points are rendered as the top layer over the not selected ones. That may break cases where selected points overlap not selected ones.
Ultimately we have to choose one way or another. Selected points are a separate layer, we cannot mix them into main points layer to make per-point layering, since that will significantly reduce performance.

**Comment by etpinard** [comment] 2018-02-15 14:46
I prefer the behavior on `master` with the selected points on top.

@cpsievert here's one way to ensure that the red marker (from the new trace added by `addTraces`) appears above the blue marker: https://codepen.io/etpinard/pen/VQMOOd?editors=0010

**Comment by cpsievert** [comment] 2018-02-20 15:45
@etpinard populating `selectedpoints` in that way will require some non-trivial changes on my end -- I imagine it should only be necessary for `scattergl`, though?

**Comment by etpinard** [comment] 2018-02-20 15:58
> I imagine it should only be necessary for scattergl, though?

yes.

**Comment by chriddyp** [comment] 2018-03-05 17:08
Looks like #2433 and https://community.plot.ly/t/webgl-context-lost-after-updating-10-times/8581/8?u=chriddyp is actually this issue. In Dash, we were recommending that users replot their data after selection to customize selection styles. 

This no longer works since the second trace (with _identical_ points as the first trace) now appears below the first trace that was originally plotted and selected. Here is a simple example: https://codepen.io/chriddyp/pen/YebmJL?editors=1010. Selecting the point used to display the second trace with the orange point on it, now it persists the first trace on top of it.

I can't necessarily use the `addTraces` method since Dash users always pass in full figures and I just call `Plotly.react` on them. I can promoted `selected` styles for the traces that support them. This is a breaking change for Dash so if we're going to keep the current behaviour I'll bump up the major version of `dash-core-components`.

**Comment by cpsievert** [comment] 2018-03-21 22:07
One way to work around this issue would be to "turn off" the selected/unselected api when a relevant event is triggered. More specifically, I'm thinking on a `plotly_selected` event, I could do this:

```js
Plotly.restyle(gd, {"selectedpoints": null})
```

before adding a trace. However, it seems `scattergl` doesn't understand this restyle call. Note how in this (similar) code pen, the opacity of the unselected markers remained dimmed for `scattergl`, but are (correctly) not dimmed for `scatter` -- https://codepen.io/cpsievert/pen/GxmWKa 

Happy to open another issue about `scattergl` respecting `Plotly.restyle(gd, {"selectedpoints": null})`

**Comment by etpinard** [comment] 2018-03-22 17:02
Thanks for the report @cpsievert 

`selectedpoints` seems to work fine in `newPlot`, but fails on `restyle` and friends ([example](https://codepen.io/etpinard/pen/qojdpE?editors=0010)). I'll try to get a fix for this out today.

**Comment by jackparmer** [comment] 2020-09-10 19:30
This issue has been tagged with `NEEDS SPON$OR`

A [community PR](https://github.com/plotly/plotly.js/pulls?q=is%3Apr+is%3Aopen+label%3A%22type%3A+community%22) for this feature would certainly be welcome, but our experience is deeper features like this are difficult to complete without the Plotly maintainers leading the effort.

**Sponsorship range: $10k-$15k**

What Sponsorship includes:
- Completion of this feature to the Sponsor's satisfaction, in a manner coherent with the rest of the Plotly.js library and API
- Tests for this feature
- Long-term support (continued support of this feature in the latest version of Plotly.js)
- Documentation at [plotly.com/javascript](https://plotly.com/javascript/)
- Possibility of integrating this feature with Plotly Graphing Libraries (Python, R, F#, Julia, MATLAB, etc)
- Possibility of integrating this feature with Dash
- Feature announcement on [community.plotly.com](https://community.plotly.com/tag/announcements) with shout out to Sponsor (or can remain anonymous)
- Gratification of advancing the world's most downloaded, interactive scientific graphing libraries (>50M downloads across supported languages)

Please include the link to this issue when [contacting us](https://plotly.com/get-pricing/) to discuss.

**Comment by gvwilson** [comment] 2024-06-11 16:56
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson

**Closed by gvwilson** 2024-06-11 16:56 UTC
Labels: type: bug, type: regression, ♥ NEEDS SPON$OR
