### ISSUE TITLE
Duplicated rug plots in subplots of violins still persists

### ISSUE THREAD

**Issue by empet** [plotly/plotly.js#1249] opened 2016-12-13 10:47 UTC
I noticed that the issue https://github.com/plotly/plotly.js/issues/1196 was closed. Yesterday I ran the code for violin  subplots again,  and  the plot still exhibits that bug:
https://plot.ly/~empet/14061/vintage-violin/

**Comment by etpinard** [comment] 2016-12-13 23:56
The issue is fixed in plotly.js, so I'll close this issue.

Note that fixes in plotly.js don't instantaneously propagate to plot.ly and plotly.py.

So if you can't replicate the issue using the latest plotly.js bundle in Javascript, I'd recommend posting your questions on https://community.plot.ly/ 

Sorry for the inconvenience

**Closed by etpinard** 2016-12-13 23:56 UTC
