### ISSUE TITLE
Inconsistency between bar and scatter in styling selected/unselected points

### ISSUE THREAD

**Issue by archmoj** [plotly/plotly.js#3900] opened 2019-05-23 17:39 UTC
There is inconsistency between `bar` and `scatter` in the way points are styled in selected/unselected modes. 
Please refer to https://github.com/plotly/plotly.js/pull/3644#issuecomment-495313047 for more info.

**Comment by etpinard** [comment] 2019-07-12 19:08
Selecting bars + error bars: https://codepen.io/etpinard/pen/agxjgz

Selecting scatter markers + error bars: https://codepen.io/etpinard/pen/wLZxLm

**Comment by etpinard** [comment] 2019-07-12 19:12
I'd argue the bar behaviour is better, though it be nice to :white_check_mark: this while adding attributes for `[un]selected.error_(x|y).color`

**Comment by gvwilson** [comment] 2024-06-14 12:00
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-14 12:00 UTC
Labels: type: bug
