### ISSUE TITLE
Parallel Coordinates Plot : Notification when the order of vertical axis is changed by the user

### ISSUE THREAD

**Issue by iakouchine** [plotly/plotly.js#3879] opened 2019-05-20 11:20 UTC
Hello,
My parallel plot listens 'restyle' events already to save / restore the constraint ranges.
In the same way, I would like to save / restore the order of vertical axis.
Unfortunately, when the user changes the order of vertical axis by dragging the axis names across the plot, a 'restyle' is well sent by plotly but without arguments (I would expect an array of strings that represents the new vertical axis' order).
Do you think, it is possible to get this kind of enhancement? 
Thanks.

**Comment by etpinard** [comment] 2019-05-20 13:14
> Do you think, it is possible to get this kind of enhancement?

Yes, I would even call that a bug. Thanks very much for reporting!

**Comment by bainro** [comment] 2020-11-21 08:33
This might be fixed or the information to do what the original user wants might be easily available:

```
t.on('plotly_restyle', () => {
  console.log(t.data[0].dimensions)
})
```

This will fire an event when the user changes the column order. It returns an array where each element is an object, and each object has a label field. Those labels can be used to detect the original order and subsequent orders.

**Comment by gvwilson** [comment] 2024-06-14 11:59
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-14 11:59 UTC
Labels: type: bug
