### ISSUE TITLE
adding data to the click event to discern which bar/plot out of several was clicked in hovermode: 'x'

### ISSUE THREAD

**Issue by sscro-ccri** [plotly/plotly.js#4590] opened 2020-02-18 19:54 UTC
When in hovermode: 'x'  it would be useful to get the closest point clicked instead of all the points. I know that hovermode: 'closest' will do this but I want to be able to compare values on hover AND get the closest point clicked. 

See discussion here: https://community.plot.ly/t/get-single-point-for-multiple-trace-plots/9604/6

**Comment by etpinard** [comment] 2020-02-19 20:21
Duplicate of https://github.com/plotly/plotly.js/issues/965

**Closed by etpinard** 2020-02-19 20:21 UTC
