### ISSUE TITLE
mouseleave event (both JQuery and React) fires when user clicks on chart

### ISSUE THREAD

**Issue by john-soklaski** [plotly/plotly.js#999] opened 2016-09-30 02:46 UTC
I am displaying a plotly chart in a hovering tooltip, but when the user interacts with the chart, the tooltip disappears because a `mouseleave` event fires. I can work around this, but it is a counter-intuitive behavior to me. Do you know why this happens?

Repro:
http://codepen.io/john-soklaski/pen/WGEJAW

Open the developer tools for your browser.
Each time you click on the plot, you will see another 'mouseleave' message.

**Comment by etpinard** [comment] 2016-09-30 21:44
Hmm.

It must be related to this [block](https://github.com/plotly/plotly.js/blob/fce36fa46bd53fa5ebe4e4892479258040783409/src/components/dragelement/index.js#L141-L145) where we simulate a click event.

This `dragElement` construct enables us, for example, to trigger the hover picking routing on mousemove and then send the same event data to both `plotly_hover` and `plotly_click`. 

But, looks like it might lead to some undesired (or at least surprising) side-effects as you're pointing out.

Maybe there's a way to pass a set of options to 

```js
varr e2 = document.createEvent('MouseEvents');
e2.initEvent('click', true, true);
```

?

**Comment by etpinard** [comment] 2016-09-30 21:53
But anyway, thanks very much for this report.

**Comment by john-soklaski** [comment] 2016-10-04 21:56
@etpinard  I won't have time to make a fix for this, but I did a little investigating. The lines you highlighted don't seem to be the cause. I tried commenting them out and was still getting `mouseleave` events. But, if I comment out this [line](https://github.com/plotly/plotly.js/blob/fce36fa46bd53fa5ebe4e4892479258040783409/src/components/dragelement/index.js#L158), I stop getting the event:
```
options.element.onmousedown = onStart;
```

Obviously that breaks dragging, but at least we can know it is somewhere within that code.

**Comment by alexcjohnson** [comment] 2017-09-29 18:52
I believe this happens because the [coverslip](https://github.com/plotly/plotly.js/blob/master/src/components/dragelement/index.js#L197) is appended to `document.body`, rather than `gd` or one of its children. We do this so that the coverslip can cover the whole window, which lets you do things like drag off the edge of the plot while zooming or panning. I suppose we could imagine a config option to allow you to append the coverslip to something else, that might fix it.

**Comment by gvwilson** [comment] 2024-06-05 17:22
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson

**Closed by gvwilson** 2024-06-05 17:22 UTC
Labels: type: bug, status: discussion needed
