### ISSUE TITLE
Dual axis line chart axis are not synchronized/lined up

### ISSUE THREAD

**Issue by Jacyle** [plotly/plotly.js#3837] opened 2019-05-06 03:53 UTC
In the following graph you can see the line chart grid lines are no matched up, is there a way to fix this in the 'Layout'?

![image](https://user-images.githubusercontent.com/8864470/57206009-93f82e00-6f90-11e9-9454-9e8cc7978070.png)

`layout = go.Layout(title = "The price of gold tends to move with inflation.",
    titlefont = dict(
        family = 'Arial, sans-serif',
        size = 18
    ),
    xaxis = dict(        
        zeroline = False
    ),
    yaxis = dict(
        title='y/y percent',
        titlefont=dict(
        family='Arial, sans-serif',
        size = 10),
        side = 'left',
        hoverformat = '.2f',
        zeroline= False,
        rangemode = 'tozero'
    ),
        yaxis2 = dict(
        title='y/y percent',
        titlefont=dict(
        family='Arial, sans-serif',
        size = 10),
        overlaying ='y',
        zeroline = False,
        side = 'right',
        rangemode = 'tozero',
        hoverformat = '.2f'),
    autosize=True,
    margin=dict(l = 200,r = 200, t = 100, b = 100),
    hovermode = 'closest',
    legend=dict(x = 0, y = 1.1, 
    orientation="h"))
`

**Comment by etpinard** [comment] 2019-05-06 13:35
Duplicate of https://github.com/plotly/plotly.js/issues/1962

**Closed by etpinard** 2019-05-06 13:35 UTC
