### ISSUE TITLE
How to plot standard time (with an extra hour) change from daylight savings time?

### ISSUE THREAD

**Issue by janine-zhu** [plotly/plotly.js#4358] opened 2019-11-17 19:07 UTC
In the fall, we fall back and there are 25 hours in the day now. How to plot 25 hours on the chart for just that one day. Any help is greatly appreciated.

**Comment by gvwilson** [comment] 2024-06-14 12:52
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-14 12:52 UTC
