### ISSUE TITLE
Color discontinuity in surfaces defined by arrays that contain an entire row/column of gaps

### ISSUE THREAD

**Issue by empet** [plotly/plotly.js#4423] opened 2019-12-16 06:02 UTC
The surface  attribute `connectgaps=True`  doesn't work when a  coordinate array, x, y, or z, 
has an entire row or column filled with nan(s). Moreover the row or column bordered by nan(s) exhibits a color discontinuity:
![fig1](https://user-images.githubusercontent.com/3627253/70882679-2f4a8a80-1fd9-11ea-9646-249d686be5d1.png)

The above surface is defined by the parameterization x= u*cos(v), y=u*sin(v), z =u^2, u, v in [0,1], and a  fixed v-row in the associated  meshgrid,  filled with nan(s).

I discovered the latter issue in an attempt to plot 169 planar disks mapped onto a sphere. To avoid defining 169 traces of  type  surface (one for each spherical disk)  I extended each  disk coordinate array with a column of nan(s), and concatenated all new arrays to get  x, y and z  coordinate arrays,   that define a unique surface,  not 169.

With these settings each initial coordinate array, except the first one, has a column of nan(s), both at left and at right, that makes the corresponding disk centers and boundary circles to be mapped to a color that illustrates a sharp discontinuity. 
I suspect that the columns of nan(s) are not skipped when the colormapping is performed.

![rsz_sphere-disks1](https://user-images.githubusercontent.com/3627253/70882791-80f31500-1fd9-11ea-9dce-c6a44b94f81a.png)

![rsz_sphere-disks2](https://user-images.githubusercontent.com/3627253/70882803-88b2b980-1fd9-11ea-9059-c035368bab11.png)

**Comment by archmoj** [comment] 2019-12-16 14:59
@empet thanks very much for the wonderful post.
This [demo](https://codepen.io/MojtabaSamimi/pen/ZEYBOpK?editors=0010) appears to work OK.
I suspect the data grid may not match (or exceed) Ni X Nj in your example.
Would you mind trying a case where Ni==Nj and possibly count the length of data points?

**Comment by empet** [comment] 2019-12-16 15:10
When a colorscale is darker the discontinuity does not appear. Please check with deep_r or matter_r colorscales, available in plotly.py color, in the folder cmocean.

**Comment by archmoj** [comment] 2019-12-16 16:00
This [parametric demo](https://codepen.io/MojtabaSamimi/pen/vYEyXry?editors=0010) appears to work as well.

**Comment by archmoj** [comment] 2019-12-16 18:12
@empet please note that in the demo above (as well as heatmap) null values could be connected using `connectgaps` if they are on the z axis not the x/y axes (i.e. similar to the example you sent me).
Do you think that we could/should support missing values on an axis other than z?
cc: @alexcjohnson

**Comment by empet** [comment] 2019-12-16 18:45
@archmoj  In the case of paraboloid I can avoid setting  nan(s) on a  row/column in x or y , but not for disks.  But the issue in the spherical disks  is not related to the fact that connectgaps=true does not work when x or y contains a column of nan(s)., because I don't want to connect the gaps I introduced in their parameterization.  My complaint  refers to  color discontinuity created by gaps.

**Comment by archmoj** [comment] 2019-12-16 20:25
This [demo](https://codepen.io/MojtabaSamimi/pen/GRgNEge?editors=0010) may also be used to illustrare a similar webgl bug during calculation of the normal for surface lighting. It is more clear when using a small number of segments.

**Comment by archmoj** [comment] 2019-12-16 22:19
With n=3, one side of the plot (facing the light) displays undesirable shading:
![newplot (1)](https://user-images.githubusercontent.com/33888540/70947886-30ef6f00-2028-11ea-9049-e51fbab03c1e.png)

**Comment by archmoj** [comment] 2019-12-16 22:20
And that is not related to `connectgaps` being enabled or disabled.

**Comment by gvwilson** [comment] 2024-06-14 12:53
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-14 12:53 UTC
