### ISSUE TITLE
smart defaults for funnel and image traces are not applied when restyling or reacting from trace with visible false

### ISSUE THREAD

**Issue by mafar** [plotly/plotly.js#4324] opened 2019-10-31 05:57 UTC
Both pen are bare minimum for bug reproduction.

**Funnel Defualt Behaviour:**
Pen: https://codepen.io/mafar/pen/rNNYeLX?editors=0010
initialised with default options =>  **Observe Funnel Direction**

**Funnel updated with Plotly.restyle:**
Pen: https://codepen.io/mafar/pen/YzzEqqN?editors=0010
initialised with empty x,y options and then x,y are updated with ```Plotly.restyle``` =>  **Observe Funnel Direction**

**Image:**
![funnel](https://user-images.githubusercontent.com/4101480/67922639-23436e80-fbcd-11e9-9a89-50c26190cad9.png)

**Comment by archmoj** [comment] 2019-10-31 17:58
@mafar thanks for reporting.
This is happening because the layout default was set in the `newPlot` call. Since the `funnel` had no data, it would be invisible. In the second call (i.e react) this change of data is not applied to the layout default.

**Comment by alexcjohnson** [comment] 2019-10-31 18:40
FWIW `Plotly.react` shows the same problem as `Plotly.restyle`
https://codepen.io/alexcjohnson/pen/oNNodGr?editors=0010

**Comment by archmoj** [comment] 2019-10-31 22:10
A similar issue could be noticed with the `image` trace: [demo](https://codepen.io/MojtabaSamimi/pen/RwwjYda?editors=0010).

**Comment by etpinard** [comment] 2019-11-20 17:29
This bug is a side-effect of our input `range` and `autorange` mutations:

https://github.com/plotly/plotly.js/blob/1a3d38339dc7c9b5594f94a1b1f3625f3854d2ac/src/plots/cartesian/autorange.js#L255-L256

With this piece of logic:

https://github.com/plotly/plotly.js/blob/1a3d38339dc7c9b5594f94a1b1f3625f3854d2ac/src/plots/cartesian/axis_defaults.js#L56-L62

after the first plot call (the one with empty `x` and `y` coordinates), we have:

```js
gd.layout.yaxis.autorange = true;
gd.layout.yaxis.range = [-1, 4];
```

On the second react/update call, we get

```js
gd.layout.yaxis.autorange = true;
gd.layout.yaxis.range = [-0.5, 3.5]
```

That is, `yaxis.autorange` gets coerced to `true` (not `'reversed'` as `true` got mutated in the user layout) where it should be coerced to `'reversed'` leading a yaxis range of `[3.5, 0.5]`.

----

So, adding 

```js
delete gd.layout.yaxis.autorange;
delete gd.layout.yaxis.range;
```

before the second react/update call is enough to work around this bug. Example: https://codepen.io/etpinard/pen/MWWxKLv?editors=0010

**Comment by mafar** [comment] 2019-11-21 05:28
```
delete gd.layout.yaxis.autorange;
delete gd.layout.yaxis.range;
``` 
works . can we request an official fix please

**Comment by gvwilson** [comment] 2024-06-14 12:53
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-14 12:53 UTC
Labels: type: bug
