### ISSUE TITLE
This x,y.z set of scatter3d data pts does not render 

### ISSUE THREAD

**Issue by etpinard** [plotly/plotly.js#551] opened 2016-05-18 19:58 UTC
See http://codepen.io/etpinard/pen/JXQPaE

**Comment by mdtusz** [comment] 2016-05-19 18:15
I'm not sure what I'm supposed to be looking at that's wrong.

They seem to render for me?
![screen shot 2016-05-19 at 14 15 13](https://cloud.githubusercontent.com/assets/6494463/15404573/268309da-1dcc-11e6-9595-617091a93b14.png)

**Comment by bombaci-vsc** [comment] 2016-06-17 20:23
Looks like it fails to render when using plotly version >= 1.3.0.  

http://codepen.io/anon/pen/VjKLKa

**Comment by etpinard** [comment] 2016-06-17 20:25
@bombaci-vsc this bug is a side-effect of https://github.com/plotly/plotly.js/pull/112

**Comment by bombaci-vsc** [comment] 2016-06-17 20:40
I have a similar case which partially renders (rather than not at all).  I was going to write a ticket, but I'm thinking it has the same underlying cause.

http://codepen.io/anon/pen/Gqjgxp 

It appears to happen when the plotted values can't be represented in a 32 bit float.

**Comment by etpinard** [comment] 2016-06-17 20:58
@bombaci-vsc Yep. Looks like the same issue. No need for another ticket.

**Comment by alexcjohnson** [comment] 2017-12-01 22:07
@bcdunbar in #2190 brought up that this is a pretty easy problem to encounter with date axes. The good news is gl2d doesn't have this limitation (see [gl2d_date_axes.png](https://github.com/plotly/plotly.js/blob/master/test/image/baselines/gl2d_date_axes.png)), so (presumably?) we know exactly what's needed to fix it in gl3d.

**Comment by brian428** [comment] 2018-01-31 16:15
If the cause of the problem is known, any idea when this will be addressed? We could really use the 3d scatter plot for our app, but this issue with the time axis is a blocker.

**Comment by etpinard** [comment] 2018-01-31 16:37
@brian428 can you share a reproducible example of the problem you're seeing. Perhaps it's unrelated to this ticket.

**Comment by brian428** [comment] 2018-01-31 16:55
@etpinard Here is a fiddle showing the problem with date axis and 3D scatter. No console errors, and the axes and legend render, but no trace data is shown. When we use non-date axes for all 3 axes, things plot correctly.  http://jsfiddle.net/brian428/pq74L32h/

**Comment by brian428** [comment] 2019-03-04 16:30
Just thought I'd check back on this again, since it's been open for 3 years now. It makes the 3D scatter plot unusable for anyone who needs to plot date/time-related data.

**Comment by brian428** [comment] 2019-10-08 17:35
And again, just trying to see if this is on anyone's radar?

**Comment by brian428** [comment] 2020-03-10 18:34
Just bumping this to see if this bug is on the roadmap any time soon.

**Comment by jackparmer** [comment] 2020-09-10 19:26
This issue has been tagged with `NEEDS SPON$OR`

A [community PR](https://github.com/plotly/plotly.js/pulls?q=is%3Apr+is%3Aopen+label%3A%22type%3A+community%22) for this feature would certainly be welcome, but our experience is deeper features like this are difficult to complete without the Plotly maintainers leading the effort.

**Sponsorship range: $10k-$15k**

What Sponsorship includes:
- Completion of this feature to the Sponsor's satisfaction, in a manner coherent with the rest of the Plotly.js library and API
- Tests for this feature
- Long-term support (continued support of this feature in the latest version of Plotly.js)
- Documentation at [plotly.com/javascript](https://plotly.com/javascript/)
- Possibility of integrating this feature with Plotly Graphing Libraries (Python, R, F#, Julia, MATLAB, etc)
- Possibility of integrating this feature with Dash
- Feature announcement on [community.plotly.com](https://community.plotly.com/tag/announcements) with shout out to Sponsor (or can remain anonymous)
- Gratification of advancing the world's most downloaded, interactive scientific graphing libraries (>50M downloads across supported languages)

Please include the link to this issue when [contacting us](https://plotly.com/get-pricing/) to discuss.

**Comment by gvwilson** [comment] 2024-06-05 16:52
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson

**Closed by gvwilson** 2024-06-05 16:52 UTC
Labels: type: bug, ♥ NEEDS SPON$OR
