### ISSUE TITLE
Regression: touch to simulate hover on scatter plots

### ISSUE THREAD

**Issue by alubbock** [plotly/plotly.js#1967] opened 2017-08-22 23:18 UTC
On touch devices, scatter plots used to have "touch to simulate hover" in Plotly 1.28.3, but this seems to have been removed in Plotly 1.29 and later. Is this a regression/bug?

Can touch to simulate hover (Plotly 1.28.3):
https://codepen.io/anon/pen/YxvzZR

Cannot touch to simulate hover (Plotly latest - 1.30.0 at time of writing):
https://codepen.io/plotly/pen/WvPgPP

The two examples are the same except for the Plotly version. Behaviour verified on Ipad running iOS 10.3.2 and a mobile phone running Android 6.0

**Comment by etpinard** [comment] 2017-08-23 14:07
Some _native_ touch interactions were added in https://github.com/plotly/plotly.js/pull/1804 and released in `1.29.0`.

> On touch devices, scatter plots used to have "touch to simulate hover"

I'm not sure what you're referring to here. Can you be more specific?

**Comment by alubbock** [comment] 2017-08-23 15:31
On the desktop, hovering the cursor over data points shows the y-axis values and the trace labels by default (shown below). On mobile/tablet, tapping on the plot near data points would achieve the same effect on Plotly 1.28.3 - it was a way to see the actual trace values, which doesn't now seem possible on mobile devices.

![image](https://user-images.githubusercontent.com/2590257/29624226-236783ce-87ee-11e7-881e-73f2b8578c8b.png)

**Comment by bluppfisk** [comment] 2017-12-01 08:23
Confirmed on Firefox and Chrome on Nokia 6 (Android 7.1) and iPad Air 2 (iOS 11).

**Comment by swiperii** [comment] 2018-01-24 13:10
I also have these problems. 

@etpinard 
> Some native touch interactions were added in #1804 and released in 1.29.0.

What does this mean for the ability to select points on touch events? 

I can currently handle point selection logic from mouse events (using the `onClick=...` prop in react-plotly.js). How can I get the same behaviour for touch events? I tried the touchHandler method demonstrated in [this codepen example](https://codepen.io/MalinaKirn/pen/ZJXxyg) (as referenced in #480 but it doesn't seem to work anymore.

**Comment by Haimrik** [comment] 2018-02-03 21:00
Subscribed. Any solution for that? 
On the latest v1.33.1 i still cant do the touch on mobile like on v1.28.3

**Comment by RichardNeill** [comment] 2018-08-29 13:38
This also affects large (wall-mounted) touchscreens using traditional desktop browsers.

**Comment by fourgates** [comment] 2018-08-29 15:18
I'm using the latest, 1.40.1, and this issue still persists. Is there any progress or ETA on this?

Since this worked but is now broken, is this something a contributor could help fix?

**Closed** 2018-09-18 15:16 UTC
Labels: type: regression
