### ISSUE TITLE
Allow Plotly.extendTraces() to support multiple trace types

### ISSUE THREAD

**Issue by bcliang** [plotly/plotly.js#3703] opened 2019-04-01 04:15 UTC
The Plotly.extendTraces() api takes in the following parameters:
```javascript
/**
 * @param {Object|HTMLDivElement} gd The graph div
 * @param {Object} update The key:array map of target attributes to extend
 * @param {Number|Number[]} indices The locations of traces to be extended
 * @param {Number|Object} [maxPoints] Number of points for trace window after lengthening.
 */
```

The `update` object raises an error if a key value is undefined/null. This may happen in the case that different trace types are present within the graph div. For a simple example, consider a figure that has two traces:

1. line object with a single key, `y`
2. scatter object with two keys, `x`, and `y`

If I wish to extend either trace individually, the api will work fine:
```javascript
function rand() {
  return Math.random();
}

Plotly.plot('graph', [{y: [1,2,3].map(rand)}, 
                      {x: [0], y:[0]}]);

let cnt = 0;
setInterval(function() {
  Plotly.extendTraces('graph', {
    x: [[++cnt]],
    y: [[rand()]]
  }, [1]); // update trace 1
  
}, 300);
```
or 
```
...
  Plotly.extendTraces('graph', {
    y: [[rand()]]
  }, [0]); // only update trace 0
```
However, attempting to extend both traces within a single call will generate an error.
 
```javascript
function rand() {
  return Math.random();
}

Plotly.plot('graph', [{y: [1,2,3].map(rand)}, 
                      {x: [0], y:[0]}]);

let cnt = 0;
setInterval(function() {
  Plotly.extendTraces('graph', {
    x: [[null], [++cnt]],
    y: [[rand()], [rand()]]
  }, [0, 1]); // update both traces
  
}, 300);
```

> Uncaught Error: cannot extend missing or non-array attribute: x

I brought this up in a dash-core-components PR (https://github.com/plotly/dash-core-components/pull/461#issuecomment-478371369) in which it was recommended that I create an issue here. 

Suggested syntax for handling multiple trace types, from the discussion:
```javascript
Plotly.extendTraces(gd,
{
  y: [newY, null],
  locations: [null, newLocs]
},
[0, 1],
{
  y: [maxY, null],
  locations: [null, maxLocs]
})
```

**Comment by etpinard** [comment] 2019-04-01 15:27
Thanks for the report!

You're right `extendTraces` is a too little stringent. I'm thinking something like:

```js
function two() {
  let cnt = 0;
  setInterval(function() {
    Plotly.extendTraces('graph', {
      x: [null, [++cnt]],
      y: [[rand()], [rand()]]
    }, [0, 1]); // update both traces
  }, 300);
}
```

where that `null` in the first `x` entry would mean "skip" this coordinate could work.

**Comment by ChloeStevovitch** [comment] 2021-06-17 18:42
Hello!

Any update concerning this feature? :)

**Comment by wdroz** [comment] 2021-07-25 16:41
Hi,

So no update? should we switch to another tools? (this is blocking). If yes, any recommendations?

**Comment by gvwilson** [comment] 2024-06-14 11:54
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-14 11:54 UTC
Labels: type: feature
