### ISSUE TITLE
Mode bar auto-scale button click test is failing on Windows 

### ISSUE THREAD

**Issue by aleburato** [plotly/plotly.js#357] opened 2016-03-25 10:18 UTC
Hi guys,

on windows 8.1 tests fail with a pristine copy of the 1.7.0 source downloaded form github. Here's the log:

[testLog.txt](https://github.com/plotly/plotly.js/files/189353/testLog.txt)

Hope it helps!

**Comment by etpinard** [comment] 2016-03-25 15:59
Looks like only one test is failing. Pretty good since these tests are not often run on Windows, no :smiley:?

More specifically this mode bar [test](https://github.com/plotly/plotly.js/blob/bbb8205903cdd34ae019d5cd6a2c197e9a2550e7/test/jasmine/tests/modebar_test.js#L621-L658) is failing.

I suspect that this discrepancy is caused by that fact the mock [layout](https://github.com/plotly/plotly.js/blob/bbb8205903cdd34ae019d5cd6a2c197e9a2550e7/test/jasmine/tests/modebar_test.js#L593-L612) does not specify a layout `width` and `height` leading our [auto-scale](https://github.com/plotly/plotly.js/blob/bbb8205903cdd34ae019d5cd6a2c197e9a2550e7/src/plots/cartesian/axes.js#L108) results to differ from platform to platform.

Due to the unimportance of this issues, no plotly.js team member will dedicate time to fixing this issue.

Thanks for the report.

**Comment by aburato** [comment] 2016-03-25 16:01
Great! :) As I must develop on a windows machine, would you like me to report bugs like this one when I see them? :) Of course, I don't care at all about this particular test failing, but maybe there could be important gotchas on windows.

**Comment by etpinard** [comment] 2016-03-25 16:04
> would you like me to report bugs like this one when I see them

Yes please.

> but maybe there could be important gotchas on windows.

very true. :beers:

**Comment by etpinard** [comment] 2017-05-08 19:42
Closing due to lack of relevance.

**Closed by etpinard** 2017-05-08 19:42 UTC
Labels: type: community, type: maintenance
