### ISSUE TITLE
histogram colored bars

### ISSUE THREAD

**Issue by chriddyp** [plotly/plotly.js#1984] opened 2017-09-04 19:04 UTC
as reported in https://community.plot.ly/t/coloring-selected-range-in-histogram/5619/1

it looks like `marker.color` is documented in the schema
![image](https://user-images.githubusercontent.com/1280389/30036523-3144cd10-9182-11e7-8e7f-cf5ce6a477d6.png)

but i couldn't get it to work
![image](https://user-images.githubusercontent.com/1280389/30036533-4a717a54-9182-11e7-90ac-361efb2fda34.png)

**Comment by etpinard** [comment] 2017-09-05 12:47
Here's one that works: http://rickyreusser.com/plotly-mock-viewer/#histogram_colorscale

But really, how is `marker.color` supposed to work for histogram where `x.length` in general doesn't match `marker.color.length`?

**Comment by alexcjohnson** [comment] 2017-09-05 18:07
right, we had already discussed removing histogram colorscale functionality, at least as implemented now - see https://github.com/plotly/plotly.js/issues/420#issuecomment-287809360 and #1500 - because it only works accidentally and depends on you explicitly making the correspondence between bins and color values. But I could certainly see supporting a histogram-specific colorscale functionality, where probably you would specify it similarly to `#histogram_colorscale` but instead of a `color` array you'd connect the color to either the `x` or the `y` values.

@chriddyp the issue with doing it the way you tried is, as @etpinard alluded, the values you want to color don't match up with the values you're binning... so it's redundant (and ambiguous - what happens when two values that get binned together have different colors?) and also generally you'd want to color by either the bin value or the bin height rather than the pre-binned values.

**Comment by chriddyp** [comment] 2017-09-05 18:12
>  but instead of a color array you'd connect the color to either the x or the y values.

Yeah, that sounds right. For more context, they would likely be using this to make these types of interactions (currently made with a bar chart):
![histogram-colored-bar](https://user-images.githubusercontent.com/1280389/30075597-3b2e6c10-9244-11e7-9bf8-c64455f7aa80.gif)

**Comment by jmmease** [comment] 2017-11-28 20:14
If `marker.color` is specified as an array of numbers then perhaps an aggregate function from the transform framework (`count`, `sum`, `mean`, etc.) could be specified (e.g. `marker.coloragg`) to be applied prior to mapping the result to a final color using `marker.colorscale`.

In this case, `color=y` with `coloragg='count'` would be equivalent to coloring by bar height and `color=y` with `coloragg='mean'` would be equivalent to coloring by bar position.  But lots of other interesting possibilities would be available as well, like  `color=z` with `coloragg='median'` to color by the median of some other data array `z`.

@chriddyp @alexcjohnson @etpinard

**Comment by gvwilson** [comment] 2024-06-10 17:44
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson

**Closed by gvwilson** 2024-06-10 17:44 UTC
