### ISSUE TITLE
Charts rendering with larger left margin only in Safari.

### ISSUE THREAD

**Issue by Sschumac** [plotly/plotly.js#3861] opened 2019-05-14 00:04 UTC
This graph is rendering smaller in Safari than other browsers.
Safari: <img width="1280" alt="Screen Shot 2019-05-13 at 6 06 59 PM" src="https://user-images.githubusercontent.com/7979887/57661881-03ca7200-75aa-11e9-859a-deda96314fca.png">
Chrome: <img width="1237" alt="Screen Shot 2019-05-13 at 6 06 43 PM" src="https://user-images.githubusercontent.com/7979887/57661885-075df900-75aa-11e9-82f9-572c62c994fc.png">

Reproduction example: https://codepen.io/Sschumac2/pen/LobYvE

**Comment by etpinard** [comment] 2019-05-17 15:51
Confirmed in Safari 12 (on browserstack).

I'm thinking this has to do with Safari's default CSS, but I could be wrong.

Thanks for posting.

**Comment by etpinard** [comment] 2019-05-17 15:56
I can't get to reproduce the behavior outside of codepen.io. @Sschumac are you affected by the problem outside of codepen.io?

**Comment by Sschumac** [comment] 2019-05-20 17:21
Yes, affected in the browser environment with that exact graph.

**Comment by gvwilson** [comment] 2024-06-14 11:57
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-14 11:57 UTC
Labels: type: bug
