### ISSUE TITLE
Memory Leak in javascript Surface Plot for Edge and IE browsers

### ISSUE THREAD

**Issue by omarmussa** [plotly/plotly.js#1273] opened 2016-12-27 06:24 UTC
Running the js surface plot example in MS Edge or IE browsers exhibits a memory leak.  I used the profile tool in Edge for the surface example (http://codepen.io/plotly/pen/MaxrwW) and did not do anything (no mouse or cursor moves, no interaction with the chart) during the test.

When I run the codepen in Edge, within 100 seconds I can see the memory increase as shown in the screenshot here:
<img width="640" alt="ie memory profile" src="https://cloud.githubusercontent.com/assets/7425007/21492194/21717c94-cbb7-11e6-8301-9c18b522fcf6.png">

(notice the ramp pattern on upper edge of the total memory used)

When I run the example in Chrome and do a memory profile for 100 seconds it looks like the browser memory is doing a similar ramp pattern but it doesn't appear to have the same leak (maybe Chrome garbage collector is more efficient, not sure).  Here is the Chrome profile:
<img width="1432" alt="chrome profile" src="https://cloud.githubusercontent.com/assets/7425007/21492369/f7167cc2-cbb8-11e6-941b-6d6b5746b298.png">

(notice the upper edge of RAM used doesn't appear to ramp over time).

This issue is a major problem for me.

**Comment by etpinard** [comment] 2017-01-04 14:22
duplicate of https://github.com/plotly/plotly.js/issues/957

**Closed by etpinard** 2017-01-04 14:22 UTC
Labels: type: duplicate
