### ISSUE TITLE
Modebar download button auto-size image

### ISSUE THREAD

**Issue by marcusblevin** [plotly/plotly.js#1725] opened 2017-05-25 14:25 UTC
I would like to request the modeBarButtons.toImage function be expanded to include the current plot dimensions when creating the image. 

modeBarButtons.toImage = {
    name: 'toImage',
    title: 'Download plot as a png',
    icon: Icons.camera,
    click: function(gd) {
        var format = 'png';
        **var w = gd.offsetWidth;
        var h = gd.offsetHeight;**

        Lib.notifier('Taking snapshot - this may take a few seconds', 'long');

        if(Lib.isIE()) {
            Lib.notifier('IE only supports svg.  Changing format to svg.', 'long');
            format = 'svg';
        }

        downloadImage(gd, {'format': format, **width: w, height: h**})
          .then(function(filename) {
              Lib.notifier('Snapshot succeeded - ' + filename, 'long');
          })
          .catch(function() {
              Lib.notifier('Sorry there was a problem downloading your snapshot!', 'long');
          });
    }
};

Thanks

**Comment by etpinard** [comment] 2017-05-25 14:31
duplicate of https://github.com/plotly/plotly.js/issues/1576

**Closed by etpinard** 2017-05-25 14:31 UTC
