### ISSUE TITLE
Can't set parcoords color array as strings

### ISSUE THREAD

**Issue by slishak** [plotly/plotly.js#3793] opened 2019-04-19 13:16 UTC
Potentially related to https://github.com/plotly/plotly.js/issues/3595

I adapted the codepen from there, setting the `color` array to a list of strings, but they all come up as black:

https://codepen.io/anon/pen/OGZzXG?editors=1010

**Comment by etpinard** [comment] 2019-04-22 13:10
That's correct, `parcoords` only support numeric colorscales at the moment.

**Comment by archmoj** [comment] 2019-06-03 14:20
One may simply use `colorscale` for this. Here is [a simple codepen](https://codepen.io/MojtabaSamimi/pen/XwOoob?editors=0010).
In respect to `parcoords` implementation which is optimised for speed and the 256 texture limit, it is not recommended to give every single line different colour.
Here is [another example](https://codepen.io/MojtabaSamimi/pen/VOggay?editors=0010) with 256 different colours.

**Comment by gvwilson** [comment] 2024-06-14 11:55
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-14 11:55 UTC
Labels: type: feature
