### ISSUE TITLE
Setting a low margin top with parcoords cuts off labels and therefore ability to drag axes too

### ISSUE THREAD

**Issue by cpsievert** [plotly/plotly.js#1592] opened 2017-04-12 22:30 UTC
Initially discovered in https://github.com/ropensci/plotly/issues/945

http://codepen.io/cpsievert/pen/dWydGq

**Comment by etpinard** [comment] 2017-04-13 14:54
cc @monfera

**Comment by monfera** [comment] 2017-04-13 21:06
Thanks, I initially reported that labels / drag handles don't show up in the R example but didn't suspect it was an issue with plotly.js.

In the codepen the top margin is set to such a small value that there's no room for the heading. With `parcoords`, the margin is relative to the screen projection of the data space, which is a rectangle, formed by the tops/bottoms of the axes vertically, and leftmost/rightmost axes horizontally. If the margin above this rectangle is not enough, there won't _currently_ be room for the label.

As one option, we can let CSS `overflow: visible` happen - in this case, the label will be above the actual chart, but it's nicely separated vertically (why does it matter? -because it's a drag handle, and placing it too close to the also interactive axis wouldn't be good Fitts law wise).

As another option, I can adaptively place the labels on the top such that whatever the top margin, it tries to squeeze itself into it. E.g. if the top margin is 25, then it'd be barely offset from the axis tops, but would be visible nonetheless. 

_Personal_ thought, it would look a bit unbalanced and there's also Fitts law so I'm not sure why we'd _want_ to place the labels significantly closer to the axis tops, is there actual use case for it?

Another thing I mentioned about the R doc page is that with parcoords, the panels are typically square-ish as much as possible, because very steep lines and their crossings are hard to read and interpret e.g. as densities in the point->line space, while our R example was quite tall compared to its width and looked a bit unusual. So maybe if we taylor the demos such that they follow some of the above principles then the issue doesn't arise.

I probably miss legit use cases or plotly standards to follow, so please advise what I'm missing and what resolution it leads to.

**Comment by monfera** [comment] 2017-04-13 21:09
I changed the title because the issue isn't caused by setting margins in general, e.g. this example works fine: http://codepen.io/anon/pen/JNoKdx

**Comment by monfera** [comment] 2017-04-13 21:17
One more thing, on axes with continuous domain, there can be an extent value on the top/bottom which also uses up some space. Since the extent values aren't interactive hotspots, in some way they're also acting as a Fitts buffer between the label and the axis itself that doubles as an interactive filter.

**Comment by gvwilson** [comment] 2024-06-10 14:05
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson

**Closed by gvwilson** 2024-06-10 14:05 UTC
Labels: type: bug
