### ISSUE TITLE
Smarter defaults for layout.hovermode

### ISSUE THREAD

**Issue by joshua-gould** [plotly/plotly.js#778] opened 2016-07-26 14:24 UTC
Please see http://codepen.io/anon/pen/akKOvE for an example.

**Comment by etpinard** [comment] 2016-07-28 14:29
Confirmed. Thanks.

**Comment by etpinard** [comment] 2017-02-09 23:05
Looking at this issue again, I'm thinking this is the desired behavior under `layout.hovermode: 'x'` which is the default in your case because not all traces are _horizontal_ (see logic [here](https://github.com/plotly/plotly.js/blob/32ccae5a5e86bcd8c974fea923436223d6fb723d/src/plots/cartesian/graph_interact.js#L46-L54)).

Setting `layout.hovermode` to either `'y'` or `'closest'` gives the desired behavior.

**Comment by alexcjohnson** [comment] 2017-08-15 22:28
setting `layout.hovermode` to `'y'` in this case mucks up hover for the rug trace, so that's not a good option. But I think what this points to is that "compare" mode is only a good default hover mode in certain (albeit very common) cases - where there are multiple traces of the same type with monotonic data mostly in common for the "compare" axis. What we should really do is default to `'closest'` if any of those conditions is not met. That would help in even relatively simple cases like one or more scatter traces with nonmonotonic points (and perhaps we could even figure out if it's `y` that's monotonic instead of `x` and switch to `hovermode: 'y'`). Renaming this issue accordingly.

**Comment by etpinard** [comment] 2018-05-23 17:32
Adding this to the v2 milestone

**Comment by archmoj** [comment] 2021-05-20 22:38
We could possibly close this now that `hovermode` is going to default to `closest` in v2. Right?

**Comment by nicolaskruchten** [comment] 2021-05-20 23:17
Yes.

**Closed by nicolaskruchten** 2021-05-20 23:17 UTC
Labels: type: feature
