### ISSUE TITLE
heatmap yaxis category axes can support sequence ?

### ISSUE THREAD

**Issue by phiedulxp** [plotly/plotly.js#2570] opened 2018-04-18 03:00 UTC
I change Annotated Heat Map with Plotly.js Charts demo to:
`
var xValues = ['A', 'B', 'C', 'D', 'E'];

var yValues = ['W', 'X', 'Y', 'Z','W', 'X', 'Y', 'Z'];

var zValues = [
  [0.00, 0.00, 0.75, 0.75, 0.00],
  [0.00, 0.00, 0.75, 0.75, 0.00],
  [0.75, 0.75, 0.75, 0.75, 0.75],
  [0.00, 0.00, 0.00, 0.75, 0.00],
  [0.75, 0.75, 0.75, 0.75, 0.75],
  [0.00, 0.00, 0.00, 0.75, 0.00],
  [0.75, 0.75, 0.75, 0.75, 0.75],
  [0.00, 0.00, 0.00, 0.75, 0.00],
  [0.75, 0.75, 0.75, 0.75, 0.75]
];
`
but yaxis only show 'W', 'X', 'Y', 'Z' as 'W', 'X', 'Y', 'Z','W', 'X', 'Y', 'Z' is expected.

**Comment by phiedulxp** [comment] 2018-04-18 05:59
As I add yaxis  sequence to 100+ items, some item just hide to fit the height of canvas.

**Comment by alexcjohnson** [comment] 2018-04-18 12:41
duplicate of https://github.com/plotly/plotly.js/issues/1516 - see in particular the [`ticktext/tickvals` workaround posted there](https://github.com/plotly/plotly.js/issues/1516#issuecomment-289139760)

**Closed by alexcjohnson** 2018-04-18 12:41 UTC
