### ISSUE TITLE
Highlighting the range selected by the user in Line/Bar Chart.

### ISSUE THREAD

**Issue by gk-patel** [plotly/plotly.js#4076] opened 2019-07-24 07:13 UTC
Hi Team Plotly,

It would be nice to have a possibility to highlight a particular range selected by the user in line/bar charts. In order to make my feature-request more clear, I would like to explain my use-case:

Many times, I have a line/bar chart wherein a user is allowed to select a particular range. After the selection is done, an HTTP request is sent to update other charts in the dashboard, but the content of the line/bar chart is not to be update. In this case, I would like to indicate to the user what they have selected by highlighting the portion they previously selected (i.e. before the HTTP request was sent). 

This feature could be very easy to implement by adding an attribute called "highlight", which could take a JSON contain keys "x" and "y" that contain a list of two values defining the range to be highlighted. For example, `highlight={ "x": [1,5], "y": [3,6] }`. 

After the HTTP request is send, the chart would look as shown below, (i.e. it would retain the selection made by the user).
![image](https://user-images.githubusercontent.com/42677721/61772496-bf9dee00-adf2-11e9-9061-9893a8905270.png)

Moreover, it would be nice if the user could interactively adapt the highlighted-range, for example to send a new HTTP request. 

You guys do have something similar to what I am asking, but somehow it always apprears as a seperate range-selection component (e.g. https://plot.ly/python/range-slider/). But, it would be good to have highlighting and range-selection-effect integrated into the main line/bar chart.

**Comment by gvwilson** [comment] 2024-06-14 12:47
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-14 12:47 UTC
