### ISSUE TITLE
Plotly hover popup location misalignment issue after applying css transform scale 

### ISSUE THREAD

**Issue by contactsandygo** [plotly/plotly.js#4343] opened 2019-11-08 17:30 UTC
Due to a specific requirement of fitting multiple charts which are added dynamically and arranged  horizontally in available viewport without scroll I am using transform scale for example  transform: translateZ(0) scale(0.50, 0.50) on charts based on available space, although the whole chart is scaled down uniformly but when mouse hover over is done on chart I observe  there is offset between mouse location and hover popup location  shown in attached screen shot 

![tooltipissue](https://user-images.githubusercontent.com/31977079/68498153-2d481b80-0224-11ea-9fc5-353199d7984a.jpeg)

   

Using resize() or relayout does not give crisp chats when they are scale down due to uneven transform of chart and labels. 

![issue](https://user-images.githubusercontent.com/31977079/68498019-e6f2bc80-0223-11ea-90a1-11328ceb9d55.png)

I have created code pen to explain issue 
https://codepen.io/contactsandygo/pen/wvvXdov

Regards
San

**Comment by etpinard** [comment] 2019-11-18 16:51
This appears like a duplicate of https://github.com/plotly/plotly.js/issues/888

**Comment by etpinard** [comment] 2019-11-19 23:19
Merging into https://github.com/plotly/plotly.js/issues/888

**Closed** 2019-11-19 23:19 UTC
