### ISSUE TITLE
[FEAT] "x unified" hover mode working across subplots

### ISSUE THREAD

**Issue by emmanuelle** [plotly/plotly.js#4755] opened 2020-04-11 14:56 UTC
This would make it possible to display the information of several subplots in the same hoverbox. Probably this would need an attribute since this behaviour is not desired in all cases.

**Comment by alexbhatt** [comment] 2020-07-01 18:33
it would be most helpful, particularly in visualizing across COVID time series for multiple graphs; linked across R and python functionality.

**Comment by GitJJ** [comment] 2020-07-15 05:31
I would also find this feature particularly useful.

**Comment by schoolie** [comment] 2020-08-12 18:14
+1, would love to see this feature.

**Comment by g-deoliveira** [comment] 2020-08-14 02:10
+1, this would be great

**Comment by nicolaskruchten** [comment] 2020-08-14 12:35
Thanks for the enthusiasm, folks! It's a good feature and we'd love to have it in the library but it's not on anyone's roadmap at the moment. That said, we as maintainers would be happy to help someone from the community to implement it, or to accept [sponsorship](https://plot.ly/products/consulting-and-oem/) to get it on to our short-term roadmap :)  

A few notes re how this might work at the schema/behaviour level... This would need to be one or likely a few new accepted values for `hovermode`: we currently accept `closest`, `x` and `x unified`. In both the latter cases, hovering over a trace linked to a given pair of x and y axes causes hover labels to appear for each trace linked the same x/y axis pair. We would need a variant on both `x` and `x unified`, perhaps something like `all x` and `all x unified`, which would cause hover labels to appear for every trace linked to the same x axis, regardless of y axis. We would also need to think about "matched" axes, and this could be yet another flavour of `hovermode` (`all x` and `matched x`?). We'd also need to think about what this would visually look like in `unified` mode: would there be one unified label per x/y pair or one big unified label near the cursor? We'd also need to take into consideration spikelines, especially with matched axes.

**Comment by addarnr** [comment] 2020-08-14 14:10
The solution for this issue is at the link below.
https://stackoverflow.com/questions/63358465/scope-in-python-subplot-similar-to-matlabs-stackedplot

**Comment by nicolaskruchten** [comment] 2020-08-14 14:57
> The solution for this issue is at the link below

That question isn't about plotly ... ?

**Comment by immartian** [comment] 2021-04-05 04:34
> it would be most helpful, particularly in visualizing across COVID time series for multiple graphs; linked across R and python functionality.

exactly, like this one https://covid19-projections.com/path-to-herd-immunity/

**Comment by POI-Root** [comment] 2021-10-04 06:46
+1, this would be very helpful

**Comment by yhmickey** [comment] 2021-11-29 13:09
+1

**Comment by InvisOn** [comment] 2021-12-04 22:03
Using the [Generic Crossfilter Recipe](https://dash.plotly.com/interactive-graphing) may be a suitable alternative for some people. I've used it with some success to highlight points across subplots.

**Comment by GreekQuant** [comment] 2021-12-11 14:43
+1

**Comment by GlebMorgan** [comment] 2021-12-16 14:12
+1

**Comment by nicolaskruchten** [comment] 2021-12-16 14:18
Yes, this is a duplicate of #2114 and in the same state: it's very unlikely that anyone on the Plotly team can work on this without a financial sponsor, although we'd be happy to work with someone from the community who wants to implement this themselves and submit a pull request.

**Comment by Disorrder** [comment] 2023-05-26 16:03
+1

**Comment by Sank-WoT** [comment] 2023-07-20 02:54
+1

**Comment by jacobrichey** [comment] 2023-07-28 21:25
+1

**Comment by rudolferemyan** [comment] 2023-09-17 07:36
+1

**Comment by SIDD2310** [comment] 2023-09-27 13:14
+1

**Comment by MarcSkovMadsen** [comment] 2023-11-17 08:46
+1. Would love this feature too.

**Comment by loicduffar** [comment] 2023-12-15 19:39
+1
Still not in the road map ?

**Comment by Sladerix** [comment] 2024-01-12 15:04
+1

**Comment by Episkiliski** [comment] 2024-01-12 15:41
+1

**Comment by AlanCPSC** [comment] 2024-01-21 06:43
+1
Related bug here: [add_hline() breaks when axis is shared](https://github.com/plotly/plotly.py/issues/3209)

**Comment by walkerpayne** [comment] 2024-02-02 18:23
+1 :)

**Comment by chikko80** [comment] 2024-03-09 13:05
+1

**Comment by Cian-Byrne** [comment] 2024-03-11 10:30
+1

**Comment by drypatrick** [comment] 2024-03-13 12:15
+1

**Comment by sde-cdsp** [comment] 2024-03-15 10:52
+1

**Comment by giudici-uturn** [comment] 2024-03-19 12:49
+1

**Comment by raja-jain-skydio** [comment] 2024-03-28 19:22
+1

**Comment by drypatrick** [comment] 2024-04-02 13:11
I found how to make it works, check out the [codepen](https://codepen.io/drypatrick/pen/LYvOKjv?editors=0010)

**Comment by archmoj** [comment] 2024-04-05 22:53
This would be resolved by #6947.

**Closed** 2024-04-09 18:39 UTC
Labels: ♥ NEEDS SPON$OR
