### ISSUE TITLE
sankey: display group information

### ISSUE THREAD

**Issue by antoinerg** [plotly/plotly.js#3761] opened 2019-04-11 17:05 UTC
As of right now, grouped nodes are visually the same as normal nodes. Maybe they should be distinguishable?

@nicolaskruchten

**Comment by nicolaskruchten** [comment] 2019-04-11 19:46
see also #3760 !

**Comment by nicolaskruchten** [comment] 2019-04-11 19:46
I think we should have grouped style attrs for sure... thicker lines or something. double lines?

**Comment by gvwilson** [comment] 2024-06-14 11:55
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-14 11:55 UTC
Labels: type: feature
