### ISSUE TITLE
Add RTL for mapbox

### ISSUE THREAD

**Issue by rahimramezanian** [plotly/plotly.js#2390] opened 2018-02-21 06:09 UTC
There is a mapbox library

[https://github.com/mapbox/mapbox-gl-rtl-text](https://github.com/mapbox/mapbox-gl-rtl-text)

which fixes the right to left names over map. It will be nice to add this feature too.

**Comment by alexcjohnson** [comment] 2018-02-21 14:31
Thanks, that does seem like a nice feature to add. I'm not sure though that I would know what success looks like, not being familiar with any RTL languages and specifically how they're used on maps. But we would be happy to look at a pull request that includes a test image locking down how it works!

**Comment by etpinard** [comment] 2018-02-21 15:17
Hmm. This would add minified `200kb` to our mapbox bundles. Maybe it would be best to come up with a plugin system for mapbox plugins?

**Comment by gvwilson** [comment] 2024-06-11 17:02
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson

**Closed by gvwilson** 2024-06-11 17:02 UTC
Labels: type: feature, type: community
