### ISSUE TITLE
barmode, barnorm, bargap, and bargroupgap not documented in reference

### ISSUE THREAD

**Issue by jdugge** [plotly/plotly.js#1503] opened 2017-03-21 14:31 UTC
The layout options for bar graphs `barmode`, `barnorm`, `bargap`, and `bargroupgap`, which are defined and described in [src/traces/bar/layout_attributes.js](https://github.com/plotly/plotly.js/blob/43d3710bdb183f9c1681f40efe8649a7238efce5/src/traces/bar/layout_attributes.js), do not appear in the [Full Reference](https://plot.ly/javascript/reference/).

I guess the documentation is generated automatically, so presumably this file was just missed?

**Comment by etpinard** [comment] 2017-03-21 14:34
duplicate of https://github.com/plotly/documentation/issues/202

**Closed by etpinard** 2017-03-21 14:34 UTC

**Comment by jdugge** [comment] 2017-03-21 14:35
Oops, I missed that! Sorry for the noise
