### ISSUE TITLE
Make input formatting configurable in AxisRangeEntryBoxes

### ISSUE THREAD

**Issue by lenhatnguyen** [plotly/plotly.js#4428] opened 2019-12-17 04:55 UTC
When i choose min max but it allway auto format d3.format('.' + dig + 'g') in getEndText method . Is there any way to don't round it.

![Capture](https://user-images.githubusercontent.com/9036390/70965920-ec191600-20c3-11ea-8edb-e20383a2c853.PNG)

    function getEndText(ax, end) {
    var initialVal = ax.range[end];
    var diff = Math.abs(initialVal - ax.range[1 - end]);
    var dig;
    // TODO: this should basically be ax.r2d but we're doing extra
    // rounding here... can we clean up at all?
    if(ax.type === 'date') {
        return initialVal;
    } else if(ax.type === 'log') {
        dig = Math.ceil(Math.max(0, -Math.log(diff) / Math.LN10)) + 3;
        return d3.format('.' + dig + 'g')(Math.pow(10, initialVal));
    } else { // linear numeric (or category... but just show numbers here)
        dig = Math.floor(Math.log(Math.abs(initialVal)) / Math.LN10) -
            Math.floor(Math.log(diff) / Math.LN10) + 4;
        return d3.format('.' + String(dig) + 'g')(initialVal);
    }
}

**Comment by etpinard** [comment] 2019-12-24 21:32
So if I understand correctly, you have a graph similar to

```js
Plotly.newPlot('graph', [{
  y: [0, 440e6]
}], {
  yaxis: {
    range: [0, 441123321]
  },
  width: 500,
  height: 500
})
```

In codepen form: https://codepen.io/etpinard/pen/XWJgjdM?editors=1010

When clicking the upper-left corner of the main subplot (to edit the `yaxis.range[1]`) you get something like:

![Peek 2019-12-24 16-26](https://user-images.githubusercontent.com/6675409/71425390-2e18fd80-266a-11ea-964a-e451074a2412.gif)

But you'd like to see to full unformated `yaxis.range[1]` value instead i.e. `441123321` in my example.

----

If that's indeed what you're looking for, unfortunately we don't expose a way to customize the behavior at the moment. This could be an interesting addition to the library though, probably via a new axis attribute. 

You correctly spotted the lines responsible for the current behavior in `dragbox.js`:

https://github.com/plotly/plotly.js/blob/4137ed22c957aa088bf9e30861c84056f9347a94/src/plots/cartesian/dragbox.js#L965-L982

Thanks very much for posting!

**Comment by lenhatnguyen** [comment] 2019-12-31 02:07
Exactly. I hope to receive it in the future. Thanks

**Comment by gvwilson** [comment] 2024-06-14 12:55
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-14 12:55 UTC
Labels: type: feature
