### ISSUE TITLE
TypedArrays as mesh3d attributes

### ISSUE THREAD

**Issue by dfcreative** [plotly/plotly.js#2319] opened 2018-02-01 18:56 UTC
Sometimes 3d data, like [simplicial-complex](https://www.npmjs.com/package/simplicial-complex), has _TypedArray_ format, eg. _Float32Array_ for positions and _Uint32Array_ for cell indices:

```js
  // positions = Float32Array
  // cells = Uint32Array

  Plotly.plot(document.body, [{
    "x": positions.filter((p, i) => !(i % 3)),
    "y": positions.filter((p, i) => !((i-1) % 3)),
    "z": positions.filter((p, i) => !((i-2) % 3)),
    "i": indices.filter((p, i) => !(i % 3)),
    "j": indices.filter((p, i) => !((i-1) % 3)),
    "k": indices.filter((p, i) => !((i-2) % 3)),
  }])
```

Would be nice for plotly to be able to deal with TypedArrays and not force users cast data to exact datatype.

**Comment by etpinard** [comment] 2018-02-01 19:00
duplicate of https://github.com/plotly/plotly.js/issues/860

**Closed** 2018-02-01 19:02 UTC
