### ISSUE TITLE
Event that emits only new points of selection event

### ISSUE THREAD

**Issue by cpsievert** [plotly/plotly.js#2357] opened 2018-02-09 23:18 UTC
I already have a (more general) model for persistent selection in the R interface and being able to directly access only the *newly* selected points (rather than *all* selected points) would improve performance on my end and help me avoid [doing this workaround](https://github.com/ropensci/plotly/commit/a847c7478dd07d01c909ba0015e8ead805d3263a). See [this issue](https://github.com/ropensci/plotly/issues/1195) for a bit more context.

**Comment by alexcjohnson** [comment] 2018-02-11 00:18
Good idea, seems useful. Would it work for you if we added this information to the existing event data, rather than making a new event? So in addition to `points` we'd have `pointsAdded` and `pointsRemoved` perhaps.

Thinking about `plotly_selecting` vs `plotly_selected` - I suppose they should independently manage their added/removed lists, ie `plotly_selecting` would show one point added or removed at a time, but `plotly_selected` would show all changed points since the previous `plotly_selected` event. Sound right?

**Comment by cpsievert** [comment] 2018-02-11 18:20
Yea, sounds good!

**Comment by gvwilson** [comment] 2024-06-11 17:01
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson

**Closed by gvwilson** 2024-06-11 17:01 UTC
Labels: type: feature
