### ISSUE TITLE
scatter3D plot time series problems

### ISSUE THREAD

**Issue by seziCZ** [plotly/plotly.js#3155] opened 2018-10-25 10:41 UTC
Scatter 3D plot suffers of multiple problems if time series to be rendered fits in window smaller than ~4 hours:

https://codepen.io/sezicz/pen/QZzjZM - single point, only axis names are displayed
https://codepen.io/sezicz/pen/KGbdpN - two points in one second, only axis names are displayed
https://codepen.io/sezicz/pen/WaLQpG - two points in one minute, plot is broken
https://codepen.io/sezicz/pen/PyXPdN - two points in one hour, z axis lables are shifted

**Comment by alexcjohnson** [comment] 2018-10-25 14:10
Thanks for pointing this out! It looks like we have a timezone issue here, where the range over which to draw ticks gets shifted by the UTC time zone offset, yet the ticks we end up drawing have the correct values for where they were drawn.

**Comment by etpinard** [comment] 2018-10-25 14:20
Might be related (unfortunately) to https://github.com/plotly/plotly.js/issues/2646

**Comment by gvwilson** [comment] 2024-06-11 17:28
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson

**Closed by gvwilson** 2024-06-11 17:28 UTC
Labels: type: bug
