### ISSUE TITLE
showLink link reloads the page in Angular app

### ISSUE THREAD

**Issue by MarcSerretCRG** [plotly/plotly.js#3921] opened 2019-05-29 09:33 UTC
The showLink link reloads the current page in Chrome and reloads the page in Firefox and open the edit page.

I'm using Angular 7 and Plotly 1.47.4.
I can't include codepens because the page doesn't support a large Angular project .

**Comment by etpinard** [comment] 2019-06-07 19:41
By _showLink_, I assume you're referring to https://plot.ly/javascript/configuration-options/#display-the-edit-chart-link - @MarcSerretCRG can you confirm?



> I'm using Angular 7

In https://github.com/plotly/plotly.js/issues/3700, a user was able to reproducible an Angular-only bug using stackblitz (example: https://stackblitz.com/edit/angular-eezqzs?file=src%2Findex.html), I wonder if the problem described here could only be reproduced in stackblitz.

**Comment by etpinard** [comment] 2019-09-26 20:55
Closing due to lack of reproducible example.

Feel free to open another issue if you can provide code that recreates the problem in a control environment.

**Closed by etpinard** 2019-09-26 20:55 UTC
