### ISSUE TITLE
Responsive figure with locked aspect ratio

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.js#3467] opened 2019-01-23 18:12 UTC
Right now if I have a container that's got a constrained width but an unconstrained height (like, say, a Jupyter Notebook output cell ;) then I can make my figure responsive, which will cause it to fill the available width, but then I have to explicitly set the height of the figure. It would be really great to be able to set the desired aspect ratio such that the heigh would depend on the responsive width (and vice versa)

**Comment by antoinerg** [comment] 2019-01-23 19:13
The following CSS trick can help with this scenario: https://spin.atomicobject.com/2015/07/14/css-responsive-square/

Here's an example of it in action: https://codepen.io/anon/pen/GzJjKL

Because this CSS trick is subtle, maybe it should be managed by plotly.js.

**Comment by eMaringolo** [comment] 2019-03-22 21:14
The trick is a good workaround for single plots, but won't work for subplots. 

It would be great to be able to display independent subplots using a constrained ratio (or at least unconstrained/square).

**Comment by etpinard** [comment] 2019-03-22 21:16
> It would be great to be able to display independent subplots using a constrained ratio

You must be looking for:

- https://plot.ly/javascript/reference/#layout-xaxis-scaleanchor
- https://plot.ly/javascript/reference/#layout-yaxis-scaleratio
- https://plot.ly/javascript/reference/#layout-yaxis-constrain

**Comment by gvwilson** [comment] 2024-06-11 17:39
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson

**Closed by gvwilson** 2024-06-11 17:39 UTC
Labels: type: feature
