### ISSUE TITLE
Transforms don't work correctly while interacting during animation

### ISSUE THREAD

**Issue by rreusser** [plotly/plotly.js#1293] opened 2017-01-11 20:18 UTC
For reference, here is a plot illustrating interaction during animation with all of the current restrictions removed (which amounted to locking out dragbox events while transitions are taking place). Solving these issues requires getting pretty far into the weeds regarding transforms etc.

https://rreusser.github.io/demos/plotly-unsupported/interaction-failure.html

cc @etpinard @alexcjohnson  @bpostlethwaite

**Comment by bpostlethwaite** [comment] 2017-01-11 20:23
I think you meant to tag @alexcjohnson instead of @alexander-daniel :)

**Comment by rreusser** [comment] 2017-01-11 21:03
To be clear, this is the behavior that results if the interaction-during animation restriction is removed. It's not the worst, but it's not the best.

**Comment by bpostlethwaite** [comment] 2017-01-11 21:05
what are some of the "not best" things you see?

**Comment by rreusser** [comment] 2017-01-11 21:46
If you mousewheel zoom, the trace zooms correctly while animating 🎉 

Then once you're done, it transitions back to the initial axis limits before transitioning *back* to the new correct axis limits. 😞 

Dragging a zoom box is similar. It's not the worst. If we need to enable this we need to enable it and we can tick off corner cases. I had trouble managing exactly *when* the interaction transformation is removed relative to the animation updates since there aren't really any guarantees that API commands finish all of there asynchronous updates before another might be triggered.

**Comment by bpostlethwaite** [comment] 2017-01-11 21:47
@alexcjohnson I have no idea what any of this means. Are you able to help out here?

**Comment by rreusser** [comment] 2017-01-11 21:48
![ezgif com-a4d67ca066](https://cloud.githubusercontent.com/assets/572717/21867781/bfaa7efc-d81d-11e6-909a-4eac0cf0d1d5.gif)

**Comment by rreusser** [comment] 2017-01-11 21:49
It also seems that mousewheel zooms don't always complete successfully. Sometimes it snaps back to the original limits instead of properly updating. The above gif is a bit confusing but shows what should be pretty simple zooming in and out being pretty all over the place.

**Comment by alexcjohnson** [comment] 2017-01-11 23:38
What's going on here is that during these drags, I do funny things with what the axis thinks its range is. That's because:
- The plot area itself doesn't get redrawn, just rescaled, until the end, so during the interaction it doesn't care what the axis thinks its range is
- But the ticks, grids, and labels DO get completely redrawn at every step, so they need to think the axis has its new range
- Then at the end, we redraw the plot area. In order to make sure it really redraws, and to get the `undoit` value correct, I first put the axis range back to what it was before, and then call `relayout` to set it to the new value. This, presumably, is what is causing it to look like it jumps back to the old value and transitions to the new one.

So I suspect if we don't include the intermediate reset to the original range, this problem would go away. Maybe we don't actually care about including these transitions in undo/redo? Maybe we already don't? Maybe it would just work to `relayout` from the final range to the same values with no actual changes, or maybe we need to insert an infinitesimal change just to force a redraw? Or maybe we don't use `relayout` at all for this, and just go straight to the redraw, which could then be done more granularly, esp. with subplots. Just some thoughts.

@rreusser and I also chatted just now about, before we go for the full fix, whether we can keep the zoom/pan interactions disabled but enable other interactions (notably click).

**Comment by rreusser** [comment] 2017-01-11 23:40
@alexcjohnson Yeah, I worked through a moderate share of the details but had a tricky time figuring out a few of the subtleties and then just _had_ to move on without fully resolving it. I'll submit a patch to enable `plotly_click` and then may have to ping you regarding specific pain points to get a more complete fix through.

cc @bpostlethwaite

**Comment by jacobq** [comment] 2018-03-07 21:20
@rreusser the link in your original post appears to be broken (domain parked). I'd like to see if this is related to the `transform: scale(0.5)` problem I have: https://jsbin.com/dogefe/9/edit?js,output.

**Comment by jackparmer** [comment] 2020-09-10 19:57
This issue has been tagged with `NEEDS SPON$OR`

A [community PR](https://github.com/plotly/plotly.js/pulls?q=is%3Apr+is%3Aopen+label%3A%22type%3A+community%22) for this feature would certainly be welcome, but our experience is deeper features like this are difficult to complete without the Plotly maintainers leading the effort.

**Sponsorship range: $45k-$50k**

What Sponsorship includes:
- Completion of this feature to the Sponsor's satisfaction, in a manner coherent with the rest of the Plotly.js library and API
- Tests for this feature
- Long-term support (continued support of this feature in the latest version of Plotly.js)
- Documentation at [plotly.com/javascript](https://plotly.com/javascript/)
- Possibility of integrating this feature with Plotly Graphing Libraries (Python, R, F#, Julia, MATLAB, etc)
- Possibility of integrating this feature with Dash
- Feature announcement on [community.plotly.com](https://community.plotly.com/tag/announcements) with shout out to Sponsor (or can remain anonymous)
- Gratification of advancing the world's most downloaded, interactive scientific graphing libraries (>50M downloads across supported languages)

Please include the link to this issue when [contacting us](https://plotly.com/get-pricing/) to discuss.

**Comment by gvwilson** [comment] 2024-06-06 15:14
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson

**Closed by gvwilson** 2024-06-06 15:14 UTC
Labels: type: bug, ♥ NEEDS SPON$OR
