### ISSUE TITLE
Fully orientable 3d markers

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.js#4372] opened 2019-11-20 15:10 UTC
Right now in scatter3d we have 2d markers, and in cone we have partially-orientable 3d markers (symmetric about 1 axis). What about spherical markers? Cube-shaped markers that are fully-orientable? Or even axis-aligned cube-shaped markers? Same as voxels? #4371

**Comment by gvwilson** [comment] 2024-06-14 12:52
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-14 12:52 UTC
Labels: type: feature
