### ISSUE TITLE
Pyramid diagrams

### ISSUE THREAD

**Issue by archmoj** [plotly/plotly.js#4582] opened 2020-02-14 00:44 UTC
It might be of interest to add the `orientation` option to flip `funnelarea` and make Pyramid Diagrams.

**Comment by gvwilson** [comment] 2024-06-14 12:56
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-14 12:56 UTC
Labels: type: feature
