### ISSUE TITLE
Uncaught in promise: Mapbox error

### ISSUE THREAD

**Issue by jackparmer** [plotly/plotly.js#2345] opened 2018-02-07 04:35 UTC
This map throws a Mapbox+Plotly.js console error on load and does not fire any selection events afterwards:
`Uncaught (in promise) Error: Mapbox error.`

https://plot.ly/~jackp/18343/

This map is the exact same Plotly graph, but has different geojson overlayers. It does not fire any console errors and responds to selection events.

https://plot.ly/~jackp/18345/

I'm guessing mapbox-gl is having an issue with the geojson in Graph1, but not in Graph2. The geojson for problematic Graph1 is here for convenience:

https://github.com/jackparmer/mapbox-counties/tree/master/1999

It would be nice if the mapbox error was caught and Plotly.js events still fired for Graph1.

**Comment by etpinard** [comment] 2018-02-07 05:00
I think this happens when the geojson source data is (somewhat) invalid.

We should try running http://geojsonlint.com/ on those geojsons

**Comment by jackparmer** [comment] 2018-02-07 05:24
> We should try running http://geojsonlint.com/ on those geojsons

I did some linting with this project and didn't find any issues: https://github.com/mapbox/geojsonhint

http://geojsonlint.com/ has some right-hand rule guidance but it's the same for the working and non-working geojson files.

**Comment by etpinard** [comment] 2018-02-07 19:46
Looks like plain `mapbox-gl` (even their latest version `v.0.44.0`) outputs the same error. From https://codepen.io/etpinard/pen/aqBLgv?editors=0010, I get

![image](https://user-images.githubusercontent.com/6675409/35937723-20b7adce-0c15-11e8-80b1-12d1c13adba4.png)

Maybe we should open a bug report there?

--------

> It would be nice if the mapbox error was caught and Plotly.js events still fired for Graph1.

I can catch that error no problem. But I don't get why events wouldn't get triggered regardless. How are you attaching your event handlers?

**Comment by leejt489** [comment] 2018-06-02 03:01
Hi, I'm also getting a similar error. I have a map that loads fine, but then when I update it with a slider this error fires in browser with the callback to update. Any update? I think my GeoJSON is fine.

**Comment by etpinard** [comment] 2018-06-04 12:59
@leejt489 can you please share the problematic geojson in question? Better yet, can you a reproducible plotly.js or [mapbox-gl](https://codepen.io/etpinard/pen/NzxeJJ) example? That way we can determine if it is a problem with plotly.js or mapbox-gl. Thanks.

**Comment by leejt489** [comment] 2018-06-07 19:13
Sure, see the Dash app here https://github.com/leejt489/solar-reliability-cost-web. I dumped the geojson files into the [debug folder](https://github.com/leejt489/solar-reliability-cost-web/tree/master/debug). The error arises not the first time the map is loaded, but when the slider is adjusted. Maybe it's a dash (or my) error but this issue was the best I could find.

**Comment by leejt489** [comment] 2018-06-11 21:05
@etpinard see the app here https://solar-reliability-cost.herokuapp.com/. On Chrome dev tools, the error appears after hitting the "Update Map" button

**Comment by etpinard** [comment] 2018-06-11 22:14
@leejt489 which geojson file is used after clicking on _Update Map_?

**Comment by leejt489** [comment] 2018-06-12 14:57
Each of the files in the [debug folder](https://github.com/leejt489/solar-reliability-cost-web/tree/master/debug) are used for a different layer

**Comment by leejt489** [comment] 2018-06-13 20:40
@etpinard I'm seeing that when I click "update map" multiple times, the layout only updates after the first click. The data property updates correctly, and I can see numbers change when I hover over the map, but the layers aren't re-rendered. I updated the heroku app today, and corresponding code is on the dev branch https://github.com/leejt489/solar-reliability-cost-web/tree/dev Thanks!

**Comment by etpinard** [comment] 2018-06-13 22:31
@leejt489 I appreciate your help, but it's a little for use to debug dash app. We wrote [instruction](https://github.com/plotly/plotly.js/blob/master/.github/ISSUE_TEMPLATE.md) on how dash users can help us debug, if you're willing to spend more time on this issue.

Now, I think #2734 fixed your issues as it fixes `Plotly.react` for mapbox layout layers (newer versions of dash uses `Plotly.react` to update). 

Unfortunately, you'll have to wait for us to make a new release before seeing changes in your dash app.

**Comment by leejt489** [comment] 2018-06-15 22:12
Thanks, what kind of a release schedule do you use; how long until the next release?

**Comment by leejt489** [comment] 2018-07-03 16:49
@etpinard Hi, I just wanted to check if you anticipate a release this week, or if there is a workaround. This is becoming a blocking issue for a demo I have next week. Thanks!

**Comment by etpinard** [comment] 2018-07-03 16:57
Yes, we'll release 1.39.0 this weejk.

**Comment by etpinard** [comment] 2019-05-17 20:57
Getting 404 on those geojson now. I suspect this ticket is obsolete. Closing (for now).

**Closed by etpinard** 2019-05-17 20:57 UTC
Labels: type: bug
