### ISSUE TITLE
Latex does not render on hover for official Latex documentation

### ISSUE THREAD

**Issue by xhlulu** [plotly/plotly.js#3172] opened 2018-10-28 04:05 UTC
Latex issues were solved by https://github.com/plotly/plotly.js/pull/3018, and was shipped with plotly.js 1.41.1 and plotly.py 3.3.0. 

However, the examples on https://plot.ly/python/LaTeX/ still seem to not render correctly when you hover over a data point.

Furthermore, experiments with [dash-regression](https://github.com/plotly/dash-regression) seem to show the same problem, even when `app.py` is run on the latest dash and plotly.py versions. I will provide more examples this week if needs arise.

Please let me know if this issue has been raised previously, and I will close this issue. Thank you!

**Comment by etpinard** [comment] 2018-10-29 14:45
> when you hover over a data point.

Duplicate of https://github.com/plotly/plotly.js/issues/559

**Closed by etpinard** 2018-10-29 14:45 UTC

**Comment by xhlulu** [comment] 2018-10-30 15:25
Thank you
