### ISSUE TITLE
Tables with a lot of columns are messy

### ISSUE THREAD

**Issue by AbdealiLoKo** [plotly/plotly.js#3693] opened 2019-03-29 09:12 UTC
<img width="1137" alt="Screen Shot 2019-03-29 at 2 40 55 PM" src="https://user-images.githubusercontent.com/2200743/55221979-c5166d80-5230-11e9-8366-ace0bceb9506.png">

When trying to make a Table trace with a large number of columns that do not really fit within the viewport - it is very messy and truncates the cells in the table

**Comment by etpinard** [comment] 2019-03-29 13:59
Could someone try to replicate this in JS to help us debug?

**Comment by AbdealiJK** [comment] 2019-03-29 14:59
```
nums = [...new Array(100).keys()]
Plotly.newPlot(
  'graph',
  [{'cells': {'values': nums.map((x) => [1, 2, 3])},
   'header': {'values': nums.map((x) => `col${x}`)},
   'type': 'table'}],
  {});
```
https://codepen.io/AbdealiJK/pen/yrBeVo

**Comment by etpinard** [comment] 2019-04-01 16:15
Here too, what is the desired behavior in your mind? 

Should we add an horizontal scroll bar? Should we hide text labels that don't fit in their cells?

**Comment by AbdealiJK** [comment] 2019-04-02 08:26
This one's a bit more difficult to answer. Cause I can see merits in the current behavior for smaller number of columns...
I think we should list down the different kind of usecases a Table could have and ensure we have the ability to do each.

 - **Scenario 1** - Table with 2 columns, want to take the entire width available to show these 2 columns
 - **Scenario 2** - Table with 100 columns, want to scroll automatically for the columns to be visible - with all text visible
 - **Scenario 3** - Table with 100 columns, want to scroll automatically for the columns to be visible - with a max-width for the columns so 1 column doesn't get too long (and wrap text or truncate text) 

I think these are the scenarios I'm trying to implement when using the table. First is the current behavior. Second and Third I'm not super sure how to do and am doing weird hacks

**Comment by etpinard** [comment] 2019-07-04 14:30
Related: https://github.com/plotly/plotly.js/issues/2056

**Comment by gvwilson** [comment] 2024-06-13 19:52
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-13 19:52 UTC
