### ISSUE TITLE
Add support for date angular axes

### ISSUE THREAD

**Issue by mtadams007** [plotly/plotly.js#4379] opened 2019-11-22 14:45 UTC
I'm trying to create a scatterpolar chart where the values for theta are all dates but this displays nothing. If one value in the theta array is a date it displays nothing:

https://codepen.io/mtadams007/pen/WNNPgdw

I tried using dtheta and while the graph displays the labels don't display:

https://codepen.io/mtadams007/pen/xxxMapj?editors=0010

It would be good to have a way to disable this behavior so that we can display the charts with dates.

**Comment by etpinard** [comment] 2019-11-22 14:49
Part of https://github.com/plotly/plotly.js/issues/2255

**Comment by etpinard** [comment] 2019-11-22 18:57
Past discussions in https://github.com/plotly/plotly.js/pull/2200#discussion_r156397924) and some considerations in the last part of https://github.com/plotly/plotly.js/commit/1e81039384ebf89de376c3ddd004d0f103278fa6#r26653662

**Comment by gvwilson** [comment] 2024-06-14 12:53
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-14 12:53 UTC
Labels: type: feature
