### ISSUE TITLE
Draw error in scattergl for plot with markers and lines traces

### ISSUE THREAD

**Issue by vincex** [plotly/plotly.js#2846] opened 2018-07-26 08:58 UTC
https://codepen.io/anon/pen/WKEdQb?editors=1010

In this pen, as you can see the last trace is not visible.
If you press the autoscale the last trace appears.

This happens only if you plot trace in the following order:
[Marker Trace 1, Marker Trace 2, ..., Marker Trace N, Line Trace]

Maybe it is not a plotly bug, it could be something related to regl-line2d, or the way plotly uses it.
If this can be usefull, in regl-line2d, there are a step where undefined passes are filtered out.

```js
// remove null items
this.passes = this.passes.filter(Boolean)
```

This leads to a misalignment of ids between plotly and regl-line2d.

**Comment by alexcjohnson** [comment] 2018-07-26 12:09
@vincex confirmed, thanks for the example and partial debugging. I'll let @dy figure out where the fix goes, but regardless it counts as a bug in plotly.js!

**Comment by alexcjohnson** [comment] 2018-07-26 12:13
Oh sorry - this is a duplicate of #2765 - and the example there behaves the same way, the last line shows up on a redraw.

**Closed by alexcjohnson** 2018-07-26 12:13 UTC
Labels: type: bug
