### ISSUE TITLE
Can plotly.js draw 3D bar chart like this?

### ISSUE THREAD

**Issue by lx1054331851** [plotly/plotly.js#1606] opened 2017-04-19 09:15 UTC
Can plotly.js draw 3D bar chart like this below:
 If it can,  can give me a simple demo code
![image](https://cloud.githubusercontent.com/assets/12423206/25172462/b5b1b8ae-2523-11e7-814e-928323ebb071.png)

**Comment by etpinard** [comment] 2017-04-19 13:45
duplicate of https://github.com/plotly/plotly.js/issues/270

**Closed by etpinard** 2017-04-19 13:45 UTC
