### ISSUE TITLE
"# Format" does not apply formatting to some values

### ISSUE THREAD

**Issue by alexander-daniel** [plotly/plotly.js#274] opened 2016-02-22 19:44 UTC
Not sure if it's a bug or not, so forgive me if this is expected behaviour!

I've set the `# Format` in the Layout Panel, however the axes labels for  `1000` and `1001` do not conform to that format. Only the axes labels that **aren't** associated to data points show the formatted style.

<img width="1016" alt="screen shot 2016-02-22 at 2 26 58 pm" src="https://cloud.githubusercontent.com/assets/5408720/13230218/8a73a4e8-d972-11e5-9102-f134252ced3b.png">

**Comment by mdtusz** [comment] 2016-02-22 21:31
This may be related to [this](https://github.com/plotly/plotly.js/pull/267) which should be merged in today or tomorrow.

**Comment by etpinard** [comment] 2016-02-23 00:25
This looks like the intended behaviour (cc @alexcjohnson)

http://codepen.io/etpinard/pen/RrzXmv

the [`layout.separtor`](https://github.com/plotly/plotly.js/blob/master/src/plots/layout_attributes.js#L136-L156) attribute respects significant values in the data.

Note that the comma can *forced in* with `layout.xaxis.tickformat`.

**Comment by etpinard** [comment] 2016-02-23 00:29
Oops I spoke too done. This behaviour is not due to significant values in the data, but to the fact that all 4-digit integers all showed w/o separators by design. 

See relevant code [here](https://github.com/plotly/plotly.js/blob/d430e30ba54924227433afd5e2be12888ff2ceb1/src/plots/cartesian/axes.js#L1122-L1141).

**Closed by etpinard** 2016-02-23 00:29 UTC

**Comment by rantler** [comment] 2016-02-29 17:48
I'm trying to experiment with the linked codepen example to for the separators using `layout.xaxis.tickformat` but I can't get it working. Is there a working example one can link to?

**Comment by mdtusz** [comment] 2016-02-29 17:54
Hi Rantler,

What problem are you encountering with the codepen example? As mentioned above, not displaying a comma with 4 digit values seems to be by design. More documentation on `tickformat` usage can be found [here](https://plot.ly/javascript/reference/#layout-xaxis-tickformat).

**Comment by rantler** [comment] 2016-02-29 18:10
Thanks, I'll keep experimenting. I was just hoping for a working example of forcing the format that we're looking for since the by-design behavior isn't meeting our needs.
