### ISSUE TITLE
GL plots seem to be using up multiple GL contexts with Plotly 1.37.1

### ISSUE THREAD

**Issue by brian428** [plotly/plotly.js#2614] opened 2018-05-04 15:53 UTC
Previously, we were able to show 7-8 or more WebGL plots at once. With 1.37.1, we're hitting the browser GL context limit (typically 16) much earlier. When showing 7 plots, the first two immediately lose their GL contexts and appear as blank.

Here is a repro case: http://jsfiddle.net/brian428/fqhb7kk9/

It seems like Plotly is using up multiple GL contexts for each scattergl plot. With 7 plots, there are 5 console warnings about losing contexts, so it appears that each scattergl plot is using **3** GL contexts for some reason. 

We need to show multiple plots together (and allow each one to be individually manipulated by the user), so this is a blocking issue. Can someone take a look?

**Comment by etpinard** [comment] 2018-05-04 15:59
Duplicate of https://github.com/plotly/plotly.js/issues/2333

**Comment by brian428** [comment] 2018-05-04 16:08
Thanks, I missed that one. Would it help you if add my repro case to that ticket?

**Comment by brian428** [comment] 2018-05-04 16:09
Also just to be clear, we had been on 1.35 I believe. So it seems like maybe something changed between 1.35 and 1.37 that made this worse. Maybe the addition of Splom?

**Comment by etpinard** [comment] 2018-05-24 17:28
@brian428 sorry for the wait. We just merged https://github.com/plotly/plotly.js/pull/2662 which makes `scattergl` graphs use 2 (not 3) WebGL contexts as was the case before `1.36.0`.

A little more info on the topic: we use two WebGL contexts per scattergl (and splom) graph to improve selection (via select-box and lasso) performance. Since `1.33.0` , WebGL contexts are shared across subplots on the same graph `<div>`. So, one way to decrease the number of created contexts would be to merge your graphs into subplots on the same graph `<div>` when possible. 

Now, ticket https://github.com/plotly/plotly.js/issues/2333 has some thoughts on sharing WebGL contexts across graph `<div>`s. Hopefully using an external library like [`multi-regl`](https://github.com/regl-project/multi-regl) will be enough. If not, we might have to add another API method e.g. `Plotly.dashboard` to solve this problem.

I'll close this issue. But please feel free to comment on https://github.com/plotly/plotly.js/issues/2333.

**Closed by etpinard** 2018-05-24 17:28 UTC
