### ISSUE TITLE
make date autoformatting (duplicate 2nd line omission) configurable 

### ISSUE THREAD

**Issue by cldougl** [plotly/plotly.js#3108] opened 2018-10-15 21:28 UTC
When using properly formatted dates in the default format the second line is automatically omitted after the first tick if it doesn’t change.
- it would be useful if this behaviour was configurable
- it would be useful if this behaviour worked when `tickformat` is applied as well.

**Comment by markzolotoy** [comment] 2018-10-15 21:38
Yes, very useful. It is absolutely **critical** for international applications.

**Comment by alexcjohnson** [comment] 2018-10-16 02:42
@markzolotoy interesting, can you say more about why this becomes more important internationally? I agree that it's a useful feature, but the implication of your comment is that the labels are actually wrong, or unintelligible perhaps, with automatic duplicate pruning in other languages/calendars?

**Comment by markzolotoy** [comment] 2018-10-16 10:14
When using default date formatting which for US dates it is working in that way. But try to achieve the same for any foreign date such as French or Chinese. Since the app. allows our customers flip between languages it is critical that it looks and feels exactly the same in every language.

**Comment by stringfellow** [comment] 2018-11-15 13:01
Another use case for this is one I have - I'd like to show the weekday in that date format part, which is very important for my use case, but I also don't want that to be repeated on every time tick. I think the line that causes this is:

https://github.com/plotly/plotly.js/blob/30ed4a4a59789a486b70dda360d630d290811816/src/lib/dates.js#L474

Would be very grateful for some way to customise or work around this (even if a workaround is to somehow overried the `dayMonthYear` format...?)

**Comment by gvwilson** [comment] 2024-06-11 17:24
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson

**Closed by gvwilson** 2024-06-11 17:24 UTC
Labels: type: feature
