### ISSUE TITLE
Small fragment of yaxis line is not displayed in mirror mode

### ISSUE THREAD

**Issue by DaanyWaay** [plotly/plotly.js#4003] opened 2019-07-01 04:57 UTC
1px of yaxis line is missing, this happens only when yaxis is in mirror mode and is 1px width:
https://codepen.io/anon/pen/agqPNJ

**Comment by etpinard** [comment] 2019-07-02 19:48
Hmm, this is what I'm seeing:

![image](https://user-images.githubusercontent.com/6675409/60541965-b7b1c900-9ce0-11e9-8fe3-946c5928a3f1.png)

@DaanyWaay could you help me find that missing pixel? Thanks for posting!

**Comment by etpinard** [comment] 2019-07-02 20:00
Might be related to: https://github.com/plotly/plotly.js/issues/2796

**Comment by DaanyWaay** [comment] 2019-07-04 05:05
This is how it looks in my Chrome/Opera in 1920x1080 res. When zooming in/out the gap disappears but it is always visible in 100% zoom.
![missing1px](https://user-images.githubusercontent.com/30828682/60640953-e1c2d280-9e29-11e9-8bcb-f78f8cd7e8dc.png)

**Comment by etpinard** [comment] 2019-07-04 13:45
Thanks for following up!

Can any other @plotly/plotly_js member reproduce this bug?

**Comment by archmoj** [comment] 2019-07-04 14:08
@DaanyWaay I was not able to reproduce the bug. 
Would you mind testing [this codepen](https://codepen.io/MojtabaSamimi/pen/gNjWxQ?editors=0010) to see if you still see the bug (only) on y-axis or the two axes?
Also it may help if you possibly provide more info about the hardware and operating system you use.
Thanks.

**Comment by DaanyWaay** [comment] 2019-07-05 06:51
@archmoj yes it is reproducible, only for y-axis
- Windows 7
- res 1920x1080
- reproducible on Chrome / Opera
- works OK on FF
- works OK with 2px borders - 2px x-axsis just fills the 1px gap
![plot borders - Opera](https://user-images.githubusercontent.com/30828682/60702350-118fda00-9eff-11e9-9414-41822cd5e3a3.png)

**Comment by archmoj** [comment] 2019-07-05 13:17
Cannot replicate this issue.
@DaanyWaay What would happen if you download the png image? Do you still get a missing point on y-axis?

**Comment by DaanyWaay** [comment] 2019-07-09 04:32
The PNG looks fine.

**Comment by etpinard** [comment] 2019-07-11 20:44
@DaanyWaay thanks for following up!

It appears like we have a Chrome/Opera bug in our hands. I'm not sure if we could or should do anything about it. One thing for sure though: we should check how your graph looks in new versions of Chrome/Opera as they are released.

@DaanyWaay could you provide the Chrome and Opera versions on which you're seeing this bug? 

Thank you very much.

**Comment by DaanyWaay** [comment] 2019-08-16 06:28
Sorry for my late answer, I was to busy: Opera 62, Chrome 76.

**Comment by gvwilson** [comment] 2024-06-14 12:48
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-14 12:48 UTC
