### ISSUE TITLE
Safari not rendering scattergl traces

### ISSUE THREAD

**Issue by LeanderK** [plotly/plotly.js#2543] opened 2018-04-11 11:58 UTC
When I look at [this](https://plot.ly/python/webgl-vs-svg/) example, the first 2 scatterplots are empty.

this is the log :
```
[Error] WebGL: INVALID_VALUE: bufferData: size == 0
	bufferData
	u (plotlyjs-bundle.c9ee06fe8613.js:1:2698524)
	create (plotlyjs-bundle.c9ee06fe8613.js:1:2698698)
	buffer (plotlyjs-bundle.c9ee06fe8613.js:1:2710935)
	exports (plotlyjs-bundle.c9ee06fe8613.js:1:2601002)
	plot (plotlyjs-bundle.c9ee06fe8613.js:1:2490441)
	v (plotlyjs-bundle.c9ee06fe8613.js:1:1948244)
	plot (plotlyjs-bundle.c9ee06fe8613.js:1:1952031)
	(anonymous function) (plotlyjs-bundle.c9ee06fe8613.js:1:1858047)
	syncOrAsync (plotlyjs-bundle.c9ee06fe8613.js:1:1795598)
	promiseReactionJob
[Error] WebGL: INVALID_VALUE: bufferData: size == 0
	bufferData
	u (plotlyjs-bundle.c9ee06fe8613.js:1:2698524)
	create (plotlyjs-bundle.c9ee06fe8613.js:1:2698698)
	buffer (plotlyjs-bundle.c9ee06fe8613.js:1:2710935)
	exports (plotlyjs-bundle.c9ee06fe8613.js:1:2601120)
	plot (plotlyjs-bundle.c9ee06fe8613.js:1:2490441)
	v (plotlyjs-bundle.c9ee06fe8613.js:1:1948244)
	plot (plotlyjs-bundle.c9ee06fe8613.js:1:1952031)
	(anonymous function) (plotlyjs-bundle.c9ee06fe8613.js:1:1858047)
	syncOrAsync (plotlyjs-bundle.c9ee06fe8613.js:1:1795598)
	promiseReactionJob
[Error] WebGL: INVALID_VALUE: bufferData: size == 0
	bufferData
	u (plotlyjs-bundle.c9ee06fe8613.js:1:2698524)
	create (plotlyjs-bundle.c9ee06fe8613.js:1:2698698)
	buffer (plotlyjs-bundle.c9ee06fe8613.js:1:2710935)
	exports (plotlyjs-bundle.c9ee06fe8613.js:1:2601173)
	plot (plotlyjs-bundle.c9ee06fe8613.js:1:2490441)
	v (plotlyjs-bundle.c9ee06fe8613.js:1:1948244)
	plot (plotlyjs-bundle.c9ee06fe8613.js:1:1952031)
	(anonymous function) (plotlyjs-bundle.c9ee06fe8613.js:1:1858047)
	syncOrAsync (plotlyjs-bundle.c9ee06fe8613.js:1:1795598)
	promiseReactionJob
[Error] WebGL: INVALID_VALUE: bufferData: size == 0
	bufferData
	u (plotlyjs-bundle.c9ee06fe8613.js:1:2698524)
	create (plotlyjs-bundle.c9ee06fe8613.js:1:2698698)
	buffer (plotlyjs-bundle.c9ee06fe8613.js:1:2710935)
	exports (plotlyjs-bundle.c9ee06fe8613.js:1:2623124)
	plot (plotlyjs-bundle.c9ee06fe8613.js:1:2490478)
	v (plotlyjs-bundle.c9ee06fe8613.js:1:1948244)
	plot (plotlyjs-bundle.c9ee06fe8613.js:1:1952031)
	(anonymous function) (plotlyjs-bundle.c9ee06fe8613.js:1:1858047)
	syncOrAsync (plotlyjs-bundle.c9ee06fe8613.js:1:1795598)
	promiseReactionJob
[Error] WebGL: INVALID_VALUE: bufferData: size == 0
	bufferData
	u (plotlyjs-bundle.c9ee06fe8613.js:1:2698524)
	create (plotlyjs-bundle.c9ee06fe8613.js:1:2698698)
	buffer (plotlyjs-bundle.c9ee06fe8613.js:1:2710935)
	exports (plotlyjs-bundle.c9ee06fe8613.js:1:2623177)
	plot (plotlyjs-bundle.c9ee06fe8613.js:1:2490478)
	v (plotlyjs-bundle.c9ee06fe8613.js:1:1948244)
	plot (plotlyjs-bundle.c9ee06fe8613.js:1:1952031)
	(anonymous function) (plotlyjs-bundle.c9ee06fe8613.js:1:1858047)
	syncOrAsync (plotlyjs-bundle.c9ee06fe8613.js:1:1795598)
	promiseReactionJob
[Error] WebGL: INVALID_VALUE: bufferData: size == 0
	bufferData
	u (plotlyjs-bundle.c9ee06fe8613.js:1:2698524)
	create (plotlyjs-bundle.c9ee06fe8613.js:1:2698698)
	buffer (plotlyjs-bundle.c9ee06fe8613.js:1:2710935)
	exports (plotlyjs-bundle.c9ee06fe8613.js:1:2623231)
	plot (plotlyjs-bundle.c9ee06fe8613.js:1:2490478)
	v (plotlyjs-bundle.c9ee06fe8613.js:1:1948244)
	plot (plotlyjs-bundle.c9ee06fe8613.js:1:1952031)
	(anonymous function) (plotlyjs-bundle.c9ee06fe8613.js:1:1858047)
	syncOrAsync (plotlyjs-bundle.c9ee06fe8613.js:1:1795598)
	promiseReactionJob
[Error] WebGL: INVALID_VALUE: bufferData: size == 0
	bufferData
	u (plotlyjs-bundle.c9ee06fe8613.js:1:2698524)
	create (plotlyjs-bundle.c9ee06fe8613.js:1:2698698)
	buffer (plotlyjs-bundle.c9ee06fe8613.js:1:2710935)
	exports (plotlyjs-bundle.c9ee06fe8613.js:1:2623284)
	plot (plotlyjs-bundle.c9ee06fe8613.js:1:2490478)
	v (plotlyjs-bundle.c9ee06fe8613.js:1:1948244)
	plot (plotlyjs-bundle.c9ee06fe8613.js:1:1952031)
	(anonymous function) (plotlyjs-bundle.c9ee06fe8613.js:1:1858047)
	syncOrAsync (plotlyjs-bundle.c9ee06fe8613.js:1:1795598)
	promiseReactionJob
[Error] WebGL: INVALID_OPERATION: drawElements: unable to simulate vertexAttrib0 array
	drawElements
	batch (Anonymous Script 1 (line 1966))
	(anonymous function) (plotlyjs-bundle.c9ee06fe8613.js:1:2692519)
	M (plotlyjs-bundle.c9ee06fe8613.js:1:2632387)
	draw (plotlyjs-bundle.c9ee06fe8613.js:1:2487054)
	plot (plotlyjs-bundle.c9ee06fe8613.js:1:2493114)
	v (plotlyjs-bundle.c9ee06fe8613.js:1:1948244)
	plot (plotlyjs-bundle.c9ee06fe8613.js:1:1952031)
	(anonymous function) (plotlyjs-bundle.c9ee06fe8613.js:1:1858047)
	syncOrAsync (plotlyjs-bundle.c9ee06fe8613.js:1:1795598)
	promiseReactionJob
[Error] WebGL: INVALID_VALUE: bufferData: size == 0
	bufferData
	u (plotlyjs-bundle.c9ee06fe8613.js:1:2698524)
	create (plotlyjs-bundle.c9ee06fe8613.js:1:2698698)
	buffer (plotlyjs-bundle.c9ee06fe8613.js:1:2710935)
	exports (plotlyjs-bundle.c9ee06fe8613.js:1:2623124)
	plot (plotlyjs-bundle.c9ee06fe8613.js:1:2490478)
	v (plotlyjs-bundle.c9ee06fe8613.js:1:1948244)
	plot (plotlyjs-bundle.c9ee06fe8613.js:1:1952031)
	(anonymous function) (plotlyjs-bundle.c9ee06fe8613.js:1:1858047)
	syncOrAsync (plotlyjs-bundle.c9ee06fe8613.js:1:1795598)
	promiseReactionJob
[Error] WebGL: INVALID_VALUE: bufferData: size == 0
	bufferData
	u (plotlyjs-bundle.c9ee06fe8613.js:1:2698524)
	create (plotlyjs-bundle.c9ee06fe8613.js:1:2698698)
	buffer (plotlyjs-bundle.c9ee06fe8613.js:1:2710935)
	exports (plotlyjs-bundle.c9ee06fe8613.js:1:2623177)
	plot (plotlyjs-bundle.c9ee06fe8613.js:1:2490478)
	v (plotlyjs-bundle.c9ee06fe8613.js:1:1948244)
	plot (plotlyjs-bundle.c9ee06fe8613.js:1:1952031)
	(anonymous function) (plotlyjs-bundle.c9ee06fe8613.js:1:1858047)
	syncOrAsync (plotlyjs-bundle.c9ee06fe8613.js:1:1795598)
	promiseReactionJob
[Error] WebGL: INVALID_VALUE: bufferData: size == 0
	bufferData
	u (plotlyjs-bundle.c9ee06fe8613.js:1:2698524)
	create (plotlyjs-bundle.c9ee06fe8613.js:1:2698698)
	buffer (plotlyjs-bundle.c9ee06fe8613.js:1:2710935)
	exports (plotlyjs-bundle.c9ee06fe8613.js:1:2623231)
	plot (plotlyjs-bundle.c9ee06fe8613.js:1:2490478)
	v (plotlyjs-bundle.c9ee06fe8613.js:1:1948244)
	plot (plotlyjs-bundle.c9ee06fe8613.js:1:1952031)
	(anonymous function) (plotlyjs-bundle.c9ee06fe8613.js:1:1858047)
	syncOrAsync (plotlyjs-bundle.c9ee06fe8613.js:1:1795598)
	promiseReactionJob
[Error] WebGL: INVALID_VALUE: bufferData: size == 0
	bufferData
	u (plotlyjs-bundle.c9ee06fe8613.js:1:2698524)
	create (plotlyjs-bundle.c9ee06fe8613.js:1:2698698)
	buffer (plotlyjs-bundle.c9ee06fe8613.js:1:2710935)
	exports (plotlyjs-bundle.c9ee06fe8613.js:1:2623284)
	plot (plotlyjs-bundle.c9ee06fe8613.js:1:2490478)
	v (plotlyjs-bundle.c9ee06fe8613.js:1:1948244)
	plot (plotlyjs-bundle.c9ee06fe8613.js:1:1952031)
	(anonymous function) (plotlyjs-bundle.c9ee06fe8613.js:1:1858047)
	syncOrAsync (plotlyjs-bundle.c9ee06fe8613.js:1:1795598)
	promiseReactionJob
[Error] WebGL: INVALID_OPERATION: drawElements: unable to simulate vertexAttrib0 array
	drawElements
	batch (Anonymous Script 2 (line 1966))
	(anonymous function) (plotlyjs-bundle.c9ee06fe8613.js:1:2692519)
	M (plotlyjs-bundle.c9ee06fe8613.js:1:2632387)
	draw (plotlyjs-bundle.c9ee06fe8613.js:1:2487054)
	plot (plotlyjs-bundle.c9ee06fe8613.js:1:2493114)
	v (plotlyjs-bundle.c9ee06fe8613.js:1:1948244)
	plot (plotlyjs-bundle.c9ee06fe8613.js:1:1952031)
	(anonymous function) (plotlyjs-bundle.c9ee06fe8613.js:1:1858047)
	syncOrAsync (plotlyjs-bundle.c9ee06fe8613.js:1:1795598)
	promiseReactionJob
[Error] Failed to load resource: the server responded with a status of 404 () (plotly-ico.png, line 0)
```

**Comment by etpinard** [comment] 2018-04-11 13:18
Thanks very much for the report.

That's interesting. I've seen those `WebGL: INVALID_VALUE: bufferData: size == 0 bufferData` messages in Chrome before (e.g. https://github.com/plotly/plotly.js/issues/1976 mentions something similar), but those were never fatal. Looks like Safari is more strict.

WebGL issues can be very browser version and hardware dependent. To help us out even more, would you mind posting those info (something like in https://github.com/plotly/plotly.js/issues/2518#issuecomment-378546848). Thanks!

cc @dy

**Comment by etpinard** [comment] 2018-04-13 17:27
Interesting I found https://github.com/plotly/plotly.js/issues/2457 which also present issues with scattergl and safari. Not sure why the https://github.com/plotly/plotly.js/issues/2457 didn't report any fatal errors, but only warnings.

**Comment by cpsievert** [comment] 2018-04-17 18:53
I'd consider this a 🚫-ing issue for the R 📦 (scattergl no longer renders in RStudio because of it).

**Comment by etpinard** [comment] 2018-04-17 18:57
> (scattergl no longer renders in RStudio because of it).

So, RStudio **errors** when logging _WebGL: INVALID_VALUE: bufferData: size == 0 bufferData_  unlike your other report in https://github.com/plotly/plotly.js/issues/2457?

**Comment by cpsievert** [comment] 2018-04-17 19:34
@etpinard I think the fatal error is `WebGL: INVALID_OPERATION: drawElements: unable to simulate vertexAttrib0 array`. Looks like I did a poor job of reporting the full problem #2457. I think it's a duplicate of this issue.

**Comment by etpinard** [comment] 2018-04-17 19:37
Ok thanks @cpsievert ! 

Can anyone working out of the MTL office (cc @nicolaskruchten @VeraZab @chriddyp ) lend their Mac to @dy for a few hours this week to try to fix this thing? I guess we could also get @dy setup on browserstack, but debugging WebGL there sounds painful.

**Comment by nicolaskruchten** [comment] 2018-04-17 20:07
If @dy works evenings then sure, otherwise it's hard for me to get anything done without my machine :)

**Closed** 2018-05-01 22:28 UTC
Labels: type: bug
