### ISSUE TITLE
Xaxis getting cut off when labels are long and tilted 45 degrees.

### ISSUE THREAD

**Issue by donnyv** [plotly/plotly.js#1344] opened 2017-01-30 20:22 UTC
Xaxis labels are getting cut off when labels are long and tilted 45 degrees.
I make the height taller but that only makes the bar section longer not the xaxis container.
`
var needs_bar_layout = {  
      barmode: "stack",  
      height: 650  
 };
`
![capture](https://cloud.githubusercontent.com/assets/2224189/22440026/e97c8504-e6ff-11e6-990e-e420097e6b7a.PNG)

**Comment by etpinard** [comment] 2017-01-30 20:24
duplicate of https://github.com/plotly/plotly.js/issues/296

**Closed by etpinard** 2017-01-30 20:24 UTC
