### ISSUE TITLE
UpdateMenus: Trigger external event if filter gets applied

### ISSUE THREAD

**Issue by Boesinga** [plotly/plotly.js#4581] opened 2020-02-13 09:16 UTC
Hello fellow Plotly users,

I’am using the update menus to create a dropdown menu, out of which the user can select different filter values.
If the user selects a value, the graph gets updated automatically, as wished. Furthermore, I would like to trigger an external event, because the filtered values have to be used in another case, too.

Is it possible to apply this kind of event, if a user selects a filter?

If it is otherwise not possible to trigger this kind of event, is it possible to get any information about the filter, which is currently active?

Thanks for your help,

Boesinga

**Comment by etpinard** [comment] 2020-02-13 14:57
Duplicate of https://community.plot.ly/t/updatemenus-trigger-external-event-if-filter-gets-applied/34816/2

**Closed by etpinard** 2020-02-13 14:57 UTC
