### ISSUE TITLE
Add way to reverse ternary axes

### ISSUE THREAD

**Issue by foolmadao** [plotly/plotly.js#4010] opened 2019-07-03 07:07 UTC
* How I can reversed ternary diagram axis ,for example this Mole fraction CR axis
![image](https://user-images.githubusercontent.com/39939976/60568040-420c3280-9d9e-11e9-9040-ad4cf5a13420.png)

**Comment by etpinard** [comment] 2019-07-03 13:23
By _reverse_ you mean have 1 at the bottom-left corner and 0 at the top of the triangle?

**Comment by foolmadao** [comment] 2019-07-11 10:05
> By _reverse_ you mean have 1 at the bottom-left corner and 0 at the top of the triangle?

yes, just like this
![image](https://user-images.githubusercontent.com/39939976/61042227-61423a00-a406-11e9-9460-f86ac9c287eb.png)

**Comment by etpinard** [comment] 2019-07-12 13:55
Thanks for the screenshot @foolmadao !

We don't offer a way to do this at the moment unfortunately. This would make a great addition to the library though. Thanks again for writing in!

**Comment by alexcjohnson** [comment] 2019-07-12 17:54
Looks interesting! A few things to note about this:
- Those v-shaped ticks are super confusing - I might go so far as to say objectively wrong for the labeled axes, since only one of those directions corresponds to the labels. The ones on the left axis should be horizontal, because lines of constant C are horizontal. And the ones on the bottom axis should be tilted northeast to match lines of constant CR.
- The right axis could stay as is, with v-shaped ticks and no labels, just to mark the other end of the lines started by the ticks on the other two axes.
- But that means this version has no way to show all three components; the third one is just "whatever's left" and the right axis *is* the line of the third component absent. I'm guessing for the use case you're showing the third component is just a solvent/filler ie something you don't care about per se, and that's probably a pretty common use case. We may want to use that fact as the way to enable this mode. Something like:
```js
ternary.tickorigin = ('a'|'b'|'c'|'')
```
to say "start the ticks from pure B" etc - which would prevent showing ticks for B itself.
- In principle there's also a configuration where all three axes are flipped. Right now we have the increasing direction of all axes' labels going clockwise but it would be possible to have them all counterclockwise. That would have to be either a separate attribute (`ternary.tickdirection: ('clockwise'|'counterclockwise'`?) that's only valid if you don't use `tickorigin`, or perhaps we can find an attribute name that would make sense with values like `('a'|'b'|'c'|'clockwise'|'counterclockwise'`.

**Comment by foolmadao** [comment] 2019-07-15 09:19
thanks for your reply @alexcjohnson @etpinard  ,
This diagram export by Thermo-Calc software , you are right, the ticks should not be v-shaped， they should be parallel to each other's axis。
This diagram is same meaning as this Cartesian coordinate, but some thermodynamic researcher think use  ternary diagram is more clear。
![image](https://user-images.githubusercontent.com/39939976/61206038-2ac92f80-a724-11e9-8c2c-3ad28fa1387f.png)
If you can add this feature is very nice! thanks again.

**Comment by gvwilson** [comment] 2024-06-14 12:47
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-14 12:47 UTC
Labels: type: feature
