### ISSUE TITLE
Adding traces on click to a 3d line plot causes an infinite loop.

### ISSUE THREAD

**Issue by brgirardeau** [plotly/plotly.js#1780] opened 2017-06-12 20:41 UTC
An example of this occurring can be seen here:
https://codepen.io/brgirardeau/pen/pwbbge?editors=1010

**Comment by etpinard** [comment] 2017-06-12 20:59
duplicate of https://github.com/plotly/plotly.js/issues/1025

**Closed by etpinard** 2017-06-12 20:59 UTC
