### ISSUE TITLE
Toggle subsampling of tick labels when tickmode="array"

### ISSUE THREAD

**Issue by Alanocallaghan** [plotly/plotly.js#1779] opened 2017-06-12 19:56 UTC
It would be useful to allow users to specify tick values and tick labels, and then have plotly perform the same subsampling of labels that it performs when tickmode="auto".

This would be useful because it is important to use common co-ordinates for subplots. This sometimes requires mapping categorical variables to numeric values in order to align with a numeric axis.

I imagine this may not be a massive fix; if you'd like and don't mind pointing in the right direction, I would be happy to implement this

**Comment by etpinard** [comment] 2017-06-12 20:32
Duplicate of https://github.com/plotly/plotly.js/issues/1618

**Closed by etpinard** 2017-06-12 20:32 UTC
