### ISSUE TITLE
plotly interfering with other controls that may be using off screen realestate

### ISSUE THREAD

**Issue by jmsunseri** [plotly/plotly.js#393] opened 2016-04-05 01:11 UTC
I had an issue where once i called the plotly constructor and the graph is drawn then a few of my angular ui bootstrap  based calendar controls completely disappeared.  I never had a problem with it in the past and it is still not a problem in IE but when working in Chrome the issue began to pop up. After modifying the drawing.makeTester function it began to work without interfering with my other controls.  making the left and top properties below even greater into negative space seemed to solve the problem.  I'm not an expert on what's going on in this function but it was causing me a lot of trouble.  I wish I could reproduce the issue for you but i can't even reproduce the issue for myself right now.

```
drawing.makeTester = function(gd) {
    var tester = d3.select('body')
        .selectAll('#js-plotly-tester')
        .data([0]);

    tester.enter().append('svg')
        .attr('id', 'js-plotly-tester')
        .attr(xmlnsNamespaces.svgAttrs)
        .style({
            position: 'absolute',
            left: '-90000px',
            top: '-90000px',
            width: '9000px',
            height: '9000px'
        });

    // browsers differ on how they describe the bounding rect of
    // the svg if its contents spill over... so make a 1x1px
    // reference point we can measure off of.
    var testref = tester.selectAll('.js-reference-point').data([0]);
    testref.enter().append('path')
        .classed('js-reference-point', true)
        .attr('d','M0,0H1V1H0Z')
        .style({
            'stroke-width': 0,
            fill: 'black'
        });

    if(!tester.node()._cache) {
        tester.node()._cache = {};
    }

    gd._tester = tester;
    gd._testref = testref;
};
```

**Comment by mdtusz** [comment] 2016-04-05 14:59
Without more details of *what the issue is*, we likely won't be able to remedy it. 

If/when you can reproduce the issue, post a link to a working example (jsbin/codepen or the like) and we'll take a look.

**Comment by jmsunseri** [comment] 2016-04-05 15:37
I've created a plunker to display what's going on though I can't reproduce
the issue exactly

http://plnkr.co/edit/xNLXcglEIA8Q9dgAjnb8?p=preview

after pressing the search button in my application the plotly constructor
is called and the input box and date picker button would completely
disappear.




Sincerely

Justin Sunseri
Please don't print this e-mail unless you really need to.

**Comment by mdtusz** [comment] 2016-04-20 14:35
Are you still experiencing this issue?

**Comment by jmsunseri** [comment] 2016-04-20 14:37
If you want I can replace my modified version of plotly.js with the the
latest available version and see if it is still happening.


Sincerely

Justin Sunseri
Please don't print this e-mail unless you really need to.

**Comment by mdtusz** [comment] 2016-04-20 14:40
Please do. If the issue cannot be recreated, we will close this issue.

**Comment by jmsunseri** [comment] 2016-04-20 15:55
It looks like with the 1.9 release we are in the clear.  Did you guys make
a change on purpose to fix this?


Sincerely

Justin Sunseri
Please don't print this e-mail unless you really need to.

**Comment by mdtusz** [comment] 2016-04-20 16:23
Nope. Nothing done for this issue.

**Closed by mdtusz** 2016-04-20 16:23 UTC

**Comment by jmsunseri** [comment] 2016-04-20 19:18
sorry to do this but it is still broken

Before:

[image: Inline image 2]


After:
[image: Inline image 1]

Maybe the size of the window has something to do with it?



Sincerely

Justin Sunseri
Please don't print this e-mail unless you really need to.

**Comment by mdtusz** [comment] 2016-04-20 19:35
In the future, please respond directly on Github. Email replies pollute the issue with unnecessary text and things like images will not display. 

We will not be able to do anything for this issue without **concrete information** e.g. what the element is, what classes the elements have, and what your plot is doing. As this seems to be a problem specific to your usage of plotly.js and no an issue with the library, I will point you in the direction of the [plotly forums](community.plot.ly/) for further support.

**Comment by jmsunseri** [comment] 2016-04-20 19:37
I tried to help
