### ISSUE TITLE
Display edges lines for Mesh3d

### ISSUE THREAD

**Issue by emmanuelle** [plotly/plotly.js#4485] opened 2020-01-14 17:02 UTC
See https://community.plot.ly/t/show-edges-of-the-mesh-in-a-mesh3d-plot/33614, I don't know if the geometry of the edges is already computed and it would be a question of adding an `edges` or `lines` attribute to `mesh3d`, or if it's more complicated than that.

**Comment by archmoj** [comment] 2020-01-14 18:03
`gl-mesh3d` module kind of support this:
![wireframe](https://user-images.githubusercontent.com/33888540/72369431-18797f80-36ce-11ea-9aa7-d3f4e744564a.png)

**Comment by archmoj** [comment] 2020-01-14 18:06
What should be the API for this?

**Comment by emmanuelle** [comment] 2020-01-14 19:01
Cute :-). Maybe an `edge` or `line` object? Is it possible with `gl-mesh3d` to visualize both the faces and the edges?

**Comment by archmoj** [comment] 2020-01-14 19:18
I simply passed lines instead of triangles in a quick prototype to make use of this part of `gl-mesh3d` code: https://github.com/gl-vis/gl-mesh3d/blob/master/mesh.js#L492-L510

I am not sure if this should be a new trace/mode with lineColor...

**Comment by archmoj** [comment] 2020-01-15 14:49
Also see https://community.plot.ly/t/add-border-to-3d-mesh-cube/3434

**Comment by archmoj** [comment] 2020-01-23 22:33
@emmanuelle just noticed this wonderful post at https://plot.ly/~empet/15416 by @empet which also includes a wireframe plot using `scatter3d`.
Thought we should mention this neat approach in reply to those community questions.

**Comment by archmoj** [comment] 2020-02-04 16:50
Here is a demo: http://requirebin.com/?gist=37a8df8ace4ecafa010f
Seems like an interesting feature to add.

**Comment by gvwilson** [comment] 2024-06-14 12:56
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-14 12:56 UTC
Labels: type: feature
