### ISSUE TITLE
Fx.hover always failing on mobile view

### ISSUE THREAD

**Issue by notnotphilphil** [plotly/plotly.js#2732] opened 2018-06-13 15:00 UTC
I'm having trouble testing my chart on mobile view (using chromes mobile view helper thing). 
![plotly fxhover fail](https://user-images.githubusercontent.com/28711461/41359445-83bf10ba-6ef8-11e8-9f5f-e165bcf5e80b.png)

Every time I click anywhere on my graph this error occurs. I tried adding `<script src="https://cdn.plot.ly/plotly-latest.js"></script>` but same error occurs. This is even happening on <a href="https://plot.ly/python/line-charts/">their website</a>.

**Comment by etpinard** [comment] 2018-06-26 14:08
duplicate of https://github.com/plotly/plotly.js/issues/1967 

discussion in https://github.com/plotly/plotly.js/issues/1858

**Closed by etpinard** 2018-06-26 14:08 UTC
