### ISSUE TITLE
Axis ticks don't get cleared up on `scattergl` interaction

### ISSUE THREAD

**Issue by monfera** [plotly/plotly.js#2259] opened 2018-01-18 10:23 UTC
Saw this when working on another issue: 

![axis](https://user-images.githubusercontent.com/1548516/35092947-2fcd3236-fc41-11e7-9cc0-6b2cb0a88ba9.gif)

https://codepen.io/monfera/pen/vXvVqb or the [codepen](https://codepen.io/anon/pen/dRwQGK?editors=1010) I found in https://github.com/plotly/plotly.js/issues/1874 when checking if mine might be a duplicate issue.

cc @dfcreative

**Comment by dfcreative** [comment] 2018-01-18 11:33
Thank you @monfera!
Should be fixed in https://github.com/plotly/plotly.js/pull/2258/commits/f48cc2f74712927e1646f9b2cfe3e906e86df055

**Comment by monfera** [comment] 2018-01-18 11:55
@dfcreative man that was quick! Just a note, the fix commit is for the error bar and the other linked pen (plain scatterplot) has the same appearance
![image](https://user-images.githubusercontent.com/1548516/35097062-cb4405e8-fc4e-11e7-9881-05fed2d4150b.png)

**Comment by dfcreative** [comment] 2018-01-18 12:17
@monfera that should be fixed in #2258, I cannot reproduce that. If there is an urge to fix that in current master, I can come up with a patch.

**Comment by monfera** [comment] 2018-01-18 14:10
Depends on when the next `plotly.js` bundle is out, as now both the zoom and pan interactions seem to be impacted in the bundle. Best is to ask Étienne

**Comment by etpinard** [comment] 2018-01-18 15:41
> Depends on when the next plotly.js bundle is out

Hopefully today,

**Comment by etpinard** [comment] 2018-01-18 22:00
fixed by https://github.com/plotly/plotly.js/pull/2258

**Closed by etpinard** 2018-01-18 22:00 UTC
Labels: type: bug, type: regression
