### ISSUE TITLE
Stacked Histogram not rendering correctly when sample sizes are different 

### ISSUE THREAD

**Issue by cldougl** [plotly/plotly.js#1864] opened 2017-07-07 19:10 UTC
It seems that stacked hists aren't stacking correctly when the traces have different sample sizes.

![screen shot 2017-07-07 at 3 09 29 pm](https://user-images.githubusercontent.com/2789078/27973000-514b6f18-6326-11e7-8bed-089548d0a4e3.png)

Example: https://codepen.io/plotly/pen/owPQqg
Working Example: https://codepen.io/plotly/pen/BzqwbE

(noticed this recently in the python doc example and I think it worked at some point despite different sample sizes).

**Comment by alexcjohnson** [comment] 2017-08-07 15:52
haha @cldougl when I open your [working example](https://codepen.io/plotly/pen/BzqwbE) I sometimes get it "working"
![screen shot 2017-08-07 at 11 33 16 am](https://user-images.githubusercontent.com/2678795/29033837-50237828-7b64-11e7-9a62-034759e68790.png)

And sometimes it automatically offsets one of the traces (presumably via the [edge-avoidance algo](https://github.com/plotly/plotly.js/blob/master/src/plots/cartesian/axes.js#L667) though I'm a bit surprised that this would be so unstable):
![screen shot 2017-08-07 at 11 33 01 am](https://user-images.githubusercontent.com/2678795/29034312-f1788780-7b65-11e7-9ec3-177bcbf2314d.png)

And in fact sometimes your [non-working example](https://codepen.io/plotly/pen/owPQqg) does this and "sort of works":
![screen shot 2017-08-07 at 11 36 12 am](https://user-images.githubusercontent.com/2678795/29034091-21c8bf28-7b65-11e7-8dae-15fa9a2ee939.png)

I say "sort of works" because this is still not the outcome we want. Yes, the orange trace gets stacked on the blue, but the bin width used for the orange trace is not what's displayed as the bar widths.

I think in the end this may be the same as https://github.com/plotly/plotly.js/issues/50 - currently our oldest open bug! 🏆  So I'm pretty sure this is not a regression, just a hazard of using `random` in a bug report!

**Comment by alexcjohnson** [comment] 2017-08-15 03:12
closed by #1944

**Closed by alexcjohnson** 2017-08-15 03:12 UTC
Labels: type: bug
