### ISSUE TITLE
Printing changes layout of the graph

### ISSUE THREAD

**Issue by nyan314sn** [plotly/plotly.js#2184] opened 2017-11-27 23:19 UTC
Here is the graph that I created using Plotly python ( dash to be specific ) rendered in Chrome. But, I don't think it should matter in this case.

![image](https://user-images.githubusercontent.com/7884934/33294537-18eb5482-d39f-11e7-9b2f-e28b1fe1f23c.png)

Here is what it looks like when I tries to print in Chrome 

![image](https://user-images.githubusercontent.com/7884934/33294568-3ce6882a-d39f-11e7-8079-7cae176feeb8.png)

As one can see, the underlying grid lines become too think.  What can I do to make sure that the print accurately reflect what I plot ?

**Comment by etpinard** [comment] 2017-11-28 15:16
> What can I do to make sure that the print accurately reflect what I plot ?

I have no idea. Thanks for pointing this out though.

**Comment by etpinard** [comment] 2017-12-01 14:32
Related: https://github.com/plotly/plotly.js/issues/1275

**Comment by ricazhang** [comment] 2018-01-08 21:58
I saw the same thing when looking at print preview in Chrome but when I actually print out the chart, on paper the grid lines look like they are the correct width.

**Comment by HedgeShot** [comment] 2019-12-09 14:09
Hi,

Any idea on how to solve this?
It looks as intended on Chrome and Firefox but line are getting dark when printing from Chrome while it is OK when printing using Firefox:

Displayed on both Chrome & Firefox:

![browser-chrome](https://user-images.githubusercontent.com/3944600/70441917-8f9b7280-1a95-11ea-8279-063a8f975042.png)

Printed as PDF from Chrome:
![printed-chrome](https://user-images.githubusercontent.com/3944600/70441933-95915380-1a95-11ea-9bef-c7bcf79782fe.png)

**Comment by gvwilson** [comment] 2024-06-10 21:04
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson

**Closed by gvwilson** 2024-06-10 21:04 UTC
Labels: type: bug
