### ISSUE TITLE
Add Circular Selection similar to Box Selection

### ISSUE THREAD

**Issue by archmoj** [plotly/plotly.js#4597] opened 2020-02-23 17:57 UTC
Drawing circular shapes in #4374 will make it easy to add Circular Selection to 2-D plots.

**Comment by archmoj** [comment] 2020-02-23 19:36
[Demo](https://codepen.io/MojtabaSamimi/pen/KKpaPbm?editors=0010)

**Comment by gvwilson** [comment] 2024-06-14 12:59
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-14 12:59 UTC
Labels: type: feature
