### ISSUE TITLE
Unable to display plots in PyQt4  WebKit browser

### ISSUE THREAD

**Issue by ensight** [plotly/plotly.js#500] opened 2016-05-03 20:49 UTC
I'm looking to move from another js plotting package to plotly.js.  My target browser is a Qt4 WebKit instance, which other js plotting packages are working ok with.  In Python, my example is:

```
from PyQt4 import QtCore
from PyQt4 import QtGui
from PyQt4 import QtWebKit
import sys
QtGui.qApp = QtGui.QApplication(sys.argv)
webView = QtWebKit.QWebView()
webView.settings().setAttribute(QtWebKit.QWebSettings.JavascriptEnabled, True)
webView.show()
html = '''
<!DOCTYPE html>
<head>
  <!-- Plotly.js -->
  <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
</head>
<body>
  <div id="myDiv" style="width: 480px; height: 400px;"><!-- Plotly chart will be drawn inside this DIV --></div>
  <script>
var trace1 = {
  x: ['Feature A', 'Feature B', 'Feature C', 'Feature D', 'Feature E'],
  y: [20, 14, 23, 25, 22],
  marker:{
    color: ['rgba(204,204,204,1)', 'rgba(222,45,38,0.8)', 'rgba(204,204,204,1)', 'rgba(204,204,204,1)', 'rgba(204,204,204,1)']
  },
  type: 'bar'
};
var data = [trace1];
var layout = {
  title: 'Least Used Feature'
};
Plotly.newPlot('myDiv', data, layout);
  </script>
</body>
'''
f = open("test.html","wb")
f.write(html)
f.close()
webView.setHtml(html)
webView.show()
sys.exit(QtGui.qApp.exec_())
```

The result is an empty window.  Are there any options I can try to set to make this work?  I have also tried this with Qt5 without any better luck.  The html looks ok as I can load the 'test.html' file in Chrome and it displays properly.  Any suggestions, I have tried replacing all of the UTF-8 characters from the cdn drop and embedding the result directly in the html file with the same results.  Nothing in Qt, but it works in Chrome.

Thanks.
rjf.

**Comment by etpinard** [comment] 2016-05-03 22:41
Interesting. I've never used Qt4 WebKit before. I suspect that plotly.js is using some w3c spec that hasn't been implemented in Qt4 yet.

In all honesty, no plotly.js team member will devote time troubleshooting this issue. Perhaps someone from the community can help.

**Comment by ensight** [comment] 2016-05-04 12:34
Thanks for the reply!  I was hoping it was something stupid I was doing.  I can appreciate not being able to spend any time on it. So, if anyone can give me some insight into how to troubleshoot this issue, I would be all ears.  I'm willing to do the legwork, but I don't know the plotly.js codebase so I don't know what to try/where to look.  Are there any options I can set to help debug or any place it looks for a browser signature, etc that I can look into?  The QWebView will let me lie about the browser, etc.  If there were any raw js tests I could run, please let me know. TIA.

**Comment by liubin1977** [comment] 2016-05-07 12:33
I've tried the mini-browser provided by Qt 5.5/4.10 WebKit examples, and the 5.5 version can go well with the plotly web pages, even with the 3D WebGL pages. So I suspect that the you can update the Qt version to solve the issue.
If you stick in PyQt4, maybe you can use the PyQt4 binding with the Qt5 backend.
Cheers.

**Comment by ghtmtt** [comment] 2017-05-11 09:01
I know this in an old issue, but it could be related with this other https://github.com/plotly/plotly.py/issues/716

so also with Qt 5 the problem is still here. Any change to find the guilty?

@liubin1977 have you maybe your Qt 5 Webkit code snippet to share? Would be great, thanks!

**Comment by etpinard** [comment] 2019-03-28 21:47
Closing, probably obsolete.

**Closed by etpinard** 2019-03-28 21:47 UTC
Labels: type: community

**Comment by ghtmtt** [comment] 2019-03-29 06:32
confirmed, working nice with pyqt5
