### ISSUE TITLE
"Download plot as png" exports with wrong size

### ISSUE THREAD

**Issue by mlaily** [plotly/plotly.js#2478] opened 2018-03-18 17:00 UTC
Hi,

The toolbar button "Export plot as png" does not always work properly on my plot.

If the browser is maximized when the page loads, the button exports an image with the default size (700x450) instead of the actual size of the rendered plot.

As soon as I resize my browser, the button works as expected, even if I maximize the window afterwards.

This may be related to the auto-scaling of the plot implemented as follows:
```js
        var resizeDebounce = null;
        var graph = document.getElementById("graph");

        function resizePlot() {
            var bb = graph.getBoundingClientRect();
            Plotly.relayout(graph, {
                width: bb.width,
                height: bb.height
            });
        }

        window.addEventListener("resize", function () {
            if (resizeDebounce) {
                window.clearTimeout(resizeDebounce);
            }
            resizeDebounce = window.setTimeout(resizePlot, 100);
        });
```
(I don't remember where I found this code, probably the plotly forum or stackoverflow)

Calling `resizePlot()` after `Plotly.plot(...)` fixes the problem, but I don't understand why it's required.

You can reproduce the issue here: https://lastfm-stats.200d.net/?color=artist&timezone=Europe%2FParis&startDate=2018-01-01&endDate=2018-03-18&username=Yaurthek

**Comment by etpinard** [comment] 2018-03-19 13:55
Duplicate of https://github.com/plotly/plotly.js/issues/1576

**Closed by etpinard** 2018-03-19 13:55 UTC
