### ISSUE TITLE
'Layout options' section has disappeared from online documentation

### ISSUE THREAD

**Issue by gramster** [plotly/plotly.js#335] opened 2016-03-16 20:11 UTC

**Comment by etpinard** [comment] 2016-03-16 20:22
duplicate of https://github.com/plotly/documentation/issues/202

**Closed by etpinard** 2016-03-16 20:22 UTC
Labels: type: duplicate

**Comment by gramster** [comment] 2016-03-16 20:47
Is it a dup? I don't really understand what that other bug is about. Mine is about the fact that on the documentation page in the left hand nav list under 'Examples' there is a final item 'Layout Options' which links to https://plot.ly/javascript/#layout-options but that does not exist.

**Comment by etpinard** [comment] 2016-03-16 21:15
You're right. This is a separate issue. My mistake.

That said, please open docs-related issue in our [documentation repo](https://github.com/plotly/documentation/issues/new) in the future.
