### ISSUE TITLE
update plotly.js logo in the figures

### ISSUE THREAD

**Issue by antoinerg** [plotly/plotly.js#4606] opened 2020-02-27 16:04 UTC
Following the redesign of plotly.com, we need to update the plotly.js logo in the figures

cc @VeraZab

**Comment by antoinerg** [comment] 2020-02-28 16:04
While we're at it we should probably update the README.md as well. Right now it has a very outdated logo and the big image has an outdated logo:
![Screenshot_2020-02-28_11-02-56](https://user-images.githubusercontent.com/301546/75564322-eb80f200-5a19-11ea-97f3-c08466253279.png)

**Comment by VeraZab** [comment] 2020-02-28 16:10
yes please! Thanks Antoine!

**Comment by archmoj** [comment] 2020-02-28 16:13
We could include images dislaying new traces as well.

**Comment by gvwilson** [comment] 2024-06-14 12:58
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-14 12:58 UTC
