### ISSUE TITLE
Modebar does not hide on Chrome Ubuntu 17.10

### ISSUE THREAD

**Issue by ned2** [plotly/plotly.js#2222] opened 2017-12-26 02:50 UTC
The modebar is permanently displayed on Chrome on Ubuntu 17.10, when it should autohide after the mouse leaves the chart. It works fine on other 17.10 browsers.

After some hunting around, and working out that Plotly uses the [`has-hover`](https://github.com/dfcreative/has-hover) package, which in turn uses a media query to work out if the current device supports hover, I think this is a Chromium bug on Ubuntu 17.10 whereby a media query for the property `(hover:none)` incorrectly returns `true`, when it should return `false` for a desktop browser, it it _does_ support hover.  I've submitted a chromium Issue [here](https://bugs.chromium.org/p/chromium/issues/detail?id=797600).

If this is verified, then there might be nothing to do other than wait for a fix, but I figured I would report here to save others from hunting around.

**Comment by etpinard** [comment] 2017-12-27 15:49
Thanks for the report.

**Comment by etpinard** [comment] 2018-08-20 15:47
Has this been fixed in Chromium @ned2 ?

For what it's worth, I wasn't able to reproduce this bug on Ubuntu 18.04.

**Comment by etpinard** [comment] 2018-09-14 13:43
Closing due to lack of activity.

**Closed by etpinard** 2018-09-14 13:43 UTC
Labels: type: bug

**Comment by ned2** [comment] 2018-09-23 02:08
Sorry for the slow reply. Yep, looks like it's no longer a problem in Ubuntu 18.04. It might persist in 17.10, but I don't think it's worth pursuing.

**Comment by etpinard** [comment] 2018-09-24 13:05
Thanks for the info @ned2 !
