### ISSUE TITLE
animation/zoom

### ISSUE THREAD

**Issue by chaffra** [plotly/plotly.js#498] opened 2016-05-03 05:09 UTC
Hello, 
Is it possible to do things like animated zoom right now. If not, is it possible to access underlying d3 objects to perform animations directly from d3? I am looking at 
http://bl.ocks.org/mbostock/3828981
as an example.

**Comment by etpinard** [comment] 2016-05-03 22:42
duplicate of https://github.com/plotly/plotly.js/issues/142

**Closed by etpinard** 2016-05-03 22:42 UTC
Labels: type: duplicate
