### ISSUE TITLE
Restyling a date axis with timestamp data changes axis type to numeric

### ISSUE THREAD

**Issue by jdugge** [plotly/plotly.js#2144] opened 2017-11-06 19:56 UTC
Starting with Plotly.js 1.31.0, restyling a plot using timestamps instead of date strings turns the axis from a date axis to a numeric axis, even if the original data was in the same format, as can be seen in [this codepen](https://codepen.io/jdugge/pen/zPBQgp). In 1.30.0, this didn't happen.

```
var trace1 = {
  x: [1509583143188, 1510187943188], 
  y: [1, 2]
};

var data = [ trace1];

var layout = {
  title:'Line and Scatter Plot',
  xaxis: { type: 'date'}
};

Plotly.newPlot('myDiv', data, layout);

// Restyling with the same data turns the axis from date to numeric type
Plotly.restyle('myDiv', {x: [[1509441408043, 1510046208043]], y: [[1, 2]]})
```

**Comment by etpinard** [comment] 2017-11-13 14:35
Side-effect of https://github.com/plotly/plotly.js/pull/1999, thanks for the report.

**Comment by jdugge** [comment] 2018-01-23 12:58
I'd like to take a shot at fixing this behaviour, but I'm not sure where the best place to tackle this would be.

* Somehow check in the `clearAxisTypes` function whether the axis type was set by the user. This seems like a good place to do it, because there's alread a [check for whether the axis type is `log`](https://github.com/plotly/plotly.js/blob/e701b5e00a987c906d96fb0563f4c3fa550b4155/src/plot_api/helpers.js#L540), from which we infer that the axis type must have been manually set. I don't know how to check whether an axis type was manually set, though.
* When manually setting an axis when calling `newPlot`, `relayout` or `update`, the `clearAxisTypes` flag in in the trace attributes could be removed. However, I think the the trace attributes are global to all traces of the same type, so it wouldn't be possible to have the axis type fixed for traces on only one axis.
* Provide a mechanism for overriding the `clearAxisTypes` behaviour when calling `restyle`. This doesn't feel right, though, because it doesn't reinstate the old behaviour and because the `restyle` function doesn't take any parameters that could be used for this.

**Comment by etpinard** [comment] 2018-01-29 21:49
I think the _cleanest_ way to fix this would be to wait for `ax.autotype` proposed in https://github.com/plotly/plotly.js/issues/2234

But since this ticket signals a regression, perhaps we should try to make a quick (albeit temporary) fix. In this case, your first bullet point seems like the best solution.

**Comment by s31tz** [comment] 2020-07-02 19:28
I want to update timeseries data and observe the same problem in v1.54.5. Is there a workaround?

**Comment by s31tz** [comment] 2020-07-03 12:40
I found a workaround: deleteTraces() + addTraces() instead of restyle(). Downside: The trace must be completely defined.

**Comment by nikita-zamaraev-loginom** [comment] 2021-09-13 20:51
When clearing the data of the first trace, the display breaks. [codepen.io#Plotly.js axis.type discard error](https://codepen.io/x-base/pen/wveeRzV?editors=0010)

**Comment by gvwilson** [comment] 2024-06-10 21:02
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson

**Closed by gvwilson** 2024-06-10 21:02 UTC
Labels: type: regression

**Comment by bparsons5** [comment] 2024-09-17 18:20
Unfortunately, I am still getting this exact issue. plotly.js v2.35.2.
