### ISSUE TITLE
Parcoords context lines almost disappeared when there are over 1000 lines

### ISSUE THREAD

**Issue by archmoj** [plotly/plotly.js#3974] opened 2019-06-19 15:50 UTC
[Codepen](https://codepen.io/MojtabaSamimi/pen/ewBvoG?editors=0010)

cc: https://github.com/plotly/plotly.js/issues/3939

**Comment by gvwilson** [comment] 2024-06-14 12:02
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-14 12:02 UTC
Labels: type: bug
