### ISSUE TITLE
x param on Horizontal bar for date data not working as expected

### ISSUE THREAD

**Issue by ThomasLaforge** [plotly/plotly.js#4128] opened 2019-08-14 18:13 UTC
Hi,

I'm working on a TimeLine use of bar chart in plotly.
I need something like this codepen but for date data type.

https://codepen.io/etpinard/pen/ORKQNV

It seems to not work with date. Why? Did I miss something or it is just not working at all ?

here my use with dates :
https://codepen.io/thomaslaforge/pen/VwZavpW

base param is fine (start of my bar) but x param (size of my bar) is too much bigger than expected. X Datas like 1 or -1 or 1000 doing unexpected things.

Should I use number type and do my own stuff to create my xAxis as a date ?

Thanks

**Comment by etpinard** [comment] 2019-08-14 18:20
Duplicate of https://github.com/plotly/plotly.js/issues/2391

**Closed by etpinard** 2019-08-14 18:20 UTC
