### ISSUE TITLE
Implement different data-based autorange mode

### ISSUE THREAD

**Issue by fhurta** [plotly/plotly.js#928] opened 2016-09-12 14:51 UTC
Scatter graph with traces using autorange on x-axis has left and right gap if any of the traces has `markers` flag set on `trace.mode`.

If `mode='lines'` for all traces, the leftmost trace points are displayed on the leftmost point of X-axis, but if the `mode` is changed to e.g. `lines+markers`, there is a gap from the left and from the right. This visualization looks strange for time series data - it looks like there are no data point within the gaps..

See [sample](http://codepen.io/exavier/pen/GjoRom?editors=0010), change the `traceX.mode` to `lines` to see the difference.

**Comment by etpinard** [comment] 2016-09-12 14:54
This is the intended behaviour at the moment.

Can you expand on why this undesirable for your use case?

**Comment by fhurta** [comment] 2016-09-12 15:09
I'm showing the data for specified time range selected by user. On Pan event (or Zoom) I load the data for the new interval. The data is continuous time series stored in historian database for several years so user can pan backwards to see older data.

**Comment by etpinard** [comment] 2016-09-12 15:12
... and what's wrong with the current `autosize` for lines?

**Comment by etpinard** [comment] 2016-09-12 15:13
I guess you're looking for some autorange _padding_ setting?

**Comment by fhurta** [comment] 2016-09-12 15:18
Exactly, I would use padding=0 for my case

**Comment by fhurta** [comment] 2016-09-12 15:25
When all traces have `lines` mode, it is OK. That's why I haven't noticed this behavior before. Once I allowed to set (and display) the markers and the gap appeared I considered it as bug..

**Comment by etpinard** [comment] 2016-09-12 15:55
Great. I'll change this issue title accordingly.

This issue is somewhat related to https://github.com/plotly/plotly.js/issues/387

**Comment by erikrenberg** [comment] 2018-04-24 13:35
Any progress on this? 

It's a bit of a waste to have padding that could be used for actual data at both ends of the chart when markers are used.

**Comment by advaithasabnis** [comment] 2020-04-28 00:59
I'm looking for the opposite - only some scatter traces seem to have the padding but bar traces or filled-area traces don't. So if we have two or more types of traces in a plot, toggling one on or off affects the axis range. (In my specific example, I have a marker+lines scatter trace and bar trace. If I toggle off the scatter, then the bar trace "extends" to occupy the full x-axis).

**Comment by jackparmer** [comment] 2020-09-10 19:42
This issue has been tagged with `NEEDS SPON$OR`

A [community PR](https://github.com/plotly/plotly.js/pulls?q=is%3Apr+is%3Aopen+label%3A%22type%3A+community%22) for this feature would certainly be welcome, but our experience is deeper features like this are difficult to complete without the Plotly maintainers leading the effort.

**Sponsorship range: $5k-$10k**

What Sponsorship includes:
- Completion of this feature to the Sponsor's satisfaction, in a manner coherent with the rest of the Plotly.js library and API
- Tests for this feature
- Long-term support (continued support of this feature in the latest version of Plotly.js)
- Documentation at [plotly.com/javascript](https://plotly.com/javascript/)
- Possibility of integrating this feature with Plotly Graphing Libraries (Python, R, F#, Julia, MATLAB, etc)
- Possibility of integrating this feature with Dash
- Feature announcement on [community.plotly.com](https://community.plotly.com/tag/announcements) with shout out to Sponsor (or can remain anonymous)
- Gratification of advancing the world's most downloaded, interactive scientific graphing libraries (>50M downloads across supported languages)

Please include the link to this issue when [contacting us](https://plotly.com/get-pricing/) to discuss.

**Comment by amroczeK** [comment] 2021-04-29 01:04
Not sure if this helps you guys, but here is an example of removing the padding on the X-Axis for line+scatter charts.

https://jsfiddle.net/amroczeK90/waj25yc8/3/

Setting the range on the X-Axis did the trick. 

xaxis: { range: [data[0]["x"][0], data[0]["x"][data[0]["x"]-1]] }

**Comment by ajafff** [comment] 2021-06-24 09:36
FYI: I just discovered that adding `fill` removes the padding. Setting `fillcolor: 'transparent'` hides the fill and everything works as expected.

I changed the fiddle form above accordingly: https://jsfiddle.net/zv6kuh1f/

**Comment by gvwilson** [comment] 2024-06-05 17:19
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson

**Closed by gvwilson** 2024-06-05 17:19 UTC
Labels: type: feature, ♥ NEEDS SPON$OR
