### ISSUE TITLE
Free click in cartesian graphs

### ISSUE THREAD

**Issue by nmalyschkin** [plotly/plotly.js#4396] opened 2019-12-02 08:44 UTC
Hey!

I could really use a feature, that allows free click events in cartesian graphs. Currently click events are bound to points in data sets. This should be fairly easy to implement.

To make this a non-breaking feature, I propose to leave the `plotly-click` event as it is and add a new event called `plotly-freeclick`.

If there already is a feature for this, please point me in the right direction.
If there are reasons against such a feature, please tell me.

I offer myself to implement this feature.

**Comment by etpinard** [comment] 2019-12-02 14:51
Thanks for posting!

This is a duplicate of https://github.com/plotly/plotly.js/issues/2696

**Closed by etpinard** 2019-12-02 14:51 UTC
