### ISSUE TITLE
X Axis (type: category) sorting gets lost when traces have different X values 

### ISSUE THREAD

**Issue by arikfr** [plotly/plotly.js#254] opened 2016-02-12 16:34 UTC
Here's an example: http://codepen.io/anon/pen/vLbXQX

The traces are:
```js
var trace1 = {
  x: [1, 7, 8, 10, 15, 16, 17], 
  y: [10, 15, 13, 17, 5,6,7], 
  type: 'bar'
};
var trace2 = {
  x: [ 1, 4, 5, 7], 
  y: [16, 11,2, 9], 
  type: 'bar'
};
```

Resulting plot is:
![image](https://cloud.githubusercontent.com/assets/71468/13013128/ca53147c-d1b6-11e5-8cc2-92c5e14b0695.png)

Notice how the values for 4 & 5 are at the end of the X axis.

It doesn't happen all the time, for example if we switch the order of `trace1` and `trace2`, it gets drawn properly:

![image](https://cloud.githubusercontent.com/assets/71468/13013175/0202df24-d1b7-11e5-9421-7eecfae9127a.png)

Is it me holding it wrong or an actual issue?

**Comment by etpinard** [comment] 2016-02-12 16:44
@arikfr thanks for the very detailed report :beers: 

What you described is actually the desired behaviour in the current specs. plotly.js does not sort categories. Categories are listed in the order where they are supplied in the data. 

So, the categories in the first trace come first then the categories in the second trace either get paired up with the categories already present or are appended at the end of the category list.

We are planning on adding more control to categorical axes. See https://github.com/plotly/plotly.js/issues/189 for more details. So I'll mark this issue as a duplicate.

**Comment by etpinard** [comment] 2016-02-12 16:44
duplicate of https://github.com/plotly/plotly.js/issues/189

**Closed by etpinard** 2016-02-12 16:44 UTC

**Comment by arikfr** [comment] 2016-02-12 21:09
@etpinard thanks for the quick reply. I will follow #189 and apply some workaround on our side until then.

**Comment by Aravinth-0812** [comment] 2020-07-06 08:59
@arikfr Hi did you get a fix for this problem

**Comment by lalitcse** [comment] 2021-02-09 10:53
@arikfr have you found any solution??

**Comment by lalitcse** [comment] 2021-02-09 10:53
<img width="624" alt="Screenshot (909)" src="https://user-images.githubusercontent.com/36290540/107353553-2e38be80-6af3-11eb-8ed9-0d3754abaf57.png">

**Comment by lalitcse** [comment] 2021-02-09 10:55
I am also having the same issue @etpinard
