### ISSUE TITLE
Extend `categoryorder` to multicategory axes

### ISSUE THREAD

**Issue by etpinard** [plotly/plotly.js#3908] opened 2019-05-24 18:12 UTC
Currently we [don't](https://github.com/plotly/plotly.js/blob/19e60bedc70e50acbbf11049a38f8ae29775bfe4/src/plots/cartesian/category_order_defaults.js#L56-L57) coerce `categoryorder` and friends for mulitcategory axes. Extending `categoryarray` and sorting will be a little challenging from an API standpoint. 

- Should we refer to category pairs in `categoryarray` as 2-item arrays e.g. `categoryarray: [['q1', 'A'], ['q2', 'B]]`
- We'll have to disallow some combinations to ensure that we don't jump from one parent category to another and back
- We'll probably need to sort parent and child categories separately?

Related: https://github.com/plotly/plotly.js/issues/3723

Some context: https://community.plot.ly/t/ordering-on-multi-level-bar-charts/23747

**Comment by LarryMartell** [comment] 2019-05-24 19:54
I have charts with 3 levels. I'd like for each level to be sorted within its higher level. See https://community.plot.ly/t/ordering-on-multi-level-bar-charts/23747 for an example of my 3 level chart.

**Comment by davepattie** [comment] 2019-05-24 21:26
controlling the child sort order within the parent would be great +1

**Comment by LarryMartell** [comment] 2019-07-31 19:11
Any update on when this might be fixed?

**Comment by kmcentush** [comment] 2020-04-29 21:00
I would love for this to be implemented as well.

**Comment by AndreasUntch** [comment] 2020-09-14 17:36
Any updates on this feature?  Hope it will get implemented soon

**Comment by nicolaskruchten** [comment] 2020-09-25 13:39
This issue has been tagged with `NEEDS SPON$OR`

A [community PR](https://github.com/plotly/plotly.js/pulls?q=is%3Apr+is%3Aopen+label%3A%22type%3A+community%22) for this feature would certainly be welcome, but our experience is deeper features like this are difficult to complete without the Plotly maintainers leading the effort.

**Sponsorship range: $10k-$15k**

What Sponsorship includes:
- Completion of this feature to the Sponsor's satisfaction, in a manner coherent with the rest of the Plotly.js library and API
- Tests for this feature
- Long-term support (continued support of this feature in the latest version of Plotly.js)
- Documentation at [plotly.com/javascript](https://plotly.com/javascript/)
- Possibility of integrating this feature with Plotly Graphing Libraries (Python, R, F#, Julia, MATLAB, etc)
- Possibility of integrating this feature with Dash
- Feature announcement on [community.plotly.com](https://community.plotly.com/tag/announcements) with shout out to Sponsor (or can remain anonymous)
- Gratification of advancing the world's most downloaded, interactive scientific graphing libraries (>50M downloads across supported languages)

Please include the link to this issue when [contacting us](https://plotly.com/get-pricing/) to discuss.

**Comment by nicolaskruchten** [comment] 2020-09-25 13:39
See also https://github.com/plotly/plotly.js/issues/3723

**Comment by gvwilson** [comment] 2024-06-14 12:00
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-14 12:00 UTC
Labels: type: feature, ♥ NEEDS SPON$OR
