### ISSUE TITLE
Bar attributes shouldn't have anim:true in the schema

### ISSUE THREAD

**Issue by cpsievert** [plotly/plotly.js#3737] opened 2019-04-05 17:30 UTC
Perhaps this is expected, but I found it surprising since `bar`'s y atttribute has a `anim: true` flag in this config (this means it should work with the react transitioning API, right?)

https://codepen.io/cpsievert/pen/axZZeP

**Comment by etpinard** [comment] 2019-04-05 17:36
Duplicate of https://github.com/plotly/plotly.js/issues/1019

**Comment by etpinard** [comment] 2019-04-05 18:46
Ha oops. Sorry @cpsievert I misread the issue. I thought we were asking whether bar traces can be smoothly transitioned. The answer is no.

But you're right, `anim: true` for `x`, `y` etc should be there in the `bar` trace schema. Have you noticed `anim: true` showing up anywhere else?

**Comment by cpsievert** [comment] 2019-04-05 20:05
No, but I haven't really been playing around with `Plotly.react()` much at all yet

**Closed** 2019-07-08 12:36 UTC
Labels: type: documentation
