### ISSUE TITLE
Identical axis labels removed in heatmap (need new category mode or axis type)

### ISSUE THREAD

**Issue by lvdmaaten** [plotly/plotly.js#1516] opened 2017-03-24 20:14 UTC
Consider the following plot (as JSON):
```
{'layout': {u'margin': {u'r': 60, u'b': 60, u't': 60, u'l': 60}}, 'data': [{u'zmax': 1.0054633722786, u'colorscale': u'Viridis', u'zmin': -1.4410649905944, u'y': [u'a', u'b', u'a'], u'x': [u'd', u'd'], u'z': [[-0.50443826056116, -0.55385051210768], [-0.52712315391279, 1.0054633722786], [-1.4410649905944, 0.50761805140936]], u'type': u'heatmap'}]}
```
Note how there are identical axis labels in the JSON on the x and y-axis. This leads to an incorrect rendering:
![screen shot 2017-03-24 at 4 09 04 pm](https://cloud.githubusercontent.com/assets/1168046/24311926/a66d39a8-10ac-11e7-9218-65d5b84e169c.png)

It appears the identical labels get removed automatically.

Additional context [here](https://github.com/facebookresearch/visdom/issues/21) and [here](http://stackoverflow.com/questions/40742473/plotly-seems-to-lose-labels-of-a-heatmap).

**Comment by etpinard** [comment] 2017-03-24 20:37
Thanks for bringing this up!

I agree that the expected behavior for `heatmap` traces would have two columns with label `'d'`. Unfortunately, this somewhat contradicts our category mapping where each unique category gets assigned one numeric coordinate. For example:

```js
Plotly.plot('graph', [{
  x: ['a', 'b', 'a'],
  y: [1, 2, 3]
}])
```
generates

[![image](https://cloud.githubusercontent.com/assets/6675409/24312419/e4e7c796-10ae-11e7-9f57-b1493b907878.png)](http://codepen.io/etpinard/pen/bqKJbN?)

So I'm thinking maybe we could add a new attribute (e.g. `categorymode: 'unique' | 'index'`) or a new axis `type` (e.g. `xaxis.type: 'category-by-index'` or something less verbose :smile: ) to make the distinction between the desired heatmap behavior and the current (scatter) behavior.

----

In the meantime, you can make those categories _unique_ by inputting `x: ['d', 'd ']`:

[![image](https://cloud.githubusercontent.com/assets/6675409/24312677/fd7a1074-10af-11e7-9a9e-0ed3f2e0f177.png)](http://codepen.io/etpinard/pen/peKBJN?editors=0010)

**Comment by lvdmaaten** [comment] 2017-03-24 20:49
Ah, interesting work-around. I didn't realize it would remove the whitespaces when rendering. Thanks!

**Comment by cpsievert** [comment] 2017-03-24 20:51
Another option would be to use [ticktext](https://plot.ly/javascript/reference/#layout-xaxis-ticktext)/[tickvals](https://plot.ly/javascript/reference/#layout-xaxis-tickvals):

http://codepen.io/cpsievert/pen/bqKJoe

**Comment by alexcjohnson** [comment] 2017-03-30 14:20
> I didn't realize it would remove the whitespaces when rendering. 

I don't think it does remove them... look closely at the positioning, the second `d` is a little left of center. So I guess you could use `' d '` to make it symmetric (though adding spaces will probably muck up hover text), or use a [zero-width space](https://en.wikipedia.org/wiki/Zero-width_space#Encoding), but @cpsievert has a much better solution.

Unless this problem generalizes substantially to the point that ticktext/tickvals becomes unworkable, I wouldn't be in favor of making a new axis mode or type for it. Too many strange follow-on effects if data<->position isn't a 1:1 mapping. Like what does it mean if you try to position something else on the axis at `'d'`? Or if you have a second heatmap, or some scatter data, that you want to plot on top of this? What position value do we report for click or hover events?

**Comment by etpinard** [comment] 2017-05-17 22:15
To solve this issue, we could:

- add an axis `type` value e.g. `xaxis.type: 'category-nonunique'`, or
- add an axis boolean attribute e.g. `xaxis.uniquecategories: true || false`
- add a more general enumerated axis attribute e.g. `xaxis.categorymode` with possible values: `'unique'` (the default) and `'duplicate'` and potentially others down the road.

I can't think of another possible `categorymode` value, so I'd vote for adding a `uniquecategories` boolean. Thoughts?

**Comment by alexcjohnson** [comment] 2017-05-17 23:47
I still think it’s a bad idea to have an axis that doesn’t map data one-to-one to position. What if you want to tile several heatmaps? What if you want a scatter or bar trace on the same axis? What if you bind a click or hover handler, how will you know on which copy of the item the event really happened? All of these situations would be easy to manage with `ticktext` / `tickvals` but would be ambiguous, and probably in some cases impossible to get right, with a many-to-one mapping.

Perhaps we could consider a mode within the `heatmap` trace (and potentially in other trace types too) that automatically maps `x` and `y` string arrays to `tickvals` and `ticktext` on the appropriate axis (with an optional `x0` and `dx` etc so `tickvals` need not be `[0, 1, 2...]`)? That seems like it would yield the same visual result without the ambiguities.

**Comment by jdepons** [comment] 2017-06-02 18:46
I am having the same issue with a bar chart and see this as a major oversight.  I just want to print a simple bar chart for a group of clinical measurements.  Some animals were measured multiple times and some were not so traces will not work correctly.  I should be able to display multiple values with the same x axis label without having 10 white spaces surrounding the 10th measurement for a specific label.

As an example my x axis may look like the following Rat, Rat, Rat, Rat, Rat, Chicken, Squirrel, Chicken.

Any ideas other than the white space fix above are appreciated.

**Comment by zbjornson** [comment] 2017-06-02 18:51
@jdepons the method suggested by @cpsievert in https://github.com/plotly/plotly.js/issues/1516#issuecomment-289139760 works better than the white space hack, although it's a little bit tedious.

**Comment by SaucePan1** [comment] 2017-11-07 16:51
Is there any official solution to this? Im generating the x_labels automatically in-app and the whitespace solution is definetely not an option! 

Any recomendations?

**Comment by Dantalion** [comment] 2017-11-16 10:10
This is actually severe. The priority to fix this should be highest.
It would be best if we had a data attribute to set x and y values to unique or not.
The functionality without that is highly impacted and holds the potential back at the moment.

**Comment by alexcjohnson** [comment] 2017-11-16 13:51
@SaucePan1 @Dantalion have you tried the `tickvals`/`ticktext` suggestion @cpsievert [mentioned](https://github.com/plotly/plotly.js/issues/1516#issuecomment-289139760) and demonstrated in http://codepen.io/cpsievert/pen/bqKJoe ? I feel pretty strongly that we cannot make an axis type where data do not map 1:1 to position, it just causes unending headaches when you try to do anything beyond a single trace.

One current limitation I see of this approach is that we always show every tick when using `tickvals`/`ticktext`. That's a more general problem that has its own issue https://github.com/plotly/plotly.js/issues/1812

**Comment by RBVI** [comment] 2019-01-03 22:49
Just to add another voice to this.  I've got a heatmap where I'm showing the results of differential expression experiment with 6 clusters.   I'm showing the top 10 and bottom 10 genes for each cluster, so the Y: genes, X: clusters.  In many cases, the genes overlap.   I'll certainly try the ticktext approach, but I might have 100's of genes, so the ability to automatically choose the tick interval is extremely nice...

**Comment by LeUser111** [comment] 2019-04-02 08:13
Hey guys!

A little late to the party - however we've just run into this exact issue with the stacked-bar-chart. We are trying to display the properties of tools that are used in a process. Of course tools can be used multiple times.

Thanks to the solution of @cpsievert it works like a charm! (Thank you very much!).

Here's a simple example where I just mixed the example code for [stacked-bar-charts](https://plot.ly/javascript/bar-charts/#stacked-bar-chart) with the solution proposed by @cpsievert :

```
var trace1 = { 
  y: [20, 14, 23],
  name: 'Primary Processing',
  type: 'bar'
};

var trace2 = { 
  y: [12, 18, 29],
  name: 'Secondary Processing',
  type: 'bar'
};

var data = [trace1, trace2];
var layout = {barmode: 'stack', "xaxis": {
    "ticktext": ["tool1", "tool2", "tool1"], "tickvals": [0, 1, 2]
  }};

Plotly.newPlot("graph", data, layout);
```

The reason why I'm posting this:

Would you kindly consider adding this information to the official documentation? (e.g. [here](https://plot.ly/javascript/bar-charts/#stacked-bar-chart))

As this issue shows it's not an uncommon requirement and since there is a practical solution for this it would be great if it was described close to the charts themselves - maybe as an additional example (e.g. "bars with multiple occurrences of x-values").

(Sorry if it's already there and I just missed it!)

**Comment by RBVI** [comment] 2020-01-03 22:22
**Help!**  With the latest plotly.js (1.51.3) the tickvals/ticktext solution no longer works.  If you look at [http://codepen.io/cpsievert/pen/bqKJoe](http://codepen.io/cpsievert/pen/bqKJoe) you can see that only one category is shown.  This is broken some important functionality for our pipeline.

**Comment by zbjornson** [comment] 2020-01-03 22:27
@RBVI your tickvals and x/y values need to match up:

```js
var dat = [{
  "x": [0,1],
  "y": [2,3],
  "z": [[1,2], [3,4]],
  "type": "heatmap"
}];

Plotly.plot(
  "graph", dat,
  {
    "xaxis": {
      "ticktext": ["a", "a"], "tickvals": [0, 1]
    },
    "yaxis": {
      "ticktext": ["b", "c"], "tickvals": [2, 3]
    }
  }
);
```

(don't want to sign up for codepen to save that.)

**Comment by jackparmer** [comment] 2020-09-10 19:25
This issue has been tagged with `NEEDS SPON$OR`

A [community PR](https://github.com/plotly/plotly.js/pulls?q=is%3Apr+is%3Aopen+label%3A%22type%3A+community%22) for this feature would certainly be welcome, but our experience is deeper features like this are difficult to complete without the Plotly maintainers leading the effort.

**Sponsorship range: $10k-$15k**

What Sponsorship includes:
- Completion of this feature to the Sponsor's satisfaction, in a manner coherent with the rest of the Plotly.js library and API
- Tests for this feature
- Long-term support (continued support of this feature in the latest version of Plotly.js)
- Documentation at [plotly.com/javascript](https://plotly.com/javascript/)
- Possibility of integrating this feature with Plotly Graphing Libraries (Python, R, F#, Julia, MATLAB, etc)
- Possibility of integrating this feature with Dash
- Feature announcement on [community.plotly.com](https://community.plotly.com/tag/announcements) with shout out to Sponsor (or can remain anonymous)
- Gratification of advancing the world's most downloaded, interactive scientific graphing libraries (>50M downloads across supported languages)

Please include the link to this issue when [contacting us](https://plotly.com/get-pricing/) to discuss.

**Comment by thammegowda** [comment] 2021-11-30 22:51
If we are going to use a spacer workaround, using zero-width-space[1] would save some space 

```javascript
function pad_unique(arr, pad='\u200b'){
  let mem = new Set()
  for (let idx = 0; idx < arr.length; idx++) {
    let val = arr[idx]
    while (mem.has(val)) {
      val += pad
    }
    mem.add(val)
    arr[idx] = val
  }
  return arr
}
// call this on x and y arrays to make them unique 
pad_unique(x)
pad_unique(y)
```

-[1] https://unicode-table.com/en/200B/

**Comment by gvwilson** [comment] 2024-06-10 14:03
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson

**Closed by gvwilson** 2024-06-10 14:03 UTC
Labels: type: feature, ♥ NEEDS SPON$OR

**Comment by SuperCowProducts** [comment] 2026-07-15 05:48
@gvwilson a similar issue occurs with sunburst charts for example:

Works
```python
import plotly.express as px
data = dict(
    character=["Eve", "Cain", "Seth", "Enos", "Noam", "Abel", "Awan", "Enoch", "Azura"],
    parent=["", "Eve", "Eve", "Seth", "Seth", "Eve", "Eve", "Awan", "Eve" ],
    value=[10, 14, 12, 10, 2, 6, 6, 4, 4])

fig = px.sunburst(
    data,
    names='character',
    parents='parent',
    values='value',
)
fig.show()
```
Doesn't
```python
import plotly.express as px
data = dict(
    character=["a", "b", "c", "d", "a", "b", "c", "d", "e"],
    parent=["", "Eve", "Eve", "Seth", "Seth", "Eve", "Eve", "Awan", "Eve" ],
    value=[10, 14, 12, 10, 2, 6, 6, 4, 4])

fig = px.sunburst(
    data,
    names='character',
    parents='parent',
    values='value',
)
fig.show()
```
