### ISSUE TITLE
ScatterGL Hover Missing /w Data Gaps

### ISSUE THREAD

**Issue by Kolano** [plotly/plotly.js#2524] opened 2018-04-04 19:00 UTC
On ScatterGL plots with gaps in their data (i.e. null values on Y axis array) hover pop-ups only show up for the right-most (last?) data points. This seems to be handled correctly with the Scatter type.

**Comment by etpinard** [comment] 2018-04-04 19:06
Thanks for the report! Can you please a reproducible example to help us out?

**Comment by Kolano** [comment] 2018-04-04 20:03
I tried to provide a Chart Studio link for it, but is seems Chart Studio may not use the GL versions of plots, so here's a CodePen... 
https://codepen.io/Kolano/pen/ZxMKza

**Comment by alexcjohnson** [comment] 2018-04-04 22:45
Interesting - it depends on the length of the gap, or perhaps the total number of missing values? See https://codepen.io/alexcjohnson/pen/NYLaPR - at the end I have a loop that replaces `null` with `0` up to a certain point (`for(var i = 0; i < fig.data[0].y.length/1.8; i++)`) - at 1.8 the problem is still there (and in fact some of the `0` values before (to the right of) the gap also have no hover) but if you decrease that number to 1.75 or less it all works as expected.

**Comment by etpinard** [comment] 2018-04-06 20:44
This appears fixed in `master`:

![peek 2018-04-06 16-40](https://user-images.githubusercontent.com/6675409/38443309-4aa37f38-39b9-11e8-96d3-cdf4f6dfe491.gif)

most likely due to @dy's point clustering improvements in https://github.com/plotly/plotly.js/pull/2499

---- 

So ... I'll close this thing. @Kolano feel free to open up a new issue if this bug persist in `1.36.0` once it is released (about ~10 days from now).

**Closed by etpinard** 2018-04-06 20:44 UTC
Labels: type: bug
