### ISSUE TITLE
Camera rotation restrictions

### ISSUE THREAD

**Issue by cy6eria** [plotly/plotly.js#4150] opened 2019-08-27 08:09 UTC
It would be nice to be able to limit a camera rotation angles or just disable axis rotation.

**Comment by gvwilson** [comment] 2024-06-14 12:49
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-14 12:49 UTC
Labels: type: feature
