### ISSUE TITLE
js-plotly-tester causing other elements to vanish (Chrome)

### ISSUE THREAD

**Issue by benjeffery** [plotly/plotly.js#513] opened 2016-05-05 14:01 UTC
Some unrelated elements are hidden when a plot is created in Chrome.
I've tried to make as minimal test case as possible: https://jsfiddle.net/r5uzc7rd/3/
In the fiddle after 2 seconds js-plotly-tester is removed from the DOM and an element becomes visible.
This element is only hidden when using Chrome (I'm on version 50).
A possible workaround is to put z-index:1 on js-plotly-tester but I don't know if that has other consequences. I think #393 may be related.

**Comment by etpinard** [comment] 2016-05-05 14:17
Thanks for bringing this up and :beers: for that very nice reproducible example.

After a quick look on browerstack, this issue seems to be apparent **only** in Chrome 49 and up.

It is not obvious to me what Chrome dislikes about our [svg tester node](https://github.com/plotly/plotly.js/blob/5aef0e78487985978a2fa8a20c137cf892751b75/src/components/drawing/index.js#L447-L486).

**Comment by benjeffery** [comment] 2016-05-05 14:22
It is certainly a strange one - if you remove the "transform3d" style on the sibling div, OR remove the "absolute-overlay" div OR remove the z-index on the hidden element then the element is not hidden!

**Comment by mdtusz** [comment] 2016-05-09 17:14
I'm not 100% convinced this is a plotly.js bug. @benjeffery if you encounter more strangeness with this, please let us know so if it is on our end, we can solve it.

**Comment by benjeffery** [comment] 2016-05-10 01:16
Yes, this is not the fault of plotly - this is clearly a browser bug. However plotly could help by including a workaround, such as the z-index on the tester SGV. I'm happy to make a PR for that. 

I'm trying to pin down the exact bug to submit a browser issue, but the behaviour is hard to pin down.

**Comment by jec99** [comment] 2016-05-26 17:25
I am also experiencing this bug. I'm using Angular Material and if a header is designated as `<md-toolbar>` it is hidden by Plotly, but if it is written as a  `<div>` it is not. It also interferes with the `<md-sidenav>` directive. It is not an issue of interference because it does not occur in Firefox. The bug does not occur if the element is set to `display: table-group-header;`, `display: table-row`, or a few others, but it does occur with all common `display` settings.

**Comment by benjeffery** [comment] 2016-07-14 14:32
As suggested in the contributing guide, I have made a PR against my fork. Could this be reviewed? I'll then make a PR against this repo. Thanks!

**Comment by etpinard** [comment] 2016-07-14 15:41
@benjeffery your fix comes at a good time. Looks like this issue is happening on FF47 too.

**Comment by etpinard** [comment] 2016-07-14 16:58
My mistake. Everything is fine in FF47. I misunderstood what the jsFiddle :arrow_double_up: was trying to show. 

Even better news: looks like this bug is in fact _fixed_ in Chrome 51.

**Comment by etpinard** [comment] 2016-07-14 17:08
fixed via https://github.com/plotly/plotly.js/pull/745

**Closed by etpinard** 2016-07-14 17:08 UTC
Labels: type: bug, type: community

**Comment by benjeffery** [comment] 2016-07-15 11:10
Thanks!
