### ISSUE TITLE
Voxel trace type

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.js#4371] opened 2019-11-20 15:08 UTC
This could be a good starting point: https://github.com/wwwtyro/vixel/blob/master/README.md

**Comment by alexcjohnson** [comment] 2019-11-20 17:25
how is this different from `volume`?

**Comment by nicolaskruchten** [comment] 2019-11-20 18:55
it would render as little cubes with edges and everything

**Comment by alexcjohnson** [comment] 2019-11-20 19:54
OK - could we model this then as another mode of `volume` trace? Kind of the equivalent of heatmap's `zsmooth` attribute?

**Comment by jackparmer** [comment] 2019-11-21 20:24
Would be cool to support vixel's smooth animation potential: https://twitter.com/wwwtyro/status/1093381230777774080

**Comment by gvwilson** [comment] 2024-06-14 12:53
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-14 12:53 UTC
Labels: type: new trace type
