### ISSUE TITLE
Hover text can be unreadable (eg white on yellow: wish - auto-color.

### ISSUE THREAD

**Issue by RichardNeill** [plotly/plotly.js#2947] opened 2018-08-28 14:22 UTC
By default, the hover tooltip has its background the same colour as the bar. The text is always white.

This means that, if the bar is made say, yellow, or cyan, then the text of the hover tooltip is very hard to read (white on yellow is impossible). It's possible to change the tooltip colour, to a specific constant (e.g. '#eee'), but this doesn't always solve the problem. 

So, my suggestion is that, when the hover tooltip is drawn, the text colour should follow this rule:

* If a manual colour is specified, use this.
* Else, if the tooltip background (manual, or via bar-color) is dark, set it to '#fff'.
* Else if the background is light, set it to '#000'.

(I suggest a heuristic that "light" counts as  r+g+b > 500)

Thanks.

**Comment by alexcjohnson** [comment] 2018-08-28 14:33
For the most part we do that - here it is for scatter, where you can see the orange color is light enough to trigger dark text but the (darker) blue and the black common label get white text.
![screen shot 2018-08-28 at 10 30 17 am](https://user-images.githubusercontent.com/2678795/44729714-65df5780-aaad-11e8-87bd-3baaac47c6c3.png)
But I wouldn't be surprised if we failed to do this in some cases - What context are you seeing this?

**Comment by RichardNeill** [comment] 2018-08-29 01:09
I'm seeing this when I explicitly set the trace.marker = colours  
i.e. specifying an array of colours one per marker, rather than letting the colour be auto-assigned.
So, for example, different bars are red or green depending on whether they are in/out-of spec.

I think that applying a manual colour to each marker overrides the hover-tooltip-background, but does not then cause the hover-text-colour to be re-selected.

**Comment by alexcjohnson** [comment] 2018-08-29 01:48
Here's the situation I think you're describing https://codepen.io/alexcjohnson/pen/XPjXRV?editors=1010, but I don't see that behavior, it all looks fine to me - light colors get dark hover text, dark colors get white hover text:
![screen shot 2018-08-28 at 9 46 30 pm](https://user-images.githubusercontent.com/2678795/44760227-d9b04d00-ab0b-11e8-9c09-6c2461ae55fd.png)

Can you provide a reproducible example?

**Comment by etpinard** [comment] 2018-10-05 16:35
Closing due to lack of reproducible example.

@RichardNeill feel free to open another issue once you're able to isolate the problem in a codepen.

**Closed by etpinard** 2018-10-05 16:35 UTC
