### ISSUE TITLE
3D draw order incorrect with transparent surfaces

### ISSUE THREAD

**Issue by slishak** [plotly/plotly.js#3410] opened 2019-01-07 09:51 UTC
https://codepen.io/anon/pen/pqVVyz

Setting all trace opacities in the above codepen to 1, all `surface`s and `scatter3d`s are drawn in the correct order (when looking from above I can only see the blue `surface`, when looking from below only the red `surface`).
![image](https://user-images.githubusercontent.com/12515343/50761020-a0ca7680-1269-11e9-8739-b1938bb378d0.png)

Setting the opacities to 0.999, the draw order seems solely determined by the order in which the traces were defined (so the red `surface`, which is defined first, is always occluded by the blue `surface` and all `scatter3d`s).
![image](https://user-images.githubusercontent.com/12515343/50760991-8d1f1000-1269-11e9-9bca-e17a0bf91843.png)

Transparent lines with opaque surfaces seem to be drawn correctly.

**Comment by etpinard** [comment] 2019-01-07 14:38
Essentially a duplicate of https://github.com/plotly/plotly.js/issues/3243

Thanks for the very clear report!

**Closed by etpinard** 2019-01-07 14:38 UTC

**Comment by slishak** [comment] 2019-01-07 14:41
Ah sorry, didn't find that open issue! :)

**Comment by etpinard** [comment] 2019-01-07 14:43
No worries!
