### ISSUE TITLE
Native ES6 modules vs. the bundle

### ISSUE THREAD

**Issue by oldrich-svec** [plotly/plotly.js#3518] opened 2019-02-06 09:12 UTC
When `plotly.js` is loaded in Chrome by the native ES6 `import`, the loading crashes with `Cannot read property 'document' of undefined` at line `18178`, i.e. at `var d3_document = this.document;`

The problem is that the bundler assumes that when a function is executed without any `this`, the `this` will automatically be set to `window`. This is not the case with ES6 modules, where `this` will be undefined.

I fixed it by changing line `27724` from `}();` to `}.apply(self);` but this is just a hack :)

**Comment by etpinard** [comment] 2019-02-06 14:46
Thanks for writing in.

> When `plotly.js` is loaded in Chrome by the native ES6 `import`,

Can you share a reproducible example of how you're going about doing this. Thank you!

**Comment by oldrich-svec** [comment] 2019-02-07 07:10
Try:

```
<!doctype html>
<html lang=en>
<head>
<meta charset=utf-8>
</head>
<body>
<script type="module" src="https://cdn.plot.ly/plotly-latest.min.js"></script>
</body>
</html>
```

**Comment by alexcjohnson** [comment] 2019-02-07 14:45
In a codepen: https://codepen.io/alexcjohnson/pen/aXEbOa?editors=1011

That particular error is with d3v3 - seems like v4 fixes it so we should get it when we leapfrog to v5. Will be interesting to see if there's anything else in our code that uses `this` to mean the window (or anything else that's incompatible with ES6 modules... I'm not very familiar) but it doesn't seem like there's much point trying before the d3 upgrade.

**Comment by jmsuresh** [comment] 2019-05-06 08:59
@oldrich-svec 
> I fixed it by changing line `27724` from `}();` to `}.apply(self);` but this is just a hack :)
Can you please provide which particular line had to be changed. I am stuck with this for the past two days (tried many things with babel options - nothing worked)

**Comment by leolorenzoluis** [comment] 2019-06-02 03:34
Any fix for this?

**Comment by LRagji** [comment] 2019-06-14 06:49
For version 1.48.2 the change is at line number 32481 @ /node_modules/plotly.js/dist/plotly.js

**Comment by wendelstam** [comment] 2019-07-22 11:29
Anybody know if there is a issue for this filed in the d3 project?

**Comment by oldrich-s** [comment] 2019-08-01 06:23
@jmsuresh In this file:

https://cdnjs.cloudflare.com/ajax/libs/plotly.js/1.48.2/plotly.js

search for `define(d3)`. You will find:

```
if (typeof define === "function" && define.amd) this.d3 = d3, define(d3); else if (typeof module === "object" && module.exports) module.exports = d3; else this.d3 = d3;
}();
```

Change `}();` to `}.apply(self);`

**Comment by etpinard** [comment] 2019-08-15 15:31
From https://github.com/plotly/plotly.js/issues/4130 @Arjun-Shinojiya wrote:

> I am trying to integrate plotly.js in my Angular 8 project. I successfully integrated it and tested it in local ,that time it is working fine without any error. But when I check it in live server ,that time I am getting cannot read property 'document ' of undefined error.. I also similar issue blog in this repository.`.I wanted to try this hack
changing line 27724 from }(); to }.apply(self); but this is just a hack :)
But I dont know in which module file I can get this line.Currently none of the plotly.js file have 27724 lines

Maybe someone here can help.

**Comment by Arjun-Shinojiya** [comment] 2019-08-15 16:21
> When `plotly.js` is loaded in Chrome by the native ES6 `import`, the loading crashes with `Cannot read property 'document' of undefined` at line `18178`, i.e. at `var d3_document = this.document;`
> 
> The problem is that the bundler assumes that when a function is executed without any `this`, the `this` will automatically be set to `window`. This is not the case with ES6 modules, where `this` will be undefined.
> 
> I fixed it by changing line `27724` from `}();` to `}.apply(self);` but this is just a hack :)


@oldrich-svec  can you please tell the exact location of the file which you mentioned in this questions the last line? .I am facing the same issue.

**Comment by oldrich-s** [comment] 2019-08-15 16:29
see https://github.com/plotly/plotly.js/issues/3518#issuecomment-517138019

**Comment by Arjun-Shinojiya** [comment] 2019-08-15 16:46
> see [#3518 (comment)](https://github.com/plotly/plotly.js/issues/3518#issuecomment-517138019)

So I should use plotly.js via CDN in angular 8 right?

**Comment by oldrich-s** [comment] 2019-08-16 04:57
@Arjun-Shinojiya it is up to you how you use plotly.js ;). The comment just shows you what line you want to edit.

**Comment by meriturva** [comment] 2019-08-28 06:52
@TravisLRiffle yes you have to reapply your hack every time! For me, it is not a solution for enterprise applications.

**Comment by maxmeyer** [comment] 2019-09-21 20:48
After fixing this, I got a d3_xhr-not found-error although it's defined

**Comment by AlanJMac** [comment] 2019-10-03 12:02
_Alternative workaround for Angular 8 upgraders:_ For those of us coming here having encountered this issue when upgrading to Angular 8, an alternative workaround solution to editing the plotly.js file is to not use the new "Differential Loading by Default" as mentioned in this comment on angular-plotly.js: https://github.com/plotly/angular-plotly.js/issues/75#issuecomment-526871836

> I could solve the issue forcing the typescript to be generated as "target": "es5" making it not use the <script src="..." type="module" />, thus both plotly.js and angular code is served by "legacy" way.
Please check this link for more informations: https://blog.angular.io/version-8-of-angular-smaller-bundles-cli-apis-and-alignment-with-the-ecosystem-af0261112a27

So changing the following property in the tsconfig.json file hides the issue:
`{
    "compilerOptions": {
        "target": "es5"
    }
}`

**Comment by MikeOne** [comment] 2019-12-04 13:46
Is there a 'real' solutions for this available? I'd like to use Plotly for an Angular 8 project - but reverting to es5 is not really an option (it will break for Angular 9 I think). I was so hoping to use plotly as a Highchart replacement - but no dice I'm afraid.

**Comment by kundralaci** [comment] 2020-02-12 15:34
Just tried with the current latest version (1.52.2), and it's still broken.
Angular 9 has also been released, so it's now the two latest versions that are affected. :(

We have a large Angular-based application, that we cannot update because of this issue. :(

**Comment by AlanJMac** [comment] 2020-02-12 16:44
> Just tried with the current latest version (1.52.2), and it's still broken.
> Angular 9 has also been released, so it's now the two latest versions that are affected. :(
> 
> We have a large Angular-based application, that we cannot update because of this issue. :(

First, I would recommend taking a look at [https://github.com/plotly/angular-plotly.js](angular-plotly.js) as that is apparently working with Angular 8.x+.

Otherwise, if it is an option for your project, I would recommend loading plotly.js via the CDN. 
I have upgraded to Angular 9 by lazy-loading the minified plotly.js this way and it is working very well. 
The main bundle is then also much smaller :-)
_(I'm no longer using the workaround I mentioned in my previous comment)_

**Comment by wendelstam** [comment] 2020-02-13 06:54
I managed to get it working in ng9 with ivy by including it as a regular script reference on the page and then `PlotlyModule.plotlyjs = (<any>window).Plotly;` with the PlotlyModule. I could not get PlotlyViaWindowModule, it compiled but got some invalid plotly version error.

**Comment by Scherlac** [comment] 2020-03-27 10:44
I managed to include the dist/plotly.js into some angular project. I found some issue around `d3_document = this.document` and some other places like ` var d3_mouse_bug44083 = this.navigator && /WebKit/.test(this.navigator.userAgent) ? -1 : 0;`

*On some places the `this` is `undefined` in case  we run the project with es2015 and `this` is `windows object` in case we run the project with es5.*

As far I see the line `d3_document = this.document` exist only in dist folder not in the src  

*Question*: Where is the correct place to edit this `d3_document = this.document` line in order to correct each distribution version (plotly.js, plotly.basic.js, plotly.min.js, etc)

**Comment by alexcjohnson** [comment] 2020-03-27 11:11
`d3_document` would be in the `d3` source, not the plotly.js source at all. Presumably this has been addressed in more recent `d3` versions? Could be another bit of motivation to upgrade https://github.com/plotly/plotly.js/issues/424 although unfortunately this is a substantial project

**Comment by jkunimune15** [comment] 2020-06-02 02:02
> @oldrich-svec can you please tell the exact location of the file which you mentioned in this questions last line? .I am facing the same issue.

In Plotly v1.54.1, I've found it to be line 34472. It's immediately after an if statement that seems to be talking about modules,
```javascript
  if (typeof define === "function" && define.amd) this.d3 = d3, define(d3); else if (typeof module === "object" && module.exports) module.exports = d3; else this.d3 = d3;
}.apply(self);
},{}],166:[function(_dereq_,module,exports){
```

**Comment by Rezakarimi66** [comment] 2020-06-03 08:29
Any real fix for this? 
[reproducable](https://jsfiddle.net/reza_karimi76/k0wvary8/17/)

**Comment by ImmanuelSamuel** [comment] 2020-06-28 09:19
After making the change I get self not defined

**Comment by fourgates** [comment] 2020-07-03 23:09
I had this working for Angular 9. I think `{ "compilerOptions": { "target": "es5" } }` had fixed it but its been a while since we added this. I just tried upgrading to Angular 10 and I am getting the following error:

```
TypeError: Cannot read property 'document' of undefined
    at plotly.js:24924
```
Which is:
```
var d3_document = this.document;
```

I am on `"angular-plotly.js": "^2.0.0",` and `"plotly.js": "^1.54.5"`.

**Comment by TrevorKarjanis** [comment] 2020-08-16 18:53
@fourgates I am using Plotly.js 1.54.5 with angular-plotly.js 2.0.0 in Angular 10 successfully. The property read issue only occurres when ```plotly.js/dist/plotly.js``` is imported into a shared module or a file imported into a shared module. I resolved the issue by ensuring the following two things:
1. The PlotlyModule is imported only in leaf modules. Shared modules require leaf modules to import the dependency if they use angular-plotly.js or plotly.js.
2. Import the PlotlyService and use [PlotlyService.getPlotly](https://github.com/plotly/angular-plotly.js/blob/master/FAQ.md#how-to-access-global-plotly-object-code) to access the global Plotly.js API. I only experience problems with shared files, but I use this practice everywhere.

**Comment by archmoj** [comment] 2020-08-31 00:51
@oldrich-svec have you tried the above solution?
Wondering should we keep this issue open?
If so could you please provide an update using latest plotly.js version?
Thanks.

**Comment by oldrich-svec** [comment] 2020-08-31 05:26
I have just tried to execute  v1.54.7 code as described in https://github.com/plotly/plotly.js/issues/3518#issuecomment-461310766 and yes it is still failing with

```
Uncaught TypeError: Cannot read property 'document' of undefined
    at plotly-latest.min.js:20
    at Object.164 (plotly-latest.min.js:20)
    at a (plotly-latest.min.js:7)
    at plotly-latest.min.js:7
    at Object.728.../constants/numerical (plotly-latest.min.js:61)
    at a (plotly-latest.min.js:7)
    at plotly-latest.min.js:7
    at Object.1.../src/lib (plotly-latest.min.js:7)
    at a (plotly-latest.min.js:7)
    at plotly-latest.min.js:7
```

I do not use Angular so I did not test the above solution.

If I am not mistaken, all the solutions are either

* to hack the plotly file as I did
* or to load plotly as normal script and not ES6 module

**Comment by xuke444** [comment] 2020-11-01 20:03
Looks like plotly needs to upgrade d3 to at least v4

**Comment by tony** [comment] 2021-01-02 21:33
Could anyone here get a working version of plotly.js on code sandbox?

All versions of those are failing as well. (for the sake of demos on this project and others)

**Comment by Eghizio** [comment] 2021-01-23 13:59
> (This isn't just an angular issue, all the codesandbox URLs on https://github.com/plotly/react-plotly.js are having this now)
> 
> Could anyone here get a working version of typescript + plotly.js on code sandbox?
> 
> All versions of those are failing as well. (for the sake of demos on this project and others)

@tony same issue here. Cannot use `react-plotly.js` on *Codesandbox* and *Stackblitz*, neither *JavaScript* or *TypeScript*.
It seems it is a `plotly.js` issue.

**Comment by davidhaley** [comment] 2021-01-27 16:58
OP's fix works for me. Should there be a PR for this?

**Comment by acmiyaguchi** [comment] 2021-02-03 08:43
I haven't been able to use the precompiled bundles in a Svelte+rollup application that I've been building, but I have been able to use the ES6 module e.g. `plotly.js/lib/core`. Here's a solution that works for me in `rollup.config.js`:

```js
import replace from "@rollup/plugin-replace";

export default {
    ....
    plugins([
      replace({
        "}()": "this.d3 = d3;\n}.apply(self);",
        delimiters: ["this.d3 = d3;\n", ";"],
      }),
    ...
    ])
}
```

I can't use `plotly.js-dist` because I get an issue about `process`.

<details>
<summary>error</summary>

```
Assigning to rvalue (15657:0) in node_modules\plotly.js-basic-dist\plotly-basic.js
15655: };
15656: process.title = 'browser';
15657: process.browser = true;
       ^
15658: process.env = {};
15659: process.argv = [];
```
</details>

**Comment by juliusbierk** [comment] 2021-02-16 10:02
Related: https://community.plotly.com/t/issue-in-electron-built-version/31303/5 (although this fix of marking as external does not work for me).

**Comment by juliusbierk** [comment] 2021-02-16 10:55
Solution for `vue-cli-service` (using https://www.npmjs.com/package/string-replace-webpack-plugin)

```
const StringReplacePlugin = require("string-replace-webpack-plugin");

module.exports = {
  chainWebpack: config => {
    config.module
      .rule('plotly')
      .test(/plotly\.js$/)
      .use('stringreplace')
        .loader(StringReplacePlugin.replace({
                replacements: [
                    {
                        pattern: /module.exports = d3; else this.d3 = d3;\n}\(\);/,
                        replacement: function() { return 'module.exports = d3; else this.d3 = d3;\n}.apply(self);' }
                    }
                ]}))
        .end()
  }
};
```

**Comment by tomsej** [comment] 2021-05-05 13:19
Seems it is not going to be fixed even in v.2.0.0 :(. So if anybody needs to fix this in minified version, look for:
```
"object"==typeof e&&e.exports?e.exports=t:this.d3=t}()
```
and replace it with:
```
"object"==typeof e&&e.exports?e.exports=t:this.d3=t}.apply(self)
```

**Comment by nicolaskruchten** [comment] 2021-05-05 14:06
In v2 we are no longer exporting d3 so we will have a path towards upgrading it to a version that doesn't suffer from this problem, but indeed, this current problem doesn't automatically go away in v2.

**Comment by VinodLouis** [comment] 2021-05-21 03:17
If anyone wants to implement the change in node_module and use a much more radical approach, leverage the [patch-package](https://www.npmjs.com/package/patch-package).

In package.json scripts, one can use it following command to patch the node_modules

`"postinstall": "./node_modules/.bin/patch-package"`


The patches for plotly 1.58.4
```diff
diff --git a/node_modules/plotly.js/dist/plotly-with-meta.js b/node_modules/plotly.js/dist/plotly-with-meta.js
index 1aaac5a..cb3ecfe 100644
--- a/node_modules/plotly.js/dist/plotly-with-meta.js
+++ b/node_modules/plotly.js/dist/plotly-with-meta.js
@@ -35864,7 +35864,7 @@ Object.defineProperty(exports, '__esModule', { value: true });
     return request.responseXML;
   });
   if (typeof define === "function" && define.amd) this.d3 = d3, define(d3); else if (typeof module === "object" && module.exports) module.exports = d3; else this.d3 = d3;
-}();
+}.apply(self);
 },{}],170:[function(_dereq_,module,exports){
 module.exports = function () {
     for (var i = 0; i < arguments.length; i++) {
diff --git a/node_modules/plotly.js/dist/plotly.js b/node_modules/plotly.js/dist/plotly.js
index 365230c..6268511 100644
--- a/node_modules/plotly.js/dist/plotly.js
+++ b/node_modules/plotly.js/dist/plotly.js
@@ -35864,7 +35864,7 @@ Object.defineProperty(exports, '__esModule', { value: true });
     return request.responseXML;
   });
   if (typeof define === "function" && define.amd) this.d3 = d3, define(d3); else if (typeof module === "object" && module.exports) module.exports = d3; else this.d3 = d3;
-}();
+}.apply(self);
 },{}],170:[function(_dereq_,module,exports){
 module.exports = function () {
     for (var i = 0; i < arguments.length; i++) {
```


The patches for d3 3.5.17
```diff
diff --git a/node_modules/d3/d3.js b/node_modules/d3/d3.js
index aded45c..d5b3cad 100644
--- a/node_modules/d3/d3.js
+++ b/node_modules/d3/d3.js
@@ -9551,4 +9551,4 @@
     return request.responseXML;
   });
   if (typeof define === "function" && define.amd) this.d3 = d3, define(d3); else if (typeof module === "object" && module.exports) module.exports = d3; else this.d3 = d3;
-}();
\ No newline at end of file
+}.apply(self);
```

**Closed** 2021-06-03 21:14 UTC
Labels: type: bug, ♥ NEEDS SPON$OR
