### ISSUE TITLE
Hovering on boxes/violins shows only median label under "opposite" hovermode

### ISSUE THREAD

**Issue by konieczny9lives** [plotly/plotly.js#2970] opened 2018-09-05 10:56 UTC
When box plot is the only trace, all statistics (_min,q1,median,q3,max_) are displayed on hover.
If you add another trace as a subplot, only _median_ is displayed on hover.

This only happens with **horizontal** box plot as far as I know.

Reproduction:
https://codepen.io/kotwgarnku/pen/gdxaPN

**Comment by alexcjohnson** [comment] 2018-09-05 13:12
Thanks @konieczny9lives! There's also a very strange interaction between the two plots in that codepen, that sometimes (for example, click "show closest data on hover" in the top modebar) the hover labels for the top plot show up at the positions they should have for the bottom plot !?!
![screen shot 2018-09-05 at 9 08 31 am](https://user-images.githubusercontent.com/2678795/45095283-b4af7180-b0eb-11e8-8ade-f7135dcced45.png)

**Comment by konieczny9lives** [comment] 2018-09-05 13:17
Great catch @alexcjohnson!

In regard to the original issue, I just found out that if you add `hovermode: "closest"` to layout options, all statistics (_min,q1,median,q3,max_) are displayed as intended.

**Comment by alexcjohnson** [comment] 2018-09-05 13:35
Well, *mostly* as intended... they're showing up horizontal (which requires them to be weirdly shifted vertically)
![screen shot 2018-09-05 at 9 32 53 am](https://user-images.githubusercontent.com/2678795/45096530-ba5a8680-b0ee-11e8-946a-2f7c1f52c1aa.png)


when they should be showing up tilted, which seems to me much more readable:
![screen shot 2018-09-05 at 9 31 38 am](https://user-images.githubusercontent.com/2678795/45096481-a44cc600-b0ee-11e8-97f4-88b1d8f9f6db.png)

**Comment by etpinard** [comment] 2018-09-05 14:17
Related: https://github.com/plotly/plotly.js/issues/2194

**Comment by stargazer33** [comment] 2018-09-07 04:49
It seems, this is the same problem as here:
https://community.plot.ly/t/boxplot-in-a-subplot-very-limited-information-in-hover/13109

```
It is a “subplot”; a histogram and a boxplot together, they share the X axis.
When I position the mouse cursor over boxplot I see ONLY the median values of both boxplots at the same time!
```

**Comment by etpinard** [comment] 2018-09-21 22:02
After some investigation, lines:

https://github.com/plotly/plotly.js/blob/2f0d56eaf71c4e979203d542a5e08233156ac68d/src/components/fx/hover.js#L580-L582

,

https://github.com/plotly/plotly.js/blob/2f0d56eaf71c4e979203d542a5e08233156ac68d/src/components/fx/hover.js#L657-L664

and 

https://github.com/plotly/plotly.js/blob/2f0d56eaf71c4e979203d542a5e08233156ac68d/src/components/fx/hover.js#L760-L765

shed some light on the problem. 

----

In the 2-trace (bad) graph in https://codepen.io/kotwgarnku/pen/gdxaPN: 

- hovermode is `'x'`, the default from

https://github.com/plotly/plotly.js/blob/2f0d56eaf71c4e979203d542a5e08233156ac68d/src/components/fx/layout_defaults.js#L31-L32

where `isHoriz` returns false unless all traces are _horizontal_ and in the codepen above, `trace1` is not horizontal.

- `searchData` has length 1, corresponding to one trace to 'search for' on the xy2 subplot (the trace being the box trace)

- so `rotateLabels` is false. I'd call this **wrong**.

- next stop, `showCommonLabel` is true and
- this result in the box `hoverData` (corresponding to the mean, q1, q3, ... labels) being filtered down to a single label.

---------

So, here's a few conclusions:

- We should fix the logic for `rotateLabels`, it should take into consideration cases where `searchData` has length 1 but `searchData[0].length > 1`. This should :white_check_mark: https://github.com/plotly/plotly.js/issues/2194 - easy.
- We should also make `rotateLabels` true when hovering under an "horizontal" trace under `hovemode: 'closest'`. This would fix the "mostly intended" hiccup described in @alexcjohnson 's https://github.com/plotly/plotly.js/issues/2970#issuecomment-418732786
- But this won't be enough to fully fix this https://codepen.io/kotwgarnku/pen/gdxaPN
  + `rotateLabels` will still be false (as `hovermode: 'x'` from that scatter trace)
  + `hoverData` will still get filtered down to a single label (as `showCommonLabel` is true)
- Unfortunately, I don't see an easy solution that doesn't lead to a breaking change, where we make 'closest' the hovermode default (see https://github.com/plotly/plotly.js/issues/778)

**Comment by etpinard** [comment] 2018-09-25 17:41
PR https://github.com/plotly/plotly.js/pull/3043 fixes the cases under `hovermode: 'closest'`, but does not help with:

- horizontal box/violin with `hovermode: 'x'`
- vertical box/violin with `hovermode: 'y'`

**Comment by alexcjohnson** [comment] 2018-09-25 21:00
The misalignment in the original multi-plot codepen https://codepen.io/kotwgarnku/pen/gdxaPN when you set the first plot to `closest` is still there (and yes, the codepen is now using 1.41.3). To be clear, I'm talking about how eg the "min" label is not pointing to the "min" value, but to where that value would be according to the bottom plot. There also seems to be a problem with the overlap avoidance algorithm when one of the labels is too long and gets flipped to the top - it's putting them out of order and then stretching them across each other.
![screen shot 2018-09-25 at 4 52 23 pm](https://user-images.githubusercontent.com/2678795/46042585-c0d39100-c0e3-11e8-94e2-17769f507abb.png)

**Comment by etpinard** [comment] 2018-09-25 21:02
> There also seems to be a problem with the overlap avoidance algorithm when one of the labels is too long and gets flipped to the top - it's putting them out of order and then stretching them across each other.

Ha I see. This probably deserves an issue of its own.

**Comment by etpinard** [comment] 2018-09-25 21:06
https://github.com/plotly/plotly.js/issues/2970#issuecomment-424499773 is now in -> https://github.com/plotly/plotly.js/issues/3050

**Comment by jackparmer** [comment] 2020-09-10 19:51
This issue has been tagged with `NEEDS SPON$OR`

A [community PR](https://github.com/plotly/plotly.js/pulls?q=is%3Apr+is%3Aopen+label%3A%22type%3A+community%22) for this feature would certainly be welcome, but our experience is deeper features like this are difficult to complete without the Plotly maintainers leading the effort.

**Sponsorship range: $5k-$10k**

What Sponsorship includes:
- Completion of this feature to the Sponsor's satisfaction, in a manner coherent with the rest of the Plotly.js library and API
- Tests for this feature
- Long-term support (continued support of this feature in the latest version of Plotly.js)
- Documentation at [plotly.com/javascript](https://plotly.com/javascript/)
- Possibility of integrating this feature with Plotly Graphing Libraries (Python, R, F#, Julia, MATLAB, etc)
- Possibility of integrating this feature with Dash
- Feature announcement on [community.plotly.com](https://community.plotly.com/tag/announcements) with shout out to Sponsor (or can remain anonymous)
- Gratification of advancing the world's most downloaded, interactive scientific graphing libraries (>50M downloads across supported languages)

Please include the link to this issue when [contacting us](https://plotly.com/get-pricing/) to discuss.

**Comment by gvwilson** [comment] 2024-06-11 17:21
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson

**Closed by gvwilson** 2024-06-11 17:21 UTC
Labels: type: bug, ♥ NEEDS SPON$OR
