### ISSUE TITLE
Can't find a way to disable hovertext automatic rotation

### ISSUE THREAD

**Issue by desertdev** [plotly/plotly.js#2170] opened 2017-11-17 23:18 UTC
I have a horizontal bar chart using hover text that is automatically being rotated about 45 degrees, which I don't want. I've been combing through the API full reference and existing issues (open and closed), but have not found any way to change this:

![image](https://user-images.githubusercontent.com/15255757/32972780-4d38ce86-cbb1-11e7-9c22-1749fa1a205a.png)

One detail in the data: there are 2 traces being charted, one in blue and one in grey. Initially all the data was in a single trace and I didn't have this problem. But both traces have identical options set for the hovertext:
```
            hoverinfo: 'y+text',
            hovertext: [],
            hoverlabel: {
                bordercolor: 'rgb(100, 100, 100)',
                bgcolor: 'rgb(240, 240, 240)',
                namelength: 0
            }
```
Am I just missing something or is it not possible to avoid this rotation? There seems to be plenty of room for the hovertext, and even if I reduce the text content to a very short string on a single line it still wants to do the rotation now that I split it into 2 traces.

**Comment by etpinard** [comment] 2017-11-20 14:46
You're right, we don't expose a way to set the hover label rotation at the moment.

I guess we could add something like:

```js
hoverlabel: {
  angle: 90 // or [10, 90, 45] one item per-pt
}
```

but that might not cover all the current label rotation [logic](https://github.com/plotly/plotly.js/blob/4c9458b2c421fcf84fc6032091a3c152c2ebae67/src/components/fx/hover.js#L813-L966).

**Comment by desertdev** [comment] 2017-11-20 20:14
Thank you for the response. My workaround was to use a single data trace and change colors as needed programmatically. This doesn't cause rotation, as apparently the function hoverAvoidOverlaps can see there is more room available in the total chart with a single data trace.

**Comment by adrianoesch** [comment] 2018-02-07 11:46
+1 for the angle parameter at the hoverlabels.

**Comment by eliasdabbas** [comment] 2018-04-12 20:37
+2

The solution that @desertdev proposes works. However, in the case I'm working on right now, I need to have several traces, because I want to map different colors to different categorical variables, and it's quite difficult to read at 45 and -45 degrees. 

Exposing the logic under `hoverlabel` would be great!
Thanks

**Comment by chubukov** [comment] 2018-11-05 02:58
+3

If you have a horizontal bar chart with grouped bars and multiline labels the rotation can make it look truly awful.

![image](https://user-images.githubusercontent.com/13080968/47975619-9084f800-e07c-11e8-8f7b-7ddb31b85192.png)

(This example works totally fine as a vertical bar chart)

**Comment by etpinard** [comment] 2018-11-05 17:44
@chubukov I think you might have discovered a bug, or possible another manifestation of https://github.com/plotly/plotly.js/issues/3050

Would you mind sharing a reproducible codepen to help us debug?

**Comment by chubukov** [comment] 2018-11-07 19:05
@etpinard Sure, I put an example here https://plot.ly/~victor.chubukov/18/

**Comment by alexcjohnson** [comment] 2018-11-07 19:50
This is an extreme example of what I posted in https://github.com/plotly/plotly.js/issues/3050#issuecomment-424508921 and I said:

> in this image, we could push min and q1 down so the rotated edge of their boxes align with the rotated edge of the median box perhaps?

That would fix the green label here, but I guess the fact that the orange label crosses the blue shows there's more needed - in principle all the labels except the farthest-right would need to be pushed down somewhat, though we should be careful not to push them down any more than we need do or they could easily drop off the bottom of the plot...

Simply disabling this rotation (which we do if you switch to `hovermode: 'closest'`) isn't a very complete solution though - there are lots of situations then in which one label would overlap either another label, the starting point of another label, or other data you're hovering on.

**Comment by chubukov** [comment] 2018-11-07 20:42
@alexcjohnson thanks for the tip -- `hovermode: 'closest'` is actually ok for my use case.

**Comment by jackparmer** [comment] 2020-09-10 19:51
This issue has been tagged with `NEEDS SPON$OR`

A [community PR](https://github.com/plotly/plotly.js/pulls?q=is%3Apr+is%3Aopen+label%3A%22type%3A+community%22) for this feature would certainly be welcome, but our experience is deeper features like this are difficult to complete without the Plotly maintainers leading the effort.

**Sponsorship range: $5k-$10k**

What Sponsorship includes:
- Completion of this feature to the Sponsor's satisfaction, in a manner coherent with the rest of the Plotly.js library and API
- Tests for this feature
- Long-term support (continued support of this feature in the latest version of Plotly.js)
- Documentation at [plotly.com/javascript](https://plotly.com/javascript/)
- Possibility of integrating this feature with Plotly Graphing Libraries (Python, R, F#, Julia, MATLAB, etc)
- Possibility of integrating this feature with Dash
- Feature announcement on [community.plotly.com](https://community.plotly.com/tag/announcements) with shout out to Sponsor (or can remain anonymous)
- Gratification of advancing the world's most downloaded, interactive scientific graphing libraries (>50M downloads across supported languages)

Please include the link to this issue when [contacting us](https://plotly.com/get-pricing/) to discuss.

**Comment by gvwilson** [comment] 2024-06-10 21:02
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson

**Closed by gvwilson** 2024-06-10 21:02 UTC
Labels: type: feature, ♥ NEEDS SPON$OR
