### ISSUE TITLE
Rangeslider strange behaviour and legend still working while staticPlot is true

### ISSUE THREAD

**Issue by COLLINETTEBastien** [plotly/plotly.js#5177] opened 2020-09-30 10:31 UTC
Hello,
I am using Plotly at work and I noticed that when the parameter 'staticPlot' is true, the plot events are disabled but the legend and the range slider are still usable. 
Moreover, the range slider has a strange behavior when 'staticPlot' is enabled: each click on the slider reset the selected range so we can't move it as expected.

Here's a working example to illustrate what I'm saying:
[https://codepen.io/collinettebastien/pen/bGpyvgw](https://codepen.io/collinettebastien/pen/bGpyvgw)

So is it possible to disable the events that concern the legend and the range slider without removing them or, at least, keep  the range slider working  the same as when the plot isn't static?

Thank you very much !

**Comment by alexcjohnson** [comment] 2020-09-30 15:52
Thanks @COLLINETTEBastien - this is definitely a bug, `staticPlot` should disable all interactions of any kind. Thanks for the clear codepen.

**Comment by josephernest** [comment] 2022-12-12 16:27
@archmoj @COLLINETTEBastien How did you solve the issue? It seems it is not solved as of december 2022:

In this example ([live demo here](https://jsfiddle.net/1Lymg5jq/)), the plot is static but the slider is still active:

```
<meta charset="utf8">
<script src="https://cdn.plot.ly/plotly-latest.js"></script>
<div id="myDiv"></div>
<script>
var steps = [];
for (var i = 0; i < 100; i++) 
    steps.push({label: i, method: "skip"});
Plotly.newPlot("myDiv", [{ "y": [1, 2, 3] }], {sliders: [{ len: 1, x: 0, steps: steps }]}, {staticPlot: true});
</script>
```

**Comment by josephernest** [comment] 2022-12-12 16:28
Can we reopen this @alexcjohnson?

**Comment by archmoj** [comment] 2022-12-12 16:58
> @archmoj @COLLINETTEBastien How did you solve the issue? It seems it is not solved as of december 2022:
> 
> In this example ([live demo here](https://jsfiddle.net/1Lymg5jq/)), the plot is static but the slider is still active:
> 
> ```
> <meta charset="utf8">
> <script src="https://cdn.plot.ly/plotly-latest.js"></script>
> <div id="myDiv"></div>
> <script>
> var steps = [];
> for (var i = 0; i < 100; i++) 
>     steps.push({label: i, method: "skip"});
> Plotly.newPlot("myDiv", [{ "y": [1, 2, 3] }], {sliders: [{ len: 1, x: 0, steps: steps }]}, {staticPlot: true});
> </script>
> ```

@josephernest Please note `plotly-latest` stayed at latest v1. 
To load the latest current v2 version try `https://cdn.plot.ly/plotly-2.16.4.min.js` instead.

**Comment by josephernest** [comment] 2022-12-12 21:44
Thanks @archmoj but the problem is still there with 2.16.4: 

https://jsfiddle.net/2mgzy38j/

The plot is static, but the slider is still active (it should not).

**Comment by archmoj** [comment] 2022-12-12 22:13
> Thanks @archmoj but the problem is still there with 2.16.4:
> 
> https://jsfiddle.net/2mgzy38j/
> 
> The plot is static, but the slider is still active (it should not).

Thanks for the demo.
You are right. I reopen the issue.

**Comment by archmoj** [comment] 2022-12-12 22:33
@josephernest I close this issue which was related to `rangeslider` not `slider`.
For `slider` I opened #6392.

**Closed by archmoj** 2022-12-12 22:33 UTC
Labels: type: bug
