### ISSUE TITLE
Plotly graphs not displayed on IE 11.

### ISSUE THREAD

**Issue by jasonrims** [plotly/plotly.js#4015] opened 2019-07-04 09:20 UTC
I am using plotly for creating reports in my company. Most of my stakeholders use IE11. In the past everything has been ok with the html files which i send to them having the charts created with my jupyter notebook using python.Recently i made some changes(added graph background color and legend background color) and all of a sudden these charts are not visible on IE anymore and can just be viewed on chrome. I have tried to update my plotly and ran into thesame results when trying to open the downloaded html file in IE.

**Comment by etpinard** [comment] 2019-07-04 13:44
Thanks for reporting!

Can you tell us which plotly.js trace types you're using? Better yet, can you send us the HTML files that you exported to help us debug?

Thanks for very much.

**Comment by jasonrims** [comment] 2019-07-04 14:14
Hi,
Thanks for your respond. All the traces dont work. I am using Scatter,Bar, and  Box.Sorry i cant send to you the html file because contains company data.
When i hover on the empty space i can view the plotly menu,but the chart is not available.

![Screenshot (26)](https://user-images.githubusercontent.com/39880580/60672836-b31f1900-9e76-11e9-8f3a-6280e599f1df.png)

**Comment by archmoj** [comment] 2019-07-04 14:18
@jasonrims Could you possibly try replacing the data with some other unreal data?

**Comment by jasonrims** [comment] 2019-07-04 14:39
Hi,

Here is a sample html file.
`import numpy as np
import pandas as pd
import plotly.offline as py
import plotly.graph_objs as go
from plotly.offline import download_plotlyjs,init_notebook_mode,plot,iplot
init_notebook_mode(connected=True)

x_values = np.linspace(0, 1, 100)
y_values = np.random.randn(100) 

trace0 = go.Scatter(
    x = x_values,
    y = y_values+5,
    mode = 'markers',
    name = 'markers'
)
trace1 = go.Scatter(
    x = x_values,
    y = y_values,
    mode = 'lines+markers',
    name = 'lines+markers'
)
trace2 = go.Scatter(
    x = x_values,
    y = y_values-5,
    mode = 'lines',
    name = 'lines'
)
data = [trace0, trace1, trace2] 
layout=go.Layout(title='Sample',
                yaxis=dict(title='Number'),
                xaxis=dict(title='Days'),
                legend=dict(x=-0.08,y=-0.25,bgcolor='#e3eaf7'),
                plot_bgcolor='#e3eaf7')
fig=go.Figure(data=data,layout=layout)
py.iplot(fig)`

The plot appears normal on chrome  as 
![Screenshot (28)](https://user-images.githubusercontent.com/39880580/60674331-32fab280-9e7a-11e9-813c-1cd0bcbf0477.png)

But on IE11.
![Screenshot (27)](https://user-images.githubusercontent.com/39880580/60674345-3e4dde00-9e7a-11e9-86d2-61919b835fc0.png)

**Comment by etpinard** [comment] 2019-07-04 15:30
@jasonrims are there any error messages in the IE11 browser console?

**Comment by etpinard** [comment] 2019-07-04 21:21
I tested a few plots through our test dashboard on browserstack, everything seems to work ok in IE11.

Maybe something is up with jupyter. @jasonrims can you try opening https://plot.ly/~etpinard/7329.embed in IE11?

**Comment by etpinard** [comment] 2019-07-04 21:22
Or maybe this report is a duplicate of https://github.com/plotly/plotly.js/issues/895 - where some IE11-version dependent bug was observed.

**Comment by jasonrims** [comment] 2019-07-05 07:33
> I tested a few plots through our test dashboard on browserstack, everything seems to work ok in IE11.
> 
> Maybe something is up with jupyter. @jasonrims can you try opening https://plot.ly/~etpinard/7329.embed in IE11?

@etpinard i am able to open the test dashboard you sent on IE11, but the HTML notebook created from jupyter notebook displays empty graphs.

**Comment by jasonrims** [comment] 2019-07-05 07:45
@etpinard i have been able to open other versions of my plots with IE11, but in the latest version where i have added, a color background for the graph, changed legend position and added legend color background, it doesnt render plots anymore on IE11.

**Comment by archmoj** [comment] 2019-07-05 12:56
> @etpinard i have been able to open other versions of my plots with IE11, but in the latest version where i have added, a color background for the graph, changed legend position and added legend color background, it doesnt render plots anymore on IE11.

@jasonrims what about changing only one of the three & testing them individually? That can help debugging which item may cause a problem.
Thanks.

**Comment by jasonrims** [comment] 2019-07-05 14:03
@etpinard I tried changing each individually but still no fix. Since my data increases and so do the bars on the plot, could a size problem cause this?

**Comment by archmoj** [comment] 2019-07-05 14:08
> I tried changing each individually but still no fix. Since my data increases and so do the bars on the plot, could a size problem cause this?

Just to double check: 
Q1: There is no bug when you don't touch any of the three?
Q2: But then changing any of the three it could trigger the problem?

**Comment by jasonrims** [comment] 2019-07-05 14:17
@archmoj 
1.When i change all the three updates, i still dont get any plot in IE11.
2.The changes does not make any difference.
3.The only difference only comes with increased data meaning more bars on the plots.

It works perfectly well on google chrome and other browsers

**Comment by etpinard** [comment] 2019-07-05 14:25
A few more questions:

- are there any error messages in the IE11 browser console?
- looks like you're using python, so by plotly _version_, you mean the plotly.py version, right? Which plotly.py version is that?

Thanks!

**Comment by archmoj** [comment] 2019-07-05 14:26
@jasonrims could you please test to see if this setup works?
data = [trace0, trace1, trace2]
layout=go.Layout(title='Sample',
yaxis=dict(title='Number'),
xaxis=dict(title='Days'),
legend=dict(x=-0.08,y=-0.25),
plot_bgcolor='#777')
fig=go.Figure(data=data,layout=layout)
py.iplot(fig)`

**Comment by jasonrims** [comment] 2019-07-05 14:33
@archmoj 
![Screenshot (31)](https://user-images.githubusercontent.com/39880580/60729300-a7008d80-9f42-11e9-9d91-e7ac6d1370bc.png)

**Comment by jasonrims** [comment] 2019-07-05 14:35
@etpinard 
yes i am using python. Showed you my code.
it is a plotly.py

**Comment by etpinard** [comment] 2019-07-05 14:38
> Showed you my code.
> it is a plotly.py

Yes, but which _version_?

**Comment by jasonrims** [comment] 2019-07-05 14:44
@etpinard 
![Capture](https://user-images.githubusercontent.com/39880580/60729897-1aef6580-9f44-11e9-959b-71fd20bce24a.JPG)

**Comment by etpinard** [comment] 2019-07-29 15:12
This looks more and more like a plotly.py problem, so this issue will now be tracked in https://github.com/plotly/plotly.py/issues/1693

related: https://community.plot.ly/t/plotly-charts-not-displaying-in-ie/26506/2

**Closed by etpinard** 2019-07-29 15:12 UTC
