### ISSUE TITLE
plotly.js dendrogram

### ISSUE THREAD

**Issue by PPPW** [plotly/plotly.js#1733] opened 2017-05-25 21:40 UTC
Dear plotly.js, 
I saw Plotly python supports dendrograms:
https://plot.ly/python/dendrogram/

However I didn't find this feature in Plotly.js, which I prefer to use. I wonder is there any chance this feature will be added in the future? Thank you!

**Comment by etpinard** [comment] 2017-05-26 15:26
duplicate of https://github.com/plotly/plotly.js/issues/1321

**Closed by etpinard** 2017-05-26 15:26 UTC
