### ISSUE TITLE
Wrong date labels on xaxis 

### ISSUE THREAD

**Issue by germayneng** [plotly/plotly.js#3407] opened 2019-01-07 04:30 UTC
![image](https://user-images.githubusercontent.com/22788747/50749175-2b19d700-1278-11e9-84b4-182ae68e472c.png)

Refering to:  https://github.com/plotly/plotly.js/issues/482 

But apparantly i am still getting this bug. The date are 

![image](https://user-images.githubusercontent.com/22788747/50749134-f279fd80-1277-11e9-9296-829ae9b98620.png)

However, when plotting, it seems to label the data at november to be oct. Using python version of plotly and currently at  3.4.2

**Comment by germayneng** [comment] 2019-01-07 04:35
Ok it seems that i added: 

```python
layout = go.Layout(
    xaxis = dict(tickformat = '%Y/%m', dtick = 'M1') 

                           ) 
```


and it works

**Comment by etpinard** [comment] 2019-01-07 14:59
Thanks for reporting. Could someone try to reproduce this in JS in a codepen/jsfiddle/jsbin? That would help us out a lot.

**Comment by etpinard** [comment] 2019-02-19 19:32
Closing due to lack of reproducible example. 

Feel free to reopen another issue if the problem persists.

**Closed by etpinard** 2019-02-19 19:32 UTC
