### ISSUE TITLE
Disable spikes for individual traces

### ISSUE THREAD

**Issue by paulhager** [plotly/plotly.js#3905] opened 2019-05-24 08:03 UTC
When having multiple traces in one graph (such as a scatter 3D and a mesh 3D), it doesn't seem to be possible to disable spikes for just one of the traces. All spike options are relegated to 'layout' and thus are graph wide. The problem I'm having is that I am using a mesh 3D as a type of representative hull with scatter 3D points inside. When I try to then hover over the scatter 3D points, the hover info of the points are almost never shown because spikes are always drawn to the 3D mesh which in the 3D space occurs before the scatter points. If I could disable the spikes for just the mesh 3D so that it only tries to show hover info for the scatter points, that would be fantastic. Disabling the mesh hoverinfo (or setting it to 'skip') has no effect on which points are "selected" for showing hoverinfo. Is there a setting I'm missing or are there any plans to include a feature like this in the future?

**Comment by LTribelhorn** [comment] 2020-10-17 10:03
@paulhager Did you find a workaround for this in the meantime?
Or has there been any progess on this feature?

**Comment by paulhager** [comment] 2020-10-19 08:36
I ended up  completely disabling hovering for 3D mesh. 

Code change made is in plotly.js, v1.43.0, insert a new line 42559:

if(obj.constructor.name === 'SimplicialMesh')
{continue}

**Comment by LTribelhorn** [comment] 2020-10-19 09:04
I found a workaround yesterday:
By duplicating the axes (without ticklabels & title, overlaying the real axes) and assigning these axes to one group of traces (eg. the 3D mesh) the spikelines can then be disabled as usual in the axis attributes.

But although this works in my case there could obviously be drawbacks in other cases. So having this as a feature would still be appreciated

**Comment by fMeow** [comment] 2021-06-19 07:21
This issue still exist at plotly.js v2.1.0. I am plotting a 3d scatter plot incapsulated by a 3d mesh as background. And the hover just fail to go through the mesh.

@paulhager Could you please give a little bit of details? The line 42559 in  plotly v1.43.0 ([https://cdn.plot.ly/plotly-1.43.0.js](https://cdn.plot.ly/plotly-1.43.0.js)), is a little wierd:

```javascript
proto.isTransparent = function() {
  if(this.opacity < MAX_OPACITY)  {
    return true
  }
  for(var i=0; i<3; ++i) {
    if(this.axesProject[i] && this.projectOpacity[i] < MAX_OPACITY) {
      return true
    }
  return false
 // the next line is line 42559 
}
```
Though I didn't try it, I think this edit literally did nothing since the function will already returned at this line.

@LTribelhorn Could you please explained a little bit of details? By duplicating axes, do you mean [3d scene](https://plotly.com/javascript/reference/layout/scene/) in layout?

**Comment by LTribelhorn** [comment] 2021-06-21 05:17
I don't remember where I used this so I can't provide my code right now. 
What I do remember however, is that my use case was a 2D plot in R so my solution might be unsuitable for JS and 3D plots.

**Comment by paulhager** [comment] 2021-06-21 21:35
I don't have access to the code anymore where I made the edit, sorry. To solve it I mainly investigated via chrome developer tools and setting break points until I found the loop where the spike drawing occurs. Then I set a skip for when I'm drawing spikes for SimplicialMesh (which was the trace I wanted to leave out of spike drawing). Hope that helps at least a bit.

**Comment by fMeow** [comment] 2021-06-23 09:00
Thank you! I will have a try and update my solution here for someone with the same issue.

**Comment by gvwilson** [comment] 2024-06-14 12:00
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-14 12:00 UTC
Labels: type: feature
