### ISSUE TITLE
Sampling (with LTTB or other algorithm) for performance on large data sets

### ISSUE THREAD

**Issue by djk447** [plotly/plotly.js#560] opened 2016-05-24 04:41 UTC
Hi guys- 

Really a feature request here (and I might be able to help with implementation)- I'm looking to be able to use some sort of sampling method on large datasets in plotly, similar to the sampling methods suggested here: http://hdl.handle.net/1946/15343 and implemented for flot here: https://github.com/sveinn-steinarsson/flot-downsample and in other places for other libraries. Ideally, I could load all of my data into plotly in x, y pairs and specify a max number of points to display, plotly would figure out which points to plot using the algorithm of my choice and the number of points (specified in the trace specification) then when I zoomed further in, it would first perform its normal zoom then it would resample for the new x coordinates and then redraw (or ideally not not sure exactly how it should work). Some caching of initial points etc might be in order as well. 

Anyway, wondering if anyone else is looking for something like this, or if there are plans to implement, would love to work with someone on it.

**Comment by etpinard** [comment] 2016-05-25 16:36
Thanks for suggestion!

Some sort of range-depending drawing options would be a great addition to plotly.js.

Implementing them in a robust way won't be easy and won't be a priority of ours for at least the next six months. 

That said, sampling algorithms would be a great use case for soon-to-be-released trace transforms (see PR https://github.com/plotly/plotly.js/pull/499 for more info).

**Comment by nothinkelse** [comment] 2016-06-07 13:49
Hi, this is also interesting to me. But here the problem is that downsampling has to be done on server. If I have time-series with timespan over a year and it has over 3*10^7 points (one point for every second in the year) then I can not send all the data to the javascript plot. 

Competition library Bokeh allows this, you just need to hook a callback function to zoom-range-change event and change replace the points in the python plot model with appropriate resolution, then the changes in the backend are automatically transferred to javascript plot via websocket. 

However I stopped using Bokeh, I find it difficult to use as a component in multi-component web application. Although, I have learned that this is not such a simple task. Various users might be interested in various methods of downsampling the data. 

I am looking into plot.ly now. As a solution I am thinking of using the javascript zoom-event function to request data from my server with a appropriate resolution. My server would provide such data via HTTP api. Would it be possible to update the plot.ly plot with the new data?

**Comment by lnunno** [comment] 2017-09-27 19:05
@marcelnem Have you found a good solution for plotting a large number of points? I'm looking into plotting a similar sized dataset using either Bokeh or perhaps Plotly. I might have to resort to downsampling also.

**Comment by cms26** [comment] 2017-09-27 22:02
I'm not sure if you would find this helpful but we were also in the same situation.  We ended up using Largest-Triangle-Three-Buckets algorithm (LTTB). Initially we tried using a a very simple downsampling algorithm (take the max of every n data points) but we found that LTTB retained a better "shape" of plot data. We have a Go server that does the downsampling and then pushes the data to our java script application (with Plotly JS).

This is an example of the algorithm in javascript. We modified it slightly and converted it to Go. There is a link on the page to the paper of the guy who originally wrote the algorithm too.

[https://github.com/sveinn-steinarsson/flot-downsample](https://github.com/sveinn-steinarsson/flot-downsample)

I hope someone finds this helpful.

**Comment by matanster** [comment] 2018-09-21 10:27
Interestingly, matplotlib handles the same large data without any trouble, in my case at least.

**Comment by Hadatko** [comment] 2019-06-25 06:41
Still would be nice to have.

**Comment by jonasvdd** [comment] 2022-04-04 11:32
Hi, if you mainly use the python-bindings of Plotly, this repository: can help! 
https://github.com/predict-idlab/plotly-resampler (it uses the LTTB downsampling algorithm by default)

**Comment by matanster** [comment] 2022-04-05 10:24
Is it useful also when dash (AFAIK an optional paid component is not being used?

**Comment by jonasvdd** [comment] 2022-04-05 12:10
Hey @matanster,

The dash dependence is free 😃 (we do not use any paid components of dash), but as the  front-end to back-end interaction is realized via Dash component callbacks, there is a dependency on it. I suggest you look at our [repo-examples](https://github.com/predict-idlab/plotly-resampler/tree/main/examples) and [docs](https://predict-idlab.github.io/plotly-resampler/) to see whether it meets your requirement.

if not so, you can always create an issue on our repo!

**Comment by matanster** [comment] 2022-04-06 12:55
Thanks, I'll be looking at using dash to support this (paid or not) next time I have that scenario!

**Comment by gvwilson** [comment] 2024-06-05 16:52
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson

**Closed by gvwilson** 2024-06-05 16:52 UTC
Labels: type: feature, status: discussion needed
