### ISSUE TITLE
Horizontal box hover labels out of order

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.js#3389] opened 2019-01-03 17:42 UTC
This is pretty rough... median to the left of min and max to the left of upper:

![image](https://user-images.githubusercontent.com/203523/50652585-eda20a80-0f54-11e9-99a8-7357f534f095.png)

Can we enforce an order here?

**Comment by nicolaskruchten** [comment] 2019-01-03 17:43
only happens in `closest` hovermode... Why is `closest` so different for boxes?

**Comment by nicolaskruchten** [comment] 2019-01-03 18:03
Seems related to but distinct from https://github.com/plotly/plotly.js/issues/3050 ... the hovers are pointing to the correct place, they're just 'snagged' on each other :)

**Comment by nicolaskruchten** [comment] 2019-01-03 18:06
Theory: they're getting laid out per the order here: https://github.com/plotly/plotly.js/blob/fc4511cecd225bc068926566f60a181193c8233c/src/traces/box/hover.js#L147-L155

**Comment by etpinard** [comment] 2019-01-03 23:16
Again here, the graph's "data" / "layout" would be nice.

**Comment by nicolaskruchten** [comment] 2019-01-04 01:03
as it happens, violins do this also: https://plot.ly/~nicolaskruchten/252

**Comment by nicolaskruchten** [comment] 2019-01-04 01:04
Here's the box version: https://plot.ly/~nicolaskruchten/254

**Comment by etpinard** [comment] 2019-01-04 14:54
Yeah, this one is a duplicate of https://github.com/plotly/plotly.js/issues/3050

**Closed by etpinard** 2019-01-04 14:54 UTC
Labels: type: bug

**Comment by nicolaskruchten** [comment] 2019-01-04 15:14
Well, I tried my reordering fix and it addresses my issue. Not sure how easily I can test #3050

**Comment by nicolaskruchten** [comment] 2019-01-04 15:17
OK, pretty easily, and it's a fix :)
