### ISSUE TITLE
Add legend 'auto' x|y and/or 'container' (x|y)ref

### ISSUE THREAD

**Issue by salim-b** [plotly/plotly.js#1199] opened 2016-11-25 17:42 UTC
The problem is that the horizontal legend overlaps the x-axis title. It occurs if the legend is positioned below (rather than to the right of) the plot area using `layout = {legend: {"orientation": "h"}};`. It aggravates in combination with multiline x-axis titles (using `<br>` tags).

Currently there's no way to control the spacing between the legend and the plotting area. Everything is auto-scaled, it is useless to set the bottom margin (`layout = {margin: {"b": ...}};`) in this case because it refers to the space _below_ the legend. The only way to make the whole x-axis title visible is to increase the height of the whole plot until the autoscaling sufficiently spreads the legend and the plotting area apart.

I try to illustrate the problem with the following 3 images which differ only in frame height:

_height 700px:_
![example_height700](https://cloud.githubusercontent.com/assets/20040931/20580578/6831cab0-b1d3-11e6-8162-c67bd0c11cf3.png)

_height 1000px:_
![example_height1000](https://cloud.githubusercontent.com/assets/20040931/20580582/6cd3f91c-b1d3-11e6-904f-edb748be01f7.png)

_height 1300px:_
![example_height1300](https://cloud.githubusercontent.com/assets/20040931/20580585/71203f4e-b1d3-11e6-81ad-6f0b3e8b0b3c.png)

[Here](https://plot.ly/~slim-b/225) is the above plot hosted on plot.ly.

**Comment by n-riesco** [comment] 2016-11-25 18:31
This is happening because `layout.margin.b` is set to 0 and the default position for horizontal legends is:
```js
x: 0,
xanchor: 'left',
y: 1.1,
yanchor: 'bottom'
```

@etpinard Would it make sense to make the defaults smarter and check the value of `layout.margin.b`?

**Comment by salim-b** [comment] 2016-11-25 23:25
>... and check the value of `layout.margin.b`?

I don't think `layout.margin.b` is central to this. If you play around a little with different combinations of `layout.margin.b` and `layout.legend.yanchor`, you quickly see that in the plot above you'll get nowhere desirable... actually the default of `layout.legend.yanchor`, which seems to be `top` not `bottom` (at least when I'm plotting in `R`), leads to the best results.

The problem in my eyes is that – when `layout.legend.orientation` is horizontal and the rest of the legend positioning parameters left to its default values – the legend overlaps the plotting area in the first place. In the default case the legend should always be placed below the x-axis, then it would be fine.

**Comment by etpinard** [comment] 2016-11-28 15:05
Probably a duplicate of https://github.com/plotly/plotly.js/issues/1190

**Comment by herrgruebner** [comment] 2017-01-24 19:59
I was having a similar issue with the horizontal legend overlapping x axis values, when the x axis values were long enough, like dates. I'm adding this here because it's the only issue that comes up when you google it, and it seems related. This happens with only setting {legend: 'horizontal'} in the layout and nothing else.

![legend override](https://cloud.githubusercontent.com/assets/15949350/22263429/4e74237a-e2d9-11e6-8dd3-fe35511bace8.png)

I tried a couple of different things, like playing with layout.legend.yanchor and the margins, but the legend doesn't appear to be affected by margins, it stays in the same place relative to the dates, and yanchor shifts it a little bit but it remains on top of the x axis ticks.

In the end my solution was to absolutely position the legend using 
legend: {
                "orientation": "h",
                xanchor: "center",
                y: 1.2,
                x: 0.5
            },

This has the side effect of putting the legend on top of the graph, but you can position it below the graph by lowering the Y value. It appears that the default X and Y values according to the docs (1, 1.2) are changed to a different value when the legend is set to horizontal, which makes sense, but should also be reflected in the documentation here:

https://plot.ly/javascript/reference/#layout-legend

I chose to put it above the graph because I know my x axis values are going to change in length and the graph is being iframed into a small spot, so I don't want to waste space. Not super pretty or anything, but a reasonable workaround.


![legend override 2](https://cloud.githubusercontent.com/assets/15949350/22264353/7dc331a4-e2dc-11e6-9dbb-90e0016f416e.png)


Hopefully the horizontal legends are changed so that it will take into account x axis tick length automatically, or there's another easy way to do it I haven't found.

**Comment by ck37** [comment] 2017-03-02 20:29
I am running into this issue also.

**Comment by jinuem** [comment] 2017-03-06 07:23
Same Issue :(

**Comment by hy9be** [comment] 2017-03-06 18:20
+1

**Comment by suribabu39** [comment] 2017-04-11 10:52
+1

**Comment by anafziger** [comment] 2017-04-17 13:26
+1

**Comment by kiezuz** [comment] 2017-04-19 08:01
+1

**Comment by FrantisekGazo** [comment] 2017-05-01 06:49
+1

**Comment by yunxileo** [comment] 2017-05-03 08:44
+1

**Comment by allanelder** [comment] 2017-05-22 20:05
+1

**Comment by tabuechn** [comment] 2017-06-16 13:10
+1

**Comment by rozjan** [comment] 2017-07-18 19:29
Did they fix this issue? Does Plotly takes care of it without us having to hack around? If so how can we position the legend at bottom of chart without overlapping with x-axis?

**Comment by salim-b** [comment] 2017-07-19 10:09
> Did they fix this issue?

Nope, I don't think so. At least when I'm plotting in R (newest CRAN version [based on `plotly.js 1.27.1`](https://github.com/ropensci/plotly/blob/master/NEWS.md#470)) the issue is still the same. Also I don't think it has been fixed in newest `plotly.js 1.28.3` since I can't find anything related in the [changelogs](https://github.com/plotly/plotly.js/releases).

**Comment by nzjrs** [comment] 2017-08-08 08:38
+1

**Comment by IFFranciscoME** [comment] 2017-08-26 15:47
Just to report, plotly version 4.7.1, using R 3.4.1 and embedding the graph in a RNoteBook,  as today, still same problem. Looking for a workaround now. Some of the examples above seem useful, will try.

**Comment by nzjrs** [comment] 2017-08-26 16:38
None of the work arounds worked for me, it would be helpful if you report
success here if you have any

**Comment by vladimirlukyanov** [comment] 2017-10-12 11:52
+1

**Comment by MichalSzura** [comment] 2017-10-16 08:16
+1

**Comment by salim-b** [comment] 2017-10-16 09:23
> +1

Although I appreciate the great demand for a fix of this issue, I doubt that all the "+1" comments (and the thereby triggered e-mail notifications) will eventually help to motivate the plotly developers to finally implement a solution for the problem. So just use [GitHub reactions](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments) to express your support, please 😉

**Comment by jiteshkharat53** [comment] 2017-11-03 14:38
Any updates regarding above issue?

**Comment by alexcjohnson** [comment] 2018-01-15 22:36
Digging into this a little in relation to #2243 - the background:
- Legends are positioned in paper-referenced coordinates - those are the coordinates where the bottom left of the plotting area (excluding the margins in which we draw axis labels etc) is (0,0)
- The default position is `x=0, y=-0.1, xanchor='left', yanchor='top'` - so the left edge aligned with the left edge of the plotting area, and the top in the margin, one tenth of the y axis length below the plotting area, on the theory that axis labels typically fit within that gap - but of course that's not always true!
- So if you know the size of the plot AND the area needed for axis labels and title, you can choose `legend.y` such that there will be no overlap.
- But if you need this to work with dynamic plot size or axis label length, the auto-margin mechanism we have (which is used right now to increase the margin in order to keep the legend from extending outside the visible area and will soon be used to ensure long axis labels are always visible, see #2243), CANNOT be used as is to keep the legend from overlapping axis labels.

I see two possible ways to go here. The first is less of an addition to what we currently have, but the second I think would be more powerful and probably easier to implement too:
1. Have the auto-margin system automatically change `legend.y`. When `legend.y` is not explicitly set, it would have to have an `'auto'` value or something, then the auto-margin system would have to figure out how to combine space needed for the axis labels with space needed for the legend. But this is still problematic: what if you want it at the top and you have a top x axis whose labels it needs to avoid? Would we need `'auto-top'` and `'auto-bottom'`? That sounds awkward, and there may be other possibilities I'm not thinking of.
2. Alternatively, allow the legend to be positioned in other coordinates - I'm thinking of the `'container'` coordinates as proposed in #882 for chart titles, in which (0,0) is the absolute bottom left corner *including* margins. Then we could default a horizontal legend to `x=0, xanchor='left', xref='paper'` (that wouldn't change) and `y=0, yanchor='bottom', yref='container'` (that part is new, though the result would be about the same as what we have now. In addition we could add `pad` attributes as also suggested in #882, which would add a pixel buffer between the legend and the edge of the div, and between the legend and the plot or axis labels) - and at that point, the auto-margin system could simply reserve space for anything container-referenced (including the title 🎉 ) before fitting the other things in.

**Comment by yniknafs** [comment] 2018-04-20 13:11
@nicolaskruchten @etpinard 

Any chance this is being worked on? Would be pretty clutch for my project.

**Comment by etpinard** [comment] 2018-04-20 13:13
@yankev -> https://plot.ly/products/consulting-and-oem/

**Comment by gonzofish** [comment] 2019-07-01 14:16
Was there any work being done on this or perhaps another issue that led to a fix?

**Comment by etpinard** [comment] 2019-10-09 13:11
Another example from https://github.com/plotly/plotly.js/issues/4261

---

When there are a large number of traces in a horizontal legend, they begin to overlap to x-axis label as the legend grows in size. It would be great if the horizontal legend added a scrollbar if there are >3-4 rows of legend items, or if this could be configurable.

This seems somewhat related to this issue: https://github.com/plotly/plotly.js/issues/960

![image](https://user-images.githubusercontent.com/25089669/66416948-9853c780-e9c4-11e9-815f-21dfd0bed11e.png)

**Comment by cameronwaterman** [comment] 2019-10-09 14:27
Any word on a fix for this?

**Comment by nicolaskruchten** [comment] 2019-10-09 16:40
We are chipping away at various pieces of this problem and related problems... no commitment on timelines at this time :)

**Comment by nicolaskruchten** [comment] 2019-11-01 13:53
My feeling is that with `*axis.automargin = true`, the margin pushing code should take into account the legend in cases when it's in horizontal mode below the plot, leaving room for legend *plus* the axis/tick labelling, rather than taking the *max* as we currently do, thereby allowing them to overlap. I think we should resolve #4222 the same way. This would allow us to not add extra attributes or auto-layout modes.

**Comment by nicolaskruchten** [comment] 2019-11-01 13:54
Maybe we could do this only in cases where the legend positioning is outside of [0-1] or something, so that people could still place legends within the plotting area on purpose?

**Comment by etpinard** [comment] 2019-11-20 18:02
> the margin pushing code should take into account the legend in cases when it's in horizontal mode below the plot, leaving room for legend _plus_ the axis/tick labelling,

Leaving room for both the tick labels and the legend in the margin wouldn't be too hard, but the hard part here (which we might need a new attribute for) is to reposition the legend below the ticks. The new legend position will depend on the tick label dimensions and thus we would have to introduce some new cross-component logic.

**Comment by nicolaskruchten** [comment] 2019-11-20 18:57
> The new legend position will depend on the tick label dimensions

Is the mechanism here because longer labels means pushing the margins up means in effect moving the (0,0) coordinate that the paper/domain coordinate space works within>

**Comment by nicolaskruchten** [comment] 2019-11-21 02:08
I think I'm understanding the problem and suggested solutions better now... the `container` ref idea sounds like a pretty good one as a low-level control system. We may want to layer on top of that a "placement" enum that would be the 4 corners and 4 faces of the rectangle, which would automatically set anchors and refs to container etc so that `orientation="h"` with `placement="bottom center"` would do the right thing and play well with automargins?

**Comment by etpinard** [comment] 2020-01-06 17:00
Moved to `1.53.0`

**Comment by gonzofish** [comment] 2020-04-15 01:07
Is there any update on this? I have some legends with a lot of text, the text is dynamic, so I can't do much about hose long the text is. When the chart generates, the legend overlaps the x-axis legend considerably.

Is there anything the community can do to help?

**Comment by nicolaskruchten** [comment] 2020-04-15 13:43
If someone wants to take on some implementation work, we'd be happy to iterate on a design and review some PRs, but at the moment this is no longer on our short-term roadmap.

If you work for an organization with a software budget, you could [sponsor this feature](https://plotly.com/consulting-and-oem/) to bump it up our priority list.

**Comment by gonzofish** [comment] 2020-04-15 16:22
1. I didn't know sponsoring a feature could be a thing
2. I'll try to take a look to help out

**Comment by nicolaskruchten** [comment] 2020-04-15 16:24
Great! :)

**Comment by jackparmer** [comment] 2020-09-10 18:47
This issue has been tagged with `NEEDS SPON$OR`

A [community PR](https://github.com/plotly/plotly.js/pulls?q=is%3Apr+is%3Aopen+label%3A%22type%3A+community%22) for this feature would certainly be welcome, but our experience is deeper features like this are difficult to complete without the Plotly maintainers leading the effort.

**Sponsorship range: $10k-$15k**

What Sponsorship includes:
- Completion of this feature to the Sponsor's satisfaction, in a manner coherent with the rest of the Plotly.js library and API
- Tests for this feature
- Long-term support (continued support of this feature in the latest version of Plotly.js)
- Documentation at [plotly.com/javascript](https://plotly.com/javascript/)
- Possibility of integrating this feature with Plotly Graphing Libraries (Python, R, F#, Julia, MATLAB, etc)
- Possibility of integrating this feature with Dash
- Feature announcement on [community.plotly.com](https://community.plotly.com/tag/announcements) with shout out to Sponsor (or can remain anonymous)
- Gratification of advancing the world's most downloaded, interactive scientific graphing libraries (>50M downloads across supported languages)

Please include the link to this issue when [contacting us](https://plotly.com/get-pricing/) to discuss.

**Comment by soadergi** [comment] 2021-11-17 17:37
Setting layout.legend.y = "auto" and layout.legend.yanchor = "top" helped me to avoid legend overlapping in plot

**Comment by ScottWilliamAnderson** [comment] 2023-06-28 15:11
these layout settings allowed me to avoid this issue occurring entirely:
'yref': container
'yanchor': bottom
'xanchor': center
'x': 0.5
'orientation': 'h'

**Comment by salim-b** [comment] 2023-06-28 18:22
>  Does that mean we could close this issue?

Obviously I can't speak for the people you mentioned, but [my original issue](https://github.com/plotly/plotly.js/issues/1199#issue-191746824) has indeed been fixed since I've last checked (2017). Tested with plotly.js v2.11.1 (included in the plotly R package 4.10.2). 🙂

**Closed** 2023-06-28 18:30 UTC
Labels: type: bug, type: feature, ♥ NEEDS SPON$OR

**Comment by SimonCoulombe** [comment] 2024-06-19 15:13
> > Does that mean we could close this issue?
> 
> Obviously I can't speak for the people you mentioned, but [my original issue](https://github.com/plotly/plotly.js/issues/1199#issue-191746824) has indeed been fixed since I've last checked (2017). Tested with plotly.js v2.11.1 (included in the plotly R package 4.10.2). 🙂

I still have this issues,  what settings worked for you? thanks

**Comment by salim-b** [comment] 2024-06-19 21:08
> I still have this issue, what settings worked for you?

The [code](https://chart-studio.plotly.com/~slim-b/225/korrelation-zwischen-inhaltsanalyse-und-qualitatswahrnehmung-der-bevolkerung/#code) for the plot in the first code auto-scales perfectly with recent versions of plotly.js:

[Bildschirmaufzeichnung vom 19.06.2024, 23:03:30.webm](https://github.com/plotly/plotly.js/assets/20040931/0c2a8444-6bb7-40d9-a958-bed839ce4af2)
