### ISSUE TITLE
[request] add script to find missing translations in a locale

### ISSUE THREAD

**Issue by n-riesco** [plotly/plotly.js#2269] opened 2018-01-19 19:14 UTC
What I have in mind is:
- build a list of strings to translate by running `grep` under `src`to find occurrances of  `_(gd, 'a string to translate')`
- load a locale, e.g. `lib/locales/es.js`, and find any missing strings in `exports.dictionary`.

**Comment by alexcjohnson** [comment] 2020-03-03 15:01
As shown in #4612 we also have some *incorrect* keys - that's something we can include a CI test for, since we'll generally either be able to figure out the right key or we can just delete it. Missing keys though we won't generally be able to fix without a native speaker to help, so that's probably not a good idea to run on CI.

**Comment by gvwilson** [comment] 2024-06-11 16:55
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson

**Closed by gvwilson** 2024-06-11 16:55 UTC
Labels: type: translation
