### ISSUE TITLE
More gl3d label rotation options

### ISSUE THREAD

**Issue by archmoj** [plotly/plotly.js#3999] opened 2019-06-30 23:05 UTC
Thanks to https://github.com/plotly/plotly.js/pull/3084, the `gl-axes3d` vertex shader code supports a number of options for rotating the labels on 3d axes.
https://github.com/gl-vis/gl-axes3d/blob/a7a99d8047183657a4a288dc1c9e7341103b81d9/lib/shaders/textVert.glsl#L79-L87
However; only some of these functionalities are accessible to the Plotly users.

It could potentially be useful to expose other options through the API for example in case one need to have all the ticks on a 3d-axis displayed in only one direction (not flipped individually).

Example provided by @alexcjohnson
![label flip](https://user-images.githubusercontent.com/33888540/60403248-beb5cb80-9b68-11e9-999a-12debacc9ea6.gif)

**Comment by gvwilson** [comment] 2024-06-14 12:47
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-14 12:47 UTC
Labels: type: feature
