### ISSUE TITLE
Grouped bar chart not working with multiple axis

### ISSUE THREAD

**Issue by suribabu39** [plotly/plotly.js#1692] opened 2017-05-17 07:14 UTC
Hi, 
I am unable to to plot grouped chart with multiple y-axis. It is plotting bars over bars(rather than side by side). I don't think its plotting stacked bar chart either. Its working properly for line chart with multiple axis.
Am I missing something ? Should I give some more parameters?
Codepen link: https://codepen.io/suribabu_95/pen/oWMRmE?editors=0010

Thank you,

**Comment by etpinard** [comment] 2017-05-17 13:20
duplicate of https://github.com/plotly/plotly.js/issues/78

**Closed by etpinard** 2017-05-17 13:20 UTC
