### ISSUE TITLE
Bug: saving plot as png; sizing and position

### ISSUE THREAD

**Issue by mannisobrien** [plotly/plotly.js#2619] opened 2018-05-08 18:34 UTC
I'm using plotly and Dash to create graphs and have the user save them as .png files using the 'camera' button in the modebar. My graph is formatted/sized correctly in the app when I view in the browser but it appears that plotly is getting the container size wrong when printing to the .png file. Buttons and legends block portions of the graph and axes.

See the [post on the plotly community forum](https://community.plot.ly/t/save-plot-as-png-sizing-and-positioning/10166) for a detailed explanation including code. @chriddyp helped identify that this is a bug and suggested creating this issue.

Happy to provide any further info needed.

Thanks!

**Comment by etpinard** [comment] 2018-05-08 18:36
Duplicate of https://github.com/plotly/plotly.js/issues/1576

**Closed by etpinard** 2018-05-08 18:36 UTC
