### ISSUE TITLE
Allow nested attributes for transforms targets

### ISSUE THREAD

**Issue by MrQubo** [plotly/plotly.js#4131] opened 2019-08-15 15:39 UTC
Allow nested attributes for transforms target, like `target: 'customdata.age'`. See this example on codepen: https://codepen.io/mrqubo/pen/oNvxqzz, currently it doesn't work as expected.

**Comment by MrQubo** [comment] 2019-08-15 15:40
Here's my attempt to implement this feature: https://github.com/MrQubo/plotly.js/pull/1

**Comment by etpinard** [comment] 2019-08-19 16:29
Yeah, that would be cool, but having it as `target: 'customdata.key'` would be inconsistent with our nested property notation. Here `customdata.key` implies that `customdata` is an object, not an array. 

I guess we could allow something like `target: 'customdata[i].key'` or add an attribute e.g.

```js
target: 'customdata',
customdatakey: 'age'
```

**Comment by MrQubo** [comment] 2019-08-19 19:50
`%{customdata.key}` works with hovertemplate. I thought that's intended. Maybe to be consistent with other parts of library customdata should be an object with any keys and data arrays as values.

**Comment by MrQubo** [comment] 2019-08-26 18:34
Thanks for review @etpinard. I'll try to address your points, but I'm not sure what do you mean by:
>     * I would prefer splitting the logic for "regular" `typeof target === 'string'` and `target.indexOf('customdata.') === 0` into two blocks with two distinct `for` loops.
Could you elaborate?

**Comment by gvwilson** [comment] 2024-06-14 12:49
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-14 12:49 UTC
Labels: type: feature
