### ISSUE TITLE
Plotly.Fx.hover does not work with 'scattergl'

### ISSUE THREAD

**Issue by Queatz** [plotly/plotly.js#4557] opened 2020-02-06 16:25 UTC
Codepen: https://codepen.io/queatz/pen/wvavmqJ

The example from https://plot.ly/javascript/hover-events/#triggering-hover-events only works for non-GL.  It should work the same with 'scattergl'

**Comment by etpinard** [comment] 2020-02-06 16:30
Duplicate of https://github.com/plotly/plotly.js/issues/1963

Thanks for posting!

**Closed by etpinard** 2020-02-06 16:30 UTC
