### ISSUE TITLE
Scattergl tooltips don't contain error bar info

### ISSUE THREAD

**Issue by mscotch1** [plotly/plotly.js#4303] opened 2019-10-25 16:14 UTC
See [fiddle](https://jsfiddle.net/cq49nmt8/1/).

The `scatter` example has the +- info in the tooltip whereas the `scattergl` example does not.

**Comment by gvwilson** [comment] 2024-06-14 12:51
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-14 12:51 UTC
Labels: type: feature
