### ISSUE TITLE
Legend scroll not showing on layout.legend.orientation = 'h'

### ISSUE THREAD

**Issue by psalmody** [plotly/plotly.js#766] opened 2016-07-22 00:26 UTC
When using `layout.legend.orientation.h` and have more than a few legend items, they don't appear to scroll. 

JSON code generated by ggplotly() from R but simplified. See [jsfiddle](https://jsfiddle.net/psalmody/c9x3xzg9/)

**Comment by n-riesco** [comment] 2016-07-22 12:08
At the time, I implemented horizontal legends, there were no plans for horizontal scroll bars.

As a workaround, the traces could be grouped. See the following example:

https://github.com/plotly/plotly.js/blob/master/test/image/mocks/legend_horizontal_groups.json

![](https://github.com/plotly/plotly.js/raw/master/test/image/baselines/legend_horizontal_groups.png)

**Comment by etpinard** [comment] 2016-07-22 13:22
@psalmody as @n-riesco pointed, this is the intended behavior you can look at PR #535 starting from https://github.com/plotly/plotly.js/pull/535#issuecomment-219509925 for the rationale. 

Bookkeeping duties imply closing this issue. But thanks for your interest for plotly.js :beers:

**Closed by etpinard** 2016-07-22 13:22 UTC
Labels: type: wontfix
