### ISSUE TITLE
ScatterGL redraw only draws last object

### ISSUE THREAD

**Issue by kevinwuhoo** [plotly/plotly.js#910] opened 2016-09-07 00:18 UTC
When redrawing using ScatterGL and modifying the array of data, Plotly seems to render only the last data object in an array of data. Here's a minimal example of the bug: http://codepen.io/anon/pen/EgjYGa. If you change `scatter` to `scattergl`, it only ends up plotting the last data object (red line) passed to it.

I've circumvented this by calling `Plotly.deleteTraces` then `Plotly.addTraces` which seems to accomplish the same thing, but causes an undesirable flicker since all the traces are getting deleted. Adding new traces before deleting the old ones seem to solve the flicker, but temporarily keeps both datasets while you're doing the swap. An example of this workaround is at the bottom of the above codepen. If you uncomment it and leave the type as `scattergl`, it seems to work.

**Comment by etpinard** [comment] 2016-09-07 13:49
Thanks for the report.

**Comment by etpinard** [comment] 2016-09-07 13:50
maybe @dfcreative would be interested in looking into this.

**Comment by etpinard** [comment] 2016-09-15 22:35
fixed in https://github.com/plotly/plotly.js/pull/947

**Comment by etpinard** [comment] 2016-09-15 22:35
This issue turned to be caused by the same problem as for https://github.com/plotly/plotly.js/issues/942

Closing.

**Closed by etpinard** 2016-09-15 22:35 UTC
Labels: type: bug
