### ISSUE TITLE
request: provide typings?

### ISSUE THREAD

**Issue by CarlCui-AI** [plotly/plotly.js#342] opened 2016-03-17 23:07 UTC
It would be very nice if we have a .d.ts for Plotly library. :smile:

**Comment by etpinard** [comment] 2016-03-18 13:31
duplicate of https://github.com/plotly/plotly.js/issues/28

**Closed by etpinard** 2016-03-18 13:31 UTC
Labels: type: duplicate

**Comment by CarlCui-AI** [comment] 2016-03-18 16:03
Glad somebody asked. :+1:
