### ISSUE TITLE
print sankey to PDF introduce artifcats

### ISSUE THREAD

**Issue by sdementen** [plotly/plotly.js#4547] opened 2020-02-04 06:55 UTC
When printing a page with a sankey diagram in chrome, I see extra horizontal lines being draw on the figure.
To reproduce, go on https://plot.ly/python/sankey-diagram/ and choose "print" in chrome, the preview shows the issue
![image](https://user-images.githubusercontent.com/1304950/73720959-745e8380-4723-11ea-96de-dfe47c09e4d8.png)

I also joined the rendered PDF 
[sub_form.pdf](https://github.com/plotly/plotly.js/files/4151797/sub_form.pdf)

**Comment by antoinerg** [comment] 2020-02-04 16:42
Thank you @sdementen for reporting this issue!

**Comment by sdementen** [comment] 2020-02-04 17:03
Thank you for fixing it!

**Comment by gvwilson** [comment] 2024-06-14 12:56
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-14 12:56 UTC
Labels: type: bug
