### ISSUE TITLE
Don't mutate contours start/end/size into user traces

### ISSUE THREAD

**Issue by mafar** [plotly/plotly.js#4199] opened 2019-09-18 09:17 UTC
Demo: https://codepen.io/mafar/pen/NWKOxzr?editors=0010
This pen is bare minimum for bug reproduction

**Explaination:** https://plot.ly/javascript/reference/#contour
Consider a user is given 3 inputs where he has to set 

1. [contours-start](https://plot.ly/javascript/reference/#contour-contours-start)
1. [contours-end](https://plot.ly/javascript/reference/#contour-contours-end)
1. [contours-size](https://plot.ly/javascript/reference/#contour-contours-size)

and he types invalid option and plotly breaks

**Required:**
Instead of breaking, plotly must ignore values or throw warning

**Image:** wait to load
![image](https://user-images.githubusercontent.com/4101480/65134779-b7f56280-d9b9-11e9-83c3-446630b87637.png)

**Comment by mafar** [comment] 2019-09-18 10:11
If plotly is initiated with wrong selection , it ignores values and does not break
```js
      var data = [{
        z: [[10, 10.625, 12.5, 15.625, 20]],
        type: "contour",       
        contours: {
          start: 1000,
          end: 1
        }
      }];
```

But when same option is called by ```Plotly.restyle```, plotly breaks
```js
var update = {
  'contours.start': 1000,
  'contours.end': 1,
};
Plotly.restyle("myDiv", update, 0);
```

**Comment by etpinard** [comment] 2019-09-18 15:45
Thanks very much for reporting. This issue and https://github.com/plotly/plotly.js/issues/4201 have essentially the same cause: we mutate the input `contours` object during the contour calc step - see `trace._input.contours` assignments below:

https://github.com/plotly/plotly.js/blob/be4e5a95c2a2ac84d33cc9645e111809844c4a3c/src/traces/contour/set_contours.js#L46-L55

and 

https://github.com/plotly/plotly.js/blob/be4e5a95c2a2ac84d33cc9645e111809844c4a3c/src/traces/contour/set_contours.js#L62-L74

---

In brief,

```js
Plotly.newPlot(gd,  [{
    z: [
      [10, 10.625, 12.5, 15.625, 20],
      [5.625, 6.25, 8.125, 11.25, 15.625],
      [2.5, 3.125, 5, 8.125, 12.5],
      [0.625, 1.25, 3.125, 6.25, 10.625],
      [0, 0.625, 2.5, 5.625, 10]
    ],
    type: "contour",
    colorscale: "Jet",
    ncontours: 15,
    autocontour: false 
  }])

// gives
gd.data[0].contours // => {start: 2, end: 18, size: 2}

// then
Plotly.restyle(gd, {'contours.start': 1000})
// gives
gd.data[0].contours // => {start: 1000, end: 18, size: 2}
```

----

To solve this problem the right way, we'll need to implement "relink" logic similar to what https://github.com/plotly/plotly.js/pull/3341 did for colorscale attributes and what https://github.com/plotly/plotly.js/pull/3044 did for histogram bins.

Note that in the meantime, using

```js
Plotly.restyle(gd, {contours: {start: 1000}})
// which replaces all of `gd.data[0].contours` with `{start: 1000}` and gives
gd.data[0].contours // => {start: 2, end: 18, size: 2}
// ... as start > end is not accepted
```

might be a sufficient workaround.

**Comment by etpinard** [comment] 2019-09-18 15:48
Moreover, we should probably make attributes `contours.start`, `contours.end` and `contours.size` 

https://github.com/plotly/plotly.js/blob/be4e5a95c2a2ac84d33cc9645e111809844c4a3c/src/traces/contour/attributes.js#L101-L134

`editType: 'calc'` (not `'plot'`).

**Comment by gvwilson** [comment] 2024-06-14 12:49
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-14 12:49 UTC
Labels: type: bug
