### ISSUE TITLE
heatmap: `(x|y)axis.categoryorder` not honored

### ISSUE THREAD

**Issue by antoinerg** [plotly/plotly.js#3812] opened 2019-04-26 22:28 UTC
In heatmaps, although the axis labels are appropriately reordered when changing `(x|y)axis.categoryorder`, the heatmap itself stays the same.

Codepen https://codepen.io/antoinerg/pen/WWPdoo

**Comment by alexcjohnson** [comment] 2019-04-26 22:54
essentially duplicate of #1097 and #1117

**Closed by alexcjohnson** 2019-04-26 22:54 UTC
Labels: type: bug
