### ISSUE TITLE
3d marker line width has no effect

### ISSUE THREAD

**Issue by taylorjacklespriggs** [plotly/plotly.js#4118] opened 2019-08-09 17:06 UTC
The line width was set to 0.001 for the first trace and 10 for the second trace. I expect the first trace to have markers with nearly invisible borders, and the second trace to have markers with very large borders. The result is that the marker border is always displayed with the same width.

Note: there is an exception in Safari, the border width does get larger with larder line width, but the borders have artifacts.

https://codepen.io/taylorjacklespriggs/pen/aeaPVm

#### Chrome
<img width="421" alt="Screen Shot 2019-08-09 at 10 04 19 AM" src="https://user-images.githubusercontent.com/11512276/62796070-12cb9e00-ba8d-11e9-80f4-95785da6ebfa.png">

#### Firefox
<img width="398" alt="Screen Shot 2019-08-09 at 10 05 32 AM" src="https://user-images.githubusercontent.com/11512276/62796129-48708700-ba8d-11e9-9b93-bacc5111415b.png">

#### Safari
<img width="423" alt="Screen Shot 2019-08-09 at 10 05 45 AM" src="https://user-images.githubusercontent.com/11512276/62796137-4efefe80-ba8d-11e9-9879-addcd4f1279d.png">

**Comment by etpinard** [comment] 2019-08-09 17:11
duplicate of https://github.com/plotly/plotly.js/issues/3796

**Closed by etpinard** 2019-08-09 17:11 UTC
