### ISSUE TITLE
Scatter Plot: Vertical Empty Space WITHIN PLOT AREA at the top/bottom.

### ISSUE THREAD

**Issue by bewithjonam** [plotly/plotly.js#4583] opened 2020-02-14 06:36 UTC
### Issue:
Given there are X entries to be plotted as a scatter plot
And I have given a height in the layout (X * 20) 
When I plot a scatter plot chart
Then there is an empty space at the top & bottom 
(empty space increases with the number of entries)

### Expected:
Given ....
When I plot a scatter plot chart
Then there is no empty space at the top & bottom 

### Minimum Repro Steps:
https://codepen.io/bewithjonam/pen/GRJoKLG

**Comment by etpinard** [comment] 2020-02-14 14:09
That's the expected behavior at the moment (unfortunately).

This issue is essentially a duplicate of https://github.com/plotly/plotly.js/issues/1775

The main take-home points are:

- we add "padding" about the y-axis range for scatter traces except in a few cases (full logic [here](https://github.com/plotly/plotly.js/blob/0e444b6b8ced966ccadb08bbb735f014bb80bdfb/src/traces/scatter/calc.js#L160-L204))
- that "padding" is computed as 5% of the axis length, meaning the longer the y-axis, the greater the number of pixel of padding within the y-axis range (see logic [here](https://github.com/plotly/plotly.js/blob/0e444b6b8ced966ccadb08bbb735f014bb80bdfb/src/plots/cartesian/autorange.js#L185-L201)) 

---

We are hoping the make our autorange behavior more configurable in the future. You can subscribe to https://github.com/plotly/plotly.js/issues/1876 for the most up-to-date development info.

**Comment by etpinard** [comment] 2020-02-17 15:59
Closing. Please subscribe to https://github.com/plotly/plotly.js/issues/1876 for the most up-to-date development info.

**Closed by etpinard** 2020-02-17 15:59 UTC
