### ISSUE TITLE
Direct labels on bar chart not fully visible

### ISSUE THREAD

**Issue by popes01a** [plotly/plotly.js#4244] opened 2019-10-02 09:51 UTC
Hi,

I’ve recently changed the Plotly/Dash app I’m currently working on to display the numbers on the chart, instead of relying solely on hover information. This works great most of the time, but there is an edge case that I seem to run into more and more often recently.

Sometimes, the numbers are slightly off screen and you can’t see the actual value, unless you hover over. But the issue still exists if you want to download the chart as a PNG for example.

![Screenshot from 2019-09-23 15-59-32](https://user-images.githubusercontent.com/31436997/66035120-79f05680-e502-11e9-941d-89603760c62e.png)

I’ve put an example together here using Plotly JS: https://codepen.io/andrap/pen/yLBZybm

Is there a way to force the labels to be contained within the visible graph display area?

Thanks,
Andra

**Comment by etpinard** [comment] 2019-10-02 13:29
Duplicate of https://github.com/plotly/plotly.js/issues/2000

**Closed by etpinard** 2019-10-02 13:29 UTC
