### ISSUE TITLE
Plotly.toImage: add format to remove all semi-transparent elements

### ISSUE THREAD

**Issue by antoinerg** [plotly/plotly.js#4433] opened 2019-12-18 17:32 UTC
In order to add EMF support in Orca (https://github.com/plotly/orca/pull/152), we had to remove all semi-transparency because EMF does not support it. At the time, we did this work in Orca itself. However, as @etpinard pointed out in https://github.com/plotly/orca/pull/152#issuecomment-442913435
> We could even move this compatibility logic to plotly.js' Snapshot.toSVG - which already does a few similar things. I'm not sure if we should be adding a Plotly.toImage flag (e.g. noOpacity) or add a "format" (e.g. svg-for-emf)?

> Thinking about this again, I think adding a noOpacity flag in plotly.js makes sense. There are probably other image formats out there that don't fully support an alpha channel. Now this doesn't solve all the EMF/Inkscape issues; perhaps these remaining issues could be handling in Orca? What do you think @antoinerg ?

@etpinard was clairvoyant in this regard: EPS also does not support semi-transparency. When it's present, it leads to ugly rasterization (see https://github.com/plotly/orca/issues/248 for details).

Therefore I think it would make sense to add a new format to Plotly.toImage to remove all semi-transparent elements. Its name could be `svg-opaque`.

**Comment by gvwilson** [comment] 2024-06-14 12:54
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-14 12:54 UTC
Labels: type: feature, status: discussion needed
