### ISSUE TITLE
Download as PNG not working for scatter3d network map

### ISSUE THREAD

**Issue by GaborSzalai** [plotly/plotly.js#714] opened 2016-07-03 11:05 UTC
The Download as PNG button produces an error "Sorry there was a problem downloading your png" on a scatter3d visualisation in a shiny app. 
App is available here: https://gman-works.shinyapps.io/3D_Mapping/ 
Tested on Chrome and Opera.

**Comment by etpinard** [comment] 2016-07-04 15:27
Interesting. Thanks very much for the report.

I copied your graph's `data` and `layout` and try the `Plotly.downloadImage` in our dev playground and it worked.

So I'm thinking there's something up with `Plotly.downloadImage` that makes it not work in all environments (just as reported in https://github.com/plotly/plotly.js/issues/683).

I had to guess, this issue might be related to commit https://github.com/plotly/plotly.js/commit/b0f623034a9023bea0bdbb72a76c1fe16ccc7f1f

**Comment by etpinard** [comment] 2016-07-05 19:25
@GaborSzalai upon further inspection, I noticed that your app is using plotly.js `1.8.0` **not** the latest (`1.14.1` as of today).

The bug you're describing has been fixed since `1.13.0` via PR https://github.com/plotly/plotly.js/pull/604 

To image is working fine using in the latest plotly.js release: http://codepen.io/etpinard/pen/XKgObK

----

Marked as duplicate of https://github.com/plotly/plotly.js/pull/604

**Closed by etpinard** 2016-07-05 19:25 UTC
Labels: type: bug, type: duplicate
