### ISSUE TITLE
[BUG] Scatter 3d: line not displayed correctly

### ISSUE THREAD

**Issue by emmanuelle** [plotly/plotly.js#4421] opened 2019-12-13 02:40 UTC
See https://codepen.io/emmanuelle-plotly/pen/JjoKeMV. The line is displayed only in one small region (you have to turn the scene to see it). This was reported by https://community.plot.ly/t/3d-scatter-mode-lines-error/32481/

**Comment by emmanuelle** [comment] 2019-12-13 02:40
I added the markers just to show where the line should be but the behaviour persists without the markers.

**Comment by archmoj** [comment] 2019-12-13 03:08
Thanks for the report. It is related to floating errors.
If one reduces the values on the Y-axis, it works OK: [demo](https://codepen.io/MojtabaSamimi/pen/rNaLQRo?editors=0010).

**Comment by etpinard** [comment] 2019-12-13 14:29
Related:

- https://github.com/plotly/plotly.js/issues/551
- https://github.com/plotly/plotly.js/issues/3155

**Comment by gvwilson** [comment] 2024-06-14 12:59
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-14 12:59 UTC
Labels: type: bug
