### ISSUE TITLE
Expose js an api function for saving figures as png/pdf/jpeg/eps/etc with config

### ISSUE THREAD

**Issue by spencerlyon2** [plotly/plotly.js#89] opened 2015-12-08 17:58 UTC
I'm sorry if this is already in another issue somewhere. I looked around a bit, but couldn't find it

It would be awesome if the `Snapshot` functions were exposed at a higher level - perhaps through something that would work like this:

```javascript
Plotly.save(gd, {format: 'pdf', width: '800', height: '450', dpi: '400'})
```

which would then trigger the download of the requested file (similar to how the snapshot button triggers a png download right now)

Being able to easily save to to a vector image backend like `pdf` or `eps` with specified sizes and dpi would be amazing -- then I could publish my plotly figures in latex based research articles.

**Comment by etpinard** [comment] 2015-12-09 15:19
Marked as duplicate of https://github.com/plotly/plotly.js/issues/83

All image formats listed other than png and svg required a convert step outside the js realm. That is, it will never be part of plotly.js.

Luckily, the plotly cloud handle all those image formats for you. For example, in [node.js](https://github.com/plotly/plotly-nodejs#plotlygetimagefigure-options-callback)

**Comment by mdtusz** [comment] 2015-12-09 15:44
@spencerlyon2 another option if you would like to handle pdf's in the browser *could* be [jsPDF](http://mrrio.github.io/jsPDF/), although I haven't used it, and it may not play nicely with plotly plots - you would need to convert from canvas -> png -> pdf using jsPDF.

**Comment by spencerlyon2** [comment] 2015-12-09 19:19
OK no problem, I can handle it outside of the plotly/javascript realm.

Is there as suggested method for causing the download of an SVG?

**Comment by etpinard** [comment] 2015-12-09 19:24
@spencerlyon2 this is what https://github.com/plotly/plotly.js/issues/83 will attempt to solve.

**Comment by etpinard** [comment] 2016-01-26 23:29
closed in favout of #83

**Closed by etpinard** 2016-01-26 23:29 UTC
Labels: duplicate

**Comment by etpinard** [comment] 2016-05-16 19:35
`svg`, `png`, `jpg` and `webp` to-image exports are now available natively via `Plotly.toImage` as of https://github.com/plotly/plotly.js/pull/446.

For vector-quality `pdf` or `eps` figures, I won't recommend exporting your graph to an `svg` and using a conversion utility such as [imageMagick](http://www.imagemagick.org/script/convert.php) to convert the svg to a pdf or eps.

**Comment by timelyportfolio** [comment] 2016-05-16 19:38
@etpinard, I think you mean "would recommend" instead of "won't recommend"

**Comment by etpinard** [comment] 2016-05-16 19:42
@timelyportfolio oops. Fixed above. Thanks!

**Comment by jazzyearrings** [comment] 2017-07-22 17:55
Hi, I have export my image as `svg` and do `convert -density 300 <image>.svg <image>.png`, but the quality doesn't seem to improve. What's wrong? Since we can't set dpi in plot.ly (I'm using python), the only way would be scaling width and height and the marker size, which is inconvenient.
