### ISSUE TITLE
Chord diagrams

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.js#3942] opened 2019-06-07 16:13 UTC
This would probably require a new trace-type to support... Similar to Sankey or Parcats?

https://en.wikipedia.org/wiki/Chord_diagram

**Comment by bobbyscharmann** [comment] 2019-06-13 15:49
This would be an excellent addition to plotly.js.

**Comment by Tuxprogrammer** [comment] 2019-06-13 15:50
I think this would help a lot, we're always generating radial chord diagrams.

**Comment by acxz** [comment] 2024-03-21 12:45
As reference, here is the plotly v3 webpage for [filled chord diagrams](https://plotly.com/python/v3/filled-chord-diagram/).

Looks like the functionality exists, just hasn't been ported over to the latest version.

**Comment by gvwilson** [comment] 2024-06-14 12:02
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-14 12:02 UTC
Labels: type: new trace type

**Comment by acxz** [comment] 2024-06-14 12:35
@gvwilson created a newer version of this issue.

**Comment by gvwilson** [comment] 2024-06-14 12:45
thanks very much @acxz - I'll assign it to myself and try to get it into our backlog.
