### ISSUE TITLE
Handling of duplicate ids

### ISSUE THREAD

**Issue by alexcjohnson** [plotly/plotly.js#4335] opened 2019-11-05 21:45 UTC
A confusing situation popped up in https://github.com/plotly/dash/issues/972 - turns out for animatable traces, if you have multiple points with the same value in `ids`, only the first one is drawn. But for some purposes these points are accounted for - they get space on the axis (and contribute to autorange, and for scatter lines+markers mode they appear in the line but without markers.
https://codepen.io/alexcjohnson/pen/rNNdGaJ?editors=1010
<img width="291" alt="Screen Shot 2019-11-05 at 4 29 04 PM" src="https://user-images.githubusercontent.com/2678795/68247768-7e200000-ffe9-11e9-8c44-5c8762ce970d.png">

I'm not sure whether to call this a bug or simply an unsupported usage. If it's not a noticeable performance drain I'd argue for creating a final id for each point as a concatenation of its original id and its occurrence number, so all points will show up and if animated, those with matching `ids` values will keep their relative order.

If nothing else we should find a better way to communicate this, which already means we'd have to detect duplicates.

**Comment by gvwilson** [comment] 2024-06-14 12:51
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-14 12:51 UTC
Labels: type: bug, status: discussion needed
