### ISSUE TITLE
Legend covers graph when saving as png

### ISSUE THREAD

**Issue by damiarita** [plotly/plotly.js#2224] opened 2017-12-27 16:04 UTC
I love this library and use it for a dashboard I am building for my company.

I have this issue. When I save a graph as a png, the legend covers de graph partially or totally. On the website, it looks good, though.

This is a screenshot of the graph as I see it on the website
![Screenshot](https://user-images.githubusercontent.com/16456159/34386191-c90fb99e-eb27-11e7-9bf3-868e548f9fe9.png)

And this is the png I get once saved:
![Saved PNG](https://user-images.githubusercontent.com/16456159/34386217-e01e325a-eb27-11e7-9903-7b4fcc8d03f0.png)

**Comment by etpinard** [comment] 2017-12-27 16:21
> When I save a graph as a png

How are you doing that? Using the modebar button, through the plot.ly export services or something else?

**Comment by damiarita** [comment] 2017-12-27 16:23
Hi @etpinard 

Thanks for your reply

I use the save as PNG button. The one that has a photo camera on it

**Comment by etpinard** [comment] 2017-12-27 16:24
Thanks. 

In this case, this ticket is a duplicate of https://github.com/plotly/plotly.js/issues/1576 - which offers a workaround.

**Closed by etpinard** 2017-12-27 16:24 UTC

**Comment by damiarita** [comment] 2017-12-27 16:35
Hi,

Thanks for your reply. I added the modeBarButtonsToRemove and modeBarButtonsToAdd to the last paramenter. But it doesn't help. I am creating a fiddle to show my case

**Comment by damiarita** [comment] 2017-12-27 17:01
This is my Fiddle: https://jsfiddle.net/damiarita/n11h2zm6/6/

You will see that depending on how big you make the right side, you will get the correct graph when you click "Run".

However, even if the graph shows OK on the browser, it saves badly

**Comment by etpinard** [comment] 2017-12-28 14:05
Here's a working solution: https://jsfiddle.net/n11h2zm6/7/

**Comment by damiarita** [comment] 2017-12-28 16:34
Perfect. Thanks!

**Comment by rDuinoStar** [comment] 2018-09-26 09:00
> Here's a working solution: https://jsfiddle.net/n11h2zm6/7/

Can you reshare your solution? Thanks!
