### ISSUE TITLE
subplots zoom both on xaxis and yaxis

### ISSUE THREAD

**Issue by chenzhiw** [plotly/plotly.js#3212] opened 2018-11-05 05:39 UTC
I hava a subplots of three plots with the same xaxis and the same range of yaxis. When I zoom on one plot, the yaxis range of this one would change, but others would not. Is there any option could change other plots's yaxis range at the same time?

**Comment by alexcjohnson** [comment] 2018-11-05 12:19
Duplicate of #1549

**Closed by alexcjohnson** 2018-11-05 12:19 UTC
