### ISSUE TITLE
Rotate text attached to a scatter trace [feature request]

### ISSUE THREAD

**Issue by cpsievert** [plotly/plotly.js#1210] opened 2016-11-30 16:48 UTC
I'd like to recreate a plot like this without using annotations:

![ggraph](https://cloud.githubusercontent.com/assets/1365941/20761964/55301aae-b6ea-11e6-9fba-62801ce07c4e.png)

I was thinking this could be supported through a new `textangle` (or similar) scatter attribute that accepts arrays and is only relevant when `mode` contains `"text"`

**Comment by empet** [comment] 2017-03-21 21:03
Related to this topic, I'd like to be able to place the annotation
text, even individually, at some distance  from a point on each radius (something like in this d3.js plot http://mbostock.github.io/d3/talk/20111018/cluster.html).

At the moment the radial text placement looks disordered: https://plot.ly/~empet/13870.
Unfortunately text align https://github.com/plotly/plotly.js/blob/master/src/components/annotations/attributes.js#L60
has effect only for multiline text.

**Comment by etpinard** [comment] 2017-03-21 21:08
@empet you can try using [`standoff`](https://github.com/plotly/plotly.js/blob/c753e472d6261c40534ad8e911483625ccc3e57d/src/components/annotations/attributes.js#L143)

**Comment by empet** [comment] 2017-03-21 21:16
@etpinard  Thanks! I'll try, but it appears that `standoff` refers to arrows. I don't have any arrow in my plot.

**Comment by empet** [comment] 2017-03-23 16:17
@etpinard  Here are my experiments with `standoff`: http://nbviewer.jupyter.org/gist/empet/3256c45e6b93288dab534d1759ae06ec
Unfortunately its value aligns only the arrow heads, not the radial text.

**Comment by jackparmer** [comment] 2018-02-19 02:58
Related community discussion: https://community.plot.ly/t/how-to-change-the-text-derection-in-chord-diagram/8426/5

**Comment by BaronKalle** [comment] 2018-03-01 21:42
Related to this topic: I created a sankey diagram and would like to rotate the labels of the nodes by 90° in order for them to show properly. 
![image](https://user-images.githubusercontent.com/30375389/36871163-9494a01a-1da1-11e8-8e49-8838adc97b74.png)

I know I could change the orientation of the entire graph, but I'd rather not unless there is absolutely no way to do this.

**Comment by BaronKalle** [comment] 2018-03-01 21:43
Related to this topic: I created a sankey diagram and would like to rotate the labels of the nodes by 90° in order for them to show properly.
![image](https://user-images.githubusercontent.com/30375389/36871256-f4682430-1da1-11e8-8221-9463a064d764.png)

I know I could change the orientation of the entire graph, but I'd rather not unless there is absolutely no way to do this.

**Comment by alexmascension** [comment] 2018-09-10 17:19
Looks like this feature will take time although it is a really basic one. So far only annotations can do the trick, but the text positions are not accurate, and they "blow up" when zooming.

Hope this issue is solved ASAP.

**Comment by etpinard** [comment] 2018-09-10 18:13
> , but the text positions are not accurate, and they "blow up" when zooming.

Could you provide a reproducible example to help us out?

**Comment by alexmascension** [comment] 2018-09-12 19:13
You can see it here (not my example): https://plot.ly/~empet/14803/annotations-following-a-direction-given/#/

In the moment you zoom, the position of the labels are not respeted.

**Comment by MKoesters** [comment] 2018-12-12 13:14
I'm looking for such a feature since some time, are there currently efforts implementing this?
If yes, I would like to join implementing this feature, as long as it can be solved with basic js knowledge.
Anyway, +1

**Comment by stanstrup** [comment] 2020-09-09 13:37
This is still sorely needed... Any hope?

**Comment by nicolaskruchten** [comment] 2020-09-09 13:49
There is always hope :)


It's a good feature and we'd love to have it in the library but it's not on anyone's roadmap at the moment as far as I know. That said, we as maintainers would be happy to [help someone from the community to implement it in Plotly.js](https://github.com/plotly/plotly.js/blob/master/CONTRIBUTING.md), or to [accept sponsorship](https://plot.ly/products/consulting-and-oem/) to get it on to our short-term roadmap :)

**Comment by jackparmer** [comment] 2020-09-10 18:45
This issue has been tagged with `NEEDS SPON$OR`

A [community PR](https://github.com/plotly/plotly.js/pulls?q=is%3Apr+is%3Aopen+label%3A%22type%3A+community%22) for this feature would certainly be welcome, but our experience is deeper features like this are difficult to complete without the Plotly maintainers leading the effort.

**Sponsorship range: $10k-$15k**

What Sponsorship includes:
- Completion of this feature to the Sponsor's satisfaction, in a manner coherent with the rest of the Plotly.js library and API
- Tests for this feature
- Long-term support (continued support of this feature in the latest version of Plotly.js)
- Documentation at [plotly.com/javascript](https://plotly.com/javascript/)
- Possibility of integrating this feature with Plotly Graphing Libraries (Python, R, F#, Julia, MATLAB, etc)
- Possibility of integrating this feature with Dash
- Feature announcement on [community.plotly.com](https://community.plotly.com/tag/announcements) with shout out to Sponsor (or can remain anonymous)
- Gratification of advancing the world's most downloaded, interactive scientific graphing libraries (>50M downloads across supported languages)

Please include the link to this issue when [contacting us](https://plotly.com/get-pricing/) to discuss.

**Comment by gvwilson** [comment] 2024-06-06 15:11
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson

**Closed by gvwilson** 2024-06-06 15:11 UTC
Labels: type: feature, ♥ NEEDS SPON$OR
