### ISSUE TITLE
Move data cleaning process from plot to calc

### ISSUE THREAD

**Issue by archmoj** [plotly/plotly.js#4633] opened 2020-03-12 16:13 UTC
At the moment, it appears that the only traces calling [fast-isumeric](https://www.npmjs.com/package/fast-isnumeric) during `plot` are scatterpolargl , barpolar, and bar (& friends).
In theory (to speed up redraws & reduce checks) it may be a good idea to move data cleaning process like this to `calc`.

**Comment by archmoj** [comment] 2020-03-12 16:15
Note by @alexcjohnson on slack:
`possibly - but during plot these calls should be pretty fast, as the data they are looking at should already have type number so the only question isNumeric needs to answer is whether they’re finite.`

**Comment by gvwilson** [comment] 2024-06-14 13:00
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-14 13:00 UTC
Labels: type: maintenance, type: performance
