### ISSUE TITLE
geo pan bug

### ISSUE THREAD

**Issue by archmoj** [plotly/plotly.js#4608] opened 2020-03-02 00:29 UTC
Console error when applying `pan` to bring the sphere down:
https://rreusser.github.io/plotly-mock-viewer/#geo_skymap

<pre>
plotly-latest.js:131901 Uncaught TypeError: Cannot read property '0' of undefined
    at SVGRectElement.handleZoom (plotly-latest.js:131901)
    at SVGRectElement.event (plotly-latest.js:25461)
    at plotly-latest.js:25497
    at zoomed (plotly-latest.js:26419)
    at moved (plotly-latest.js:26437)
    at plotly-latest.js:26077
</pre>

**Comment by gvwilson** [comment] 2024-06-14 12:58
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-14 12:58 UTC
Labels: type: bug
