### ISSUE TITLE
Plotting on a very fine grid

### ISSUE THREAD

**Issue by sursu** [plotly/plotly.js#4134] opened 2019-08-16 12:28 UTC
When `y`'s are big numbers with very small variance, it is a bit challenging to read the tickers, especially when they will have different number of digits.

**Example**:

```python
import numpy as np
import matplotlib.pyplot as plot
import plotly.graph_objects as go

y = np.random.normal(1883.31,0.001, size=20)
```

Plotly:
```python
go.Figure(go.Scatter(y=y))
```
![newplot](https://user-images.githubusercontent.com/12001304/63167376-6e6bcd80-c031-11e9-839b-d08a23d8c4a7.png)

Matplotlib does this:
```python
plot.plot(y)
plot.show()
```
![image](https://user-images.githubusercontent.com/12001304/63167396-788dcc00-c031-11e9-9925-bb897c9e1979.png)

If this is implemented somehow in Plotly I would like to ask how?

If not, this may be a suggestion.

I don't know whether matplotlib's way is the nicest. 
My idea was to highlight the digits that differ and to display the digits that don't differ (or those after the comma) in a lighter hue. Maybe you have a better one.

Thank you!!

**Comment by gvwilson** [comment] 2024-06-14 12:48
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-14 12:48 UTC
