### ISSUE TITLE
Plotly range slider really slow with markers

### ISSUE THREAD

**Issue by KiranBaktha** [plotly/plotly.js#2754] opened 2018-06-25 15:39 UTC
Hey guys,

I am trying to plot 15000 points using a range slider on the x axis with lines and markers. This is the codepen:

https://codepen.io/kiranbaktha/pen/ERpejP
If the mode is only lines it is fast but with markers it seems to be really slow. Is there a way to make this faster? Thanks.

**Comment by etpinard** [comment] 2018-06-26 14:01
There's a few things we could do to improve range slider performance, but really at 10k+ pts, this ticket is a duplicate of https://github.com/plotly/plotly.js/issues/2627

**Closed by etpinard** 2018-06-26 14:01 UTC

**Comment by EbrahimKaram** [comment] 2020-04-14 14:43
Hey What I ended up using was the Scattergl
https://plotly.com/python/webgl-vs-svg/
Made it so much faster
