### ISSUE TITLE
width and highlightwidth have no effect in surface plots

### ISSUE THREAD

**Issue by JanSellner** [plotly/plotly.js#3668] opened 2019-03-24 15:49 UTC
According to the [documentation](https://plot.ly/javascript/reference/#surface-contours-x-highlightwidth), it should be possible to set the width of the contour lines in a surface plot, e.g. for the z-axis:
```javascript
 z: {
    width: 16,   // Permanent lines
    highlightwidth: 16   // On hover
}
```
However, these settings seem to have no effect at all. I adapted the example from the documentation and set both values to the highest possible value (16): [https://codepen.io/anon/pen/ZPwMGE?editors=1010](https://codepen.io/anon/pen/ZPwMGE?editors=1010). Both lines (contour lines (white) and hover lines (green)) are still shown with their default width:
![grafik](https://user-images.githubusercontent.com/11442755/54881841-937a5c80-4e54-11e9-8d9e-fea8df307e01.png)

**Comment by archmoj** [comment] 2019-03-24 16:06
@Milania1 What OS+browser you use?
Webgl `gl.lineWidth` is not supported depending browsers / operating system.
With Ubuntu+Chrome your example renders well.

**Comment by Milania1** [comment] 2019-03-24 16:20
I am on Windows 10 x64 1803 and tested with Firefox 66.0.1 as well as Chrome 73.0.3683.75. Unfortunately, it works in neither.

But I just found out that this seems to be a [problem](https://stackoverflow.com/questions/47444239/how-to-use-gl-linewidth) in modern web browsers which can't get fixed at the moment :-(

**Comment by Koushikphy** [comment] 2019-06-30 14:23
Yeah, `width` is not working for me too.

**Comment by gvwilson** [comment] 2024-06-13 19:51
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-13 19:51 UTC
Labels: type: bug
