### ISSUE TITLE
Turn finance charts into first-class trace types

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.js#2510] opened 2018-03-29 19:09 UTC
The following Pen shows an issue with a sequence of `Plotly.react` calls not meshing well with candlestick charts: https://codepen.io/nicolaskruchten/pen/qooWqr

**Comment by alexcjohnson** [comment] 2018-04-04 04:26
Update: This is an issue with `Plotly.react` but NOT with `Plotly.restyle`. I spent a couple of hours fighting with it before concluding (after talking with @etpinard) that my time would be better spent turning `candlestick` and `OHLC` into first-class chart types instead of transform hacks. I'm not even going to *look* at #2508 until this is done, because the OHLC transform hacks are so different from our other transforms that the framework will be far easier to reason about and fix once they're gone. Anyway this is a change we've been discussing for ages and will allow us to fix several more otherwise-intractable bugs.

While investigating this I found a different class of errors, that may or may not impact plotly.js directly but will definitely impact the editor and perhaps other apps: traces mutating the "public" parts of `_full(Data|Layout)` outside of the `supplyDefaults` framework: either:
- adding new properties that look like attributes (because they aren't prefaced with `_`) but are not
- reshaping an existing attribute, as when we reshape 1D Z arrays into 2D
- filling in auto values only during `calc` and NOT writing them back to `data` and `layout` - this means if you make a small change to the plot that doesn't trigger `calc`, these quantities will disappear from `_full*` and will not be available to the editor.

I've fixed many of these, and explicitly ignored the others in the relevant test ([this one](https://github.com/plotly/plotly.js/blob/3d65de3adb20ca0c75e9ecb67739c5d801cc3b24/test/jasmine/tests/plot_api_test.js#L2837), where we draw and then redraw a plot with `Plotly.react` and verify that nothing was done; now I'm also testing that `fullData` and `fullLayout` are unchanged in their supposedly public portions), so that the problem is at least bounded.

**Comment by alexcjohnson** [comment] 2018-04-04 16:33
Incidentally, I came across this page that has a whole bunch of variants on candlestick charts, that we will suddenly be free to add as new features once these are their own trace type http://stockcharts.com/school/doku.php?id=chart_school:chart_analysis:arms_candlevolume
In particular, check out this one that uses color (black/red) to denote whether the closing price is higher or lower than the previous day, and filling (closed/open) to denote whether the price increased or decreased during the day
![armscv-4-can-isrg](https://user-images.githubusercontent.com/2678795/38321017-49942d7e-3804-11e8-9f63-7ec3fdf1e1a5.png)

**Comment by chriddyp** [comment] 2018-04-04 16:44
> Seems concise and clear which color is increasing/decreasing. But I'm open to tweaks.

A single legend item seems good to me and that legend item symbol looks good to. 
I'll also defer to @santosjorge for feedback on this

**Closed** 2018-04-17 14:59 UTC
Labels: type: bug
