### ISSUE TITLE
LaTeX/MathJax broken using Firefox v82.0

### ISSUE THREAD

**Issue by MRScheid** [plotly/plotly.js#5374] opened 2021-01-06 01:04 UTC
Hi Plotly team, I just recently updated my firefox browser to version 84.0.1 and have been using plotly's (v4.14.1) subplots in Jupyter notebook (v6.0.3) with Python (v3.7.6) for a couple months now without issue.  I noticed that with this new version of the browser when I call something like: 

```python
from plotly.subplots import make_subplots

fig = make_subplots(1, 3, subplot_titles=[1, 2, 3])
fig['layout'].update(width=1200, height=1200)
fig.add_trace(go.Scatter(x=[1 , 2 , 3], 
                             y=[1 , 2 , 3], 
                             name='$123$',
                            ),
                  row=1,
                  col=1
                 )

fig.add_trace(go.Scatter(x=[1 , 2 , 3], 
                         y=[1 , 2 , 3], 
                        ),
                  row=1,
                  col=2
                 )

fig.show()
```

The figures do not render properly and when I try to toggle the traces by clicking on the legend, all of the plots shrink and are illegible.  This issue seems to be caused whenever I add Latex to the legend str using the name argument in go.Scatter while ALSO using the update command to manually set the width and height of the figure.  If I do only one or the other, the behavior seems to go back to normal.  It also seems to be unique to Firefox, as I did not have an issue with Chrome when I tested this with the same environment.  Hoping this is enough information to create a reproducible example and solve this issue.

**Comment by alexcjohnson** [comment] 2021-01-06 02:51
Thanks @MRScheid - confirmed with FF84 on my Mac, at for example https://plotly.github.io/LaTeX-basics/

It looks like the LaTeX renders, but has some sort of bounding box error.

**Comment by jaladh-singhal** [comment] 2021-01-28 08:39
@alexcjohnson when can we expect this to be fixed?

**Comment by nicolaskruchten** [comment] 2021-01-28 12:18
We'll try to fix it in the coming weeks but we'd sure appreciate some help!

**Comment by antoinerg** [comment] 2021-01-29 06:24
On Firefox 84.0.2, I noticed that the latest version of MathJax 2.x (2.7.9) behaves very differently from the one checked into our repo (2.3). Based on this, I'm not sure there will be one solution that will work for both MathJax versions.

For example, using my tentative fix, I get this on 2.7.9:
![newplot(4)](https://user-images.githubusercontent.com/301546/106238859-9c19e780-61cf-11eb-8740-8737c67d6ce6.png)

But on 2.3 I get:
![newplot(3)](https://user-images.githubusercontent.com/301546/106238871-a0de9b80-61cf-11eb-8bce-5efe828cbabd.png)

On the other hand, Chromium renders the correct result for both MathJax versions.

Would a fix only targeting MathJax 2.7.9 be good enough @alexcjohnson ?

**Comment by antoinerg** [comment] 2021-01-29 18:52
For reference, this is what the very same mock looks like in Firefox 84.0.2 on Linux on `master` branch:
![newplot(2)](https://user-images.githubusercontent.com/301546/106315331-1a5ea400-6239-11eb-81c8-7249cf1875ff.png)

**Comment by alexcjohnson** [comment] 2021-01-29 19:25
We can certainly upgrade to 2.7.9 and drop 2.3, especially if we can get this into our v2 release. In fact in a perfect world we'd upgrade to MathJax v3 in plotly.js v2, but I assume that'll be more than a one-afternoon change, so not something we can do right now.

**Comment by antoinerg** [comment] 2021-02-09 17:50
Ok, so I'll try to come up with a patch to fix the issue in MathJax 2.7.x!

**Comment by maresb** [comment] 2021-05-21 09:08
Is there any known workaround, or is LaTeX in Plotly just plain broken for all recent Firefox versions?

**Comment by vvch** [comment] 2021-07-18 07:07
Jan 28> We'll try to fix it in the coming weeks

Is there any progress in half a year? Did there some serious difficulties appear?
I think this bug deserve high priority since it makes many existing services unusable.

**Comment by nicolaskruchten** [comment] 2021-07-18 16:59
We did spend some time on this in February but ran into problems around MathJax versions so we put this aside until 2.0 was released (done last month!) wherein we committed to supporting MathJax 2.7.5 moving forward, and we also upgraded our testing infrastructure. Unfortunately, no one on our staff is available to fix this issue for the next couple of months at least, so we'd really appreciate some assistance if someone from the community wanted to step in an help out :)

**Comment by archmoj** [comment] 2021-09-30 16:04
Firefox releases are [here](https://ftp.mozilla.org/pub/firefox/releases/).

**Comment by archmoj** [comment] 2021-10-09 01:18
I was able to replicate the bug on Ubuntu using `82.0 <= Firefox <= 93.0`.

**Comment by archmoj** [comment] 2021-10-19 21:33
It is likely related to this Firefox bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1709251

**Comment by gvwilson** [comment] 2024-06-26 18:13
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-26 18:13 UTC
Labels: type: bug
