### ISSUE TITLE
Implement align left and right for inside text bars, waterfall, funnel and funnelarea

### ISSUE THREAD

**Issue by archmoj** [plotly/plotly.js#4474] opened 2020-01-08 20:03 UTC
The text within traces namely `bar`, `waterfall`, `funnel` and `funnelarea` could only be aligned at the `center`.  On the other hand `treemap` has option to control `left` and `right` alignments.
#4469 should have made `left` and `right` alignments easy i.e. for the text inside bars.

**Comment by gvwilson** [comment] 2024-06-14 12:55
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-14 12:55 UTC
Labels: type: feature
