### ISSUE TITLE
Extend multicategory axes to more than 2 levels in React.js

### ISSUE THREAD

**Issue by abantodca** [plotly/plotly.js#6489] opened 2023-02-17 02:45 UTC
```
let x1 = [
    1234, 1234, 1234, 2222, 3333, 4444, 4444, 2222, 3333, 4444, 4444, 1234,
    2222, 3333, 3333, 4444, 4444, 1234, 1234, 1234, 2222, 2222, 4444, 4444,
    4444,
  ];

  let x2 = [
    1.1, 1.1, 1.1, 1.1, 1.1, 1.1, 1.1, 1.2, 1.25, 1.25, 1.25, 1.1, 1.1, 1.1,
    1.1, 1.1, 1.1, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.25,
  ];

  let x3 = [
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
  ];

  let y = [
    74.7, 73.2, 73.1, 89.9, 87.0, 78.1, 76.6, 85.8, 97.3, 76.7, 73.1, 68.8,
    79.3, 84.3, 82.5, 70.2, 72.2, 74.7, 73.3, 70.0, 81.7, 84.7, 80.0, 82.2,
    74.7,
  ];

  let tracetreecategoria = {
    x: [x1, x2, x3],

    y: y,
    type: "box",
    name: "box",
  };

  let layouttreecateogria = {
    paper_bgcolor: "WhiteSmoke",
    plot_bgcolor: "White",
    xaxis: {
      title: "x1",
      Array,
    },
  };

  var datanueva = [tracetreecategoria];

<div>
        <Plot
          data={datanueva}
          useResizeHandler={true}
          style={{ width: "100%", height: "100%" }}
          layout={layouttreecateogria}
          
        />
 </div>
```

show me!
don't showme me the three leves in my x axis.

![image](https://user-images.githubusercontent.com/121888808/219536193-6823e497-c7b2-4aa6-940b-4af6e97bc711.png)

**Comment by alexcjohnson** [comment] 2023-02-17 14:22
Duplicate of #2175 - and I'll note there's an open PR #6327 that would add this, just needs to be completed.

**Closed by alexcjohnson** 2023-02-17 14:22 UTC
