### ISSUE TITLE
scatter3d plot with 1.5M points gives RangeError: attempting to construct out-of-bounds TypedArray on ArrayBuffer

### ISSUE THREAD

**Issue by Luthaf** [plotly/plotly.js#4589] opened 2020-02-18 16:35 UTC
See the pen for a reproduction: https://codepen.io/luthaf/pen/yLNJpBY. If you set `N` to smaller values, everything works fine.

Here is the corresponding backtrace:
```
RangeError: attempting to construct out-of-bounds TypedArray on ArrayBuffer plotly-latest.js:75973:10
    mallocFloat https://cdn.plot.ly/plotly-latest.js:75973
    update https://cdn.plot.ly/plotly-latest.js:49798
    createPointCloud https://cdn.plot.ly/plotly-latest.js:50107
    update https://cdn.plot.ly/plotly-latest.js:187138
    createLineWithMarkers https://cdn.plot.ly/plotly-latest.js:187251
    plot https://cdn.plot.ly/plotly-latest.js:135424
    plot https://cdn.plot.ly/plotly-latest.js:133863
    drawData https://cdn.plot.ly/plotly-latest.js:117413
    syncOrAsync https://cdn.plot.ly/plotly-latest.js:106523
    plot https://cdn.plot.ly/plotly-latest.js:112003
    newPlot https://cdn.plot.ly/plotly-latest.js:112273
    <anonyme> pen.js:39
```

---

Is this the expected behavior? What is plotly policy concerning very large plots?

**Comment by gvwilson** [comment] 2024-06-14 12:57
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-14 12:57 UTC
Labels: type: bug
