### ISSUE TITLE
Mouse up can unintentionally toggle a trace on/off

### ISSUE THREAD

**Issue by Trintar** [plotly/plotly.js#4340] opened 2019-11-07 16:26 UTC
Steps to reproduce:

1) Open [modified Plotly example](https://codepen.io/Trintar/pen/zYYjJpo) with some text on the side to highlight.
2) Highlight the text to the right of the trace legend from right-to-left, releasing the mouse click when over the trace.
3) After releasing the mouse, moving the mouse will toggle the trace on or off.

It appears traces are toggled on/off by a mouse up event, which could allow unintentional toggling.

**Comment by gvwilson** [comment] 2024-06-14 12:52
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-14 12:52 UTC
Labels: type: bug
