### ISSUE TITLE
Boxplot points not drawn in some cases

### ISSUE THREAD

**Issue by Jeff-Clark** [plotly/plotly.js#574] opened 2016-05-27 15:08 UTC
See https://jsfiddle.net/cf4j5vxz/

Traced it into code line
newJitter = trace.jitter * 2 / maxJitterFactor;
maxJitterFactor is zero in some cases when lots of data points are zero.

**Comment by etpinard** [comment] 2016-05-30 14:19
Bug confirmed. Thanks for reporting.

Looks like you found the root of the problem. This would a great opportunity for a first contributor to make his/her first PR.

**Comment by alexcjohnson** [comment] 2016-09-08 03:28
closed by #915

**Closed by alexcjohnson** 2016-09-08 03:28 UTC
Labels: type: bug
