### ISSUE TITLE
Axes Mirror Labels

### ISSUE THREAD

**Issue by Keoghan** [plotly/plotly.js#2160] opened 2017-11-15 14:55 UTC
Hi, 

First, thanks for sharing Plotly.js.

I've had a good look around for some information on displaying labels on a mirrored axis and not found anything, nor any historical issues. 

It appears that there is a [TODO item in the code](https://github.com/plotly/plotly.js/blob/9bfbabfba9a5975edb0b6f49c625f6f7db7acd4b/src/plots/cartesian/axes.js#L1913) for producing mirrored axis labels - and so perhaps it is not possible right now. Please can you confirm? 

Many thanks,

Keoghan

**Comment by etpinard** [comment] 2017-11-15 15:41
Thanks for pointing this out.

**Comment by Braintelligence** [comment] 2020-11-01 13:11
I also stumbled over this today. The workaround seems to be to really go with a second axis. It would be awesome if this could be added.

**Comment by gvwilson** [comment] 2024-06-10 21:02
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson

**Closed by gvwilson** 2024-06-10 21:02 UTC
Labels: type: feature
