### ISSUE TITLE
ScatterGL plot fails with WebGL errors if more than 16 symbols are used.

### ISSUE THREAD

**Issue by brian428** [plotly/plotly.js#4628] opened 2020-03-11 19:45 UTC
Using plotly-latest, a ScatterGL plot will fail and throw WebGL errors if more than 16 symbols are used in the plot.

Repro case can be found at: http://jsfiddle.net/brian428/d7oh4j2m/

I tested and found that the magic number seems to be 16. With 16 symbols, the plot seems to work fine. With 17 symbols, large numbers of WebGL errors appear. For reference, the errors say:

```
WebGL: INVALID_ENUM: activeTexture: texture unit out of range
bind @ plotly-latest.js:69560
batch @ VM6468:3138
E.stats @ plotly-latest.js:69665
Scatter.drawItem @ plotly-latest.js:68498
Scatter.draw @ plotly-latest.js:68454
draw @ plotly-latest.js:190442
exports.redrawReglTraces @ plotly-latest.js:117493
exports.drawData @ plotly-latest.js:117430
lib.syncOrAsync @ plotly-latest.js:106537
plot @ plotly-latest.js:112017
exports.call @ plotly-latest.js:147449
exports.layoutReplot @ plotly-latest.js:117373
lib.syncOrAsync @ plotly-latest.js:106537
relayout @ plotly-latest.js:113531
wrappedEdit @ plotly-latest.js:114061
exports.call @ plotly-latest.js:147449
handleCartesian @ plotly-latest.js:95936
(anonymous) @ plotly-latest.js:96808
```

Not sure if it matters, but I'm using the latest Chrome (80.0.3987.132) on Win 10 x64. Also tested with Firefox 74.0 with the same results.

**Comment by archmoj** [comment] 2020-03-11 19:52
Do you think it is a regression?
I can't replicate it with Chrome and Firefox on ubuntu.
Would you please let us know which OS+browser you use?

**Comment by brian428** [comment] 2020-03-11 19:53
Yep, I tested with Chrome (80.0.3987.132) on Win 10 x64. Also tested with Firefox 74.0 with the same results.

**Comment by archmoj** [comment] 2020-03-11 19:57
Could you please investigate if this is a regression?

**Comment by brian428** [comment] 2020-03-11 20:10
I went back through previous versions and it looks like it started around 1.33.0 or 1.34.0. I didn't get the errors with 1.32.0.

**Comment by archmoj** [comment] 2020-03-11 20:15
Thanks @brian428 
Here are changelogs for further investigation:
[v1.33.0](https://github.com/plotly/plotly.js/releases/tag/v1.33.0)
[v1.33.1](https://github.com/plotly/plotly.js/releases/tag/v1.33.1)
[v1.34.0](https://github.com/plotly/plotly.js/releases/tag/v1.34.0)

**Comment by etpinard** [comment] 2020-03-11 20:23
Sounds like this has probably been a bug since the gl2d rewrite in regl #2258 two years ago.

**Comment by brian428** [comment] 2020-03-11 20:27
From the changelogs, I would guess that's probably right. We didn't notice the problem in our app until it started to be used in production, since no one thought to test it with data that created that many symbols at once. :-/

**Comment by brian428** [comment] 2020-03-11 20:29
And, again, this only seems to trigger during selection, so it's even less obvious. Not sure if that narrows it down at all, and I'm not sure yet if any other actions trigger it beyond selecting. I'll see if I can find out.

**Comment by brian428** [comment] 2020-03-12 13:16
Unsurprisingly, enabling the lasso select also triggers the WebGL errors. I couldn't trigger it with other modebar actions though. So it seems limited to selection as far as I can tell.

**Comment by archmoj** [comment] 2020-06-24 17:47
It appears to be fixed by in [v1.54.2](https://github.com/plotly/plotly.js/releases/tag/v1.54.2) via https://github.com/plotly/plotly.js/pull/4881.
@brian428 please confirm.

**Comment by brian428** [comment] 2020-07-02 17:33
@archmoj sorry it took a bit to return to this, but trying out latest (1.54.5), still seeing the issue. In addition, as number of symbols goes up, more and more points are not displayed. Hover data points to them, but the points themselves are not shown.

Updated repro: http://jsfiddle.net/brian428/d7oh4j2m/

**Comment by jackparmer** [comment] 2020-09-10 19:32
This issue has been tagged with `NEEDS SPON$OR`

A [community PR](https://github.com/plotly/plotly.js/pulls?q=is%3Apr+is%3Aopen+label%3A%22type%3A+community%22) for this feature would certainly be welcome, but our experience is deeper features like this are difficult to complete without the Plotly maintainers leading the effort.

**Sponsorship range: $10k-$15k**

What Sponsorship includes:
- Completion of this feature to the Sponsor's satisfaction, in a manner coherent with the rest of the Plotly.js library and API
- Tests for this feature
- Long-term support (continued support of this feature in the latest version of Plotly.js)
- Documentation at [plotly.com/javascript](https://plotly.com/javascript/)
- Possibility of integrating this feature with Plotly Graphing Libraries (Python, R, F#, Julia, MATLAB, etc)
- Possibility of integrating this feature with Dash
- Feature announcement on [community.plotly.com](https://community.plotly.com/tag/announcements) with shout out to Sponsor (or can remain anonymous)
- Gratification of advancing the world's most downloaded, interactive scientific graphing libraries (>50M downloads across supported languages)

Please include the link to this issue when [contacting us](https://plotly.com/get-pricing/) to discuss.

**Comment by nicolaskruchten** [comment] 2020-09-11 15:31
This is intentional in this case: we're unlikely to be able to fix this one without external sponsorship unfortunately.

**Comment by gvwilson** [comment] 2024-06-24 13:09
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-24 13:09 UTC
Labels: type: bug, type: regression, ♥ NEEDS SPON$OR
