### ISSUE TITLE
Plotly relayout autorange fails with automargins.

### ISSUE THREAD

**Issue by justnick21** [plotly/plotly.js#3106] opened 2018-10-15 13:30 UTC
When `fixLabelOverlaps` is called (axes.js:1807) via:     

> Plotly.relayout('plotly', {
>   "xaxis.autorange": true,
>   "yaxis.autorange": true
> });

`tester = drawing.tester.node();` inside `src/components/drawing/index.js.drawing.bBox` fails because there is no tester node. The `js-plotly-tester` is on the page, just not referenced in the drawing object.

Can be fixed by adding `if (!drawing.tester) drawing.makeTester()` on the line above.

I saw some discussion about the performance of the measuring so I thought I would raise as a bug before making a PR.

**Comment by alexcjohnson** [comment] 2018-10-15 14:06
Thanks @justnick21 - But I haven't managed to reproduce this error. Here's a try based on one of our existing automargin mocks: https://codepen.io/alexcjohnson/pen/wYPdBN?editors=1010
Can you make a codepen, or modify that one, to show the issue?

**Comment by justnick21** [comment] 2018-10-15 14:52
Sorry I am unable to reproduce this issue in a codepen. Not sure why the key is no longer on that object. Stack trace attached but without spending a lot of time reproducing this in a pen I am afraid I can't give any more details

`TypeError: Cannot read property 'node' of undefined
    at Object.push../node_modules/plotly.js/src/components/drawing/index.js.drawing.bBox (index.js:926)
    at SVGGElement.<anonymous> (axes.js:1803)
    at plotly.js:21021
    at d3_selection_each (plotly.js:21028)
    at Array.d3_selectionPrototype.each (plotly.js:21020)
    at fixLabelOverlaps (axes.js:1798)
    at Object.push../node_modules/plotly.js/src/lib/index.js.lib.syncOrAsync (index.js:401)
    at drawLabels (axes.js:1961)
    at Object.push../node_modules/plotly.js/src/plots/cartesian/axes.js.axes.doTicksSingle (axes.js:2132)
    at axes.js:1480
    at Object.push../node_modules/plotly.js/src/lib/index.js.lib.syncOrAsync (index.js:401)
    at Object.push../node_modules/plotly.js/src/plots/cartesian/axes.js.axes.doTicks (axes.js:1477)
    at Object.push../node_modules/plotly.js/src/plot_api/subroutines.js.exports.doTicksRelayout (subroutines.js:480)
    at doTicks (plot_api.js:1638)
    at Object.push../node_modules/plotly.js/src/lib/index.js.lib.syncOrAsync (index.js:401)
    at Object.relayout (plot_api.js:1625)
    at Chart.js:62
    at Array.forEach (<anonymous>)`

**Comment by alexcjohnson** [comment] 2018-10-15 15:00
OK thanks! I'll leave this report open for a while in hopes that we can figure out the root cause, but I don't think it's a good idea to address the symptom directly before that, as there are very likely to be other ways whatever this problem is can manifest itself.

**Comment by etpinard** [comment] 2018-12-21 22:12
Closing due to lack of reproducible example.

@justnick21 feel free to open another issue when/if you're able to reproduce this in a codepen.

**Closed by etpinard** 2018-12-21 22:12 UTC

**Comment by cognot** [comment] 2020-04-24 12:44
I have the exact same issue. Only happens if xaxis.autorange is set to true though. If I only set yaxis.autorange the issue goes away. And no, I have not been ble to reproduce it in a codepen.

This is with a simple scatter.

**Comment by federicomassa** [comment] 2021-04-27 13:27
Same here with v1.58.4. Tried to reproduce it on CodePen but couldn't

**Comment by jxu** [comment] 2021-06-23 06:08
Still have this issue in 2.1.0
