### ISSUE TITLE
FF64 renders incomplete bar charts?

### ISSUE THREAD

**Issue by mbkupfer** [plotly/plotly.js#3393] opened 2019-01-03 20:15 UTC
I noticed that my dash app was rendering poorly, but after doing cross browser testing (using Chrome and IE) , I noticed that this is only isolated to firefox. In the gif below, firefox is on left and chrome is on right. You can notice that when I switch the state to "Alabama" one of the graphs get stuck in an awkward transition and those that are stuck are still showing old data. This varies between selections sometimes being more than one graph/bar that is affected.

![firefox-issue](https://user-images.githubusercontent.com/6313008/50659263-e7119400-0f50-11e9-8b09-7c15088944e0.gif)

You can play around with my test tool which is up on heroku, albeit it is on a free tier so it will require some bootup if it went to sleep: https://pay-rate-rangefinder-demo.herokuapp.com/

**Comment by chriddyp** [comment] 2019-01-03 20:22
This example is using plotly.js 1.43.1

**Comment by mbkupfer** [comment] 2019-01-03 20:58
@etpinard 

Firefox 64.0 (64-bit)

**Comment by etpinard** [comment] 2019-01-03 23:18
Wow. Another FF64 + mac bug. :rage:

**Comment by etpinard** [comment] 2019-01-03 23:36
Ok. If someone would like to help, the next step would be to put to together a minimal codepen displaying this bug. Thanks!

**Comment by mbkupfer** [comment] 2019-01-04 00:48
This example: https://codepen.io/etpinard/pen/pbxkNb I found in plotly's documentation demonstrates this rendering issue. It's also on a line graph so it shows that this could be a broader issue and not just for bar charts.

**Comment by etpinard** [comment] 2019-01-04 02:30
Yikes. That's bad. I'm not sure what we can do here.

The next step would be to see if a similar bug has been filed on:

https://bugzilla.mozilla.org/buglist.cgi?quicksearch=svg

**Comment by mbkupfer** [comment] 2019-01-08 17:03
Not sure if a bug has been found/filed at: [https://bugzilla.mozilla.org/buglist.cgi?quicksearch=svg](https://bugzilla.mozilla.org/buglist.cgi?quicksearch=svg)
If not, then I'm happy to take the lead on this. Let me know.

**Comment by etpinard** [comment] 2019-01-08 17:07
@mbkupfer thanks for the reply!

I haven't been able to find a similar report on bugzilla, but I only searched for a few minutes.

If you're willing to make a reproducible example for the FF team, yes please, go for it! Thank you very much!

**Comment by mbkupfer** [comment] 2019-01-08 19:31
@etpinard: this filed bug looks very similar: https://bugzilla.mozilla.org/show_bug.cgi?id=1517458

Looks like there has been recent activity as well, but I'm not to savvy with bugzilla conventions so the last comment is greek to me.

**Comment by etpinard** [comment] 2019-01-08 19:39
Thanks very much @mbkupfer - that indeed looks like the same problem.

**Comment by mbkupfer** [comment] 2019-01-16 19:42
Looks like this was fixed! Should be making it into FF66. Based on their [wiki](https://wiki.mozilla.org/Releases/Firefox_66) this should be released 19 March 2019. 

The beta will be out 29 Jan 2019 so we can start testing around then, unless you want to build the nightly build yourself. I've done this before and it takes a looong time to setup the entire environment so might just wait till Beta is released.

**Comment by archmoj** [comment] 2019-02-27 01:05
Fixed in FireFox 65 & 66.
Closing.

**Closed by archmoj** 2019-02-27 01:05 UTC
Labels: type: bug
