### ISSUE TITLE
Double-click to reset uses previous x range, not new one

### ISSUE THREAD

**Issue by seansfkelley** [plotly/plotly.js#2957] opened 2018-08-30 18:36 UTC
When using `Plotly.react` to update a chart and change the X range, something seems to retain a reference to the old X range, because double-clicking to reset the range respects the old range, not the new.

### Repro

https://codepen.io/anon/pen/oPYRav?editors=0010#0

1. Double click the chart.

#### Actual

Chart zooms to [ 0, 2 ].

#### Expected

Chart zooms to [ -1, 3 ].

### Other 

For some reason, this only happens if `data` is present in `newPlot`. If you comment that line out, resetting doesn't work at all (unrelated bug?).

**Comment by fourgates** [comment] 2018-08-30 18:50
i thought that was a "feature" lol. I thought it was nice to revert back to the original range.

**Comment by etpinard** [comment] 2018-08-31 13:55
This looks like a duplicate of https://github.com/plotly/plotly.js/issues/2718

**Comment by seansfkelley** [comment] 2018-08-31 14:54
It's certainly at least related, though I'm not clear if it's a duplicate.

In #2718, the repro has different behaviors when you click the "reset axes" button versus double-clicking the X axis versus double-clicking the main plot area. I purposely didn't put any data in my example to keep the repo minimal, but perhaps it would be the same if I did?

That said, I'm using plotly through react-plotly, so I don't have the option to switch from `react` to `newPlot` or `relayout` as appears to be suggested in that ticket.

**Comment by etpinard** [comment] 2018-09-06 22:33
Thanks for the detailed report @seansfkelley 

From a plotly.js dev's perspective this ticket and #2718 are two manifestations of the same "less-than-ideal" behavior in plotly.js and bugging behavior in react-plotly.js.

Merging with #2718

**Closed by etpinard** 2018-09-06 22:33 UTC
