### ISSUE TITLE
invisible date bar

### ISSUE THREAD

**Issue by tjinaton** [plotly/plotly.js#3632] opened 2019-03-13 09:03 UTC
When i have bar-graph with date-axis and custom range specified the bar becomes invisible when there is only 1 bar. 

invisible bar: 
https://codepen.io/rtjin/pen/bZYJOp
2-bars:
https://codepen.io/rtjin/pen/oVoOJJ

Turns out the bar is very small. Which can be seen when the range becomes small.
Workaround: Set width on bar: 1 unit seems to be 1ms. 

It would be nice if the bar gets a better width.

**Comment by alexcjohnson** [comment] 2019-03-13 13:42
duplicate of #1346, feel free to weigh in over there. I doubt we'll change this behavior though - we could pick some other value but it would usually be wrong. I'd recommend setting `width` explicitly (yes, in milliseconds) https://codepen.io/alexcjohnson/pen/YgYqMW

**Closed by alexcjohnson** 2019-03-13 13:42 UTC
