### ISSUE TITLE
Investigate extreme data in all trace types

### ISSUE THREAD

**Issue by alexcjohnson** [plotly/plotly.js#2061] opened 2017-10-04 04:34 UTC
#2060 fixes display of scatter lines containing extreme-out-of-view data (#403). We should investigate whether other trace types that exist in an infinite plane / space can handle data like that. I suspect the others will all or nearly all be substantially easier to clean up than scatter lines, likely just by limiting the data-to-pixel conversions (which we can't do with scatter lines because we need to preserve angles).
- [ ] scatter markers + text
- [ ] bar/histogram
- [ ] box
- [ ] carpet
- [ ] heatmap/contour map
- [ ] all the gl3d types (see also #179)
- [ ] all the gl2d types

**Comment by etpinard** [comment] 2017-10-04 13:58
There's https://github.com/plotly/plotly.js/issues/551 for `scatter3d`.

**Comment by cpsievert** [comment] 2018-02-07 22:40
Here's an example of `box`'s `jitter` not working as intended when just one outlier exists (perhaps we could just ignore `jitter` in that case?

https://codepen.io/cpsievert/pen/KQNRWN
From https://github.com/ropensci/plotly/issues/1189

**Comment by madeleinemf** [comment] 2018-03-08 13:24
I have found that extremes in error bars on scatter plots cause the whole trace not to display (in both markers and lines mode). It seems to me to be a combination of a large value with a large error bar of a similar scale.

A simple example is:
`
var trace = {
  "mode": "markers",
  "type": "scatter",
"x":[1, 2, 3, 4],
"y":[20, 7e+20, // reduce this to 7e+10 and it will work
     30, 40],
  "error_y": {
    type: 'data',
    array: [5, 2e+20, // reduce this to 2e+10 and it will work (but not if y is at 7e+10 - this also fails! It works only if y is at 7e+20)
            6, 7]
  }

};
var data = [trace];

var layout = {
  yaxis: {
    //autorange: true,
    range: [0, 50]
  }
};

Plotly.newPlot('myDiv', data, layout);`

**Comment by madeleinemf** [comment] 2018-03-08 13:27
I have found that extremes in error bars on scatter plots cause the whole trace not to display (in both markers and lines mode). It seems to me to be a combination of a large value with a large error bar of a similar scale.

An example can be seen here:
[https://codepen.io/madeleinens/pen/JLjPWE](https://codepen.io/madeleinens/pen/JLjPWE)

**Comment by gvwilson** [comment] 2024-06-10 17:46
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson

**Closed by gvwilson** 2024-06-10 17:46 UTC
Labels: type: maintenance
