### ISSUE TITLE
Custom tick label alignment

### ISSUE THREAD

**Issue by alexcjohnson** [plotly/plotly.js#1882] opened 2017-07-14 15:36 UTC
It would be neat to allow tick labels to be dropped above or below gridlines (and left or right, for x axes) like in this Vox chart (as discussed in #1434):
![screen_shot_2015-01-14_at_11 34 49_am 0](https://cloud.githubusercontent.com/assets/2678795/23520569/925fd07a-ff49-11e6-89b0-a1247992a143.png)

**Comment by etpinard** [comment] 2017-07-14 18:26
Related:

- https://github.com/plotly/plotly.js/issues/1673
- https://github.com/plotly/plotly.js/issues/883
- https://github.com/plotly/plotly.js/issues/1137

**Comment by Braintelligence** [comment] 2019-01-21 13:50
Currently it looks like the "xanchor" of tick labels (doesn't matter if labels or boundaries) when turned around 90 degrees (due to insufficient space) is at the right of the tick labels. Resulting in this:
![grafik](https://user-images.githubusercontent.com/6761196/51478452-c0928c00-1d8b-11e9-8d9e-87c2a9b10a0d.png)
The second red line is where I would want the tick label to center to. How would I go about doing that?

**Comment by gvwilson** [comment] 2024-06-10 15:56
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson

**Closed by gvwilson** 2024-06-10 15:56 UTC
Labels: type: feature
