### ISSUE TITLE
Box Plot from Summary Statistics

### ISSUE THREAD

**Issue by kumarmsingh** [plotly/plotly.js#4073] opened 2019-07-23 11:29 UTC
My numerical data is huge, so I computed Summary Statistics in Apache Spark. Now, I just want to pass summary statistics (mean, standard deviation, min, q1, q2/median, q3, max) to plotly boxplot. I can see it creates labels like this in plotly.js 
`            labels: {
                med: _(gd, 'median:'),
                min: _(gd, 'min:'),
                q1: _(gd, 'q1:'),
                q3: _(gd, 'q3:'),
                max: _(gd, 'max:'),
                mean: trace.boxmean === 'sd' ? _(gd, 'mean ± σ:') : _(gd, 'mean:'),
                lf: _(gd, 'lower fence:'),
                uf: _(gd, 'upper fence:')
            }`
but don't know how to replace with my own summary statistics to create boxplot with mean and standard deviation. Please help.

**Comment by etpinard** [comment] 2019-07-23 13:45
duplicate of https://github.com/plotly/plotly.js/issues/1059

**Closed by etpinard** 2019-07-23 13:45 UTC

**Comment by kumarmsingh** [comment] 2019-07-23 13:48
It's not exactly duplicate of #1059, as, I wanted to also show mean & standard deviation (which can't be computed from quartiles). Its completely ok to add this ask in #1059.

**Comment by etpinard** [comment] 2019-07-23 14:00
I apologize @kumarmsingh I didn't mean to sound rude. But there's isn't much you can do at the moment before #1059 is implemented.
