### ISSUE TITLE
Uncaught error when user zoom (by mouse) or click on graph layer

### ISSUE THREAD

**Issue by skyandrd** [plotly/plotly.js#2438] opened 2018-03-05 10:06 UTC
Hello. A bug can be reproduced here https://codepen.io/skyandrd/pen/oERddp

When I click (or double click) on the graphics or select it with the mouse to zoom in, the browser console displays an error:
index.html:1 Uncaught (in promise) undefined
Promise.then (async)
update @ plotly-latest.js:127424

**Comment by etpinard** [comment] 2018-03-05 15:53
Hmm. I can't reproduce.

Could you share a videocast of the interactions that induce the uncaught error(s) to help us out?

**Comment by alexcjohnson** [comment] 2018-03-06 03:50
I see that error - draw a zoombox and hold it for a couple of seconds, such that a few of these `Plotly.update` calls happen from the `setTimeout`. It's an intentional `Promise.reject` [here](https://github.com/plotly/plotly.js/blob/3bff26f7ef21c8ca43122e86214d268f57b77418/src/plot_api/plot_api.js#L146) added way back in https://github.com/plotly/plotly.js/pull/226. We bail out of redrawing the plot at that point because there's an interaction ongoing, and I guess the returned `Promise` is rejected as a signal to the user that this happened. It's not clear to me that this is a problem though, or if it is a problem what the solution should look like.

**Comment by iMaximal** [comment] 2018-03-06 07:50
Same problem :-(

**Comment by skyandrd** [comment] 2018-03-06 08:12
@etpinard The screencast is attached [https://drive.google.com/open?id=1TEm_GefV4OXFsg8uvL_LlHayyaQLOodU](url)

**Comment by etpinard** [comment] 2018-03-06 15:26
Related https://github.com/plotly/plotly.js/issues/2382

**Comment by etpinard** [comment] 2018-12-03 20:59
Merged into https://github.com/plotly/plotly.js/issues/3305

**Closed by etpinard** 2018-12-03 20:59 UTC
