### ISSUE TITLE
Configurable color encoding of missing values

### ISSUE THREAD

**Issue by cpsievert** [plotly/plotly.js#3631] opened 2019-03-12 23:38 UTC
If `null` values are provided to a colorscale attribute (e.g., `color`/`z`), plotly.js uses gray for color encoding, for example:

https://codepen.io/cpsievert/pen/BbmYoQ
https://community.plot.ly/t/how-to-change-colors-for-na-values-to-gray-in-a-choropleth-map/15746/4

The problem is, there doesn't seem to be an official to control this in a way that is decoupled from `color`/`z` values themselves. Ideally, you would be able to control this from the `colorscale` definition, perhaps like this https://codepen.io/cpsievert/pen/xBPYZM

**Comment by alexcjohnson** [comment] 2019-03-13 00:54
Duplicate of #3035 / #975 where a separate attribute `nancolor` has been proposed

**Closed by alexcjohnson** 2019-03-13 00:54 UTC
