### ISSUE TITLE
Multiple Surface Plot traces result in plot crashing

### ISSUE THREAD

**Issue by 0x5e5e** [plotly/plotly.js#4112] opened 2019-08-08 01:19 UTC
Codepen:  https://codepen.io/0x5e5e/pen/qeoZNd

Hey plotly.js maintainers! 

I'm drawing multiple curved surfaces as part of a general 3D cone shape - see codepen above.

The codepen is only drawing 50 of the surfaces (see line 2710, feel free to have it try to load all the surfaces), I have about 300 in this case and up to 2-3k in others (number of data sections) - but whenever I try to load more than a certain amount (on my machine is 150, seems like it depends on how much RAM one has available) the plot just crashes which I'm assuming means it went out of memory.

The surface data is generated in python to use numpy functions, then embedded in the javascript.   I run into this same issue with the python plotly library as well.

**My question is** - is this normal/expected behavior based on the number of surface glyphs I have?  Is there any way I can optimize this so it uses less memory per surface plot so I can draw more without it crashing?  I'm fine without lighting if that helps at all.   If this is just a limitation of plotly's rendering I would love to try to optimize this in the code if pointed in the right direction.

I know drawing multiple surfaces might not be ideal as it could just be one single surface but I could not find a way to finagle `surfacecolor` to get it to achieve the same effect I have here (for each "bin" or section of data, it has a color based on a color range that is not the Z value - I tried to use surfacecolor but it was just one giant blended together soup of colors that looked different depending on what angle you were looking at it, instead of nice discrete sections).

**Comment by etpinard** [comment] 2019-08-14 13:20
Duplicate of https://community.plot.ly/t/multiple-surface-plots-crashing/26999

**Closed by etpinard** 2019-08-14 13:20 UTC
