### ISSUE TITLE
polar axis: some labels are slightly out of place

### ISSUE THREAD

**Issue by antoinerg** [plotly/plotly.js#3976] opened 2019-06-20 20:30 UTC
As @nicolaskruchten noticed, some labels can be slightly out of place in polar axes.

For example, this is the case for labels `45°` and `225°` in the following figure:
![newplot (93)](https://user-images.githubusercontent.com/301546/59879327-6fa5b480-9378-11e9-95c8-c94f5f23f4e3.png)

**Comment by gvwilson** [comment] 2024-06-14 12:02
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-14 12:02 UTC
Labels: type: bug
