### ISSUE TITLE
Feature Request - A Plotly wrapper for Vuejs

### ISSUE THREAD

**Issue by RaghunathHyd** [plotly/plotly.js#2691] opened 2018-06-03 12:27 UTC
Will be great if a plotly.js wrapper for Vuejs is made like its there for React with Vuejs now becoming a more popular Javascript framework.

https://github.com/plotly/react-plotly.js/blob/master/README.md

**Comment by chiaramdelucia** [comment] 2018-06-04 15:05
This one is pretty good https://github.com/statnett/vue-plotly if you're looking for something in the immediate.

**Comment by RaghunathHyd** [comment] 2018-06-04 15:10
Thanks. I tried it but its not very mature yet. Lots of bugs crop up when I use it. Wanted something from the plotly themselves like they did for the react.

**Comment by alexcjohnson** [comment] 2018-06-04 15:35
I'm afraid we don't have anyone with much Vue experience internally at Plotly, whereas we actively use React and have some in-house [Angular](https://github.com/plotly/angular-plotly.js) experience. So it would be difficult for us to create an "official" Vue wrapper and have much confidence in it. The [vue-plotly repo](https://github.com/statnett/vue-plotly) @chiaramdelucia pointed to is the most mature option I'm aware of at present. If you think it's a good start architecturally, I'd encourage you to contribute PRs or issues to improve it, perhaps using code from our official [React wrapper](https://github.com/plotly/react-plotly.js) as a point of comparison.

**Comment by chiaramdelucia** [comment] 2018-06-07 13:34
@RaghunathHyd, I'd love if you opened up some issues of bugs over on that repo. I have been using a version of that (I use the render function instead of a template) and have not had any bugs yet. So, I'd definitely love to hear what the possibilities of bugs are, but I don't want to clog up this repo. TIA!

**Comment by tetreault** [comment] 2018-12-06 21:32
+1

simply importing plotly breaks nuxt

**Comment by alexcjohnson** [comment] 2018-12-06 22:02
Correct me if I'm wrong (again, we have very little in-house Vue experience) but it looks like Nuxt is largely focused on server-side rendering, and I suspect that's why plotly.js is breaking it - we do a lot of things that require a real DOM, most fundamentally perhaps measuring text since it's on us, not the HTML layout engine, to position it correctly. See https://community.plot.ly/t/how-to-perform-server-side-manipulation-using-plotly-js/1077

**Comment by tetreault** [comment] 2018-12-06 22:37
In my case i generate static files from a nuxt site using the `generate` command, but thanks for the reply @alexcjohnson appreciate it!

**Comment by antoinerg** [comment] 2018-12-07 19:24
@tetreault See the following link https://nuxtjs.org/guide/plugins/#client-side-only to use client-side only plugins in nuxt. Also, the `<no-ssr>` might be useful (https://nuxtjs.org/api/components-no-ssr/)! I hope that helps :)

**Comment by antoinerg** [comment] 2018-12-08 18:38
On second thoughts, server-side rendering could be supported in Nuxt.js by leveraging [Orca](https://github.com/plotly/orca) as long as interactive figures are not necessary. Nuxt.js would simply make a call to Orca to produce an SVG server-side to be included on the page. If the client supports javascript, interactivity could be added once the page is loaded by using Plotly.js the usual way.

**Comment by gvwilson** [comment] 2024-06-11 17:09
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson

**Closed by gvwilson** 2024-06-11 17:09 UTC
