### ISSUE TITLE
Boxes get skinnier in a grouped boxplot with subplots

### ISSUE THREAD

**Issue by kei51e** [plotly/plotly.js#3830] opened 2019-05-02 23:19 UTC
Boxes get skinnier in grouped boxplot with subplots. Looks like boxes share the same X axis for the box width calculations.  

https://codepen.io/kei51/pen/VNoQEg

![image](https://user-images.githubusercontent.com/68080/57112282-334cc500-6cf4-11e9-8a2d-7036b4e10121.png)

In a  bar chart with the same configuration, it works as I expected. 

https://codepen.io/kei51/pen/xMdQoX

![image](https://user-images.githubusercontent.com/68080/57112315-4eb7d000-6cf4-11e9-8e98-c32496184d25.png)

I can see the same problem on Violin plot too. 

https://codepen.io/kei51/pen/qgmQgV

![image](https://user-images.githubusercontent.com/68080/57112426-c685fa80-6cf4-11e9-8eef-401f57c6704d.png)

**Comment by etpinard** [comment] 2019-05-03 13:59
This is essentially the same inconsistency as discussed in https://github.com/plotly/plotly.js/issues/3502

You can work around it using `offsetgroup`:

https://codepen.io/etpinard/pen/mYbevE?editors=0010

**Comment by etpinard** [comment] 2019-05-03 14:00
For more info:

- https://github.com/plotly/plotly.js/issues/3402
- https://github.com/plotly/plotly.js/pull/3529

**Comment by etpinard** [comment] 2019-05-06 15:31
Marking this one as duplicate of https://github.com/plotly/plotly.js/issues/3502

**Closed by etpinard** 2019-05-06 15:31 UTC

**Comment by kei51e** [comment] 2019-05-08 21:53
Thanks for the info!
