### ISSUE TITLE
Line colorscale on scatter graph

### ISSUE THREAD

**Issue by MonsieurV** [plotly/plotly.js#581] opened 2016-05-30 04:16 UTC
Hello,

I can't make work the [marker.line.colorscale](https://plot.ly/javascript/reference/#scatter-marker-line-color) property. I'm not sure how it should work, but what I can say is:
- using the `colorscale` property on lines as it is used on [markers](http://codepen.io/etpinard/pen/zqqeBJ) has [no effect](http://codepen.io/anon/pen/jrOKvY)
- if we use the property on a scatter graph with both lines and markers we have [a bug](http://codepen.io/anon/pen/aZbKPx) (or I'm not using it properly?)

So is it possible to color a line following a colorscale on a scatter graph? How we do it?

Moreover the documentation is confusing, as it states the property line is under the mark one:

> Sets the colorscale and only has an effect if `marker.line.color` is set to a numerical array.

Actually it seems not to be the case: http://codepen.io/anon/pen/OXJErp. Should the documentation states `line.color` instead?

I can do a PR to fix the doc, but I want to be sure I'm not misleading first.

**Comment by MonsieurV** [comment] 2016-05-30 04:21
Seems like the feature was already suggested in #147 [see](https://github.com/plotly/plotly.js/issues/147#issuecomment-194046036)

**Comment by etpinard** [comment] 2016-05-30 15:20
Thanks for the very detailed issue.

In plotly.js, attributes under `marker.line` describe the marker points' bordering line styling (example [here](http://codepen.io/etpinard/pen/WxNPrG?)) and have **no effect** on a `scatter` trace's line segments.

At the moment, scatter `line` attributes do not support color scales nor per-data-point style setting (as mentioned in https://github.com/plotly/plotly.js/issues/147). In other words, there is no way to apply a colour gradient to a plotly.js line chart.

Adding color scale support to line charts (possibly using svg [gradient](https://developer.mozilla.org/en-US/docs/Web/SVG/Tutorial/Gradients)) would be a great addition.

**Comment by etpinard** [comment] 2016-05-30 19:29
We should also add this feature for `scatter3d` traces e.g. 

![image](https://cloud.githubusercontent.com/assets/6675409/15657008/0685b544-267b-11e6-9a3b-7918653e1fbc.png)

from [here](http://docs.enthought.com/mayavi/mayavi/building_applications.html).

**Comment by etpinard** [comment] 2016-05-30 19:48
Assigning the `scatter3d` part to @monfera

**Comment by monfera** [comment] 2016-06-02 19:41
A comment about SVG (note: no plotly support at the moment) which underlies the regular plots that don't use WebGL:

- It is possible to do gradient coloring for anything that uses the `<line>` tag
- It is  possible to draw a polyline out of multiple `<line>` tags, with the caveat that the miters would have to be handled, i.e. a `<polyline>` or equivalent `<path>` tag with `lineTo` segments, containing N line sections will map to 2*N DOM elements (a `<line>` and a two-section `<polyline>` for each). If the line width is no more than 1px, then the miters can be omitted. The benefit with a separate DOM element for each line section is that the thickness can also be varied; in this case, we'd need to use a thin, long quadrilateral `<polygon>` rather than a `<line>` for each line section.
- For other shapes, it is also possible to do gradient coloring along the X or Y axis, or any other direction on the projection plane, for the *entire* shape only; i.e. the metric that determines where we are in the gradient is the specific direction vector (e.g. horizontal) rather than the running length of the shape.

There are techniques for gradient coloring (or similarly, varying thickness) for general SVG curves along their running length, but they involve the slicing of the original curve, as [this example does.](https://bl.ocks.org/mbostock/4163057)

**Comment by timelyportfolio** [comment] 2016-06-02 19:46
@monfera, perhaps related http://bl.ocks.org/pbeshai/ffd0f9d84b4e8df27db2

**Comment by monfera** [comment] 2016-06-02 19:52
@timelyportfolio these things look fantastic, and they show width variation too! The gradients are implemented as in the third point, i.e. the whole path has one gradient vector (example defaults to horizontal), which works as the trace points are in a strictly monotonic order when projected to the given gradient vector.

**Comment by monfera** [comment] 2016-06-02 20:00
The SVG gradient technique is suitable not only for actual gradients, but discontinuous steps at arbitrary points with arbitrary colors just by specifying a new color at the same stop value, see it e.g. here: http://codepen.io/monfera/pen/JKoVvJ?editors=1000

**Comment by monfera** [comment] 2016-06-03 09:53
WebGL: most shaders do color interpolation; it is also the case with our underlying `gl-line3d` ([see new example](https://github.com/gl-vis/gl-line3d/pull/3)). We need to properly expose it.

**Comment by monfera** [comment] 2016-06-15 19:24
Clarification: the current line color gradient, and colorscale specification for the markers and connecting lines are required to be implemented initially for `scatter3d` only, i.e. other types, SVG based `scatter` in particular are not currently in the making, in part due to the inherent complexities present with SVG paths.

**Comment by NJannasch** [comment] 2016-10-11 09:08
Any news on color scales or per-data-point style setting?
Unfortunately scatter3d do not fit my needs - is it possible to transform a 3d graphic into a 2d projection?

**Comment by monfera** [comment] 2016-10-11 10:22
@NJannasch the `scatter3d` part has been merged: https://github.com/plotly/plotly.js/pull/617 but I don't think anybody was assigned to or took on a 2D equivalent. It's possible to set the 3D `camera` such that you get an orthographic projection, and you can disable the axis ticks perpendicular to the screen surface, as well as controls (e.g. rotations) that are there for 3D navigation. Here's a [fork](http://codepen.io/monfera/pen/KMmPPV) of an example from @etpinard that uses camera controls.

**Comment by HaleKonopka** [comment] 2017-03-13 22:18
Is there any plan for future work to address this issue of adding colorscale functionality to Scatter (in 2D) with lines alone?

**Comment by kanchannmahajan** [comment] 2017-04-11 07:47
@monfera I am trying to workaround this for 2d graphs
I have managed to get the correct camera angle 
can you please be so kind to tell how to disable 3D axis and rotation  --

> you can disable the axis ticks perpendicular to the screen surface as well as controls (e.g. rotations)
Thanks

**Comment by monfera** [comment] 2018-01-18 10:42
@kanchannmahajan you can hide the entire modebar with https://codepen.io/plotly/pen/YyGOLg and the general doc for these is [here](https://plot.ly/javascript/configuration-options/). You can also [hide specific buttons](https://codepen.io/etpinard/pen/gLoNgR) on the modebar. There's also the `dragmode` property that, in the case of `scatter3d`, lets you specify `"turntable"`, `"orbit"` or, to disable dragging, `false`: https://codepen.io/anon/pen/ypQpPV

The combination of these with an axis-aligned ortographic projection, I believe, permit some kind of pseudo-2D view, but there might be gotchas.

**Comment by monfera** [comment] 2018-01-18 10:45
@etpinard I've self-unassigned as my [assignment](https://github.com/plotly/plotly.js/issues/581#issuecomment-222546535) was for the `scatter3d` part, done long ago.

**Comment by acharyatilak** [comment] 2018-10-27 17:39
Any update on adding colorscale functionality to Scatter (in 2D) ?

**Comment by brockelmore** [comment] 2018-10-28 20:57
Hard to believe this has remained open for 2.5 years. What is the main hold up? This seems like a core function to graphing. I've been messing around with trying to alter via d3 but it is an extreme pain.

**Comment by monfera** [comment] 2018-10-28 23:15
Not all data visualization packages have this feature, and my completely uninformed guess would be that there hasn't been strong demand for this specific function on client projects so far. On the off chance it's useful for covering this or larger functional gaps, Plotly has a [page](https://plot.ly/products/consulting-and-oem/) where users can directly engage in feature work, or alternatively, PR suggestions can be discussed and then implemented, there are several features that were added in large part by users.

**Comment by brockelmore** [comment] 2018-10-29 12:39
Sorry if I came off rude - just seems like a lot of other projects, Chart.js, Highcharts, etc. have this functionality. I view color gradients and line width as third and fourth dimensions without the complications of actually being in that high dimensionality. And it seems like there are a ton of applications for it so I am just surprised. I don't have $15,000 to spend on this feature, I work with a tiny startup currently

**Comment by alexcjohnson** [comment] 2018-10-29 14:20
@brockelmore as you alluded to above, this *is* an extreme pain with D3 - ie SVG. There are straightforward solutions for a few cases, like a color gradient that's purely a function of x or y coordinate, but of course this doesn't add any new information to the chart, it's purely aesthetic. Beyond these cases we would need to specify lines as filled paths, rather than stroked lines, which is both annoying to compute (at least for splines) and prone to antialiasing problems where separate paths meet. I suspect for the most general case there is actually no solution we'd be completely happy with in SVG.

But in WebGL it's manageable, which is why line color gradients were added to `scatter3d` a long time ago. Now that `scattergl` is nearly up to par with (SVG) `scatter`, I would propose adding it there and saying "if you want line color and width gradients, use `scattergl`."

**Comment by etpinard** [comment] 2018-10-29 14:22
> I would propose adding it there and saying "if you want line color and width gradients, use `scattergl`."

I'm a big fan of this proposed solution :ok_hand:

**Comment by brockelmore** [comment] 2018-10-29 14:36
Sounds great, I am going to stick around plotly and hopefully learn the systems and contribute when I can. For the record, "purely aesthetic" is an entirely valid reason to add a feature, especially when visualization is the core functionality of the project!

**Comment by gullpavon** [comment] 2020-04-28 18:40
If one were to want to display a gradient line on a line chart (purely for aesthetics purposes) , is that possible?

**Comment by archmoj** [comment] 2020-08-31 01:53
> @brockelmore as you alluded to above, this _is_ an extreme pain with D3 - ie SVG. There are straightforward solutions for a few cases, like a color gradient that's purely a function of x or y coordinate, but of course this doesn't add any new information to the chart, it's purely aesthetic. Beyond these cases we would need to specify lines as filled paths, rather than stroked lines, which is both annoying to compute (at least for splines) and prone to antialiasing problems where separate paths meet. I suspect for the most general case there is actually no solution we'd be completely happy with in SVG.
> 
> But in WebGL it's manageable, which is why line color gradients were added to `scatter3d` a long time ago. Now that `scattergl` is nearly up to par with (SVG) `scatter`, I would propose adding it there and saying "if you want line color and width gradients, use `scattergl`."

@alexcjohnson should we rename the issue title to include `scattergl` instead of `scatter`?

**Comment by jackparmer** [comment] 2020-09-10 19:04
This issue has been tagged with `NEEDS SPON$OR`

A [community PR](https://github.com/plotly/plotly.js/pulls?q=is%3Apr+is%3Aopen+label%3A%22type%3A+community%22) for this feature would certainly be welcome, but our experience is deeper features like this are difficult to complete without the Plotly maintainers leading the effort.

**Sponsorship range: $10k-$15k**

What Sponsorship includes:
- Completion of this feature to the Sponsor's satisfaction, in a manner coherent with the rest of the Plotly.js library and API
- Tests for this feature
- Long-term support (continued support of this feature in the latest version of Plotly.js)
- Documentation at [plotly.com/javascript](https://plotly.com/javascript/)
- Possibility of integrating this feature with Plotly Graphing Libraries (Python, R, F#, Julia, MATLAB, etc)
- Possibility of integrating this feature with Dash
- Feature announcement on [community.plotly.com](https://community.plotly.com/tag/announcements) with shout out to Sponsor (or can remain anonymous)
- Gratification of advancing the world's most downloaded, interactive scientific graphing libraries (>50M downloads across supported languages)

Please include the link to this issue when [contacting us](https://plotly.com/get-pricing/) to discuss.

**Comment by alexlenail** [comment] 2021-06-10 17:43
Just here to note that I'd love to see this feature available in 2D.

**Comment by gvwilson** [comment] 2024-06-05 16:53
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson

**Closed by gvwilson** 2024-06-05 16:53 UTC
Labels: type: feature, ♥ NEEDS SPON$OR
