### ISSUE TITLE
Axis `tickformat` overrides `exponentformat` settings

### ISSUE THREAD

**Issue by suribabu39** [plotly/plotly.js#1651] opened 2017-05-08 10:02 UTC
Hi,
I am getting 'G' as suffix for y axis ticks if I use tickFormat, if I don't use tickFormat then it would show it with suffix 'B'. As y axis ticks are numbers I would like to show them with 'B' (with Million, Billion, Trillion formatting).
[Codepen link1](http://codepen.io/etpinard/pen/dvBXYR?editors=0010)
Is there a way to show that way? Should I change tickFormat?
I have also tried using exponentformat, but still I am not getting ticks in Billions format.
[Codepen link2](https://codepen.io/suribabu_95/pen/zwdQXK)
Thanks in advance,

**Comment by etpinard** [comment] 2017-05-08 14:39
maybe related to https://github.com/plotly/plotly.js/issues/1264

**Comment by alexander-alvarez** [comment] 2017-07-10 19:56
I just got bit by this too. 

It's related to https://github.com/plotly/plotly.js/blob/master/src/plots/cartesian/axes.js#L1375

@etpinard what's the desired behavior? If so we should fixup or document.

D3 does not provide a numeric type  (`a`) like [numeral.js](http://numeraljs.com/#format-currency) does.
https://github.com/d3/d3-format/blob/master/README.md#locale_format
so while semi related to #1264 I'm not sure you can fix it with just the locale.

Removing my `tickformat` all together, and then adding `tickprefix: '$'` worked in my case, but not ideal since I'd have to manually manage tickprefix so it's aligned with the locale

**Comment by alexander-alvarez** [comment] 2017-07-10 20:06
as an aside, I'm not seeing where the format functions use locales. Am I missing something?

**Comment by etpinard** [comment] 2017-07-17 17:47
> as an aside, I'm not seeing where the format functions use locales. Am I missing something?

That's correct, we don't use `d3` locales anywhere in our code yet. You're correct, #1264 is a different problem, where `layout.separators` settings are overrode by `tickformat`.

@alexander-alvarez Thanks for digging around `axes.js`. Sounds like we'll need to partially reformat the output of `d3.format` instead of simply [returning](https://github.com/plotly/plotly.js/blob/700c0888f91d097a51968b4c3f245efaf0ff9108/src/plots/cartesian/axes.js#L1377) it.

**Comment by gvwilson** [comment] 2024-06-10 14:06
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson

**Closed by gvwilson** 2024-06-10 14:06 UTC
Labels: type: bug
