### ISSUE TITLE
Cannot rotate or zoom on gl3D plot while animating

### ISSUE THREAD

**Issue by emimoun** [plotly/plotly.js#3759] opened 2019-04-11 13:50 UTC
It is illustrated by this [example](https://codepen.io/anon/pen/ZZKRvr). One has to wait for the animation to finish to recover the ability to rotate or zoom with mouse interaction (hover works fine). Is this something that can be changed or is it intended?

**Comment by etpinard** [comment] 2019-04-11 13:59
Duplicate of https://github.com/plotly/plotly.js/issues/2039, but let's use this ticket as it has a nice example codepen.

**Comment by etpinard** [comment] 2019-04-11 14:00
Most likely, a _fix_ for this issue will come during the gl3d regl rewrite (cc https://github.com/plotly/plotly.js/issues/949) cc @archmoj

**Comment by gvwilson** [comment] 2024-06-14 11:55
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-14 11:55 UTC
Labels: type: feature
