### ISSUE TITLE
Bar text font-size can be different across bars which can look wonky on mobile

### ISSUE THREAD

**Issue by chriddyp** [plotly/plotly.js#2180] opened 2017-11-22 23:25 UTC
(Pulling this one out of the community forum: https://community.plot.ly/t/insidetext-font-size-is-variable-on-mobile/6876) It looks like we shrink the bar font-size in order for it to fit the bar. If the numbers inside the bars have a variable number of digits, then the fonts can be different sizes which can look kind of wonky on mobile devices

![image](https://user-images.githubusercontent.com/1280389/33153861-78d935c6-cfb2-11e7-8c5d-3c9990ae6c87.png)
![image](https://user-images.githubusercontent.com/1280389/33153863-7bb0c08e-cfb2-11e7-9888-aebe732ad687.png)
![bar-chart-variable-font-size](https://user-images.githubusercontent.com/1280389/33153866-80b392dc-cfb2-11e7-80e1-397c75354035.gif)

**Comment by radumas** [comment] 2017-11-23 21:33
Certainly depends on user preference I guess. I personally wouldn't want the numbers to rotate 90 degrees either without me explicitly enabling this. I guess the ask is for an additional option under `font` for fixing orientation and fontsize.

I didn't test for other text elements on graphs, would this also apply to tick labels?

**Comment by alexcjohnson** [comment] 2017-11-27 18:23
True, the question then is what to do instead?
- Allow these labels to overflow the bar?
- Don't show labels we would have to shrink?
- Shrink *all* labels to the same font size?

I suppose this should in principle be configurable (along with whether or not to allow rotation to minimize shrinkage), the question is just which options would be most useful and how to encode them. @radumas tick labels already have quite a bit of configurability - they will at times rotate unless you ask them not to, but they will never alter the font size. If you find anything missing there after playing with it feel free to make a new issue.

**Comment by 0anton** [comment] 2019-02-20 07:15
Moreover, setting font desired font size for one trace (because it is too small to read due to automatic font fitting the bar width) affects only the first trace, weather the remaining traces still got tiny automatic font: 

```
[Bar({
     'hoverinfo': 'y',
     'name': 'SSUITE',
     'outsidetextfont': {'size': 20},
     'text': array([   9.,  501.,    6.,   11.,  578.,    5.,   10.,  855.,   16.,    9.,
                    1176.,   41.,   18., 1236.]),
     'textposition': 'outside',
     'x': array([datetime.datetime(2018, 1, 31, 0, 0),
                        datetime.datetime(2019, 1, 31, 0, 0),
                 datetime.datetime(2019, 2, 28, 0, 0)], dtype=object),
     'y': array([   9,  501,    6,   11,  578,    5,   10,  855,   16,    9, 1176,   41,
                   18, 1236], dtype=int64)
 }), Bar({
     'hoverinfo': 'y',
     'name': 'IBP',
     'outsidetextfont': {'size': 20},
     'text': array([ 45., 343., 318.,  44., 524., 300.,  40., 759., 145.,  50., 935., 151.,
                     53., 681.]),
     'textposition': 'outside',
     'x': array([datetime.datetime(2018, 1, 31, 0, 0),
                         datetime.datetime(2019, 2, 28, 0, 0)], dtype=object),
     'y': array([ 45, 343, 318,  44, 524, 300,  40, 759, 145,  50, 935, 151,  53, 681],
                dtype=int64)
 }), Bar({
     'hoverinfo': 'y',
     'name': 'NW/CLOUD',
     'outsidetextfont': {'size': 20},
     'text': array([1.]),
     'textposition': 'outside',
     'x': array([datetime.datetime(2018, 7, 31, 0, 0)], dtype=object),
     'y': array([1], dtype=int64)
 }), Bar({
     'hoverinfo': 'y',
     'name': 'NW/BW4CLOUD',
     'outsidetextfont': {'size': 20},
     'text': array([2., 2., 3.]),
     'textposition': 'outside',
     'x': array([datetime.datetime(2018, 11, 30, 0, 0),
                 datetime.datetime(2018, 12, 31, 0, 0),
                 datetime.datetime(2019, 1, 31, 0, 0)], dtype=object),
     'y': array([2, 2, 3], dtype=int64)
 })]

```
![image](https://user-images.githubusercontent.com/17309924/53073218-ae6d5000-34e7-11e9-8b2c-e9393509cf1a.png)

**Comment by gvwilson** [comment] 2024-06-10 21:03
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson

**Closed by gvwilson** 2024-06-10 21:03 UTC
Labels: type: feature, status: discussion needed
