### ISSUE TITLE
Bar text font-size applies only for the first trace

### ISSUE THREAD

**Issue by 0anton** [plotly/plotly.js#3557] opened 2019-02-20 07:31 UTC
Seeing strange behavior with the latest version of plotly python package ('3.6.1'):
font specification for outside text is applied only to the first trace.
Expected: all traces follow the font label specification.
This example is run in Jupyter environment with the following import block:

```
import plotly.plotly as py
import plotly.graph_objs as go
from plotly.offline import iplot, init_notebook_mode
init_notebook_mode(connected=True)

```

```
[Bar({
     'hoverinfo': 'y',
     'name': 'SSUITE',
     'outsidetextfont': {'size': 20},
     'text': array([   9.,  501.,    6.,   11.,  578.,    5.,   10.,  855.,   16.,    9.,
                    1176.,   41.,   18., 1236.]),
     'textposition': 'outside',
     'x': array([datetime.datetime(2018, 1, 31, 0, 0),
                 datetime.datetime(2018, 2, 28, 0, 0),
                 datetime.datetime(2018, 3, 31, 0, 0),
                 datetime.datetime(2018, 4, 30, 0, 0),
                 datetime.datetime(2018, 5, 31, 0, 0),
                 datetime.datetime(2018, 6, 30, 0, 0),
                 datetime.datetime(2018, 7, 31, 0, 0),
                 datetime.datetime(2018, 8, 31, 0, 0),
                 datetime.datetime(2018, 9, 30, 0, 0),
                 datetime.datetime(2018, 10, 31, 0, 0),
                 datetime.datetime(2018, 11, 30, 0, 0),
                 datetime.datetime(2018, 12, 31, 0, 0),
                 datetime.datetime(2019, 1, 31, 0, 0),
                 datetime.datetime(2019, 2, 28, 0, 0)], dtype=object),
     'y': array([   9,  501,    6,   11,  578,    5,   10,  855,   16,    9, 1176,   41,
                   18, 1236], dtype=int64)
 }), Bar({
     'hoverinfo': 'y',
     'name': 'IBP',
     'outsidetextfont': {'size': 20},
     'text': array([ 45., 343., 318.,  44., 524., 300.,  40., 759., 145.,  50., 935., 151.,
                     53., 681.]),
     'textposition': 'outside',
     'x': array([datetime.datetime(2018, 1, 31, 0, 0),
                 datetime.datetime(2018, 2, 28, 0, 0),
                 datetime.datetime(2018, 3, 31, 0, 0),
                 datetime.datetime(2018, 4, 30, 0, 0),
                 datetime.datetime(2018, 5, 31, 0, 0),
                 datetime.datetime(2018, 6, 30, 0, 0),
                 datetime.datetime(2018, 7, 31, 0, 0),
                 datetime.datetime(2018, 8, 31, 0, 0),
                 datetime.datetime(2018, 9, 30, 0, 0),
                 datetime.datetime(2018, 10, 31, 0, 0),
                 datetime.datetime(2018, 11, 30, 0, 0),
                 datetime.datetime(2018, 12, 31, 0, 0),
                 datetime.datetime(2019, 1, 31, 0, 0),
                 datetime.datetime(2019, 2, 28, 0, 0)], dtype=object),
     'y': array([ 45, 343, 318,  44, 524, 300,  40, 759, 145,  50, 935, 151,  53, 681],
                dtype=int64)
 }), Bar({
     'hoverinfo': 'y',
     'name': 'NW/CLOUD',
     'outsidetextfont': {'size': 20},
     'text': array([1.]),
     'textposition': 'outside',
     'x': array([datetime.datetime(2018, 7, 31, 0, 0)], dtype=object),
     'y': array([1], dtype=int64)
 }), Bar({
     'hoverinfo': 'y',
     'name': 'NW/BW4CLOUD',
     'outsidetextfont': {'size': 20},
     'text': array([2., 2., 3.]),
     'textposition': 'outside',
     'x': array([datetime.datetime(2018, 11, 30, 0, 0),
                 datetime.datetime(2018, 12, 31, 0, 0),
                 datetime.datetime(2019, 1, 31, 0, 0)], dtype=object),
     'y': array([2, 2, 3], dtype=int64)
 })]

Layout({
    'title': {'text': 'Chart 2. Total number of cloud upgrades per month and product'},
    'xaxis': {'title': {'text': 'Time'}},
    'yaxis': {'title': {'text': 'Count'}}
})
```

```
import plotly
plotly.__version__
'3.6.1'
```

![image](https://user-images.githubusercontent.com/17309924/53073386-2f2c4c00-34e8-11e9-92b0-eb82f8a8e696.png)

This is possibly related to #2180

**Comment by etpinard** [comment] 2019-02-20 15:52
In a codepen: https://codepen.io/etpinard/pen/YBMZoq

This is essentially a duplicate of https://github.com/plotly/plotly.js/issues/2180 - where we currently does allow text to overflow past the bars' positional span. 

For example, the 2nd text of node of the second trace (in orange) in your example is drawn as:

```svg
<text class="bartext bartext-outside" transform="translate(42.99353652861796 195.08738017682643)scale(0.18315495579339244) " text-anchor="middle" data-notex="1" data-unformatted="343" data-math="N" x="0" y="0" style="font-family: &quot;Open Sans&quot;, verdana, arial, sans-serif; font-size: 20px; fill: rgb(68, 68, 68); fill-opacity: 1; white-space: pre;">343</text>
```

where `font-size` is properly, but appears (much) smaller due to the `scale` transform.

**Closed by etpinard** 2019-02-20 15:52 UTC

**Comment by 0anton** [comment] 2019-02-21 10:27
Hi Etienne,

Thank you for promptly checking that and creating the codepen repro, which I could not do.
Great that you could confirm that the font specification is correctly passed to the Java Script.
I understand your point that by current implementation that is an expected visual result.
But don't you think that visual defect is still a defect, even then the attributes traverse the application levels correctly?
I never saw these different font size labeling in any other graphing tools, to name Excel, SPSS, Matplotlib. All named use constant and consistent font size for labels.
Should it in this aspect addressed as a visual bug?

Kind regards,
Anton Golubev
