### ISSUE TITLE
Parallel coordinate plot not working in Firefox on a Mac

### ISSUE THREAD

**Issue by samzer** [plotly/plotly.js#3433] opened 2019-01-13 10:30 UTC
When a constraint range is selected, the lines within the constraint range do not get highlighted and when clicking on the contraint range, all the lines vanish. These happens to the plots on plotly website - https://plot.ly/javascript/parallel-coordinates-plot/

The parallel coorindate plot works on chrome but not on firefox in a mac system. I checked with a friend who has similar machine and the same issue persists there too. However, the plot works on firefox in a windows system.

Following are my software versions
Firefox: 64.0.2
macOs:  High Sierra 10.13.4

Attaching a gif showcasing the issue. 
![plotly](https://user-images.githubusercontent.com/1539703/51084224-2f4c6580-174c-11e9-994a-4aa743339292.gif)

**Comment by etpinard** [comment] 2019-01-14 14:13
Probably a duplicate of https://github.com/plotly/plotly.js/issues/3385

Thanks for reporting.

**Closed by etpinard** 2019-01-14 14:13 UTC
