### ISSUE TITLE
Bad data in contour x/y throws errors

### ISSUE THREAD

**Issue by rreusser** [plotly/plotly.js#1566] opened 2017-04-07 18:59 UTC
See: http://codepen.io/rsreusser/pen/xqorGO?editors=0010

Basically, if the `x` array is short, it gets extended. But if it has a string or `null` for one of the entries, it propagates through and causes a lot of d3 errors down the road. `x` and `y` should be checked and filled in with missing values.

I've made a function (for carpet but currently unused) [here](https://github.com/plotly/plotly.js/blob/7ac5f42f163388581259c3b29f3ae0492fb2d725/src/traces/carpet/smooth_fill_array.js) that both fills in missing values and extrapolates as needed. I plan to change it to return false if there's simply no data in the array.

**Comment by alexcjohnson** [comment] 2017-04-11 04:33
Nice find! I think I like that function, though I'm a little worried it's too magical and will cause people to misinterpret their data. Perhaps we should mask out the `z` data that goes with the bad `x` or `y` values, since we don't in fact know where to put it?

If we do end up using this function (even with masking, we need to know where to put the blanked points!), two thoughts:
- this is mutating the array; I guess that means as soon as we determine it needs filling in it should be copied?
- should this also handle fixing the length, if the authority on what length is required is a different array (`z` for example)?

**Comment by rreusser** [comment] 2017-04-11 16:04
True. Perhaps it's not so generally useful. For carpet the 2D version is necessary because points have to go *somewhere*. They can be masked, but things will blow up if they're not still reasonable numbers.

**Comment by gvwilson** [comment] 2024-06-10 14:04
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson

**Closed by gvwilson** 2024-06-10 14:04 UTC
Labels: type: bug
