### ISSUE TITLE
Horizontal legend does not wrap when legend group is assigned

### ISSUE THREAD

**Issue by jzthree** [plotly/plotly.js#2497] opened 2018-03-25 01:29 UTC
When legendgroup is assigned, all trace names are shown on the same line and cutoff when it is too long. This is an example to reproduce it: https://codepen.io/jzthree/pen/wmqOpj

**Comment by etpinard** [comment] 2018-03-26 13:01
duplicate of https://github.com/plotly/plotly.js/issues/1913

**Closed by etpinard** 2018-03-26 13:01 UTC
