### ISSUE TITLE
Single-datum bar trace with specified time range not showing

### ISSUE THREAD

**Issue by henryzhao95** [plotly/plotly.js#1346] opened 2017-01-31 00:35 UTC
For a bar chart with time on the x axis, only one data point, and a specified x axis range in the layout options, the chart does not display.

After a second data point is added, the chart displays as normal.

http://codepen.io/anon/pen/GryLNg

**Comment by n-riesco** [comment] 2017-01-31 09:09
I've had a quick look at this issue and I've noticed that:
-  Plotly v1.19.2 and earlier shows a bar but ignores `layout.xaxis.range`
-  Plotly v1.20.0 and above doesn't show a bar but it honours `layout.xaxis.range`

This would point towards #1142. I'm not sure how. Anyhow, I'm guessing this issue is caused by the binning algorithm (that only uses `data[0].x` to compute the bin size).

**Comment by etpinard** [comment] 2017-01-31 16:12
Thanks for the report @henryzhao95 !

**Comment by etpinard** [comment] 2017-02-08 21:39
This bug could also a side-effect of the _dates as dates_ push in https://github.com/plotly/plotly.js/pull/1078

**Comment by etpinard** [comment] 2017-02-20 19:50
After a closer inspection, the bar in http://codepen.io/anon/pen/GryLNg fails to render because the bar plot step thinks that it has zero width [here](http://codepen.io/anon/pen/GryLNg) where `x0 === x1`.

By removing the set xaxis range value, we get:

![image](https://cloud.githubusercontent.com/assets/6675409/23139483/93c41f1a-f77a-11e6-8f82-5c83e0cbd27f.png)

which is a bar of 0.8 of a millisecond - which is arguably not a very good default on date axes.

@henryzhao95 by manually setting the bar width, you can archive a better-looking result, see http://codepen.io/etpinard/pen/XpLvWv

----

Perhaps we should make the default bar width for single-datum traces fixed in pixel space?

Referencing https://github.com/plotly/plotly.js/issues/1229 which also highlight a few inconsitencies in single-datum bar traces.

**Comment by etpinard** [comment] 2019-07-25 13:20
A couple more examples of the problem:

- https://jsfiddle.net/mo65wevq/
- https://codepen.io/rtjin/pen/bZYJOp
- http://codepen.io/anon/pen/rjWoyY

**Comment by etpinard** [comment] 2019-07-25 14:30
Similar to https://github.com/plotly/plotly.js/issues/1181

**Comment by gvwilson** [comment] 2024-06-06 15:15
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson

**Closed by gvwilson** 2024-06-06 15:15 UTC
Labels: type: bug
