### ISSUE TITLE
no rangeslider in financial chart subplots

### ISSUE THREAD

**Issue by VeraZab** [plotly/plotly.js#1326] opened 2017-01-23 21:11 UTC
http://codepen.io/veraz/pen/RKgRVR
I would have expected both plots to have rangesliders...

**Comment by rreusser** [comment] 2017-01-23 21:47
I wasn't able to get a range slider to show up for anything that's not `xaxis`/`yaxis`.

**Comment by jackparmer** [comment] 2017-01-23 23:01
I imported these 3M stock prices from Quandl:

https://www.quandl.com/data/EOD/MMM-3M-Company-MMM-Stock-Prices-Dividends-and-Splits

(There's a convenient Export to Plotly button on the right-side of all Quandl stock data pages)

![image](https://cloud.githubusercontent.com/assets/1865834/22226747/9dbb19ce-e195-11e6-8bbf-c61536725c90.png)

It doesn't look like the dates plot as plotly dates:

![image](https://cloud.githubusercontent.com/assets/1865834/22226759/b103a9b0-e195-11e6-9f38-99153945742d.png)

I don't know if it's possible to change the default styling, but if it is, I think we should consider changing it to this:

https://plot.ly/~jackp/17419

Here is the dataset in Plotly (on stage):

https://stage.plot.ly/~jackp/15663

**Comment by etpinard** [comment] 2017-01-30 14:38
duplicate of https://github.com/plotly/plotly.js/issues/1250

**Closed by etpinard** 2017-01-30 14:38 UTC
