### ISSUE TITLE
Selected multiple point

### ISSUE THREAD

**Issue by etu29414** [plotly/plotly.js#2394] opened 2018-02-22 13:42 UTC
Hi,
So, i would like have more than one point in array points in data(=> this array
![image](https://user-images.githubusercontent.com/32361135/36541542-8dae480a-17de-11e8-966e-b6ca75a445e3.png)
).
I need to have 2 point in this array.
for example, i would like click on 2 points and after make a line

thx  !

**Comment by etpinard** [comment] 2018-02-22 14:49
By _select_, you mean _click_?

If so, this is a duplicate of https://github.com/plotly/plotly.js/issues/1852

**Comment by etu29414** [comment] 2018-02-22 15:02
Sry i'm french.
i have a chart =>
![image](https://user-images.githubusercontent.com/32361135/36545356-03ed6a00-17e9-11e8-8254-bf75073bd7c9.png)

and i would like drawn 2line like this =>
![image](https://user-images.githubusercontent.com/32361135/36545440-29ca5fee-17e9-11e8-8c2b-55ac1f63dcf8.png)

but these line must drawed after the selected point and i would like use the array"points" because in example of ploty you use a loop =>
![image](https://user-images.githubusercontent.com/32361135/36545616-97d87b06-17e9-11e8-97e2-9a6d7162b02d.png)
and i dont understand why because there are only one cell in this array.

this subject is on a map ,i can use the same on a scatter chart?

**Comment by etpinard** [comment] 2018-02-22 15:43
Yep, that's a duplicate of https://github.com/plotly/plotly.js/issues/1852

There's no way to select multiple points that don't share the same `x` or `y` coordinate via click at the moment.

Please subscribe to #1852 for the most up-to-date development info.

**Closed by etpinard** 2018-02-22 15:43 UTC
