### ISSUE TITLE
Order of traces affects visibility in Scatter3d

### ISSUE THREAD

**Issue by jmmease** [plotly/plotly.js#2717] opened 2018-06-09 13:01 UTC
A plotly.py user, @ivirshup, reported this issue in plotly/plotly.py#1030

> For 3d scatter plots with opacity < 1, the last trace to be added always shows up on top, regardless of camera position.

Here is a plotly.js codepen that reproduces the issues: https://codepen.io/anon/pen/aKpBed

Thanks!

**Comment by alexcjohnson** [comment] 2018-06-11 13:31
duplicate of https://github.com/plotly/plotly.js/issues/1267 - I'm afraid this is a rather long-standing issue...

**Closed by alexcjohnson** 2018-06-11 13:31 UTC

**Comment by jmmease** [comment] 2018-06-11 13:39
Ahh, thanks for the reference
