### ISSUE TITLE
Gl2d pointcloud panning behavior change between 1.21.3 and 1.22.0

### ISSUE THREAD

**Issue by RussGlover** [plotly/plotly.js#2569] opened 2018-04-17 20:35 UTC
Panning in a gl2d pointcloud does not seem to work correctly in newer versions. The change appeared to happen between 1.21.3 and 1.22.0 but I can't see anything in the changelog that would relate to this.

Here is an example with a static plot, the axis graphics are just mixed up:
plotly-gl2d-1.21.3.min.js: https://codepen.io/russg/pen/aGoXrX
plotly-latest: https://codepen.io/plotly/pen/pwRJJZ

With a dynamically updated plot, panning is very difficult:
plotly-gl2d-1.21.3.min.js: https://codepen.io/russg/pen/wjwRGQ?editors=1010
plotly-gl2d-1.22.0.min.js: https://codepen.io/russg/pen/KRPJOZ?editors=1010

I tested this on edge and chrome and the behavior seems the same.

**Comment by etpinard** [comment] 2018-04-17 21:35
Thanks for writing in. 

I think the first part of your report is a duplicate of https://github.com/plotly/plotly.js/issues/2436.

As far the second, yeah that's pretty bad. Thanks for bringing this up1

**Comment by gvwilson** [comment] 2024-06-11 17:06
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson

**Closed by gvwilson** 2024-06-11 17:06 UTC
Labels: type: bug, type: regression
