### ISSUE TITLE
Line transition oddities

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.js#4250] opened 2019-10-03 18:53 UTC
This pen https://codepen.io/nicolaskruchten/pen/YzzKryK shows a couple of oddities:

1) `layout.transition` must be at least `{}` to work, but `true` doesn't work... seems a bit odd that `{}` behaves differently from unspecified
2) the appearance of the line during the transition is a bit weird: I would expect there to be two line segments, each terminating on a real data point even during the transition, rather than having a "kink" in the line moving laterally and temporarily having a point moving that's not attached to a line

**Comment by etpinard** [comment] 2019-10-03 19:47
> 1. `layout.transition` must be at least `{}` to work, but `true` doesn't work... seems a bit odd that `{}` behaves differently from unspecified

Right. `layout.transition: {}` coerces to the `transition.duration` and `transition.easing` defaults, but `layout.transition: true` does not. I'm not opposed to accepting `layout.transition: true`, but having:

```js
typeof gd.layout.transition // => 'boolean'

// but then
typeof gd._fullLayout.transition // => 'object'
```

would be a first (I think) in plotly.js, and may lead to problems downstream.

-------------

> 2\. the appearance of the line during the transition is a bit weird: I would expect there to be two line segments, each terminating on a real data point even during the transition, rather than having a "kink" in the line moving laterally and temporarily having a point moving that's not attached to a line

That's because the 3 pts making up the line segment in the first frame is simplified (i.e. optimised) into 2 pts before rendering in [`scatter/line_points.js`](https://github.com/plotly/plotly.js/blob/master/src/traces/scatter/line_points.js). As the second frame can't be simplified, the transition looks odd. 

Luckily that thing was bothering Ricky too, so by setting `line.simplify: false`, we get

![Peek 2019-10-03 15-45](https://user-images.githubusercontent.com/6675409/66158919-e8addc80-e5f4-11e9-8da1-3ef47584699f.gif)

https://codepen.io/etpinard/pen/abboLez?editors=0010

https://github.com/plotly/plotly.js/blob/f69f7c8d2b8419f3fe4f7e31c4dd0985b675b6ef/src/traces/scatter/attributes.js#L263-L273

**Comment by alexcjohnson** [comment] 2019-10-28 14:38
`layout.transition: {}` is indeed a little odd, do we have any other objects that behave that way? I'm not a fan of accepting `true` though, would make it very confusing as a user to learn how to take the next step and control the transition parameters.

In other contexts there's a separate boolean attr (`showlegend: true`) or a boolean inside the object (`enabled` or `visible`) and you need to explicitly provide at least that one. I guess at this point we need to maintain this behavior for backward compatibility, but it may be worthwhile including an `enabled` flag if only so you can set it `false` if desired.

Now to the question of `line.simplify` - let's use this issue as a more general launching point for object constancy with lines, encompassing https://github.com/plotly/plotly.py/issues/1843 too. Copying the comment I made over there (and, per @nicolaskruchten - saying "very tricky" was in no way meant to imply we shouldn't do this; the current behavior is absolutely a bug):

> There's no per-point object constancy built into the line paths, we're simply asking the path attr to [transition from one value to the next](https://github.com/plotly/plotly.js/blob/990a96050bbab12e1e405d0974985b2fea54d2e6/src/traces/scatter/plot.js#L271), which means transitioning each control point. Working in real object constancy seems like a frankly very tricky problem in the general case. For specific cases like this, where a leading point is dropped and a new point is added at the end, we could imagine a solution in 3 steps:
> 
> 1. Before the transition, redraw the path instantaneously with an extra control point at the end (doubling up the last point)
> 2. Create the final path having that extra control point now at the beginning, and execute the transition
> 3. Redraw the path without the extra control point (or, I suppose, this step could be deferred until the next transition comes and we see what points have been added or removed)
> 
> That would work, and adding & removing points at the ends seems like a pretty common use case so may be worthwhile coding for. May be tricky to get it to work right on splines, we can't treat these ghost points like regular points that happen to overlap their neighbors as this wouldn't give the same curve to the next point; but it seems like there would be a way to handle it.
> 
> The more general case - points being inserted, removed, or reordered mid-group - creates all sorts of complications. Adding and removing points should be manageable, though accounting for all possible line shapes and getting it to look like the new points emerge from the line itself rather than splitting out of one of the existing points may be tricky. Reordering points it's not even clear to me what theoretically you should see. Take the simplest case where x, y, and id don't change, just their relative order. Then the markers wouldn't move at all, but you'd be asking the lines connecting them to change connection order? I don't see a way to do this without the lines disconnecting from the markers. Perhaps that's a sufficiently obscure edge case that this is acceptable?
> 

To follow on from that, how does this relate to `line.simplify`? Seems like at the very least steps 1 and 2 above need to force `simplify: false`; and step 3 we not even do. We might be able to improve performance in some cases (reducing delay at the start of the transition) by forcing `simplify: false` from the outset if `layout.transition` is defined. But that will only help (removing step 1) if the ids don't change; if they do, we still have to execute step 1. And if we omit step 3 then it's only the first transition that's improved anyway. So I'd probably leave `line.simplify` alone and just handle this behind the scenes. It's supposed to never have a visible effect anyway (never mind #4282 that we need to solve separately)

**Comment by gvwilson** [comment] 2024-06-14 12:51
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-14 12:51 UTC
