### ISSUE TITLE
Choropleth FigureFactory w/ scattergl trace not rendering properly

### ISSUE THREAD

**Issue by Kully** [plotly/plotly.js#2674] opened 2018-05-28 16:29 UTC
If you run the Python Example below and replace all the `scatter` in the traces to `scattergl`, this produces a mangled USA choropleth:
https://plot.ly/python/county-choropleth/#the-entire-usa

![screen shot 2018-05-28 at 12 07 32 pm](https://user-images.githubusercontent.com/10369095/40623001-7e21fab0-6272-11e8-8ee1-49618bdff94f.png)

cc. @dy

**Comment by etpinard** [comment] 2018-05-28 17:17
duplicate of https://github.com/plotly/plotly.js/issues/2291

**Closed by etpinard** 2018-05-28 17:17 UTC
