### ISSUE TITLE
BUG: Figure breaks after animating a property of an array element

### ISSUE THREAD

**Issue by jmmease** [plotly/plotly.js#2228] opened 2017-12-29 15:45 UTC
It seems that something goes wrong when using `Plotly.animate` to change a property of an array element. I hit this while working on a custom trace type, but it is reproducible on the Parallel Coordinate trace.

**Note:** I understand animated transitions are not supported for the Parallel Coordinates trace, but my expectation is that an animate command shouldn't cause an error and should behave like a relayout/restyle command.

Parallel Coordinate Example Pen: https://codepen.io/anon/pen/ZvKGxW

Summary: 
 - Animating a change to `line.color` works fine
 - Restyling a change to `dimensions[0].constraintrange` works fine
 - Animating a change to `dimensions[0].constraintrange` breaks the plot (Nothing shows up afterward) 

Example code for reference:
```
var trace = {
  type: 'parcoords',
  line: {
    color: 'blue'
  },
	
  dimensions: [{
    range: [1, 5],
    constraintrange: [1, 2],
    label: 'A',
    values: [1,4]
  }, {    
    range: [1,5],
    label: 'B',
    values: [3,1.5],
    tickvals: [1.5,3,4.5]
  }]
};

var data = [trace]

Plotly.plot('graphDiv', data).then(function() {
	// ## This animate command works as expected (line turns red) ##
	// Plotly.animate('graphDiv', 
	// 			{data: [{'line.color': 'red'}],
	// 			 traces: [0],
	// 			 layout: {}})
	
	// ## This restyle command works as expected (constraintrange extends to [1, 4]) ##
	// Plotly.restyle('graphDiv', {'dimensions[0].constraintrange': [[1, 4]]}, 0)
	
	// ## This animate command breaks things and the plot doesn't show up ##
	Plotly.animate('graphDiv', 
                                {data: [{'dimensions[0].constraintrange': [1, 4]}],
                                  traces: [0],
                                  layout: {}})
});
```

**Comment by etpinard** [comment] 2018-01-18 19:25
The fix must be done inside the [`Plots.transitions`](https://github.com/plotly/plotly.js/blob/48512eb5db6227be88790b8a5202ec06ea21b918/src/plots/plots.js#L2046) helpers most likely in [`Plots.computeFrame`](https://github.com/plotly/plotly.js/blob/48512eb5db6227be88790b8a5202ec06ea21b918/src/plots/plots.js#L1836). All trace types should _work_ with `Plotly.animate` the fallback being an equivalent `restyle`, `relayout` or `update` call.

**Comment by monfera** [comment] 2018-01-18 19:43
Thanks @etpinard! Currently `Plots.computeFrame` doesn't get called for this specific case, because it doesn't match the `type`:
![image](https://user-images.githubusercontent.com/1548516/35117697-bdfb632c-fc8f-11e7-9212-c401e0b2733c.png)

![image](https://user-images.githubusercontent.com/1548516/35117772-fb2216ba-fc8f-11e7-82e7-965f17c252e4.png)

Planning to add a branch there that'd handle `dimensions` and most likely, make that branch call `Plots.computeFrame`.

**Comment by monfera** [comment] 2018-01-31 19:04
Circling back to this one, just jotting down where I am, also if someone has a firm idea on the best way for fixing it, please tell me.

During animation, the change `src === {dimensions[0].constraintrange:  [32000, 40000]}` is merged into the preexisting data `dest` [here](https://github.com/plotly/plotly.js/blob/e341edd0d9defba39edf440947153277d9dc5e8c/src/plots/plots.js#L1945-L1969). As a result of this, all but index `[0]` of the preexisting dimensions get eliminated; dimension index `[0]` gets overwritten with `src` ie. its preexisting other properties are gone too. This is why the new render draws a blank.

In contrast, when calling the `restlye` function, it uses ultimately [`npSet`](https://github.com/plotly/plotly.js/blob/e341edd0d9defba39edf440947153277d9dc5e8c/src/lib/nested_property.js#L158), invoked [here](https://github.com/plotly/plotly.js/blob/e341edd0d9defba39edf440947153277d9dc5e8c/src/plot_api/plot_api.js#L1583) with the result that

- all `dimension` elements remain in place
- the item with index `[0]` also remains well-preserved, _except_ the change represented by the `restyle`

I think this is the cause for the differing outcome between animation and restyling. As both of these spots are part of multi-hundred line code step sequences, and both are rather critical, I'd like to get input on how to proceed. My natural inclination would be to understand why animations don't use the same code bit for the "patching" as restyling, which might be written in the code and I missed it, or would need to ask; then, depending on the answer, either make animations call this gentler `npSet` merger or would run out of ideas, as making an explicit exception for `dimensions` would feel like a hack.

**Closed** 2018-02-02 18:53 UTC
Labels: type: bug
