### ISSUE TITLE
Surface contours based con surfacecolor values insthead of axes values

### ISSUE THREAD

**Issue by gpdonnarumma** [plotly/plotly.js#4424] opened 2019-12-16 09:36 UTC
is possible to show a contour line based on surfacecolor values instead of Z axis values?

I have a 2D surface (slice) in 3D chart (tomography).
I would to draw contour based on surfacecolor values and show it.

**Comment by etpinard** [comment] 2019-12-16 14:48
This sounds like a duplicate of https://github.com/plotly/plotly.js/issues/4097

**Comment by gpdonnarumma** [comment] 2019-12-16 15:07
Hi Étienne,
I hope to explain better than before,
I would make contours of the surfacecolor data, not to color the contours, in order to obtain a 3D surface (for example vertically oriented) with contours not related to Z but to surfacecolor.

**Comment by etpinard** [comment] 2019-12-16 15:11
Ok - how is that different than the problem written down in https://github.com/plotly/plotly.js/issues/4097 ?

**Comment by gpdonnarumma** [comment] 2019-12-16 15:21
Hi,
maybe I've not understand the post.
But I read "color the contours lines".

I want to obtain something like the attached file, using surfacecolor-data.



Il Lun 16 Dic 2019, 16:11 Étienne Tétreault-Pinard <notifications@github.com>
ha scritto:

**Comment by gpdonnarumma** [comment] 2019-12-16 15:58
Hi, Etienne,
I think you're right!!

It's the same request.

Sorry.

You can close this Post.



Il Lun 16 Dic 2019, 16:21 Gian Paolo Donnarumma <gpdonnarumma@gmail.com> ha
scritto:

**Comment by etpinard** [comment] 2019-12-16 16:12
Thank you @gpdonnarumma !!

**Closed by etpinard** 2019-12-16 16:12 UTC

**Comment by gpdonnarumma** [comment] 2020-05-22 14:39
If I generate a Surface3D, is possible, using contour setting, draw the contour lines (as you can see in the image) taking as source the surfacecolor values and not the x/y/z values?

**Comment by archmoj** [comment] 2020-05-22 15:39
Hmm...
Maybe you could consider using new `opacityscale` feature like this [demo](https://codepen.io/MojtabaSamimi/pen/QWjYRVV?editors=0010)?
