### ISSUE TITLE
sankey: ungroup nodes via mouse

### ISSUE THREAD

**Issue by antoinerg** [plotly/plotly.js#3760] opened 2019-04-11 17:01 UTC
As of right now, we cannot ungroup nodes in `sankey` traces via the mouse except by clicking on the home button which resets the figure to its initial settings. This way, all groups are ungrouped.

To allow ungrouping a specific group, we could either:
1. Double-click on it 
2. Display a "ungroup" button next to it
3. Any other suggestions?

What do you think/prefer? 

@plotly/plotly_js @nicolaskruchten

**Comment by alexcjohnson** [comment] 2019-04-11 19:07
I like double-click, if people think it's discoverable enough. I suppose we could give a notifier when you first create a group, like we do when you first zoom/pan to tell you you can double-click to autoscale... though who knows how much these messages help.

**Comment by nicolaskruchten** [comment] 2019-04-11 19:45
I also like double click. first thing i tried

**Comment by gvwilson** [comment] 2024-06-14 11:55
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-14 11:55 UTC
Labels: type: feature
