### ISSUE TITLE
more markers (symbols) for gl3d

### ISSUE THREAD

**Issue by alexeypant** [plotly/plotly.js#4205] opened 2019-09-19 13:34 UTC
3d scatter plot currently supports less symbols comparing to 2d scatter plot. I've added some more. Could you please review a pul request in my fork if that is acceptable?
Regards,
Alexey

**Comment by archmoj** [comment] 2019-09-20 01:14
@alexeypant Thanks for the PR.
Here is the link to it: https://github.com/alexeypant/plotly.js/pulls

**Comment by etpinard** [comment] 2019-09-20 13:42
Can someone make a test mock showing all the marker symbols similar to this one for 2d:

https://rreusser.github.io/plotly-mock-viewer/#marker_symbols

I suspect the symbols in 3D won't look too crisps.

**Comment by gvwilson** [comment] 2024-06-14 12:50
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-14 12:50 UTC
Labels: type: feature
