### ISSUE TITLE
Table: Adding a bold cell value changes the line height

### ISSUE THREAD

**Issue by AbdealiLoKo** [plotly/plotly.js#3694] opened 2019-03-29 09:19 UTC
I was trying to make a table where any value that goes above `100` I was setting to bold so it is immediately visible.
I found that while I was implementing this, when I set the value of a cell to bold, the row width is changing. Which make the table look very very weird ...

<img width="1167" alt="Screen Shot 2019-03-29 at 2 47 52 PM" src="https://user-images.githubusercontent.com/2200743/55222382-c85e2900-5231-11e9-8b15-ed0692702451.png">
<img width="1155" alt="Screen Shot 2019-03-29 at 2 47 58 PM" src="https://user-images.githubusercontent.com/2200743/55222383-c8f6bf80-5231-11e9-9f6d-22730ce3ff33.png">

**Comment by AbdealiJK** [comment] 2019-03-29 15:01
```
nums = [...new Array(5).keys()]
cells = nums.map((x) => ['1', '2', '3'])
cells[0][0] = '<b>1</b>'
Plotly.newPlot(
  'graph',
  [{'cells': {'values': cells},
   'header': {'values': nums.map((x) => `col${x}`)},
   'type': 'table'}],
  {});
```
https://codepen.io/AbdealiJK/pen/KYPVoX

**Comment by AbdealiJK** [comment] 2019-04-01 16:11
That's a good point. I think there are two options that seem to be intuitive:
 - increase the row height for all the rows by the number of pixels that bold increases the font
 - decrease the box padding on the bold cell

I think HTML, excel, etc. do the latter - which seems to be the one prefer. 

I.e. If the font size is 15 and the table cell height is 15 - doing a bold would make it overlap a bit - which makes sense in my opinion.

**Comment by etpinard** [comment] 2019-07-04 14:30
related: https://github.com/plotly/plotly.js/issues/2056

**Comment by Lucianod28** [comment] 2020-01-01 22:14
Has anybody found a workaround to fix the cell height regardless of the contents?

**Comment by gvwilson** [comment] 2024-06-14 11:54
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-14 11:54 UTC
