### ISSUE TITLE
Axis title alignment

### ISSUE THREAD

**Issue by cpsievert** [plotly/plotly.js#3717] opened 2019-04-02 22:30 UTC
Now that [`layout.title` has an alignment API](https://github.com/plotly/plotly.js/pull/3276), it would be great to have the same for axis objects

**Comment by gvwilson** [comment] 2024-06-14 11:54
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-14 11:54 UTC
Labels: type: feature
