### ISSUE TITLE
scattergl markers rendering incorrectly with time series data

### ISSUE THREAD

**Issue by nickmzero** [plotly/plotly.js#5970] opened 2021-10-04 19:13 UTC
Noticing some unexpected behavior with time series data using scattergl. The markers are rendering off the lines at seemingly regular intervals: (this example has ~800k points)
<img width="935" alt="Screen Shot 2021-10-04 at 1 55 48 PM" src="https://user-images.githubusercontent.com/32622260/135908737-2f0a1103-b787-4487-b0ff-377d6d4f35a0.png">

**Reproducible example**
shows scatter and scattergl side-by-side with the same date values: https://codepen.io/nickmzero/pen/KKqLOGv
<img width="1415" alt="Screen Shot 2021-10-04 at 2 10 18 PM" src="https://user-images.githubusercontent.com/32622260/135910152-9b7535ac-65f5-4a8e-bd47-1ea98bffd0cd.png">

After briefly playing around with the dates in the codepen, it seems like the markers fail to correctly render on the line unless there's a day between points.

**Comment by AlanJMac** [comment] 2022-07-04 15:53
We have started to see this same behaviour on all browsers for certain MacBooks using the M1 chip.
A particular setup we have that exhibits this behaviour is a MacBook Air, OS Monterey 12.3.1, M1 chip.
It has also been seen on OS 12.3.2 and 12.4.

The scatter plots render fine, but the markers in scattergl plots render vertically.

This appears to be the same issue reported in the community forums:
- https://community.plotly.com/t/webgl-scatter-plots-not-rendering-on-new-m1-mac-in-chrome-or-safari/61397 
- https://community.plotly.com/t/plotly-fails-when-using-scattergl-and-value-greater-than-2-24-only-on-m1-chip/61927

The issue presents itself for scattergl plots with x-axis values greater than 2^24 (e.g. date values)
And can be confirmed by the following example: https://codepen.io/alanjmac/pen/jOzbMVw

![Scattergl_Issue_MacM1](https://user-images.githubusercontent.com/11413124/177187592-3e490b0f-302b-47ff-a5cf-5c82c6d0383c.png)

**Comment by chipkent** [comment] 2023-04-24 14:56
Has this been resolved?  Is there any plan to address it?

**Comment by jklimke** [comment] 2023-05-15 15:30
For me this is also a quite big problem. Is there any idea how to fix this or maybe a workaround ?

**Comment by AlanJMac** [comment] 2023-05-17 08:43
I'm not sure if there is a fix (I tried but it was beyond me) however the following workaround works for me in Chrome:

- in Chrome browser, navigate to _chrome://flags/_ and search for "ANGLE graphics backend". From the dropdown box select "Metal". (Apparently Open GL has been deprecated in Mac and may contain driver bugs).
![image](https://github.com/plotly/plotly.js/assets/11413124/0a26aab5-4160-497c-9305-f537880eeba9)

- in Chrome versions >= 109.0.5414.xx, ensure hardware acceleration is enabled:  Go to Settings => System and toggle on "Use hardware acceleration when available". In earlier versions, an alternative workaround was to toggle this to off.

I was unable to find a similar workaround for Firefox.

**Comment by sqlAlchemyNoob2004** [comment] 2023-10-05 21:55
has anybody got a workaround for this? seems like plotly doesn't plan to fix this.. do I need to refactor with a different library to handle users on newer macs?

**Comment by AlanJMac** [comment] 2024-01-08 09:53
I can confirm this issue appears to be fixed with the latest plotly.js [2.28.0](https://github.com/plotly/plotly.js/releases/tag/v2.28.0) release! 
Many thanks for the solution!

> Fix scattergl rendering bug on M1 mac devices [https://github.com/plotly/plotly.js/pull/6830],
with thanks to @justinjhendrick for the contribution!

Details of the problem + fix can be found in the similar reported issue: https://github.com/plotly/plotly.js/issues/6820

**Closed** 2024-07-12 12:42 UTC
