### ISSUE TITLE
Using hour rangebreaks causes candlestick chart to fail

### ISSUE THREAD

**Issue by AndrewSovik** [plotly/plotly.js#4795] opened 2020-04-26 23:10 UTC
Using an hour rangebreak, in my case `{'pattern': 'hour', 'bounds': [16, 9.5]}` (2nd last line) causes the candlestick chart to not plot open/close boxes and it breaks the hovering feature to preview data. There is also more space between points but I assumed that was because the lack of candle boxes.

Data:
[data.xlsx](https://github.com/plotly/plotly.py/files/4536643/data.xlsx)

Code:
`import pandas as pd
from plotly.offline import plot
import plotly.graph_objects as go
from plotly.subplots import make_subplots

df = pd.read_excel('data.xlsx')

#Plot Chart
fig = make_subplots(          
    rows=2, cols=1, 
    subplot_titles=('Price', 'Volume'),
    shared_xaxes=True,
    vertical_spacing=0.3)
fig.add_trace(go.Candlestick( #Candlesticks
    x=df['date'], open=df['open'], high=df['high'], low=df['low'], close=df['close']),
    row=1, col=1)
fig.add_trace(go.Bar( #Volume
    x=df['date'], y=df['volume'],
    marker_color='blue'),
    row=2, col=1,)
fig.update_layout(
    title_text='AAPL Technical Analysis',
    xaxis_rangeslider_visible=True,
    showlegend=False)
fig.update_xaxes(
    rangebreaks=[
        {'pattern': 'day of week', 'bounds': [6, 1]}, #Break weekends
        {'pattern': 'hour', 'bounds': [16, 9.5]}]) #Break after hours and market close

plot(fig)`

Remove `{'pattern': 'hour', 'bounds': [16, 9.5]}` to see correct candlesticks but I don't want to plot times where the market is after hours or closed.

Python 3.7.7, all modules are updated

Thanks

**Comment by nicolaskruchten** [comment] 2020-04-30 21:07
@archmoj I expect this is a duplicate of https://github.com/plotly/plotly.js/issues/4742 but I haven't had a chance to confirm.

**Comment by archmoj** [comment] 2020-05-06 13:48
To me it looks like a duplicate of #4742.

**Comment by archmoj** [comment] 2020-05-06 13:59
Bug [demo](https://codepen.io/MojtabaSamimi/pen/GRpQjLq?editors=0010) in JS.

**Closed** 2020-05-07 20:07 UTC
Labels: type: bug
