### ISSUE TITLE
Long or large tick labels cut off by left margin

### ISSUE THREAD

**Issue by sprazzeus** [plotly/plotly.js#1789] opened 2017-06-15 10:47 UTC
I have a chart where the values and tick labels are dynamic currency amounts that could be very high, in the millions, or very low. The expectation of the left margin is that it should push the entire chart _inclusive of the tick labels_ rightwards, but instead long labels (or even ones with a larger font size) simply extend _leftward_ and get cut off. Since my labels are dynamic, I'm not able to predetermine the size of the left margin that is required to view the full label.

![screen shot 2017-06-15 at 6 38 16 pm](https://user-images.githubusercontent.com/19484719/27177714-df9ee634-51f9-11e7-9800-2510c4d36f08.png)

**Comment by etpinard** [comment] 2017-06-15 13:52
duplicate of https://github.com/plotly/plotly.js/issues/296

**Closed by etpinard** 2017-06-15 13:52 UTC
