### ISSUE TITLE
sticks-to-zero for scatters

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.js#4085] opened 2019-07-29 14:31 UTC
We could add first-class support for lollypop/needle/stem plots by adding a flag to 2d/3d scatter that draws a line down to the zero-line.

**Comment by gvwilson** [comment] 2024-06-14 12:47
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-14 12:47 UTC
Labels: type: feature
