### ISSUE TITLE
plotly_doubleclick event for scatter3d?

### ISSUE THREAD

**Issue by cpsievert** [plotly/plotly.js#3266] opened 2018-11-19 22:13 UTC
Seems as though it was never implemented -- https://codepen.io/cpsievert/pen/mQqWrz

Requested as part of https://github.com/ropensci/plotly/issues/1413

**Comment by wkumler** [comment] 2022-04-18 04:40
Any plans to implement this? I spent a little time on it this weekend but didn't make any headway.

**Comment by alexcjohnson** [comment] 2022-04-19 23:47
@wkumler no plans, but I'd be happy to get you pointed in the right direction if you'd like to give it a shot. The single-click event for 3D is here:

https://github.com/plotly/plotly.js/blob/12a49c0f225dea785c98bd36f6820091d98d2d85/src/plots/gl3d/scene.js#L452

Unfortunately it can't use the same logic as most of the other click handlers, because it's based on stack.gl and it's just taking events from those packages. So I think the way to handle this is to stash the first click event and timestamp somewhere (on the `scene` object?), and when you see a new click event check if the `eventData` is the same and the timestamp is within `gd._context.doubleClickDelay` of the first click - if so, emit a `plotly_doubleclick` event first, followed by the `plotly_click` event you'd have emitted then anyway.

Same `eventData` isn't exactly the same criterion as used elsewhere to distinguish a doubleclick from two clicks while the mouse is moving, but it should be reasonable.

**Comment by gvwilson** [comment] 2024-06-11 17:34
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson

**Closed by gvwilson** 2024-06-11 17:34 UTC
Labels: type: feature
