### ISSUE TITLE
Uncaught ReferenceError: t is not defined

### ISSUE THREAD

**Issue by iubhatt17** [plotly/plotly.js#4158] opened 2019-08-30 06:40 UTC
I am using Plotly  currently in my angular 8 proejct. In local I checked the map and it was working fine but in live server , plotly is giving me this error.

Uncaught ReferenceError: t is not defined

I checked in devtool console , the error is in this line
var n = "undefined" != typeof window ? window : void 0 !== t ? t : "undefined" != typeof self ? self : {};
I dont know how to resolve it.Please help to resolve this issue
![Screenshot from 2019-08-30 12-09-55](https://user-images.githubusercontent.com/34944501/63998625-2499e180-cb1f-11e9-94a8-f35c13e9620b.png)

**Comment by etpinard** [comment] 2019-08-30 14:04
Thanks for reporting.

To help us debug, could someone try to replicate this bug in a confined environment e.g. https://stackblitz.com/

**Comment by etpinard** [comment] 2019-09-26 19:03
This looks similar to https://github.com/plotly/plotly.js/issues/3518

----------

Closing due this issue due to lack of reproducible example.

@iubhatt17 feel free to open a new issue if you able to recreate this problem in a control environment. Thank you!

**Closed by etpinard** 2019-09-26 19:03 UTC
