### ISSUE TITLE
Markers disapear when using subplots combining barmode 'relative' with scatterplot plots

### ISSUE THREAD

**Issue by fabiangehring** [plotly/plotly.js#906] opened 2016-09-06 14:23 UTC
I have two plots that combine a barmode 'relative' and a scatterplot. When I combine them themselves with subplot markers disappear. Reproducible example in the following post where it was referenced to here: https://github.com/ropensci/plotly/issues/667

**Comment by etpinard** [comment] 2016-09-06 18:26
sound like a duplicate of https://github.com/plotly/plotly.js/issues/905

**Comment by etpinard** [comment] 2016-09-07 13:45
Calling this a duplicate of the closed #905 until further info from the issue author.

**Closed by etpinard** 2016-09-07 13:45 UTC
