### ISSUE TITLE
How to add support for 'Box selection' in plotly.js 2D graphs for touch screen devices?

### ISSUE THREAD

**Issue by juni-green** [plotly/plotly.js#1605] opened 2017-04-19 05:20 UTC
Hi,
Is it possible to perform "Box selection" in plotly.js graph on touch screen devices? If not, can we integrate it in some way to plotly.js library for 2D graphs?
I've been exploring it and found that plotly triggers 'plotly_selected' event on touch event but does nothing on drag and drop. See the code here: [codePen](https://codepen.io/juni-green/pen/VbeYjw).

Any help will be appreciated.
Thanks!

**Comment by etpinard** [comment] 2017-04-19 13:47
duplicate of https://github.com/plotly/plotly.js/issues/480

**Closed by etpinard** 2017-04-19 13:47 UTC
Labels: type: duplicate
