### ISSUE TITLE
Apache Arrow support

### ISSUE THREAD

**Issue by exactlyallan** [plotly/plotly.js#3818] opened 2019-04-29 19:19 UTC
Any thoughts to having native or an arrow loader extension like [Vega loader for arrow](https://github.com/vega/vega-loader-arrow)? The discussion on #1784 left off there and wanted to see if any more thought was given - would help integration with our [RAPIDS project](https://github.com/rapidsai).

**Comment by etpinard** [comment] 2019-05-21 21:03
Hi @exactlyallan thanks for writing in.

We haven't had a discussion on adding a loader for the Arrow format. Thanks for bringing this up.

My feeling is that "loaders" could (and should) live outside of plotly.js. You can read our latest conclusions on the topic here: https://github.com/plotly/plotly.js/pull/2911#issuecomment-420314559

**Comment by gvwilson** [comment] 2024-06-14 11:56
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-14 11:56 UTC
