### ISSUE TITLE
Fx.hover renders the 'x' info near the value

### ISSUE THREAD

**Issue by bishonen** [plotly/plotly.js#4676] opened 2020-03-23 21:13 UTC
With hoverinfo set to 'y+name+x' or 'all', the x-axis hoverinfo gets rendered correctly for a chart over which one hovers manually with the mouse.

When using the Fx.hover option, however, to trigger a hoverinfo, the x-axis label shows up next to the datapoint itself (please see below), rather than at the bottom of the x-axis.
Thus, the Fx.hover option creates an inconsistency compared to the manual hover.

On the pic below, mouse was hovering over the bottom chart, whilst the upper hoverinfo got render with Fx.hover.
<img width="166" alt="image" src="https://user-images.githubusercontent.com/11603939/77363455-0d3c7300-6d53-11ea-894f-bd2423473eea.png">

**Comment by alexcjohnson** [comment] 2020-03-23 21:37
Thanks @bishonen - we should definitely make it possible to achieve this. Can you show the form of `Fx.hover` you're using in your code?

**Comment by bishonen** [comment] 2020-03-23 21:55
Certainly!

Here's the code that I have used:
```

      Plotly.Fx.hover(chartID,[{curveNumber: 0, pointNumber: pointNum, pointIndex: pointNum},
        {curveNumber: 2, pointNumber: pointNum, pointIndex: pointNum}])
```

**Comment by alexcjohnson** [comment] 2020-03-23 22:49
Thanks. That form - where you're providing each desired curve number and point number - in general need not have matching x values. So I think we opted for the current behavior because we didn't want it to flip back and forth between labeling each point with (x, y) and a common x label at the bottom.

So as I said before we'd like to add an option that forces the common x label, but I wonder if prior to that you can get the effect you want by changing to one of the other accepted forms, like:
`Plotly.Fx.hover(chartID, {xval: '2020-03-23 14:30'})`

I'm not sure if we have documentation about this other than comments in the source code, but here are said comments:

https://github.com/plotly/plotly.js/blob/6de4c751a3d702ea13f20214349460840cfab6af/src/components/fx/hover.js#L50-L74

BTW, this is likely not going to be a high-priority item for us to add, unless someone would like to sponsor it, but we would happily accept a PR!

**Comment by bishonen** [comment] 2020-03-23 23:52
Thanks for the quick reply! The reasoning makes sense, of course. I tried giving your proposal a try, but replacing the hover with your proposal yields an error [1].

When mistyping "xval" to "xVal", I get the desired position of the x-axis label, but it always gets rendered at the 50% mark of the xaxis.


[1]
<img width="1331" alt="image" src="https://user-images.githubusercontent.com/11603939/77373810-7e872080-6d69-11ea-951a-001da5332282.png">

**Comment by alexcjohnson** [comment] 2020-03-24 13:12
Ah, thanks for figuring that out - I guess I should have tested on a date axis before posting 😅 
For completeness, yes, it's epoch time, milliseconds since 1970, but be careful to use UTC. That would be another nice add, supporting date strings in `xval` / `yval` for `Fx.hover` - might even consider that a bug to be fixed.

**Comment by gvwilson** [comment] 2024-06-14 13:01
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-14 13:01 UTC
