### ISSUE TITLE
Regression bug: points jump around when LASSOing with webGL since v1.33

### ISSUE THREAD

**Issue by daattali** [plotly/plotly.js#2460] opened 2018-03-08 16:53 UTC
Codepen with sample code: https://codepen.io/anon/pen/eMYZKJ

Trying to lasso select some points after version 1.33 causes the selected points to jump around. The screen capture below is with 10,000 points but it also happens with 10 points.

![mildplushelk-max-14mb](https://user-images.githubusercontent.com/952340/37164048-4c2a90fc-22c7-11e8-923b-fd2c1e9da6ba.gif)

On Windows 7 Pro, using Chrome v64

Originally reported to @cpsievert at ropensci/plotly#1215

**Comment by alexcjohnson** [comment] 2018-03-08 17:29
That's sure annoying - but I can't reproduce this on either my mac or on Browserstack Win7/Chrome64. @dfcreative @etpinard can you see it?

@daattali thanks for including both the codepen *and* the screen capture!

**Comment by etpinard** [comment] 2018-03-08 17:32
I can't replicate this on Ubuntu/Chrome 64

**Comment by daattali** [comment] 2018-03-08 17:37
Dang, this is not looking good!

**Comment by cpsievert** [comment] 2018-04-23 16:49
@daattali just FYI, you can test out 1.36.1 in the R package via this PR `devtools::install_github('ropensci/plotly#1223')`

**Comment by etpinard** [comment] 2018-05-10 16:15
Closing until someone can reproduce this in `1.37.1`

**Comment by daattali** [comment] 2018-05-10 20:42
Just tested on the same codepen using 1.37.1 and I'm getting the behaviour. Here's a screenshot

![image](https://user-images.githubusercontent.com/952340/39893236-20fbcd8e-5471-11e8-8a69-3d4f5eaeaba1.png)

**Comment by archmoj** [comment] 2019-04-09 00:53
Was not able to replicate this.
@daattali Would you mind testing with a more recent `plotly.js` version?
Thank you in advance.

**Comment by daattali** [comment] 2019-04-09 01:14
I still see the same behaviour using plotly 1.46.1 with this codepen https://codepen.io/anon/pen/OGbEVm

**Comment by archmoj** [comment] 2019-04-09 01:21
@daattali What OS+browser(s) you currently use?

**Comment by daattali** [comment] 2019-04-09 01:22
Chrome on Win 7

**Comment by archmoj** [comment] 2019-04-09 01:26
What about other browsers? Have you tested it on FireFox/IE for example?

**Comment by daattali** [comment] 2019-04-09 01:30
It actually works on FF and even IE

**Comment by archmoj** [comment] 2019-04-09 01:31
Great! Which chrome version installed on your machine?

**Comment by daattali** [comment] 2019-04-09 01:34
Currently 73.0.3683.103 which is latest. It's been updating throughout the past few months since I first reported this.

**Comment by archmoj** [comment] 2019-04-09 01:38
@daattali Thanks for the info to narrow this issue.
Wondering do you have a similar issue with `rectangle` select or is it just the `lasso`?

**Comment by daattali** [comment] 2019-04-09 01:50
rectangle works fine

**Comment by archmoj** [comment] 2019-04-09 01:53
On my laptop with Window 7, I was not able to replicate this. 
@antoinerg Could you please test https://codepen.io/anon/pen/OGbEVm?

**Comment by daattali** [comment] 2019-04-09 01:55
Interesting. I just tested on a different laptop with Win7 and still seeing the issue. If nobody else outside my house can replicate, I wouldn't be offended is this is closed as a cannot reproduce

**Comment by gvwilson** [comment] 2024-06-11 17:04
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson

**Closed by gvwilson** 2024-06-11 17:04 UTC
