### ISSUE TITLE
Virtual WebGL Workaround Fails On 3d Plots

### ISSUE THREAD

**Issue by robertclaus** [plotly/plotly.js#7298] opened 2024-12-04 22:48 UTC
Plotly's documentation recommends using the `virtual-webgl` script to support more plots than the browser's WebGL context limit allows. This works great for displaying many large scatter charts, but with this in place 3D plots, surface plots, and mesh3d plots (and likely others) do not seem to render.

https://plotly.com/python/webgl-vs-svg/

![Image](https://github.com/user-attachments/assets/7e42558a-ec46-4c82-972f-a50c3d99b5ca)
![Image](https://github.com/user-attachments/assets/c496478a-07aa-441f-850d-a1d9af835b45)

**Comment by archmoj** [comment] 2024-12-06 20:00
@robertclaus 

Could you possibly fork and tweak [this codepen](https://codepen.io/MojtabaSamimi/pen/yrMxEV?editors=0010) to replicate the bug you noticed?

Alternatively you may use [fig2pen](https://github.com/nicolaskruchten/fig2pen) to convert a python example to codepen.

Please note in both cases you should add the `virtual-webgl` script in the html before loading the `plotly.js` script.

Thank you!

**Comment by alexcjohnson** [comment] 2024-12-06 23:10
FYI apparently virtual-webgl has compatibility issues with Bokeh too, though I haven't investigated myself https://github.com/holoviz/panel/issues/7375

**Comment by gvwilson** [comment] 2024-12-09 21:21
@archmoj just sent you a slack - please dive into this one.

**Comment by samhinshaw** [comment] 2024-12-11 18:23
@archmoj I have not been able to reproduce it in codepen yet. I am going to see if I can isolate any further differences between codepen and the environment we are experiencing the bug in.

Two attempts:
https://codepen.io/samhinshaw/pen/QwLKdjZ
https://codepen.io/samhinshaw/details/EaYgZyj

**Comment by samhinshaw** [comment] 2024-12-11 18:28
Ah. I figured it out. 

From [this thread](https://www.soft8soft.com/topic/webgl-gl_invalid_framebuffer_operation-framebuffer-is-incomplete/):
> this error hints that at the moment when WebGL is initialized, the canvas size is 0 pixels.

Our layouts do not have width & height set. If we set them explicitly in the layout, the chart renders. 


| Before | After |
|--------|--------|
| <img width="506" alt="Image" src="https://github.com/user-attachments/assets/2d8ed354-bfad-4bfd-9fa7-6cf5ba10b63e" /> | <img width="506" alt="Image" src="https://github.com/user-attachments/assets/1a624b93-018d-4767-a464-77ecaee33eac" /> |

**Comment by samhinshaw** [comment] 2024-12-11 18:34
@archmoj Here is a codepen reproducing the bug: https://codepen.io/samhinshaw/pen/gbYwgvz

**Comment by archmoj** [comment] 2024-12-11 18:45
Thank you @samhinshaw for the replicating the bug :pray:
Since this seems like a browser specific bug, I am wondering if you could possibly add a workaround for this in place?

**Comment by archmoj** [comment] 2024-12-11 22:08
@gvwilson FYI - [samhinshaw](https://github.com/samhinshaw) are now working together a fix at plotly.js level at our Vancouver office. 
After that, I should release a plotly.js release candidate patch (v3.0.0-rc.2) to help close this ticket as soon as possible.

**Comment by archmoj** [comment] 2024-12-11 23:39
@samhinshaw 
When opening the new issue at plotly.js level please use the simplified version of codepen (i.e. without importing react, etc.) and use the latest official version of plotly.js `v2.35.2` instead of the RC of v3.
Thank you! :pray:

**Closed** 2024-12-16 17:04 UTC
Labels: bug, P1, cs
