### ISSUE TITLE
Contour with x/y/z columns crashes on Chrome with 500 points

### ISSUE THREAD

**Issue by gygabyte017** [plotly/plotly.js#3166] opened 2018-10-26 09:37 UTC
I have a simple page with 500 points to be drawn on a contour plot. The plot takes a very long time to display (~100 seconds) and most of the time the page stops responding or crashes.

I'm testing it with Chrome v69.0.3497.100 (64 bit), however the same happens on other browsers as well.

What's wrong? Please see this codepen snippet https://codepen.io/anon/pen/vVbOPa

**Comment by alexcjohnson** [comment] 2018-10-26 12:29
Heh @etpinard to our discussion the other day about implementing real triplet contours with Delaunay triangulation. @gygabyte017 the issue is that we currently need to massage this into a rectangular grid, which leaves tons of blank points that we need to then interpolate. So the fix would be either Delaunay triangulation + marching triangles, or a better interpolation algorithm (but we already know we want to do the former at some point)

**Comment by gvwilson** [comment] 2024-06-11 17:28
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson

**Closed by gvwilson** 2024-06-11 17:28 UTC
Labels: type: performance
