### ISSUE TITLE
Make parcoords control line layers' color and width configurable

### ISSUE THREAD

**Issue by archmoj** [plotly/plotly.js#3949] opened 2019-06-11 18:23 UTC
Currently there is no way for declaring colors other than magenta for `parcoords` selection bars.
However users may be interest to be able set this value to other colors and per trace.
A similar `arrayOk` option for width and opacity could help this trace type look really cool while reducing the need of displaying and reading long title names for the operators.
https://github.com/plotly/plotly.js/blob/57c1fbdbf3a82855fef533e44eb82c35c93f0575/src/traces/parcoords/constants.js#L23-L26

**Comment by alexcjohnson** [comment] 2019-06-11 19:03
Or nested in `dimensions`, with trace-wide options as the default for all dimensions.

**Comment by archmoj** [comment] 2019-06-11 19:06
Good call.
@alexcjohnson Any suggestion for attribute names?

**Comment by alexcjohnson** [comment] 2019-06-11 19:32
hmm, we have a bit of an inconsistency already between `constraintrange` and `multiselect` - so we could use either `constraintline` or `selectionline` -> `{color, width}` - making it a container is nice because if later we want to add a [`mode: 'box'`](https://syntagmatic.github.io/parallel-coordinates/) or something, with additional attrs, we can always do that inside the container. That kind of possibility makes `*line` seem a bit funny... `selectionstyle`?
![Screen Shot 2019-06-11 at 3 28 52 PM](https://user-images.githubusercontent.com/2678795/59300633-a7687a00-8c5d-11e9-95c5-78431875ccf8.png)

**Comment by archmoj** [comment] 2019-06-11 19:40
True. We basically have `selected`, `deselected` & `selector` lines there.

**Comment by KaleabTessera** [comment] 2020-10-30 16:15
+1

**Comment by gvwilson** [comment] 2024-06-14 12:02
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-14 12:02 UTC
Labels: type: feature
