### ISSUE TITLE
Lines wrongly calculated while zoomed

### ISSUE THREAD

**Issue by Jodana** [plotly/plotly.js#334] opened 2016-03-16 14:31 UTC
While trying to reproduce the #333 bug, I have found lines that were not positioned correctly if the zoom goes through a certain level.

![image](https://cloud.githubusercontent.com/assets/17881065/13815522/32ff3486-eb8b-11e5-85a0-8b52713f94e3.png)

When in this state, panning on the X axis triggers a recalculation of the line position, but still not correctly.

![capture3](https://cloud.githubusercontent.com/assets/17881065/13815583/71a4c52a-eb8b-11e5-9dbd-488f35a1faf3.PNG)

I simply wanted to know if there is an underlying bug, or if it is simply a precision issue.

**Comment by etpinard** [comment] 2016-03-16 15:00
Duplicate of https://github.com/plotly/plotly.js/issues/217

**Closed by etpinard** 2016-03-16 15:00 UTC
Labels: type: duplicate
