### ISSUE TITLE
Replace country-regex

### ISSUE THREAD

**Issue by keithrob** [plotly/plotly.js#3944] opened 2019-06-08 19:52 UTC
I have created a PR[1] to replace country-regex due to some licensing issues.  Motivation for the change is detailed in the PR itself.

[1] https://github.com/keithrob/plotly.js/pull/1

@etpinard , @archmoj FYI

**Comment by keithrob** [comment] 2019-06-21 18:45
@etpinard ,
Any update on whether or not country-regex can be removed?  Another option might be to make it a pluggable/optional component that isn't included with the base package.

**Comment by G-2-Z** [comment] 2020-05-28 11:12
Is there any update on this? Its been almost a year now and this little dependency is a big hurdle for anything not open source wanting to use plotly, if they stumble uppon it (country-regex itself is still MIT).

**Comment by gvwilson** [comment] 2024-06-14 12:02
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-14 12:02 UTC
