### ISSUE TITLE
Labels wrongly displayed in bar charts with showlegend false option

### ISSUE THREAD

**Issue by nflorentin** [plotly/plotly.js#2236] opened 2018-01-08 16:35 UTC
Hi,

It seems that the display of labels fails with a bar chart with the following characteristics:
- a unique value on the x axis
- option "showlegend: false" for the layout

An example here: https://jsfiddle.net/m07hszmn/8/

**Comment by alexcjohnson** [comment] 2018-01-08 18:21
Duplicate of #2154 (and likely #865 by extension) I believe. Feel free to reopen if I'm missing something.

**Closed by alexcjohnson** 2018-01-08 18:21 UTC
