### ISSUE TITLE
dragging horizontal or vertical line shape does not work in safari

### ISSUE THREAD

**Issue by vttrifonov** [plotly/plotly.js#3877] opened 2019-05-17 23:37 UTC
I am trying this example 

[https://plotly-r.com/interactives/shiny-drag-line.html](url)

and it does not seem to work in Safari: when I move the mouse over the dotted line it never converts to a hand and I cannot drag the dotted line as the example intends.

The example works for me in Chrome (Mac and PC) and IE.

I am using Safari Version 12.1.1 (12607.2.6.1.2) on macOS Sierra 10.12.6

**Comment by cpsievert** [comment] 2019-05-21 18:26
Here's a minimal example of the same issue https://codepen.io/cpsievert/pen/oRopKy

**Comment by gvwilson** [comment] 2024-06-14 11:59
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-14 11:59 UTC
Labels: type: bug
