### ISSUE TITLE
Uncaught TypeError while zooming during extendTraces 

### ISSUE THREAD

**Issue by galuha** [plotly/plotly.js#3616] opened 2019-03-07 22:20 UTC
Hello.
The problem is, when zooming with the mouse selection while Plotly is doing extendTraces, it throws this "Uncaught TypeError: Cannot read property 'length' of undefined".
To reproduce, try to zoom the chart, i.e. select some area and hold the selection for a while. The error will be visible in the browser console

https://codepen.io/galuha/pen/ywMmPZ?editors=1111

**Comment by archmoj** [comment] 2019-03-07 22:42
@galuha Thanks for the report as well as clear codepen.

**Comment by etpinard** [comment] 2019-03-07 22:44
Essentially a duplicate of https://github.com/plotly/plotly.js/issues/3305

**Closed by etpinard** 2019-03-07 22:44 UTC
Labels: type: bug
