### ISSUE TITLE
Sync zoom and spike lines

### ISSUE THREAD

**Issue by SirCameron** [plotly/plotly.js#3863] opened 2019-05-14 20:04 UTC
Hi 

Is it possible to sync up zoom and spike lines over 2 or more graphs?
ie: if a user zooms into one graph, is there an event on that graphs and methods on a second graph that allow me to sync them up?
the same question applies when moving the mouse over graph 1.. is there an event I can attach to and methods on the second graph that would allow me to draw a spike line?

I've looked at the api and have not been able to find this.

many thanks

**Comment by etpinard** [comment] 2019-05-14 20:09
Essentially a duplicate of https://github.com/plotly/plotly.js/issues/2517

Thanks for posting!

**Closed by etpinard** 2019-05-14 20:09 UTC
