### ISSUE TITLE
Provide TypeScript definitions (aka d.ts file)

### ISSUE THREAD

**Issue by david-bouyssie** [plotly/plotly.js#28] opened 2015-11-23 17:31 UTC
The TypeScript transpiler is a useful tool for the development of web applications with a large codebase.

Popular graphics libraries such as Highcharts provides typescript definition files allowing to use their API in a safe way when called from TypeScript code.

It would be awesome if such a definition file was available for plotly.js.
The work consists in creating a TypeScript interface for each object of the public Javascript API.

**Comment by xuyang2** [comment] 2015-11-24 14:14
+1

**Comment by etpinard** [comment] 2015-11-24 14:23
I've never used typescript before. 

Could you point me to good resources or examples of other projects that support typescript (I couldn't find the relevant file in the highcharts repo).

**Comment by xuyang2** [comment] 2015-11-25 04:15
@etpinard take a look at https://github.com/DefinitelyTyped/DefinitelyTyped/

**Comment by david-bouyssie** [comment] 2015-11-25 07:06
@etpinard the Handbook from the Microsoft website is a good starting point.
http://www.typescriptlang.org/Handbook
You may also be interested by their tutorials and samples:
http://www.typescriptlang.org/Tutorial
http://www.typescriptlang.org/Samples

This blog is also an interesting resource: http://www.johnpapa.net/typescriptpost1/

As xuyang2 said the DefinitelyTyped repo is the place the search for existing TS declaration files.
Here is the folder corresponding to Highcharts: https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/highcharts

About IDE support:
* Visual Studio has a built-in support of TypeScript
* Intellij and Webstorm also provide a support through a free plugin. I think it now installed by default.
* Under Eclipse (I develop my TS project under Eclipse) I suggest to use the free plugin from the palantir company: https://github.com/palantir/eclipse-typescript

Now about the methodology you have two possibilities:
1. Keep the development of plotly.js in pure JS and provide TS declaration files. They will contain interfaces describing your functions, classes and objects. This will be done in a "d.ts" file (d standing for declaration).
2. Develop plotly.js directly in TS. You will benefit from the type-safety of the language which simplifies the refactoring of big projects. The compiler will generate for you a JS file that could be used as a dro-pin replacement of plotly.js and a plotly.d.ts file corresponding to the API of your plotly.ts file. This plotly.d.ts will be useful for other TS developers.

I will suggest to start with approach 1. and to switch to 2. if you think it is useful for your team.
Note that the declarations defined in approach 1 could leveraged when switching to the TS dev, so you won't loose your work.

As a short example if you have a JS config object defining points coordinates, you w'ill define something like that in JS:
```
var point = { x: 10, y: 20 };

function plotPoint(p) {
 // your JS code here
}

plotPoint(point);
```

To provide a TS type describing this JS object here is what you should have in your "d.ts" file:
```
interface Point {
  x: number;
  y: number;
}

declare function plotPoint(p: Point): void
```

Now if you define your code directly in a TS file, this should be like this:
```
interface Point {
  x: number;
  y: number;
}

function plotPoint(p: Point): void = {
 // your TS code here
}

var point = <Point>{ x: 10, y: 20 };
plotPoint(point);
```

Compiling your TS file will result in the JS and .d.ts code above. But as you can see when switch from d.ts to .ts coding, we re-use interfaces defined in the d.ts file. Only the TS code has to be ported from the JS one.

Hope this will be useful.

Best.

**Comment by xuyang2** [comment] 2015-11-26 11:39
@etpinard Videos on Typescript
* [Evolving JavaScript with TypeScript by Anders Hejlsberg](https://www.youtube.com/watch?v=Ut694dsIa8w)
* [Introducing TypeScript by Anders Hejlsberg](https://www.youtube.com/watch?v=IRunqezn4pQ)
* [Typescript Demystified](https://www.youtube.com/watch?v=kb7tvaBJeMs)

**Comment by ryanlin1986** [comment] 2015-11-27 02:18
+1

**Comment by bpostlethwaite** [comment] 2015-12-03 14:24
Thanks for the information! Plotly intends to focus on feature development, bug fixing and performance. Internally we are satisfied with a minimal build system and vanilla JS as this reaches a wide developer and user base. TypeScript is an amazing project that brings static tooling and safety to JS so we have marked this issue as `community` and are open to any TypeScript definition PRs.

**Comment by ichpuchtli** [comment] 2015-12-15 03:41
+1

**Comment by stefan505** [comment] 2015-12-15 09:04
Would really like to see `.d.ts` for Plotly.

**Comment by lifan0127** [comment] 2016-01-09 12:40
+1

**Comment by zheffie** [comment] 2016-03-13 17:49
+1

**Comment by george3447** [comment] 2016-08-25 11:44
+1

**Comment by stemcstudio** [comment] 2017-03-09 01:25
Plotly folks,
I have been working with my own TypeScript definition file for plotly.js for some time now. I would be glad to contribute it to the project. I do not have the bandwidth to get involved with plotly development so I would have to simply hand off the index.d.ts file to you. It accurately describes a UMD library. It "belongs" with you as a versioned artifact. It would be great for you to release it with the distribution. The TypeScript project describes how to integrate the file with your project and NPM. I can't attach the file because the type is not supported. Please shoot me an email at david.geo.holmes@gmail.com and I'll send it to you.
Best,
David Geo Holmes https://github.com/geometryzen

BTW. Love Plotly. I'm pushing it into education. See it at https://www.stemcstudio.com (best in Chrome).

**Comment by stefan505** [comment] 2017-03-23 12:27
@stemcstudio , plotly has [starter definitions](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/plotly.js/index.d.ts) on DefinitelyTyped. Why not consider creating a pull request for your definitions? 

That way, people usings Typings and TypeSearch (npm @Types) can simply use it.

Also check out this: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/7202 

cc @chrisgervang

**Comment by chrisgervang** [comment] 2017-03-25 04:02
Just opened a PR for the definitions file I've been working on: DefinitelyTyped/DefinitelyTyped#15379

**Comment by chrisgervang** [comment] 2017-06-10 20:27
Adding the legend layout: DefinitelyTyped/DefinitelyTyped#17108

**Comment by alanpurple** [comment] 2017-08-11 00:55
As I said in issue board of plotly.js repository, this is not compatible with 3dscatterplot ( try example in official page )

**Comment by alanpurple** [comment] 2017-08-14 07:01
there is no datatype for boxplot

**Comment by davidctj** [comment] 2017-09-13 12:56
I built a simple react typescript plotlyjs module for the people who looking for simple solution in typescript, check it here
https://github.com/davidctj/react-plotlyjs-ts

**Comment by chrisgervang** [comment] 2017-09-16 20:42
@alanpurple, would you mind adding those types to our definition in DefinitelyTyped? Our communities definition isn't complete unfortunately, as there are tons and tons of graphs and components in plotly.

If you don't want to, then everything should work just fine if you use `any` type since it's just javascript and the plotly library will work without typescript.

I'd be happy to review the PR for you and help were needed.
To make additions:
1. clone definitlytyped repo
2. make branch for your change
3. find the plotly.js definition file in the repo and make your changes. 
- You can test your changes against your code by copying the definition file into your project somewhere and including it with your tsconfig.json (I think the `types` compiler option is where that goes, or `files`
- To figure out what the definition should be I read the plotly code, looking for `attribute` files. I also used `any` types while testing my comprehension of the source code.
4. Add an example (helps others a lot!)
5. Once it looks good, publish the branch and make a PR. You can @mention me (and I think it auto mentions the original contributor)

**Comment by alanpurple** [comment] 2017-09-17 04:22
@chrisgervang  Okay I'll try

**Comment by brian428** [comment] 2018-02-15 22:28
I have a Gradle-based TSD generator that parses the plot-schema.json file and generates a TypeScript TSD. I'll attach it here in case anyone finds it useful. If I hear back that it's working for others, I may add it to DefinitelyTyped.

[plotly.js.zip](https://github.com/plotly/plotly.js/files/1729618/plotly.js.zip)

**Comment by brian428** [comment] 2018-07-02 16:23
@EricForgy sorry, I hadn't checked this thread in a while. I'm **sure** there are places where things aren't quite right (which will almost always be due to related issues with the Plotly schema JSON that the TSD is generated from, or less common "multiple-type" options for various properties). Since I mainly use the scattergl plots, and not the other plot types, I'm sure it'll take a range of people trying to use it to really squash any lingering problems with the TSD.

**Comment by jacobq** [comment] 2019-01-24 16:53
There are 2 things I'd like to add to the discussion for consideration:

1. Are the long lists of choices, e.g. names of marker symbols (`Drawing.symbolList`), provided separately or are they missing? I'm thankful for the [current (community provided) type definitions](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/plotly.js), but the "magic strings" are what I most wanted to get from there since I have trouble remembering them & thus frequently make mistakes. 

2. Rather than using union types of literal strings (e.g. `'linear' | 'spline' | 'hv' | 'vh' | 'hvh' | 'vhv'`), could we use an [`enum`](https://www.typescriptlang.org/docs/handbook/enums.html) instead? This helps make those lists accessible so that consuming applications do not need to duplicate them. e.g. One could do something like this:
    ```js
    // definition
    export const enum LineShapeType {
      Linear = 'linear',
      Spline = 'spline',
      HV = 'hv',
      VH = 'vh',
      HVH = 'hvh',
      VHV = 'vhv',
    }
    // ...
      'line.shape': LineShapeType;
    // ...
    
    // user code
    import { LineShapeType } from 'plotly.js';
    // ...
    const choices = Object.values(LineShapeType);
    // ...
    ```

**Comment by brian428** [comment] 2019-01-24 17:55
@jacobq I'm not sure if you're referring to the current TSD on DefinitelyTyped, or my new TSD (zip is above). But for my version, the main challenge is that it is generated from the Plotly source code (mainly via `plot-schema.json`). The TSD **has** to be generated (IMO), because the changes come too quickly and the API is too vast to try and keep up with it manually. My version, which I think is fairly complete, is over 26,000 lines (including doc comments).

I'm not sure that creating enums for the various "magic strings" will work, because an ambient TSD is a compile-time-only artifact. (If there's a way to export concrete types from a TSD, I'm not aware of it.) But it _might_ be possible to generate a non-TSD "companion" file that could be copied into a project.

**Comment by jacobq** [comment] 2019-01-24 20:58
> I'm not sure if you're referring to the current TSD on DefinitelyTyped, or my new TSD (zip is above). 

I had been using what I found on DefinitelyTyped (`yarn add -D @types/plotly.js`). 

> The TSD **has** to be generated (IMO), because the changes come too quickly and the API is too vast to try and keep up with it manually.

I agree. Ideally, plotly.js would define and export these itself to ensure that they're always consistent and to avoid the need for a separate package. In the mean time, generating it programmatically for each plotly.js release seems like a reasonable stop-gap solution.

> I'm not sure that creating enums for the various "magic strings" will work, because an ambient TSD is a compile-time-only artifact. (If there's a way to export concrete types from a TSD, I'm not aware of it.) But it _might_ be possible to generate a non-TSD "companion" file that could be copied into a project.

While I don't know all the technical details, I've seen this done in other definition files in DefinitelyType's repo. For example [in `@types/webc`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/5344bfc80508c53a23dae37b860fb0c905ff7b24/types/webcl/index.d.ts#L325-L685) (try searching the repo for `"const enum"`; there are a lot of results). Maybe it's not as simple as I imagine, but since string enums are just named string literals they should be functionally the same (i.e. everything happens at compile time).

**Comment by brian428** [comment] 2020-04-07 13:22
Just figured I'd update this with a TSD for 1.53.0 if anyone has use for it.
[plotly.js.zip](https://github.com/plotly/plotly.js/files/4444566/plotly.js.zip)

**Comment by gvwilson** [comment] 2024-06-05 12:39
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson

**Closed by gvwilson** 2024-06-05 12:39 UTC
Labels: type: community
