### ISSUE TITLE
Spike: Not removable border or shadow

### ISSUE THREAD

**Issue by fsmeier** [plotly/plotly.js#3042] opened 2018-09-24 11:47 UTC
Hey,

I just figured out that spikes have a small border or shadow I can not change over the options. I also did not find any similar topic here, in the docu or via google.

Example: https://codepen.io/anon/pen/yxWaRL
![spike-border](https://user-images.githubusercontent.com/1506919/45950423-fdc65780-bfff-11e8-9246-2e5f07a28f88.PNG)

Tested in FF and Chrome on Windows10.

Is this a wanted behaviour? If yes: why has it be like this? Any tech-reason? 
If no: how can I contribute to fix this?

All the best,
Florian

**Comment by alexcjohnson** [comment] 2018-09-24 13:38
Good point, we allow changing the thickness of the spike line but there's always a  1px border around it matching the plot background

https://github.com/plotly/plotly.js/blob/7714aa6f6bb9421c1cc0f94245a10b58475d86f8/src/components/fx/hover.js#L1335

The reason for this is to make sure the spike is always visible no matter what data or background it crosses. But we could certainly add a way to control this; as your example shows, it's not necessary in all cases.

Would make a great first PR if you're looking to get involved 🙏

**Comment by cacsfre** [comment] 2020-10-08 20:37
Hi ! Any workaround on this ? I'm facing the same issue using a transparent background : 

![spikes](https://user-images.githubusercontent.com/50526826/95510823-84022c00-0984-11eb-8d8f-8ea182511fd6.png)

It looks good on a light theme, but certainly not as expected on a dark theme.

**Comment by gvwilson** [comment] 2024-06-11 17:22
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson

**Closed by gvwilson** 2024-06-11 17:22 UTC
Labels: type: feature, type: community
