### ISSUE TITLE
Persistent Selection Handles and Draggable Box Select

### ISSUE THREAD

**Issue by chriddyp** [plotly/plotly.js#1851] opened 2017-07-04 18:22 UTC
In addition to customized selection styles (https://github.com/plotly/plotly.js/issues/1847) and persistent selection data (https://github.com/plotly/plotly.js/issues/1848), it'd be nice if selection box widget could be made persistent and modifiable. 

Crossfilter.js has a great example of this:

![image](https://user-images.githubusercontent.com/1280389/27840065-0b36f286-60c4-11e7-95d0-b59b11bf4c57.png)

**Comment by etpinard** [comment] 2017-07-04 18:34
Like https://github.com/plotly/plotly.js/issues/181 ?

**Comment by monfera** [comment] 2017-11-03 08:43
@etpinard having read the original post https://github.com/plotly/plotly.js/issues/181#issue-126633751 it looks like that was more about specific issues back then. The description doesn't mention the above select box resizing. Maybe that issue was renamed to reflect intention for working on it; let me rename it back so it sticks to its original feedback and let's continue with this this issue for the select box resizing manipulation.

**Comment by siakouchine** [comment] 2018-12-17 10:56
Hello Plotly team, do you have any news about this issue? The example of behavior defined in Crossfilter in terms of persistent selection handles and draggable box is exactly what we are looking for for our plots. Do you think it could be implemented shortly?

**Comment by mlisthenewcool** [comment] 2021-03-11 09:33
Hi, any news about this issue from Plotly team ? Something like [brushable-scatterplot-matrix](https://observablehq.com/@d3/brushable-scatterplot-matrix) would be awesome !
Did someone managed to find a way around this issue ?

**Comment by nicolaskruchten** [comment] 2021-03-11 18:39
This isn't on our roadmap at the moment but we're still very interested in this feature if someone wants to work on some pull requests or sponsor it!

**Comment by gvwilson** [comment] 2024-06-10 15:55
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson

**Closed by gvwilson** 2024-06-10 15:55 UTC
Labels: type: feature, status: discussion needed, ♥ NEEDS SPON$OR
