### ISSUE TITLE
Sankey link ordering bug

### ISSUE THREAD

**Issue by alexcjohnson** [plotly/plotly.js#4390] opened 2019-11-29 15:49 UTC
While tweaking a sankey diagram for publication, I ran into a funny bug in the link layout algorithm: links sometimes cross unnecessarily, depending on the positions of their source & target nodes.
https://codepen.io/alexcjohnson/pen/abbxdWW?editors=0010
```js
// <=0.24 gets the link order correct,
// >=0.25 swaps the links incorrectly
var yYellow3 = 0.24;
```
correct @ 0.24:
![Screen Shot 2019-11-29 at 10 37 21 AM](https://user-images.githubusercontent.com/2678795/69879212-de2a5f00-1294-11ea-9bd9-80302a340057.png)

wrong @ 0.25:
![Screen Shot 2019-11-29 at 10 36 53 AM](https://user-images.githubusercontent.com/2678795/69879230-e84c5d80-1294-11ea-9a0f-4f3ca31f7eb4.png)

**Comment by antoinerg** [comment] 2019-11-29 16:13
Thanks for reporting this issue @alexcjohnson . It seems like the underlying layout engine https://github.com/d3/d3-sankey is not giving an optimal result in this instance. This does not really surprise me: it focuses on being fast and gives no guarantees that it converges to an optimal solution. In this sense, this is not really a bug. Two options:

1. Try to "fix" https://github.com/d3/d3-sankey
2. Write our own layout algorithm

**Comment by alexcjohnson** [comment] 2019-11-29 16:26
Not high priority bug, but it definitely is a bug, and since we're operating our own fork of `d3-sankey` at this point, we certainly have the control to fix it.

To be clear this isn't anything about node positioning - in the example here I'm positioning the nodes 100% manually, and just expecting the best links drawn between them.

**Comment by gvwilson** [comment] 2024-06-14 12:53
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-14 12:53 UTC
Labels: type: bug
