### ISSUE TITLE
Plotly Not Responsive When Parent Size Changes

### ISSUE THREAD

**Issue by YoavIlan** [plotly/plotly.js#3984] opened 2019-06-25 19:28 UTC
Hi,

I am having issues with Plotly not resizing properly when the parent component changes in size. The plot has responsive set to true, but that only affects it in the case of a window resize, not a resizing of the parent component.

See this [stackblitz](https://stackblitz.com/edit/angular-y2kbzh) for a reproduction of the issue. It highlights the issue both within a flexbox and when a scrollbar is introduced into the view.

**Comment by antoinerg** [comment] 2019-06-25 21:25
Unfortunately, until majors browsers start supporting [`resizeObserver`](https://developers.google.com/web/updates/2016/10/resizeobserver), there is no way to be notified when an element changes size.

If we can't call `Plotly.Plots.resize(gd)` on a resize event, the only other way to achieve the desired behavior would be to produce fully-scalable SVG as discussed in https://github.com/plotly/plotly.js/issues/2711 . Unfortunately, addressing #2711 is not a simple fix.

**Comment by etpinard** [comment] 2019-06-26 14:28
It should be pretty easy for plotly.js users to call `Plotly.Plots.resize(gd)` inside a `resizeObserver` callback. 

Maybe we should add an example in our docs. @antoinerg would you be interested in making a quick codepen showing that off?

**Comment by antoinerg** [comment] 2019-06-27 01:07
Here's a proof of principle of using  `resizeObserver` (tested to work in Chrome). In order to show that it really works using `resizeObserver`, I turn off plotly.js' responsive config option: https://codepen.io/antoinerg/pen/KjXbEo

Note that one should probably turn responsive on when using this to make the proper CSS to grow and shrink in `flexbox` and `grid` is applied (see PR https://github.com/plotly/plotly.js/pull/3056 for details).

**Comment by TrevorKarjanis** [comment] 2019-07-12 21:20
Looks like the observer compatibility is improving, although, it is still in draft. Thank you for the codepen.
https://caniuse.com/#feat=resizeobserver
https://developer.microsoft.com/en-us/microsoft-edge/platform/status/resizeobserver/

**Comment by pcparagc** [comment] 2021-05-24 12:00
> Here's a proof of principle of using `resizeObserver` (tested to work in Chrome 72). To make the example clear, I turned off plotly.js' responsive config option: https://codepen.io/antoinerg/pen/KjXbEo
> 
> Note that one should probably turn responsive on for real usage to apply the appropriate CSS to grow and shrink in `flexbox` and `grid` (see PR #3056 for details).
> 
> [MDN - ResizeObserver#Browser_compatibility](https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver#Browser_compatibility)

Is there any codepen for react also? I am stuck with the issue (When i open my sidebar the graph goes outside of parent div)

**Comment by gvwilson** [comment] 2024-06-14 12:02
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-14 12:02 UTC
