### ISSUE TITLE
Plot export (using toolbar) not working properly under IE and Edge

### ISSUE THREAD

**Issue by bruno-rino** [plotly/plotly.js#1408] opened 2017-02-23 12:04 UTC
The "download plot as a png" toolbar button is not working properly under IE and Edge.

Firstly, I get an SVG instead of an PNG.

Secondly, the SVG is URI encoded, which makes it unusable.

This can be reproduced with the "Hello World" plot from the "Getting started" page:
http://codepen.io/plotly/pen/PPVeer

This is the "SVG" I get:
http://pastebin.com/dKzyFyXx

I'm using these versions of the browsers (from the stable win10 available at https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/):
IE 11.0.14393
Edge 38.14393

**Comment by bruno-rino** [comment] 2017-02-23 12:15
And there's a thirdly!

A more complex plot has yet another issue:
http://codepen.io/bruno-rino/pen/xqxwXJ

After URL decoding the downloaded "SVG", the xml has a few errors related to mismatched quotes:
```
clip-path='url("clip037303xyplot')'
```
and
```
clip-path='url('#legend037303")'
```

**Comment by etpinard** [comment] 2017-02-23 15:08
duplicate of https://github.com/plotly/plotly.js/issues/699

**Closed by etpinard** 2017-02-23 15:08 UTC
