### ISSUE TITLE
Allow user to revert to the assigned hovermode after clicking on compare or closest

### ISSUE THREAD

**Issue by jonmmease** [plotly/plotly.js#3832] opened 2019-05-03 10:30 UTC
From https://github.com/plotly/plotly.py/issues/1545 by @AlexC84

> The user/viewer of a plot is currently unable to revert back to the assigned hovermode for the plot if it is set to False in the layout. The plot will load with hovermode initially set to False but as soon as the user clicks on 'Show closest data on hover' or 'Compare data on hover' they can't turn hovermode back off without reloading the plot.
>
> the same is true if the hovermode is set to 'y' in the layout; as soon as the user clicks on 'Show closest data on hover' or 'Compare data on hover' the user can't revert to the assigned hovermode and they're stuck with either 'hovermode':'closest' or 'hovermode':'x'

For the `hovermode: false` case, I could see it making sense to support toggling off the hovermode by clicking the active mode.  I'm not sure what the UI should look like to restore `hovermode:'y'`.  

This wouldn't be backward compatible, but if the original hovermode is `hovermode:'y'`, would it make sense for the "compare data on hover" button to switch back to `hovermode:'y'` instead of `hovermode:'x'`?

**Comment by AlexC84** [comment] 2019-05-03 11:49
Thanks for opening this in the correct place.

Currently the 'Compare' UI button has two horizontal 'labels' for the button image, maybe have the button image toggle between that image for `hovermode: 'x'` and then flip these labels to vertical to indicate `hovermode:'y'` and greyed out for `hovermode: False`?

**Comment by gvwilson** [comment] 2024-06-14 11:56
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-14 11:56 UTC
Labels: type: feature
