### ISSUE TITLE
Bar diagram wrong end point with time on x axis

### ISSUE THREAD

**Issue by robmass** [plotly/plotly.js#3148] opened 2018-10-24 16:01 UTC
Hi, I was creating a timeline diagram and I found that, in order to have a correct endpoint of the bar, the data must be one hour before the real end time. You can see the bug in the following codepen: 
https://codepen.io/anon/pen/YJRNJy

**Comment by etpinard** [comment] 2018-10-25 02:10
I think this might be a duplicate of https://github.com/plotly/plotly.js/issues/2391

**Comment by alexcjohnson** [comment] 2018-10-25 13:43
Yes, duplicate of one part of #2391 anyway. @robmass I'm guessing you're 1 hour away from UTC right now? Because I see a 5-hour error in that codepen (wait but I'm in UTC-4... huh, somehow it's getting the non-daylight shift? anyway it's the same problem)

**Closed by alexcjohnson** 2018-10-25 13:43 UTC
