### ISSUE TITLE
scatter3d error-bar hoverlabel inconsistent with scatter

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.js#4133] opened 2019-08-17 02:04 UTC
The hoverlabels in this pen https://codepen.io/nicolaskruchten/pen/wVqBKY don't include the error information the way it would show up in 2d `scatter`

**Comment by gvwilson** [comment] 2024-06-14 12:48
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-14 12:48 UTC
Labels: type: feature
