### ISSUE TITLE
Adding traces on hover can cause infinite loops

### ISSUE THREAD

**Issue by cpsievert** [plotly/plotly.js#1467] opened 2017-03-11 00:53 UTC
MRE of the problem (hover on any of the markers) -- http://codepen.io/cpsievert/pen/dvWydK

FYI this was working pre-1.24.0 -- http://codepen.io/cpsievert/pen/qrmBVx

**Comment by rreusser** [comment] 2017-03-11 02:59
I think either 1.24.1 or 1.24.2 might already fix this.

**Comment by etpinard** [comment] 2017-03-13 13:57
Thanks for posting @cpsievert !

#1446 fixed a `plotly_unhover` -> `Plotly.Fx.hover` -> `plotly_unhover` infinite. But looks like `addTraces` suffers from another https://github.com/plotly/plotly.js/pull/1304 side-effect.

We should fix this before releasing [`1.25.0`](https://github.com/plotly/plotly.js/milestone/18).

**Comment by etpinard** [comment] 2017-03-13 18:50
Ok. This problem is pretty tricky and is quite frankly (unless @cpsievert can prove otherwise) an edge case. 



The infinite loop is triggered only when `addTraces` adds a trace containing similar enough coordinates to the one given in the `plotly_hover` event data. For example take http://codepen.io/etpinard/pen/xqrjza which adds traces outside the hover distance and does not trigger an infinite loop.

In @cpsievert 's http://codepen.io/cpsievert/pen/dvWydK, an infinite loop is triggered since https://github.com/plotly/plotly.js/pull/1304 because:

- `addTraces` now leads to a [`Plots.rehover`](https://github.com/plotly/plotly.js/blob/d5303abf8dc9458cfe41660731383d8f333e7882/src/plots/plots.js#L2042) call (via `Plotly.redraw`),
- `Plots.rehover` leads to a [`Fx.hover`](https://github.com/plotly/plotly.js/blob/d5303abf8dc9458cfe41660731383d8f333e7882/src/plots/cartesian/graph_interact.js#L279) cal which then leads to
- `Fx.hover` emiiting `plotly_hover` even though the mouse position hasn't changed ([here](https://github.com/plotly/plotly.js/blob/d5303abf8dc9458cfe41660731383d8f333e7882/src/plots/cartesian/graph_interact.js#L624) `hoverChanged(gd, evt, oldhoverdaa)` is true as the `curveNumber` changed after the `addTraces` call)
- and then the `plotly_hover` handler triggers `addTraces`
- :loop: 
---

Now, how to fix this problem?

In my opinion, I think the most robust solution would be to make `rehover` not trigger `gd.emit('plotly_hover')` while still updating `gd._hoverdata` and the visible hover labels.

@rreusser @alexcjohnson event data updates wasn't :lock: ed down in the https://github.com/plotly/plotly.js/pull/1304 tests, so I guess this would be ok?

**Comment by alexcjohnson** [comment] 2017-03-13 19:35
Honestly I'm not sure if I would consider this a bug - yes it's an infinite loop, but you'd get an explosion of traces in a case like this anyway, at least for real data sets where you cause hundreds of hover events every time the mouse crosses the plot. And I do think we want rehover-hovers to emit an event so the more typical case of updating something outside the plot (or on a different subplot at least) will still happen.

Is there a more realistic use case for this? There are always going to be ways to trigger infinite loops when you modify a plot from inside an event handler, and I think at some level it's up to the user to avoid these, otherwise we'll be restricting what they can do.

**Comment by cpsievert** [comment] 2017-03-13 19:40
> Is there a more realistic use case for this? 

It basically enables all of this -- https://cpsievert.github.io/plotly_book/linking-views-without-shiny.html

> you'd get an explosion of traces in a case like this anyway

I do a check to make sure I don't add the same trace twice. The example I linked to was a simplified version to help isolate the issue.

**Comment by rreusser** [comment] 2017-03-13 19:47
@cpsievert just to clarify: the objective of #1304 is to update the hover state when the plot changes, e.g. streaming or animation and maybe a few other cases @alexcjohnson mentioned that were considered long-running issues where the hover state would not update to reflect new data until new mouse input triggered a new hover.

I think `plotly_hoverupdate` on rehover wouldn't be bad if it's not too bad to implement and if it's enough to disambiguate. At least then there's a way to distinguish between hover state changing as the result of input vs. reflecting a new state.

**Comment by alexcjohnson** [comment] 2017-03-13 20:21
> I do a check to make sure I don't add the same trace twice. The example I linked to was a simplified version to help isolate the issue.

After that check do you still have a problem (and if so can you post it?), or were you just hoping not to need the check?

I wouldn't want to add a new event type for rehover, because then people would have to know that in the normal case they need to listen to both types. But we could certainly add something to the event to indicate whether it was triggered by a mouse event or something else like a rehover. Like... the mouse event itself? That could come in handy for other purposes too.

**Comment by cpsievert** [comment] 2017-03-13 20:36
> After that check do you still have a problem (and if so can you post it?), or were you just hoping not to need the check?

Ooops -- I thought I had implemented that check, but it appears I haven't yet. Will work on it and report back if I still have issues, thanks!

**Comment by etpinard** [comment] 2017-03-13 22:10
Looks like this issue is up in the air. 

Dropping from `1.25.0` for now. Adding `discussion needed`.

**Comment by alexcjohnson** [comment] 2017-07-07 21:02
This seems to have broken the last codepen on the hover event docs page https://plot.ly/javascript/hover-events/

https://codepen.io/plotly/pen/eJOyej

FYI @cldougl

**Comment by jackparmer** [comment] 2020-09-10 19:41
This issue has been tagged with `NEEDS SPON$OR`

A [community PR](https://github.com/plotly/plotly.js/pulls?q=is%3Apr+is%3Aopen+label%3A%22type%3A+community%22) for this feature would certainly be welcome, but our experience is deeper features like this are difficult to complete without the Plotly maintainers leading the effort.

**Sponsorship range: $5k-$10k**

What Sponsorship includes:
- Completion of this feature to the Sponsor's satisfaction, in a manner coherent with the rest of the Plotly.js library and API
- Tests for this feature
- Long-term support (continued support of this feature in the latest version of Plotly.js)
- Documentation at [plotly.com/javascript](https://plotly.com/javascript/)
- Possibility of integrating this feature with Plotly Graphing Libraries (Python, R, F#, Julia, MATLAB, etc)
- Possibility of integrating this feature with Dash
- Feature announcement on [community.plotly.com](https://community.plotly.com/tag/announcements) with shout out to Sponsor (or can remain anonymous)
- Gratification of advancing the world's most downloaded, interactive scientific graphing libraries (>50M downloads across supported languages)

Please include the link to this issue when [contacting us](https://plotly.com/get-pricing/) to discuss.

**Comment by gvwilson** [comment] 2024-06-10 14:02
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson

**Closed by gvwilson** 2024-06-10 14:02 UTC
Labels: type: bug, status: discussion needed, ♥ NEEDS SPON$OR
