### ISSUE TITLE
Allow users to limit x/y coordinates visible on pan/zoom

### ISSUE THREAD

**Issue by Alanocallaghan** [plotly/plotly.js#1746] opened 2017-05-30 21:58 UTC
I realise this is a tricky ask, but would it be possible to set "hard" limits for the x and y axes of a plot, such that users could not pan (or zoom, though that might be trickier) to areas beyond it?

**Comment by etpinard** [comment] 2017-05-30 22:01
duplicate of https://github.com/plotly/plotly.js/issues/887

**Closed by etpinard** 2017-05-30 22:01 UTC
Labels: type: duplicate

**Comment by Alanocallaghan** [comment] 2017-05-30 22:19
Cheers I had a quick search but couldn't find one, sorry for the duplicate

**Comment by etpinard** [comment] 2017-05-30 22:22
@Alanocallaghan no worries. Searching for previous issues on Github can be a bit of pain. 

Thanks for writing in :beers:

**Comment by samuelnimi** [comment] 2023-07-25 16:07
I have the same question?
