### ISSUE TITLE
Legend drag gets misaligned in the bottom 2/3 of the plot

### ISSUE THREAD

**Issue by alexcjohnson** [plotly/plotly.js#1438] opened 2017-03-02 17:34 UTC
Another one discovered while fiddling re: #1432 - If you make a plot with a legend (perhaps http://localhost:3000/devtools/test_dashboard/#legend_style) and make it editable so you can drag the legend (`Plotly.newPlot(gd, gd.data, gd.layout, {editable: true})`) you can drag the legend around anywhere in the top 1/3 of the plot area and it positions itself correctly. But if you drag it to the middle or bottom of the plot area, it jumps back up a bit when you drop it.

This comes from a miscalculation with `yanchor: auto`, which is the default `yanchor` value, and means that when you're in the middle third of the plot, the position (`legend.y`) is anchored to the middle of the legend, and when you're in the bottom third it's anchored to the bottom of the legend. This setting is designed to make it easy to keep the legend aligned near a corner of the plot even when the plot size might change.

It seems like `x` also has this problem, but it has an additional problem that `xanchor` defaults to `left` rather than `auto` as it should. That may be a tougher one to solve, as we can't just change the default without breaking backward compatibility for some plots...

Annotations (when paper-referenced with no arrow) have the same auto anchor behavior, but they do not have either of these bugs.

**Comment by etpinard** [comment] 2019-09-30 21:01
Looks like https://github.com/plotly/plotly.js/pull/4160 made this behave a little bit better:

![Peek 2019-09-30 16-59](https://user-images.githubusercontent.com/6675409/65916656-b9ecf780-e3a3-11e9-827f-c9d12b6f81e6.gif)

This bug is essentially what @antoinerg noticed while reviewing in #4160 in https://github.com/plotly/plotly.js/pull/4160#issuecomment-534213914

**Comment by gvwilson** [comment] 2024-06-10 14:02
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson

**Closed by gvwilson** 2024-06-10 14:02 UTC
Labels: type: bug
