### ISSUE TITLE
Category axis range values can overlap with categories in category list

### ISSUE THREAD

**Issue by kei51e** [plotly/plotly.js#4449] opened 2019-12-29 02:28 UTC
It happens with the latest on CDN (1.51.3).

If you create a scatter type chart with "lines" mode and categorical X Axis, it doesn't show all the categories. Here is a reproducible pen. https://codepen.io/kei51/pen/vYEJRoW

Sample data.

```
var trace1 = {
  x: [1, 2, 3, 4],
  y: [10, 15, 13, 17],
  type: 'scatter',
  mode:'lines'
};


var data = [trace1];
var layout = {
  xaxis: {
    type:"category"
  }
};
Plotly.newPlot('myDiv', data, layout);

```

Sample screenshot. It should show 1, 2, 3, 4 but it misses 4. 

![image](https://user-images.githubusercontent.com/68080/71551550-eca48d00-299e-11ea-8dac-c005e1fc8d0b.png)

It happens only with specific type of data like 1, 2, 3, 4. It happens only with "lines" mode. It doesn't happen with "lines+scatter" mode.

**Comment by etpinard** [comment] 2020-01-02 21:21
Thanks very much for posting!

This bug happens when the autorange returns a range (`[0, 3]` in this case for the x-axis) with a min/max value to matches a category.

**Comment by gvwilson** [comment] 2024-06-14 12:55
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-14 12:55 UTC
Labels: type: bug
