### ISSUE TITLE
parcoords interactive filtering not working in this example?

### ISSUE THREAD

**Issue by chriddyp** [plotly/plotly.js#3490] opened 2019-01-28 17:53 UTC
Taken from https://nbviewer.jupyter.org/github/plotly/px/blob/master/gallery.ipynb

The bottom part of the chart doesn't update when filtering with the draggable axis handle:

![parcoords-filtering](https://user-images.githubusercontent.com/1280389/51855612-a7458e80-22fb-11e9-907d-28e8a8c1a14e.gif)

Mac
Firefox 64.0.2

**Comment by etpinard** [comment] 2019-01-28 18:03
Duplicate of https://github.com/plotly/plotly.js/issues/3385

**Closed by etpinard** 2019-01-28 18:03 UTC
