### ISSUE TITLE
Parcoords brush can be hidden

### ISSUE THREAD

**Issue by MrHejtmar** [plotly/plotly.js#4622] opened 2020-03-11 12:48 UTC
I am not sure this is an issue, but to me it seems not the best way.

When brush is applied on any axis, it can then be dragged above or below the axis ends.
For example, I drag the applied brush above the axis, so the brush is no longer visible.

However, it means that all lines remain grey in background, but as the brush is no longer visible, user does not know on which axis to click, in order to delete the brush and make all lines visible again.

Example here:
https://codepen.io/mrhejtmar/pen/oNXEWYQ?editable=true
On the second axis, the brush is applied above the axis (by setting constraintrange from 9 to 10), which is the same as if brush was dragged above the axis.
Still, user can't see on which axis the brush is applied to cancel it.

Is this proper behavior?

**Comment by archmoj** [comment] 2020-03-11 13:24
I think that is the proper behavior in terms of selection.
But you are right. Displaying an ( extended ) icon ( e.g. three dots ) for selections that go beyond the visible axis ranges can help.

**Comment by gvwilson** [comment] 2024-06-14 13:00
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-14 13:00 UTC
Labels: type: bug, type: feature
