### ISSUE TITLE
Allow custom formatters for hoverformat and tickformat

### ISSUE THREAD

**Issue by ianrcooke** [plotly/plotly.js#2322] opened 2018-02-01 23:12 UTC
I'd like to be able to provide a callback to `hoverformat` and `tickformat` so that the data can be clearly separated from its presentation and I have finer-grained control than the mini-languages provided by D3.

The issue I'm trying to solve is showing data values over time where time is expressed in relative milliseconds. I want to have x values (time) accessible, e.g. in click events, in their original form (a millisecond count) while displaying the data in hovers and on the x axis ticks as hh:mm:ss.milliseconds.  Currently I appear to have to convert the milliseconds to datetime strings and then when capturing a click event do the conversion back from a datetime string to milliseconds to get my original data.

Other Javascript charting libraries like Chart.js and Highcharts allow this sort of control of display without modification of the underlying data.

A feature like this would also address issues like: https://github.com/plotly/plotly.js/issues/1744

**Comment by etpinard** [comment] 2018-02-01 23:18
Duplicate of https://github.com/plotly/plotly.js/issues/1464

**Closed** 2018-02-02 15:38 UTC
