### ISSUE TITLE
(hover|text)template: list all the available variables in the attribute's description

### ISSUE THREAD

**Issue by antoinerg** [plotly/plotly.js#4139] opened 2019-08-20 17:51 UTC
At the moment, many traces lack a list of the available variables in the `hovertemplate`. For example, `scattermapbox` has none:
https://github.com/plotly/plotly.js/blob/508b1c9c757c7bde0afc3614dcad22825b890b8d/src/traces/scattermapbox/attributes.js#L124

`parcats` is an example of good documentation where all the variables are appropriately listed under `keys`: https://github.com/plotly/plotly.js/blob/508b1c9c757c7bde0afc3614dcad22825b890b8d/src/traces/parcats/attributes.js#L68-L81

**Comment by antoinerg** [comment] 2019-10-02 15:59
Listing all those keys would not only benefit the documentation but could be used to automate our testing to guarantee that they are all really available to `(text|hover)template`.

**Comment by gvwilson** [comment] 2024-06-14 12:50
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-14 12:50 UTC
Labels: type: documentation
