### ISSUE TITLE
Scatter 3d - strange blending when specifying opacity per point using rgba 

### ISSUE THREAD

**Issue by joshua-gould** [plotly/plotly.js#4481] opened 2020-01-10 13:00 UTC
I have attached 3 plots of the same points. The first plot does not set an opacity and looks good. The second plot sets marker.opacity=0.1 and looks ok. The third plot sets the alpha value of every element in marker.color to 0.1 and looks terrible.

![no_opacity](https://user-images.githubusercontent.com/5237151/72154599-12f30100-337f-11ea-863e-ba7efc0c448d.png)
![marker_opacity_0 1](https://user-images.githubusercontent.com/5237151/72154603-15555b00-337f-11ea-96a3-64ecdf608bfc.png)
![marker_color_rgba](https://user-images.githubusercontent.com/5237151/72154614-18504b80-337f-11ea-8eda-4aee68c70073.png)

**Comment by archmoj** [comment] 2020-01-11 02:15
There are some slight differences in this [demo](https://codepen.io/MojtabaSamimi/pen/wvBjeWN?editors=0010), but...
Would you mind sharing a codepen to help us find the source of this problem?
Thanks!

**Comment by archmoj** [comment] 2020-01-11 03:00
On another note implementing `opacityscale` for `scatter3d` (#3940) may be helpful too.

**Comment by joshua-gould** [comment] 2020-01-13 13:09
I created an example at https://jsfiddle.net/joshuagould/d56utzao/6/

**Comment by archmoj** [comment] 2020-01-13 13:57
@joshua-gould 
Thanks very much!

**Comment by archmoj** [comment] 2020-01-13 19:22
May be related: https://github.com/plotly/plotly.js/issues/3138

**Comment by gvwilson** [comment] 2024-06-14 12:55
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-14 12:55 UTC
Labels: type: bug
