### ISSUE TITLE
Custom hover label issue [scatter3d]

### ISSUE THREAD

**Issue by marcus1812** [plotly/plotly.js#2884] opened 2018-08-08 09:58 UTC
If i set custom hover text on point then PointName is duplicated from this text and seems incorrect. I want be able to set both custom name and custom hover.

For example:
![image](https://user-images.githubusercontent.com/18421290/43830589-ee7ae192-9b01-11e8-857a-921722d37c44.png)
I want to see only "FirstPrice" as name of point

Code of trace with incorrect display:
```
                var overbookingShowsPointsX = overbookingShowsPoints.map(point => point.x);
                var overbookingShowsPointsY = overbookingShowsPoints.map(point => point.y);
                var overbookingShowsPointsZ = overbookingShowsPoints.map(point => point.z);
                var overbookingShowsPointsText = overbookingShowsPoints.map(point =>
                    "Days = " + point.x + "<br>" +
                    "Cap = " + point.y + "<br>" +
                    data.currency + " = " + point.z + "<br>" + 
                    point.text);
                var overbookingShowsPointsTrace = {
                    name: "Overbooking & No shows",
                    type: 'scatter3d',
                    mode: 'markers+text',
                    x: overbookingShowsPointsX,
                    y: overbookingShowsPointsY,
                    z: overbookingShowsPointsZ,
                    text: overbookingShowsPointsText,
                    textposition: 'top',
                    hoverinfo: "text",
                    marker: {
                        size: markerRadius,
                        color: 'rgb(11, 31, 255)',
                    },
                    namelength: 0
                };
```

**Comment by etpinard** [comment] 2018-08-08 13:50
What if you set `hoverinfo: 'text+name'`?

**Comment by marcus1812** [comment] 2018-08-10 08:55
Same issue
![image](https://user-images.githubusercontent.com/18421290/43948739-f38d6250-9c8b-11e8-9b05-1f7f2397c51d.png)

**Comment by etpinard** [comment] 2018-08-10 13:25
Hmm. I don't think I understand your problem. Are you referring to the `<br>` characters? If so, this issue is likely a duplicate of https://github.com/plotly/plotly.js/issues/2551

**Comment by marcus1812** [comment] 2018-08-10 14:14
I mean that i should see as name of point - Max overbooking (0%). Instead of this i see text which used in hover div

**Comment by etpinard** [comment] 2018-08-10 15:40
That's because, you have `mode: 'markers+text'`. I think `mode: 'markers'` is what you want.

**Comment by etpinard** [comment] 2018-08-10 16:54
what with `mode: 'markers'` you set `hoverinfo: 'text+name'`? 

If that doesn't work, please use codepen or jsfiddle to sent us a fully reproducible example. I don't think this is a bug, so you might want to look https://community.plot.ly/c/plotly-js for help. Thank you.

**Comment by etpinard** [comment] 2018-08-16 20:48
Closing due to lack of activity.

**Closed by etpinard** 2018-08-16 20:48 UTC

**Comment by marcus1812** [comment] 2018-09-25 10:42
Hello, sorry for lack of activity. I was on vacation.
Here is plotly example: https://plot.ly/~marcus1812/1/
My goal is to see only PointName as name of points of trace: "Overbooking & no shows".

> what with mode: 'markers' you set hoverinfo: 'text+name'?
Its not working
