### ISSUE TITLE
[Feature Request] Allow indexing data in pmeta using x and y coordinates

### ISSUE THREAD

**Issue by orenbenkiki** [plotly/plotly.js#4145] opened 2019-08-18 12:32 UTC
**Problem Description.**

Displaying a heatmap, I'd like to include in the hover box some data which depends only on the X (column) or Y (row).

**Describe the solution you'd like**

Allow specifying `%{data.pmeta.foo.%{x}}` and/or `%{data.pmeta.bar.%{y}}` in the `hovertemplate`. 
In general, if a path element is in the format `%{...}`, then evaluate it, and use this as the next key.

**Describe alternatives you've considered**

It is possible to specify per-entry hover text for a heatmap, but this would require precomputing and sending much more data between the client and the server (N * M complete texts instead of N + M text fragments).

**Comment by orenbenkiki** [comment] 2019-08-26 14:22
Good question...

I think that `%{x}` should be a string and be used as a key. After all, a normal `%{x}` expands into a string.

Perhaps an additional syntax such as `[%{x}]` should be allowed if `x` is known to be an integer and the data is known to be an array. "Explicit is better than implicit" :-)

**Comment by gvwilson** [comment] 2024-06-14 12:49
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-14 12:49 UTC

**Comment by orenbenkiki** [comment] 2024-06-14 13:26
Yes, this is still a concern. But after almost 5 years, is there much point in re-opening it? Perhaps you should have changed the status to "won't fix" rather than "completed".

**Comment by gvwilson** [comment] 2024-06-14 13:33
thanks @orenbenkiki - I'll reopen and assign to myself, and try to get it into our backlog.

**Comment by orenbenkiki** [comment] 2024-06-14 13:39
Thanks!
