### ISSUE TITLE
Default color for gauge chart should be from default palette instead of green

### ISSUE THREAD

**Issue by mtadams007** [plotly/plotly.js#4311] opened 2019-10-28 15:25 UTC
When creating a gauge chart using the plotly indicator trace, the default color is green. Since green has a connotation of success, I think it would be better for the default bar color to follow the palette of the other graphs. This would be expected and a bit more natural as in general that wouldn't have a meaning attached to it. 

I've opened a PR (https://github.com/mtadams007/plotly.js/pull/2) to address this if anyone has time to review it. Thanks!

**Comment by antoinerg** [comment] 2019-10-28 22:16
Thank you @mtadams007 for your comment. I agree that green may not be the best default but at this point, changing it would be considered a breaking change. @etpinard can you confirm that this is the case?

**Comment by etpinard** [comment] 2019-10-29 13:37
Correct, we can't change this until v2 at the very least.

**Comment by mtadams007** [comment] 2019-10-29 13:45
Ok cool, makes sense. It would be nice to change it in the next version. Thanks.

**Comment by gvwilson** [comment] 2024-06-14 12:51
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-14 12:51 UTC
