### ISSUE TITLE
Bar plot: singular datapoint bar not visible when xaxis is set to a fixed range

### ISSUE THREAD

**Issue by GlennMatthys** [plotly/plotly.js#4078] opened 2019-07-25 09:25 UTC
Example: https://jsfiddle.net/mo65wevq/

When plotting a bar graph with only one datapoint and the xaxis set to a fixed range, no bar is seen on the chart. When a second data element is added, the bar becomes visible. Expected behavior: a bar chart with a single datapoint shows one bar.

![image](https://user-images.githubusercontent.com/31989842/61862620-7b801b80-aece-11e9-9b22-29db4b40917c.png)

Note that the second datapoint doesn't have to contain data, its Y value can be null. There just has to be a second datapoint for the bar graph to work.

**Comment by etpinard** [comment] 2019-07-25 13:01
Looks like a duplicate of https://github.com/plotly/plotly.js/issues/1346

**Comment by etpinard** [comment] 2019-07-25 13:18
merged into https://github.com/plotly/plotly.js/issues/1346

**Closed by etpinard** 2019-07-25 13:18 UTC
