### ISSUE TITLE
Add support of quarterly dates

### ISSUE THREAD

**Issue by nul0m** [plotly/plotly.js#4960] opened 2020-06-26 08:48 UTC
This feature has been added to d3-time-format quite a while ago (https://github.com/d3/d3-time-format/pull/58). I know you have your own implementation of date formatting inspired by them, so I believe it should be quite easy to adopt, right?

**Comment by archmoj** [comment] 2020-07-29 13:32
Duplicate of #5009.

**Closed by archmoj** 2020-07-29 13:32 UTC
