### ISSUE TITLE
Contour Issues (slider/zoom, and log axis)

### ISSUE THREAD

**Issue by brian428** [plotly/plotly.js#705] opened 2016-06-29 19:23 UTC
I'm creating one ticket for these two issues because they **look** like they might be related:

- Using a log axis, the contour lines flow beyond the plot area
- Using the range slider, the contour lines flow beyond the plot area. (The same thing seems to happen with zooming enabled)

I also see two other problems that I believe are already ticketed (range sliders don't resize, and contour lines can loop/cross other contours).

I'll attach two screenshots to show what's happening. I'll also see if I can replicate it in a JSFiddle. (This is using real data and app logic, so replicating it may take some work).
![contour_zoom_and_slider_bug](https://cloud.githubusercontent.com/assets/140338/16465485/fbef7918-3e0c-11e6-90d4-44284cad2fea.png)
![contour_log_issue](https://cloud.githubusercontent.com/assets/140338/16465486/fbefba0e-3e0c-11e6-9282-d4a8d26f23c8.png)

**Comment by etpinard** [comment] 2016-06-29 19:29
Hmm. Looks like some `<clipPath>` node is not getting updated properly.

@brian428 Can you please try to reproduce this bug in a _vanilla_ environment (e.g. jsFiddle).

If not, this issue might be a duplicate of https://github.com/plotly/plotly.js/issues/558

**Comment by etpinard** [comment] 2016-07-11 21:02
Calling this a duplicate of https://github.com/plotly/plotly.js/issues/558 until a reproducible example can be made.

**Closed by etpinard** 2016-07-11 21:02 UTC
Labels: status: discussion needed
