### ISSUE TITLE
text/texttemplate on heatmap/histogram2d traces

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.js#4955] opened 2020-06-25 12:14 UTC
It would be great to be able to deprecate the `create_annotated_heatmap` figure factory in Python :)

**Comment by archmoj** [comment] 2020-06-25 12:18
What 'text' attribute does on heatmap right now?

**Comment by nicolaskruchten** [comment] 2020-06-25 12:47
If it's there now then it just appears in the hover label if `hoverinfo` contains `text` I would assume.

**Comment by archmoj** [comment] 2020-06-25 13:48
> If it's there now then it just appears in the hover label if `hoverinfo` contains `text` I would assume.

That does not seem to be working. Tracked in #4956.

**Comment by archmoj** [comment] 2021-11-17 21:19
duplicate of #1116

**Closed by archmoj** 2021-11-17 21:19 UTC
Labels: type: feature
