### ISSUE TITLE
Invalid heatmap values

### ISSUE THREAD

**Issue by workerclass** [plotly/plotly.js#2233] opened 2018-01-04 14:36 UTC
This heatmap shows that my values are (15, 22.75), (22.75, 28), (26, 11), the first two are wrong.

https://jsfiddle.net/zc5r6v6t/3/

![plotly](https://user-images.githubusercontent.com/21059634/34568117-730afc42-f16d-11e7-8585-5e4069aa8665.PNG)

**Comment by alexcjohnson** [comment] 2018-01-04 18:54
Yes, you're right - thanks! We don't handle nonuniform brick sizes correctly. We've labeled the center of the *brick*, but as the brick boundaries are drawn halfway between adjacent data values, the brick center is not the same as the data values that created the brick in the case of nonuniform bricks.

**Comment by alexcjohnson** [comment] 2018-01-04 19:23
Actually the problem is deeper than just hover labels - consider what happens when you set `zsmooth: 'best'` in that same plot (that triggers automatic `connectgaps`) - you can see that the color is ascribed to the brick center as well, and not to the data point as desired.
![screen shot 2018-01-04 at 2 16 52 pm](https://user-images.githubusercontent.com/2678795/34580233-3dc6e496-f15a-11e7-93a7-5708a08fd069.png)
And it spills over into `contour` traces too: the contour lines themselves are fine, as are the hover labels, but `coloring: 'heatmap'` puts the colors in the wrong places again.
![screen shot 2018-01-04 at 2 21 18 pm](https://user-images.githubusercontent.com/2678795/34580377-ca76e224-f15a-11e7-9cb9-58b1d1f39da1.png)

**Comment by LarryMartell** [comment] 2018-01-21 03:38
Any ETA on when this will be fixed?

**Comment by LarryMartell** [comment] 2018-01-23 04:28
Looks like the same bug exist with a contour map as well.

**Closed** 2018-01-24 20:14 UTC
Labels: type: bug

**Comment by LarryMartell** [comment] 2018-01-24 20:17
Does this mean it is fixed? How can I get the latest code with the fix?

**Comment by alexcjohnson** [comment] 2018-01-24 20:37
v1.33.1 will be published later this afternoon including this fix. Until then you can build your own bundle from the master branch.

**Comment by LarryMartell** [comment] 2018-01-24 20:39
That is great. I will wait for 1.33.1. Can you let me know when it's available for download?

**Comment by alexcjohnson** [comment] 2018-01-25 02:18
We hit a snag actually publishing to npm and our CDN (may not happen until Monday), but if you just want the built files, these have been updated and you can download them from https://github.com/plotly/plotly.js/tree/master/dist

**Comment by LarryMartell** [comment] 2018-01-26 03:29
I pulled the latest and it does seem to fix this bug in heatmaps. However it seems to have introduced a new bug. I have plots with a title in them and in the new version the title is not displayed. Here are 2 screen shots showning the plots with the old and new versions. The same code and data is used in both. I will try and put up some codepens tomorrow to demonstrate this, buy clearly the new version has broken something, 
![screen shot 2018-01-25 at 10 33 03 pm](https://user-images.githubusercontent.com/1308192/35424057-280c0a3e-021f-11e8-9939-72d02858b0b6.png)
![screen shot 2018-01-25 at 10 32 21 pm](https://user-images.githubusercontent.com/1308192/35424058-2818b1f8-021f-11e8-8ded-281d17d6a2d1.png)

**Comment by alexcjohnson** [comment] 2018-01-26 13:59
> I pulled the latest and it does seem to fix this bug in heatmaps. However it seems to have introduced a new bug.

Yikes, that's no good! Please open a new issue though, as it does not look related to the heatmap issue, must have been introduced by something else that happened in the same release.
