### ISSUE TITLE
SPLOM IE issues

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.js#3852] opened 2019-05-09 18:32 UTC
A PX user reports SPLOM misbehaviour in IE: https://github.com/plotly/plotly_express/issues/71

**Comment by gvwilson** [comment] 2024-06-14 11:57
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-14 11:57 UTC
Labels: type: bug
