### ISSUE TITLE
Range slider not responsive

### ISSUE THREAD

**Issue by camper9** [plotly/plotly.js#927] opened 2016-09-12 02:49 UTC
Plotly chart is responsive and can be resized using "Plotly.Plots.resize". But the range slider never resizes.

Any fixes for this issue?

**Comment by camper9** [comment] 2016-09-12 02:51
Plotly chart is responsive and can be resized using "Plotly.Plots.resize". But the range slider never resizes.

Any fixes for this issue?

**Comment by etpinard** [comment] 2016-09-12 12:28
duplicate of https://github.com/plotly/plotly.js/issues/686

**Closed by etpinard** 2016-09-12 12:28 UTC
