### ISSUE TITLE
Boxplots render as lines for datetime x-axis and multiple y-axes

### ISSUE THREAD

**Issue by lemurey** [plotly/plotly.js#3516] opened 2019-02-05 21:28 UTC
When using a datetime x axis and two y-axes single boxplots appear as vertical lines:
![two axes](https://user-images.githubusercontent.com/11200672/52305103-2ca6ef80-2949-11e9-8265-f466b9ef0d27.png)
This also happens with a single y-axis and multiple plot types:
![single axis](https://user-images.githubusercontent.com/11200672/52304871-907ce880-2948-11e9-8b0e-27483d26dc2f.png)
If you add a second boxplot on the same y-axis both render properly:
![multiple box plots](https://user-images.githubusercontent.com/11200672/52305278-9cb57580-2949-11e9-9019-7fba6a814445.png)
Code example for case 1:
https://codepen.io/anon/pen/zeEKEo

**Comment by etpinard** [comment] 2019-02-06 16:15
Thanks for the report.

Very related to https://github.com/plotly/plotly.js/issues/3508

**Comment by alexcjohnson** [comment] 2019-02-06 16:51
FWIW what's happening is we don't know what width to give the boxes, because there are no other boxes on the same subplot to to give a distance to the next box, so they get a width of 1 - which for dates means 1 millisecond, hence on a scale of days it looks like zero width. You can fix this with an explicit width attribute (added recently in #3234, as @etpinard mentioned in #3508)

@etpinard are you thinking we can have boxes on overlaying subplots consider each other in width calculations? That seems like it would work for the first example, with boxes on each axis, and offhand I don't see any cases you'd *want* the existing behavior. Would you want to do this for stacked subplots as well? ie consider all boxes on the same position axis? That would be useful if @lemurey's 
first example were converted to stacked subplots, though I can also imagine cases it might constitute a breaking change...

The second example (box + scatter) I don't really see any solution for except explicit width; there's really nothing to guide us in scaling the box.

**Comment by lemurey** [comment] 2019-02-06 17:13
@alexcjohnson Thanks for the note on width, I hadn't seen that, that will easily solve my immediate issue.

**Comment by gvwilson** [comment] 2024-06-11 17:40
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson

**Closed by gvwilson** 2024-06-11 17:40 UTC
Labels: type: bug
