### ISSUE TITLE
Traces inside rangeslider do not stack vertically for stacked subplots

### ISSUE THREAD

**Issue by jackparmer** [plotly/plotly.js#2172] opened 2017-11-20 02:55 UTC
Here's an example:

![image](https://user-images.githubusercontent.com/1865834/33000095-ef4a87fa-cd73-11e7-98e4-1f4e5714f233.png)

The rangeslider here should have its own 5 "subplots" so that the traces are ordered vertically in the same way.

This is going to very nice combined with vertical line hover spanning subplots:
https://github.com/plotly/plotly.js/issues/2155

**Comment by etpinard** [comment] 2017-11-20 14:12
So should it _always_ do that? (not obvious to me)

**Comment by jackparmer** [comment] 2017-11-20 19:10
> So should it always do that? (not obvious to me)

The only case I can see for not doing it is if the y axis ranges for all of the subplots are the same, so maybe it should be optional.

**Comment by alexcjohnson** [comment] 2017-11-27 18:34
I feel like the range slider should *always* mirror exactly the y layout of the subplots it's controlling - seems like it would be nonintuitive to see traces overlaid there but not on the main plot.

The only case I can see where you might not want the y *ranges* in the range slider to match what's on the main plot is if we implement autorange to visible data (see https://github.com/plotly/plotly.js/issues/1876#issuecomment-314913229) - then you might want the range slider to keep the full y autorange (because that's the visible data there) even as the main plot zooms in to smaller y ranges.

**Comment by jumanbar** [comment] 2019-01-16 21:35
I have another example to add, this time with histograms. Consider this arrangement made with the iris dataset (using R & plotly):

![](https://user-images.githubusercontent.com/1039904/51279180-65dbe780-19bb-11e9-9309-26eb3f4a852e.png "Multiple histograms with rangeslider.")

The rangeslider below shows a weird mix between the subplots. In fact, if you examine it closely, it's just the superposition of the three plots, resulting in this kind of things:

![](https://user-images.githubusercontent.com/1039904/51279354-ed295b00-19bb-11e9-9ebd-8ffc86b9bd39.png "Detail of the rangeslider, showing bar-stacking done wrong.")

Compare this to the same data in one stacked histogram:

![](https://user-images.githubusercontent.com/1039904/51279565-66c14900-19bc-11e9-8996-6b737e975100.png "Now the rangeslider is OK, because it just mirrors the main plot.")

IMO, the rangeslider for the multiple stacked-histogram plot should look either like the one in the last example or simply a histogram of the whole dataset with just one color.

Even when there's only 1 color, the histogram shown in the rangeslider should stack the bars of the subplot instead of simply putting one over the others.

**Comment by gvwilson** [comment] 2024-06-10 21:03
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson

**Closed by gvwilson** 2024-06-10 21:03 UTC
Labels: type: bug
