### ISSUE TITLE
histnorm documentation is too bar- and count-specific

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.js#3913] opened 2019-05-27 15:50 UTC
The current `histnorm` documentation is: https://github.com/plotly/plotly.js/blob/master/src/traces/histogram/attributes.js#L71-L88

This has two major issues at the moment:

1. It assumes that `histfunc = 'count'` by talking about "occurrences" (but the same math is applied when `histfunc = 'avg'`, say!)
2. It assumes that `type = 'histogram'` by talking about "span of bar" (but this is reused in `histogram2d` and `histogram2dcontour`!) 

I might propose something like:

* "If `None`, the output of `histfunc` is not changed.",
* "If `'probability'`, the output of `histfunc` for a given bin is divided by the sum of the output of `histfunc` for all bins.",
* "If `'percent'`, the output of `histfunc` for a given bin is divided by the output of `histfunc` for all bins and multiplied by 100.",
* "If `'density'`, the output of `histfunc` for a given bin is divided by the size of the bin.",

But I have no idea how to better describe the `probability density` case :)

**Comment by nicolaskruchten** [comment] 2019-05-27 15:52
Something like:

* "If `'probability density'`, the output of `histfunc` for a given bin is normalized such that it corresponds to the probability that a random event whose distribution is described by `histfunc` will fall into that bin.",

**Comment by alexcjohnson** [comment] 2019-05-28 16:27
That all sounds good, nice catch and thanks for figuring out more generic alternative descriptions. It would be nice to still include info about the totals, which I think are still clear and easy to state (even if not necessarily useful) for all cases except `density`: `percent`/`probability` the sum of bin *heights* is 100%/1, `probability density` the sum of bin *areas* is 1.

I don't see much meaning to `density` with any `histfunc` but `count`, so if we want to be maximally explicit we can just say that, something like: "density, with histfunc='count' (the default), sets the sum of bin areas equal to the total number of sample points"

**Comment by nicolaskruchten** [comment] 2019-05-28 19:57
> nice to still include info about the totals, which I think are still clear and easy to state

I'm not sure I understand what you're saying here... I think we should not mention "area" or "height" because they're both ambiguous wrt bar vs height vs contour... ?

**Comment by alexcjohnson** [comment] 2019-05-28 20:26
Ah sorry, I missed the point about 2D reusing this. I guess ideally we'd tailor the description for the different types, but if that's too much to ask then I could live with area/height disappearing for now.

Maybe a procedural description like you have is enough for users to know which `histnorm` will do what they want... my own thought process goes something like "I want (a total of 1 | a total of 100 | an integral matching the sample size | an integral of 1)" and it's a bit tough to connect those desires to (probability | percent | density | probability density) in the proposed docs. But maybe the histnorm values themselves are sufficient if that's your starting point.

**Comment by nicolaskruchten** [comment] 2019-05-29 00:42
I don’t really understand the density/prob-density math in the 2D case actually... can you explain it to me plz? The area analogy doesn’t work in that case and the probability of event analogy doesn’t work in the non-count case.

**Comment by alexcjohnson** [comment] 2019-05-29 02:28
Right, I don't see any sense in `(probability) density` if you're not binning counts, though `histfunc='sum'` can also represent counts, pre-grouped by position. You might have data like this from something like a CCD - a digital camera, counting photons or electrons per pixel - it has a lot of very fine bins, but you still might want to analyze with coarser bins for noise reduction.

The 2D analog of area -- ∫y・dx -- is volume -- ∫z・dx・dy

So with that said, The appeal of `probability density` is that bin heights/intensities are independent of both the total sample size and the size of bins you choose to group it into. If you start with a small sample and you can only bin very coarsely, you can keep adding to it and, aside from smoothing out fluctuations, the value at each location won't change, even when you have enough data that you can reduce bin sizes and see more detail. That holds for both 1D and 2D binning.

`density` has a more limited appeal: in that case bin height/intensity is insensitive to bin size, but it *is* sensitive to the total sample size. My favorite example where this is useful is scattering experiments, like X-ray diffraction to study crystal structure. You know that from run to run the same number of X-rays are fired at your target, but how many you're going to collect in *any* of your detectors depends on the crystallinity of the material. It's very important to know if you see all the same peaks twice as high, or if a new peak showed up, do the first set get bigger, smaller, or stay the same? If you use `probability density` that constrains the integral of all peaks to a volume of 1, you can't answer these questions.

**Comment by gvwilson** [comment] 2024-06-14 12:01
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-14 12:01 UTC
Labels: type: documentation
