### ISSUE TITLE
3d grid lines are not anti-aliased in firefox

### ISSUE THREAD

**Issue by taylorjacklespriggs** [plotly/plotly.js#4117] opened 2019-08-09 16:22 UTC
The grid lines in firefox do not appear to be antialiased which can be seen by the gaps and corners in the screenshot below. The grid lines in the chrome screenshot look totally fine.
I'm using firefox version 68.0.1 on Sierra.

Screenshots taken from the [codepen example](https://codepen.io/plotly/pen/XmGVdd) on the docs

#### Firefox
<img width="349" alt="Screen Shot 2019-08-09 at 9 14 43 AM" src="https://user-images.githubusercontent.com/11512276/62793621-d1d08b00-ba86-11e9-930b-b3d59fc02571.png">

#### Chrome
<img width="311" alt="Screen Shot 2019-08-09 at 9 14 58 AM" src="https://user-images.githubusercontent.com/11512276/62793636-deed7a00-ba86-11e9-992e-c5c4463ba1a4.png">

specs
MacOS Sierra 10.12.6
MacBook Pro (15-inch, 2017)
Graphics
 - Radeon Pro 555 2048 MB
 - Intel HD Graphics 630 1536 MB

**Comment by archmoj** [comment] 2019-08-09 16:45
This may not be a `plotly.js` bug.
Please note that: `although anti-aliasing is requested by the web-gl code on some hardware it may not be enabled e.g. Mac with FireFox`.

cc: https://github.com/plotly/plotly.js/issues/2756
https://github.com/plotly/plotly.js/issues/2756#issuecomment-473122752

Increasing `plotGlPixelRatio` may help improve the situation: see [codepen](https://codepen.io/MojtabaSamimi/pen/GVXwMN?editors=0010).

**Comment by taylorjacklespriggs** [comment] 2019-08-09 17:09
Thanks @archmoj, the suggestion helped, I suppose it's because of the 9x supersampling?

**Comment by archmoj** [comment] 2019-08-09 17:18
If I recall the `plotGlPixelRatio` is by default 2. So that's the supersaturating diff is (9/4)x about 2x.

**Comment by taylorjacklespriggs** [comment] 2019-08-14 21:41
@archmoj here's a few screenshots with different `plotGlPixelRatio` settings (using your [codepen example](https://codepen.io/MojtabaSamimi/pen/GVXwMN?editors=0010))
IMO Firefox with `plotGlPixelRatio: 0` looks better than `plotGlPixelRatio: 3`, and Chrome with `plotGlPixelRatio: 0` is clearly the most desirable.
Firefox does seem to blacklist MSAA on my hardware https://wiki.mozilla.org/Blocklisting/Blocked_Graphics_Drivers#On_Mac

### Chrome with `plotGlPixelRatio: 0`
![Screen Shot 2019-08-14 at 2 35 02 PM](https://user-images.githubusercontent.com/11512276/63058097-b8717980-bea0-11e9-9cbf-928b4b61f557.png)

### Chrome with `plotGlPixelRatio: 3`
![Screen Shot 2019-08-14 at 2 35 42 PM](https://user-images.githubusercontent.com/11512276/63058141-d3dc8480-bea0-11e9-8850-3f4545af3c86.png)

### Firefox with `plotGlPixelRatio: 0`
![Screen Shot 2019-08-14 at 2 36 26 PM](https://user-images.githubusercontent.com/11512276/63058186-ee166280-bea0-11e9-89fe-c096d383dd5d.png)

### Firefox with `plotGlPixelRatio: 3`
![Screen Shot 2019-08-14 at 2 37 03 PM](https://user-images.githubusercontent.com/11512276/63058221-04242300-bea1-11e9-885f-1ff35b8fa908.png)

**Comment by gvwilson** [comment] 2024-06-14 12:48
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-14 12:48 UTC
