### ISSUE TITLE
Don't select points with zero opacity in volume hover

### ISSUE THREAD

**Issue by archmoj** [plotly/plotly.js#4166] opened 2019-09-05 16:04 UTC
When parts of the graph is filtered out by zero values in `opacityscale`, the hover should not display invisible points.
[Codepen](https://codepen.io/MojtabaSamimi/pen/gOYorRO?editors=0010)
![pickInvisibles](https://user-images.githubusercontent.com/33888540/64358841-3115b280-cfd5-11e9-988c-a934a65935f6.gif)

**Comment by gvwilson** [comment] 2024-06-14 12:49
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-14 12:49 UTC
Labels: type: bug
