### ISSUE TITLE
Performance of scattergl when coloring markers

### ISSUE THREAD

**Issue by joshua-gould** [plotly/plotly.js#3477] opened 2019-01-24 20:24 UTC
Plotly chart takes ~60 seconds to render - https://codepen.io/anon/pen/GzpvOa

Equivalent echarts takes ~12 seconds - https://codepen.io/anon/pen/daYzLr

**Comment by etpinard** [comment] 2019-01-24 20:40
Thanks very much for the report!

Looks like we'll need to optimize our color / colorscale parser. 

Setting colors as `rgba` 4-item array (which is closer to what we send to the shaders) e.g.

```js
function gaussianRand() {
  var rand = 0;
  for (var i = 0; i < 6; i += 1) {
    rand += Math.random();
  }
  return (rand / 6)-0.5;
}
  
var X = [],
    Y = [],
    color = [],
    n = 1200000,
    i;

for (i = 0; i < n; i += 1) {
  X.push(gaussianRand());
  Y.push(gaussianRand());
  color.push([Math.random(), Math.random(), Math.random(), 1])
}

var data = [{
	type: "scattergl",
   mode: "markers",
   marker: {
		color : color
		
	},
   x: new Float32Array(X),
   y: new Float32Array(Y)
}]
var start = new Date();
console.time(0)
Plotly.newPlot('graph', data, {}, config={showSendToCloud: true})
console.timeEnd(0)
```

clocks it at around 4000 ms (on my machine).

**Comment by etpinard** [comment] 2019-01-24 20:41
Referencing two commits on our color implementation (which could potentially be optimized also):

- https://github.com/gl-vis/regl-scatter2d/pull/15/commits/74a1e4486b7968a9c4648e95b9c2138a2f0840a1
- https://github.com/gl-vis/regl-scatter2d/pull/17

**Comment by joshua-gould** [comment] 2019-01-24 20:41
Thanks. I will update my code to provide colors as rgba 4-item array.

**Comment by gvwilson** [comment] 2024-06-11 17:39
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson

**Closed by gvwilson** 2024-06-11 17:39 UTC
Labels: type: performance
