### ISSUE TITLE
A line graph is not displayed if update 1.28.0

### ISSUE THREAD

**Issue by ozamasa** [plotly/plotly.js#1805] opened 2017-06-21 03:26 UTC
When I take the screen capture in [wkhtmltopdf](https://wkhtmltopdf.org/) a line graph is not displayed. 

```
xvfb-run wkhtmltoimage https://live.shiolab.com hoge.jpg
```

1. In the case of 1.28.0
 ![2017-06-21_1211](https://user-images.githubusercontent.com/1070032/27365603-e0003d68-567b-11e7-9658-14a825688172.jpg)

2. In the case of 1.27.1
 ![2017-06-21_1213](https://user-images.githubusercontent.com/1070032/27365607-e2e4e84e-567b-11e7-9b66-314e46d704b1.jpg)

By the way, even 1.28.0 seems to be displayed by the browsers such as chrome or firefox.

**Comment by etpinard** [comment] 2017-06-21 18:11
I suspect this is caused by the same problem as https://github.com/plotly/plotly.js/issues/1801 - which was resolved in `1.28.2`

@ozamasa can you try running your command with plotly.js `1.28.2`?

**Comment by ozamasa** [comment] 2017-06-22 00:41
@etpinard 
Thank you! I confirmed that it was fixed. 👍

**Closed** 2017-06-22 15:02 UTC
