### ISSUE TITLE
Log-axis minor label customization problem

### ISSUE THREAD

**Issue by helloshuangzi** [plotly/plotly.js#3679] opened 2019-03-25 18:08 UTC
When an axis scales like below, it only shows one single main-label (0.01) with the remaining of sub-label (3 4 .. 8 9 and 2 3 4). It seems not intuitive for users without the familiarity of plotly style to figure out the actual value of those sub-labels. 
```
3  4  5  6  7  8  9 (0.01)  2  3  4  
```
![image](https://user-images.githubusercontent.com/17074894/54956998-c123dc00-4f0e-11e9-9c74-7a388321682b.png)

To avoid this confusion, does plotly support to show the sub-labels as its original value, or just hide them?

**Comment by etpinard** [comment] 2019-03-26 14:33
This might be part of https://github.com/plotly/plotly.js/issues/903 - where users could set a new attribute e.g. named `yaxis.minortickformat`.

In the meantime, you can try using `tickvals` and `ticktext`, but watch out for https://github.com/plotly/plotly.js/issues/2885

**Comment by gvwilson** [comment] 2024-06-13 19:52
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-13 19:52 UTC
Labels: type: feature
