### ISSUE TITLE
Keep zoom level on scattergeo plot?

### ISSUE THREAD

**Issue by collioud** [plotly/plotly.js#1817] opened 2017-06-24 14:25 UTC
Hi,

I  am wondering if there is a way to keep the zoom level (or the axis ranges) after a restyle/relayout of a scattergeo plot?
See:
[https://codepen.io/anon/pen/QgMXEg?editors=0010](https://codepen.io/anon/pen/QgMXEg?editors=0010)

Try to zoom in next to a data point, click on this point.
The restyling is done (the point color and size are modified), but the zoom is set back to its initial state. Is there a way to prevent that? Or a way to re-zoom as before?

Thanks in advance for your answer.

**Comment by etpinard** [comment] 2017-06-26 13:52
duplicate of https://github.com/plotly/plotly.js/issues/292

**Closed by etpinard** 2017-06-26 13:52 UTC
