### ISSUE TITLE
Add automargin behavior to paper-referenced annotations

### ISSUE THREAD

**Issue by laura-cbre** [plotly/plotly.js#4297] opened 2019-10-23 16:15 UTC
Ideally, it would be nice to have a chart caption for plotly figures.
Currently, to add text where a chart caption would be, you can add an annotation. However, newlines of annotations quickly get cut off, unless margin size is manually updated. Is it possible to have automargin dependent on annotations?
Example chart (caption `c` is partly cut off, caption `d` is not shown at all)
![image](https://user-images.githubusercontent.com/56594408/67412731-ba9a3780-f5b7-11e9-938b-0b83b0bc3550.png)

Its data and layout attributes:

```python
Scatter({
    'hoverinfo': 'x+name+text',
    'line': {'color': '#e53935'},
    'marker': {'color': '#e53935', 'line': {'color': '#e53935'}},
    'mode': 'lines',
    'name': 'a',
    'text': [1.000, 2.000, 3.000, 4.000],
    'x': [
        datetime.datetime(2018, 1, 1, 0, 0),
        datetime.datetime(2018, 1, 5, 0, 0),
        datetime.datetime(2018, 1, 8, 0, 0),
        datetime.datetime(2018, 1, 15, 0, 0)
    ],
    'y': [1, 2, 3, 4]
})
```

```python Layout({
    'annotations': [{'showarrow': False, 'text': 'a', 'x': Timestamp('2018-01-10 00:00:00'), 'y': 1.05, 'yref': 'paper'},
                    {'showarrow': False, 'text': 'b', 'x': Timestamp('2018-01-07 00:00:00'), 'y': 1.05, 'yref': 'paper'},
                    {'showarrow': False, 'text': 'b', 'x': Timestamp('2018-01-11 00:00:00'), 'y': 1.05, 'yref': 'paper'},
                    {'showarrow': False, 'text': 'c', 'x': Timestamp('2018-01-05 00:00:00'), 'y': 1.05, 'yref': 'paper'},
                    {'font': {'color': 'red', 'size': 15},
                     'showarrow': False,
                     'text': 'a: data I found somewhere.',
                     'x': 0,
                     'xanchor': 'left',
                     'xref': 'paper',
                     'xshift': 0,
                     'y': -0.15,
                     'yanchor': 'auto',
                     'yref': 'paper',
                     'yshift': 0},
                    {'font': {'color': 'red', 'size': 15},
                     'showarrow': False,
                     'text': 'b: upgrade period',
                     'x': 0,
                     'xanchor': 'left',
                     'xref': 'paper',
                     'xshift': 0,
                     'y': -0.2,
                     'yanchor': 'auto',
                     'yref': 'paper',
                     'yshift': 0},
                    {'font': {'color': 'red', 'size': 15},
                     'showarrow': False,
                     'text': 'c: something happened',
                     'x': 0,
                     'xanchor': 'left',
                     'xref': 'paper',
                     'xshift': 0,
                     'y': -0.25,
                     'yanchor': 'auto',
                     'yref': 'paper',
                     'yshift': 0},
                    {'font': {'color': 'red', 'size': 15},
                     'showarrow': False,
                     'text': "d: can't see me at all",
                     'x': 0,
                     'xanchor': 'left',
                     'xref': 'paper',
                     'xshift': 0,
                     'y': -0.3,
                     'yanchor': 'auto',
                     'yref': 'paper',
                     'yshift': 0}],
    'shapes': [{'line': {'dash': 'dot'},
                'type': 'line',
                'x0': Timestamp('2018-01-10 00:00:00'),
                'x1': Timestamp('2018-01-10 00:00:00'),
                'y0': 0,
                'y1': 1,
                'yref': 'paper'},
               {'fillcolor': 'LightSalmon',
                'layer': 'below',
                'line': {'width': 0},
                'opacity': 0.5,
                'type': 'rect',
                'x0': '2018-01-07',
                'x1': '2018-01-11',
                'xref': 'x',
                'y0': 0,
                'y1': 1,
                'yref': 'paper'},
               {'line': {'dash': 'dot'},
                'type': 'line',
                'x0': Timestamp('2018-01-05 00:00:00'),
                'x1': Timestamp('2018-01-05 00:00:00'),
                'y0': 0,
                'y1': 1,
                'yref': 'paper'}],
    'showlegend': False,
    'title': {'text': ''},
    'yaxis': {'rangemode': 'normal', 'title': {'text': 'degC'}}
})
```

**Comment by gvwilson** [comment] 2024-06-14 12:51
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-14 12:51 UTC
Labels: type: feature
