### ISSUE TITLE
Leftover traces in animations

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.js#3931] opened 2019-06-03 19:46 UTC
In the following pen https://codepen.io/nicolaskruchten/pen/KLEprV?editors=0010 the trace in `data` has no `uid` but in `frames` there are `uids` ... hitting 'play' results in the original trace still being visible but not hoverable. I would expect that `animate()` would clean up the original rendering there?

**Comment by etpinard** [comment] 2019-06-05 14:56
We don't animate trace enter/exit at the moment cc https://github.com/plotly/plotly.js/issues/932

So transitions with `redraw: false` won't work as expected. Commenting the `redraw: false` lines in your codepen make things work ok https://codepen.io/etpinard/pen/RmOXPb?editors=0010

More in https://github.com/plotly/plotly.js/issues/1688

**Comment by nicolaskruchten** [comment] 2019-06-06 02:31
so when you say "animate trace exit" you mean "we leave them there on purpose even if they're no longer present in the active frame"? That's what I'm seeing right now, and the markers that are left aren't hoverable...

**Comment by nicolaskruchten** [comment] 2019-06-06 02:32
Setting redraw to true does fix this, but is very janky, as the animation appears to 'stall' at every frame 
:(

**Comment by etpinard** [comment] 2019-07-03 20:26
removing the `isFullReplot` condition around:

https://github.com/plotly/plotly.js/blob/d75e956db2fffe23bcf818c3ca9eb8952f68eab2/src/traces/scatter/plot.js#L80-L82

seems to solve the problem and doesn't make any test fail.

I can't remember what Ricky envisioned with that `isFullReplot` condition, but we should probably manually test out a few things before making a PR.

**Comment by etpinard** [comment] 2019-09-06 16:46
cc @antoinerg who may have copied that 

```js
 if(isFullReplot) { 
     join.exit().remove(); 
 } 
```

block in `bar/plot.js` while working on bar transitions.

**Comment by etpinard** [comment] 2019-09-30 22:08
Here's the `bar` version of @nicolaskruchten 's codepen (https://codepen.io/nicolaskruchten/pen/KLEprV i.e. with `redraw:false`):

https://codepen.io/etpinard/pen/MWgMEmx?editors=0010

![Peek 2019-09-30 18-01](https://user-images.githubusercontent.com/6675409/65920212-72b73480-e3ac-11e9-848d-b10f9b60d13c.gif)

after @antoinerg's bar transition work in #4180 and #4186.

-------

`bar/plot.js` uses slightly different wrappers than `scatter/plot.js` (see https://github.com/plotly/plotly.js/pull/4180#discussion_r322767085 for more on that topic) - notably `bar/plot.js` does not have any `isFullReplot` logic which seems to be the cause of this issue here (see https://github.com/plotly/plotly.js/issues/3931#issuecomment-528928552).

So, the bar version above does clear the "leftover" trace correctly, but looks like it tries to transition from the base trace (w/o a `uid`) to the first frame (with a set `uid`) using a black (misdefined?) bar before transitioning to the position of the second frame.

**Comment by gvwilson** [comment] 2024-06-14 12:01
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-14 12:01 UTC
Labels: type: bug
