### ISSUE TITLE
Hoveron fills broken this on `tozerox` fill trace

### ISSUE THREAD

**Issue by etpinard** [plotly/plotly.js#3203] opened 2018-11-01 16:41 UTC
https://codepen.io/etpinard/pen/NOQVrq

![peek 2018-11-01 12-40](https://user-images.githubusercontent.com/6675409/47865751-665cdd00-ddd3-11e8-836b-be55b3eb91e1.gif)

**Comment by etpinard** [comment] 2018-11-01 16:41
Related: https://github.com/plotly/plotly.js/issues/2165

**Comment by nicolaskruchten** [comment] 2018-11-01 22:03
I was having trouble with hover on fills+points with 2 traces also: https://codepen.io/nicolaskruchten/pen/eQOJzY?editors=0010

**Comment by alexcjohnson** [comment] 2018-11-02 01:47
Ah, thanks @etpinard - looking at this more closely I think it's not just related but in fact a duplicate of #2165 - nothing to do with single vs multi trace, it's just that `hoveron: 'fills'` was only ever really built for `fill: 'toself'`.

**Closed by alexcjohnson** 2018-11-02 01:47 UTC
Labels: type: bug
