### ISSUE TITLE
table rows disappear on scroll in IE

### ISSUE THREAD

**Issue by cldougl** [plotly/plotly.js#3986] opened 2019-06-26 15:15 UTC
table rows disappear when scrolling in IE 
![dis](https://user-images.githubusercontent.com/2789078/60192212-81b5a600-9803-11e9-9bc4-d6665c9051e3.gif)

**Comment by gvwilson** [comment] 2024-06-14 12:46
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-14 12:46 UTC
Labels: type: bug
