### ISSUE TITLE
Pointcloud with log axes: bad tick labels

### ISSUE THREAD

**Issue by mccalluc** [plotly/plotly.js#2240] opened 2018-01-09 16:55 UTC
With pointcloud and logarithmic axes, the tick labels are strange: Instead of getting 10 to a small integer, it's 10 to some 4 digit number, with internal superscripting. Switch the plot type and the axes are back to normal, and non-logarithmic axes also seem fine.

https://codepen.io/anon/pen/XVZVPN
```javascript
var myPlot = document.getElementById('myDiv'),
    d3 = Plotly.d3,
    N = 100,
    x1 = d3.range(N).map( d3.random.logNormal(7) ),
    y1 = d3.range(N).map( d3.random.logNormal(7) ),
    data = [{ x: x1, y: y1, type: 'pointcloud'}];
    layout = { 
        xaxis:{type: 'log'},
        yaxis:{type: 'log'}
     };

Plotly.newPlot('myDiv', data, layout);
```
![screen shot 2018-01-09 at 11 48 36 am](https://user-images.githubusercontent.com/730388/34732352-0d1b40b2-f533-11e7-8df6-19fc6543e949.png)

**Comment by alexcjohnson** [comment] 2018-01-10 04:41
Wow, that's an "interesting" effect. @etpinard is regl going to fix this?

**Comment by etpinard** [comment] 2018-01-10 16:18
> is regl going to fix this?

nop, the first regl-based `scattergl` push won't include any pointcloud improvements. 

@monfera was pointcloud ever intended to work on non-linear axes?

**Comment by monfera** [comment] 2018-01-10 16:28
Hey @etpinard nope, it was going to be just linear.

**Comment by archmoj** [comment] 2018-11-19 02:38
Version 1.34 was the last minor that displays the points and this effect. Here is a codepen [demo](https://codepen.io/MojtabaSamimi/pen/XyegEd).
When using current latest (v.1.42.5) the axes and texts are drawn differently; however the data points do not show up! Here is another codepen [demo](https://codepen.io/MojtabaSamimi/pen/RqLgyy).

**Comment by gvwilson** [comment] 2024-06-10 21:05
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson

**Closed by gvwilson** 2024-06-10 21:05 UTC
Labels: type: feature
