### ISSUE TITLE
[Sankey] Can't link 2 nodes with >3 links

### ISSUE THREAD

**Issue by jackparmer** [plotly/plotly.js#1886] opened 2017-07-17 19:33 UTC
@alishobeiri has been making some really nice Sankey examples in Python:

https://plot.ly/~alishobeiri/1257/plotly-sankey-diagrams/

I think we found an issue where in plotly.js >=1.28.3, you can't connect 2 nodes with more than 3 links. Ali made a nice reproducible example here in Python:

https://plot.ly/~alishobeiri/1358/problem-first-identified-on-wapo-sankey/

To confirm this is a plotly.js issue, you can see that the WaPo example (many nodes with >3 links) works here using https://rawgit.com/monfera/plotly-webgl-parcoords/sankey-example-01/plotly-sankey.min.js:

https://codepen.io/plotly/pen/yXEJYZ

However if you change the plotly.js version to 1.28.3 it doesn't work:

https://codepen.io/plotly/pen/GEapyx

(Or using plotly-latest.min.js):

https://codepen.io/plotly/pen/zzQvjq

**Comment by etpinard** [comment] 2017-07-17 19:35
cc @monfera

**Comment by monfera** [comment] 2017-08-04 15:31
indeed, another reproduction is https://codepen.io/anon/pen/ayBoGG

**Comment by monfera** [comment] 2017-08-05 20:52
It should be fixed by the above commit.

@jackparmer thanks for the clear details! A minor note, the referred WaPo drone codepen mock precedes the decision to switch to a columnar representation so it won't work with the fix.

Indeed great examples by @alishobeiri, I especially love the Scottish referendum ones! The colors and opacity change on hover works out very well. An unrelated thing: now the tooltip value seems to be out of the hover tooltip box, I'll check what's going on.

![image](https://user-images.githubusercontent.com/1548516/28998639-a954a7bc-7a30-11e7-9710-afc47a091c7f.png)

**Comment by monfera** [comment] 2017-08-05 20:54
Interestingly the tooltip value is properly inside the box on my machine so I'm not yet sure how to reproduce it locally, will check.

![image](https://user-images.githubusercontent.com/1548516/28998650-05fdb896-7a31-11e7-9093-da3204340e4b.png)

**Closed** 2017-08-07 21:41 UTC
Labels: type: bug
