### ISSUE TITLE
marker.line.width not working in scatter3d

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.js#3807] opened 2019-04-24 17:23 UTC
See this pen: https://codepen.io/nicolaskruchten/pen/QPJwZZ?editors=0010

Ref https://community.plot.ly/t/scatter-3d-marker-line-width-only-affects-to-legend/14378 and https://github.com/plotly/react-plotly.js/issues/138

**Comment by etpinard** [comment] 2019-04-24 17:36
Dupe of https://github.com/plotly/plotly.js/issues/3796

**Closed by etpinard** 2019-04-24 17:36 UTC
