### ISSUE TITLE
Can time axis show 60 minutes instead of 00?

### ISSUE THREAD

**Issue by juni-green** [plotly/plotly.js#1514] opened 2017-03-24 11:29 UTC
Hi,
Is it possible to format time axis ticks in such a way that it shows 60 minutes instead of 00?
For example; customize the time format using:
tickformat: "%M:%S"
such that only Minutes:Seconds appear on the time axis. On 60 minutes value, the tick format becomes 00:00 instead of 60:00.

Any help will be appreciated.
Thanks!

**Comment by etpinard** [comment] 2017-03-24 14:44
Maybe there's a way using `tickformat`. We use d3's [time-format](https://github.com/d3/d3-time-format) under hood. Someone should investigate.

**Comment by etpinard** [comment] 2017-03-24 14:52
Duplicate of https://community.plot.ly/t/can-time-axis-show-60-minutes-instead-of-00/3735

Closing.

**Closed by etpinard** 2017-03-24 14:52 UTC
