### ISSUE TITLE
Outside tick marker gap

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.js#2796] opened 2018-07-10 00:37 UTC
Unless I turn on the axis lines, there appears to be a 1px gap between the `outside` tick markers and the gridlines. This is problematic in cases like bar charts with the zero line activated but not the axis lines. 

See https://codepen.io/nicolaskruchten/pen/ajoreY

![image](https://user-images.githubusercontent.com/203523/42482846-f2f5c1d0-83b7-11e8-9a8c-2afc3d2c0890.png)

**Comment by nicolaskruchten** [comment] 2018-07-10 00:40
In addition, in the screenshot above the bar occludes the zero line, suggesting that the best way to draw such a chart would be to hide the zero line and show the x axis line, but this isn't what happens by default in a simple bar chart.

**Comment by etpinard** [comment] 2018-12-07 16:46
> there appears to be a 1px gap between the `outside` tick markers and the gridlines.

Looks like this problem can be fixed by changing 

https://github.com/plotly/plotly.js/blob/df066d595410a7f30af617034cafe1c40d2a19e3/src/plots/cartesian/axes.js#L1933

to 

```js
var pad = (ax.linewidth || 0) / 2;

// or 
var pad = ax.ticks === 'outside' ? (ax.linewidth || 0) / 2 : 0;
```

note that `ax.linewidth` is undefined when `ax.showline` is false.

**Comment by etpinard** [comment] 2018-12-11 13:40
see the updated baselines here:

https://github.com/plotly/plotly.js/compare/multicategory...no-tick-pad-if-no-axis-line

**Comment by nicolaskruchten** [comment] 2018-12-11 14:01
Interestingly, in some cases I actually like the gap better: https://github.com/plotly/plotly.js/compare/multicategory...no-tick-pad-if-no-axis-line?short_path=a423726#diff-a423726162d617e1421fe14bcc4ab95e

I think it's mostly when the edge of the plot has a gridline, or even worse, a zeroline, then the gap is awkward.

should we eventually add an option for tick gap? Or is there already one?

**Comment by nicolaskruchten** [comment] 2018-12-11 14:02
Let me revise: I think when there are visible gridlines that are clearly continuations of the tick, it looks awkward too

**Comment by etpinard** [comment] 2020-03-13 15:57
Looking through old branches. Branch

https://github.com/plotly/plotly.js/compare/no-tick-pad-if-no-axis-line

made an attempt at the fix, so I won't delete it.

**Comment by gvwilson** [comment] 2024-06-11 17:11
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson

**Closed by gvwilson** 2024-06-11 17:11 UTC
Labels: type: bug
