### ISSUE TITLE
Ticks width is not consistent in Chrome and Firefox when zoom is applied.

### ISSUE THREAD

**Issue by IsmaelAlfaroRodriguez** [plotly/plotly.js#4486] opened 2020-01-14 17:44 UTC
Zoom Percentage: 250%

**Chrome** (Issue)
<img width="921" alt="chrome" src="https://user-images.githubusercontent.com/37251349/72367858-8e77e980-36c2-11ea-8e65-c6bc8ca2b838.PNG">

**Firefox** (Issue)
<img width="925" alt="Firefox" src="https://user-images.githubusercontent.com/37251349/72367982-ce3ed100-36c2-11ea-835e-5759ab76e0c1.PNG">

**Edge**
<img width="906" alt="Edge" src="https://user-images.githubusercontent.com/37251349/72368040-eadb0900-36c2-11ea-8516-4a594e156e1d.PNG">

**IE**
<img width="908" alt="IE" src="https://user-images.githubusercontent.com/37251349/72368052-f0385380-36c2-11ea-9ad0-2fc6ff37d74a.PNG">

**Comment by archmoj** [comment] 2020-01-14 19:23
@IsmaelAlfaroRodriguez would you mind providing the layout and data in a demo? e.g. using codepen

**Comment by IsmaelAlfaroRodriguez** [comment] 2020-01-14 22:06
@archmoj This is an example of the behavior I mentioned: https://codepen.io/IsmaelAR/pen/ExapXvV
The width of some ticks is different from the others. I need that they all have the same width.

**Comment by gvwilson** [comment] 2024-06-14 12:55
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-14 12:55 UTC
