### ISSUE TITLE
zooming with right button drag (matplotlib-like)

### ISSUE THREAD

**Issue by mzechmeister** [plotly/plotly.js#4005] opened 2019-07-01 07:31 UTC
Matplotlib has a nice zoom mode, when dragging with the right mouse button. From https://matplotlib.org/3.1.0/users/navigation_toolbar.html:
> Press the right mouse button to zoom, dragging it to a new position. The x axis will be zoomed in proportionately to the rightward movement and zoomed out proportionately to the leftward movement. The same is true for the y axis and up/down motions. The point under your mouse when you begin the zoom remains stationary, allowing you to zoom in or out around that point as much as you wish.

PyQtGraph has a similar same zoom behaviour, see http://www.pyqtgraph.org/documentation/mouse_interaction.html.
How can I get this for plotly?

**Comment by gvwilson** [comment] 2024-06-14 12:47
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-14 12:47 UTC
