### ISSUE TITLE
Bar not showing in barchart when range is specified

### ISSUE THREAD

**Issue by saimaparveen** [plotly/plotly.js#2079] opened 2017-10-11 13:45 UTC
Hi,

Unable to see bar when there is 1 bar and range specified in barchart.
https://codepen.io/anon/pen/KXeoWZ

if there is more than 1 bar then its visible.
https://codepen.io/anon/pen/yzEKoj

Is there any way I can show bar in the first case

Thanks,
Saima

**Comment by etpinard** [comment] 2017-10-11 14:02
That bar is showing, it is simply very very very tiny. After zooming in a little bit, we get:

![image](https://user-images.githubusercontent.com/6675409/31444388-1e77794e-ae6a-11e7-95a1-d4d2a1b92bcf.png)

To be precise, it has a width of 1 millisecond (the default value) - which on your set range get ignored but most browsers. 

By setting the `width` to e.g. 12 hours https://codepen.io/etpinard/pen/oGyqJj?editors=0010 your bar is _visible_ again.

---

Related https://github.com/plotly/plotly.js/issues/1181 /  https://github.com/plotly/streambed/issues/3529

**Comment by alexcjohnson** [comment] 2017-10-11 15:14
duplicate of https://github.com/plotly/plotly.js/issues/1346

**Closed by alexcjohnson** 2017-10-11 15:14 UTC
