### ISSUE TITLE
add stacked grouped bars

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.js#4914] opened 2020-06-10 13:00 UTC
We need to permit mixed stacked and grouped bars.

We will implement this with a new `bar.stackgroup` attribute as spec'ed here: https://github.com/plotly/plotly.js/issues/3402

**Comment by kStanleyds** [comment] 2020-07-30 13:39
I see this issue is marked as closed but I'm having trouble tracking resolution. Could you point me in the right direction, please?
> See also related #3614, #1835, #1015. I'd like to keep the current issue as the master tracking one for this work, so we can close out others and refer to this one as needed.

**Comment by nicolaskruchten** [comment] 2020-07-30 17:19
This issue is actually still open :)

**Comment by valentinstn** [comment] 2020-12-11 12:22
Is there any update on this issue?

**Comment by nicolaskruchten** [comment] 2020-12-11 13:48
This issue is going to be worked on in the next couple of months.

**Comment by valentinstn** [comment] 2020-12-11 14:39
Thanks @nicolaskruchten

**Comment by anyadmitrieva** [comment] 2021-03-15 18:18
Hello, could you please tell me if this feature is still expected to be available soon?

**Comment by nicolaskruchten** [comment] 2021-03-15 18:49
We will be working on it in the near future but I can't publicly commit to a timeline at this time.

**Comment by tanya-pix** [comment] 2021-06-17 06:23
> We will be working on it in the near future but I can't publicly commit to a timeline at this time.

Are there any updates on this yet?

**Comment by RenaudLN** [comment] 2021-07-13 06:00
For anyone trying to do this, whilst waiting for the official feature you can get the same outcome by creating the second stackgroup on another yaxis and playing with the traces offsets.
![image](https://user-images.githubusercontent.com/20662281/125399000-58204500-e3f3-11eb-889c-84b9227aa154.png)

**Comment by Alexander-Serov** [comment] 2022-02-07 18:14
@RenaudLN Yes, could you please share the code for your plot?

**Comment by RenaudLN** [comment] 2022-02-07 23:31
Here is a minimum reproducible example. Note that the offsets are suited to this monthly data and will have to be adjusted with other inputs.

```python
import numpy as np
import pandas as pd
import plotly.graph_objects as go


index = pd.date_range("2020", "2021", freq="MS", closed="left")
df = pd.concat(
    [
        pd.DataFrame(
            np.random.rand(12, 3) * 1.25 + 0.25,
            index=index,
            columns=["Revenue1", "Revenue2", "Revenue3"]
        ),
        pd.DataFrame(
            np.random.rand(12, 3) + 0.5,
            index=index,
            columns=["Revenue1", "Revenue2", "Revenue3"]
        ),
    ],
    axis=1,
    keys=["Product1", "Product2"]
)

fig = go.Figure(
    layout=go.Layout(
        height=600,
        width=1000,
        barmode="relative",
        yaxis_showticklabels=False,
        yaxis_showgrid=False,
        yaxis_range=[0, df.groupby(axis=1, level=0).sum().max().max() * 1.5],
        yaxis2=go.layout.YAxis(
            visible=False,
            matches="y",
            overlaying="y",
            anchor="x",
        ),
        font=dict(size=24),
        legend_x=0,
        legend_y=1,
        legend_orientation="h",
        hovermode="x",
        margin=dict(b=0,t=10,l=0,r=10)
    )
)
colors = {
    "Product1": {
        "Revenue1": "#F28F1D",
        "Revenue2": "#F6C619",
        "Revenue3": "#FADD75",
    },
    "Product2": {
        "Revenue1": "#2B6045",
        "Revenue2": "#5EB88A",
        "Revenue3": "#9ED4B9",
    }
}
for i, t in enumerate(colors):
    for j, col in enumerate(df[t].columns):
        if (df[t][col] == 0).all():
            continue
        fig.add_bar(
            x=df[t].index,
            y=df[t][col],
            yaxis=f"y{i + 1}",
            offsetgroup=str(i),
            offset=(i - 1) * 1000000000,
            width=1000000000,
            legendgroup=t,
            legendgrouptitle_text=t,
            name=col,
            marker_color=colors[t][col],
            marker_line=dict(width=2, color="#333"),
            hovertemplate="%{y}<extra></extra>"
        )

fig.show()
```

![image](https://user-images.githubusercontent.com/20662281/152889693-28f12d2f-8d2f-4588-8236-60849f366973.png)

**Comment by lyndon-bird** [comment] 2023-04-26 22:20
Is there any update with this issue? Would be great to have implemented!

**Comment by gusblack-tt** [comment] 2024-04-23 14:38
Is there any update on this feature? Looks like it has been asked for in one form or another for 8 years

**Comment by clarson0** [comment] 2024-05-07 21:19
@araichev  Is this different than multicategory?  I recently made a similar chart to the screenshot above

`function onlyUnique(value, index, array) {
  return array.indexOf(value) === index;
}

// Example data for the x-axis, normally you would fetch this from your data set
var categories = [
  ["2023-12-01", "Dog"], ["2023-12-02", "Cat"], ["2023-12-03", "Mouse"],
  ["2023-12-04", "Dog"], ["2023-12-05", "Cat"], ["2023-12-06", "Mouse"],
  ["2023-12-07", "Dog"], ["2023-12-08", "Cat"], ["2023-12-09", "Mouse"]
];

let dates = categories.map(c => {
  return c[0];
})

let animals = categories.map(c => {
  return c[1]
})

dates = dates.filter(onlyUnique);
animals = animals.filter(onlyUnique);

let xDates = [];
dates.forEach(d => {
  animals.forEach(c => {
    xDates.push(d);
  })
})

let xAnimals = [];
dates.forEach(d => {
  animals.forEach(c => {
    xAnimals.push(c);
  })
})

var yValuesA = xAnimals.map(() => Math.random() * 0.95 + 0.05);
var yValuesB = xAnimals.map(() => Math.random() * 0.95 + 0.05);

var data = [
  {
    "marker": {
        "color": [
            "rgb(25, 80, 22)",
            "rgb(15, 60, 90)",
            "rgb(113, 13, 14)",
            "rgb(127, 63, 0)",
            "rgb(25, 80, 22)",
            "rgb(15, 60, 90)",
            "rgb(113, 13, 14)",
            "rgb(127, 63, 0)",
            "rgb(25, 80, 22)",
            "rgb(15, 60, 90)",
            "rgb(113, 13, 14)",
            "rgb(127, 63, 0)",
            "rgb(25, 80, 22)",
            "rgb(15, 60, 90)",
            "rgb(113, 13, 14)",
            "rgb(127, 63, 0)",
            "rgb(25, 80, 22)",
            "rgb(15, 60, 90)",
            "rgb(113, 13, 14)",
            "rgb(127, 63, 0)",
            "rgb(25, 80, 22)",
            "rgb(15, 60, 90)",
            "rgb(113, 13, 14)",
            "rgb(127, 63, 0)",
            "rgb(25, 80, 22)",
            "rgb(15, 60, 90)",
            "rgb(113, 13, 14)",
            "rgb(127, 63, 0)",
            "rgb(25, 80, 22)",
            "rgb(15, 60, 90)",
            "rgb(113, 13, 14)",
            "rgb(127, 63, 0)",
            "rgb(25, 80, 22)",
            "rgb(15, 60, 90)",
            "rgb(113, 13, 14)",
            "rgb(127, 63, 0)",
            "rgb(25, 80, 22)",
            "rgb(15, 60, 90)",
            "rgb(113, 13, 14)",
            "rgb(127, 63, 0)",
            "rgb(25, 80, 22)",
            "rgb(15, 60, 90)",
            "rgb(113, 13, 14)",
            "rgb(127, 63, 0)",
            "rgb(25, 80, 22)",
            "rgb(15, 60, 90)",
            "rgb(113, 13, 14)",
            "rgb(127, 63, 0)",
            "rgb(25, 80, 22)",
            "rgb(15, 60, 90)",
            "rgb(113, 13, 14)",
            "rgb(127, 63, 0)",
            "rgb(25, 80, 22)",
            "rgb(15, 60, 90)",
            "rgb(113, 13, 14)",
            "rgb(127, 63, 0)",
            "rgb(25, 80, 22)",
            "rgb(15, 60, 90)",
            "rgb(113, 13, 14)",
            "rgb(127, 63, 0)",
            "rgb(25, 80, 22)",
            "rgb(15, 60, 90)",
            "rgb(113, 13, 14)",
            "rgb(127, 63, 0)",
            "rgb(25, 80, 22)",
            "rgb(15, 60, 90)",
            "rgb(113, 13, 14)",
            "rgb(127, 63, 0)",
            "rgb(25, 80, 22)",
            "rgb(15, 60, 90)",
            "rgb(113, 13, 14)",
            "rgb(127, 63, 0)",
            "rgb(25, 80, 22)",
            "rgb(15, 60, 90)",
            "rgb(113, 13, 14)",
            "rgb(127, 63, 0)",
            "rgb(25, 80, 22)",
            "rgb(15, 60, 90)",
            "rgb(113, 13, 14)",
            "rgb(127, 63, 0)",
            "rgb(25, 80, 22)",
            "rgb(15, 60, 90)",
            "rgb(113, 13, 14)",
            "rgb(127, 63, 0)"
        ],
        "opacity": 0.5
    },
    "name": "Test data A",
    "showlegend": false,
    "type": "bar",
    "x": [
        xDates,
        xAnimals
    ],
    "y": yValuesA,
},
  {
    "marker": {
        "color": 'darkblue',
        "opacity": 0.5
    },
    "name": "Test data B",
    "showlegend": false,
    "type": "bar",
    "x": [
        xDates,
        xAnimals
    ],
    "y": yValuesB,
},
           ];

var layout = {
    paper_bgcolor: "lightblue",
    plot_bgcolor: "lightgrey",
    margin: {
        "t": 20,
        "r": 20,
        "b": 120,
        "l": 20,
        // "pad": 0
    },
    barmode: "stack",
    xaxis: {
        "anchor": "y",
        "type": "multicategory",
        "tickangle": "auto",
        "autotickangles": [
            90
        ],
        "tickfont": {
            "size": 9
        },
        "showdividers": true,
        "tickson": "boundaries",
        "ticklen": 14,
        "dividercolor": "grey",
        "dividerwidth": 1,
        "range": [
            -0.5,
            83.5
        ],
        "autorange": true
    },
    yaxis: {
      type: 'linear', 
      range: [0,1],
    }
  }

// console.log('data', data);
// console.log('layout', layout);
// console.log('xDates', xDates);
// console.log('xAnimals', xAnimals)

Plotly.newPlot('myDiv', data, layout);`

<img width="715" alt="Screenshot 2024-05-07 at 2 15 39 PM" src="https://github.com/plotly/plotly.js/assets/1282099/825759d1-e135-4a7d-a73d-95cfe9cd3af8">

**Closed as completed** 2024-11-08 20:03 UTC
Labels: feature, P3
