### ISSUE TITLE
Improve hover label visual for off-plot points 

### ISSUE THREAD

**Issue by etpinard** [plotly/plotly.js#3985] opened 2019-06-25 20:33 UTC
Following-up on https://github.com/plotly/plotly.js/pull/3965#issuecomment-505603345

> Does look a little weird to have the arrows pointing right at the edge of the plot area, but of course this is what we do in other contexts where you're hovering on something off-plot. So maybe at some point we can alter that somehow to make it clearer they're not actually right there. Maybe as simple as getting rid of the arrow altogether, so these ones only have the box?

**Comment by etpinard** [comment] 2019-10-11 21:23
For example

```js
Plotly.newPlot(gd, [{
  type: 'box',
  y: [1,2,2,3]
}], {
  yaxis: {range: [1.6, 2.4]},
  hovermode: 'x'
})
```

gives

![Peek 2019-06-14 17-08](https://user-images.githubusercontent.com/6675409/59538232-00871680-8ec7-11e9-8d88-261ee44d18bc.gif)

**Comment by etpinard** [comment] 2019-10-11 21:23
Another example with bars: https://codepen.io/etpinard/pen/bPEqQL

**Comment by gvwilson** [comment] 2024-06-14 12:50
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-14 12:50 UTC
Labels: type: feature
