### ISSUE TITLE
Reverse ranges when interacting with parcoords labels

### ISSUE THREAD

**Issue by archmoj** [plotly/plotly.js#3941] opened 2019-06-07 00:19 UTC
Flipping the minimum and maximum ranges can help users find desirable layouts e.g. to minimize line crossings. This feature could be triggered by moving the labels up and down or by double-clicking the label (or range - noting that there are no min/max ranges displayed for category axes).

**Comment by gvwilson** [comment] 2024-06-14 12:01
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-14 12:01 UTC
Labels: type: feature
