### ISSUE TITLE
support legend for image trace and to display an icon in (x|y) unified hovermode

### ISSUE THREAD

**Issue by archmoj** [plotly/plotly.js#4632] opened 2020-03-12 15:22 UTC
At the moment an `image` trace cannot have a legend.
As a result there is no icon displayed in unified hover in #4620.
It might be of interest to enable legend option for `image` traces.
cc: @emmanuelle

**Comment by gvwilson** [comment] 2024-06-14 13:00
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-14 13:00 UTC
Labels: type: feature
