### ISSUE TITLE
restyle not working for ternary charts

### ISSUE THREAD

**Issue by VeraZab** [plotly/plotly.js#526] opened 2016-05-12 16:55 UTC
Hi, 
I'm unable to create ternary charts with the restyle function:
http://codepen.io/veraz/pen/GZeVVx

Could you please take a look. Thanks!

**Comment by etpinard** [comment] 2016-05-12 17:36
There are two distinct _issues_ highlighted in this bug report.

1.  Cartesian axes not clearing after the first `restyle` call
1. Ternary `a`, `b`, `c` data arrays are not updating in the subsequent `restyle` calls.

For 1. that's the intended behaviour (unfortunately).

**Full explanation:** the first `Plotly.plot` call creates a graph with 1 `visible: false` trace (because it has no `x`/`y` coordinates). This invisible trace spans a set of cartesian axes - you can see it by adding `console.log(gd.layout.xaxis, gd.layout.yaxis)`.  Then, `Plotly.restyle` updates that first trace to type `scatterternary` which spans a `ternary` layout object - you can see it by adding `console.log(gd.layout.ternary)`, **BUT** does not remove the now-orphan `layout.xaxis` and `layout.yaxis`. Note that this `Plotly.plot` + `Plotly.restyle` signature works as expected for `scattergeo` and `scatter3d` restyle calls because of this very cheeky [block](https://github.com/plotly/plotly.js/blob/19030614649428a0341d28402178bdd32fc75357/src/plots/cartesian/layout_defaults.js#L70-L74) that hasn't been expended for ternary **on purpose** because I'm thinking about dropping it in `v2.0.0`. For more info about how orphan subplots work see PR https://github.com/plotly/plotly.js/pull/289.

**To fix issue:** http://codepen.io/etpinard/pen/ which is far from clean. Bringing in @chriddyp , how hard would it be for trace `type` updates to be done through `newPlot` instead? That would be the most robust solution I think. If that's inconceivable, we could make ternary subplot _on-par_ with geo and gl3d by not showing orphan cartesian axes when ternary subplots are present. 

For 2. well ... that's a bug. 

But an easy one to fix: we just need to add `a`, `b`, `c` to the list of recalc restyle attributes [here](https://github.com/plotly/plotly.js/blob/19030614649428a0341d28402178bdd32fc75357/src/plot_api/plot_api.js#L1575).

**Comment by chriddyp** [comment] 2016-05-12 21:02
anything is possible. we can probably make that work.

**Comment by mdtusz** [comment] 2016-05-17 14:44
**Part 2** is complete - part 2 however will likely remain as is until `v2.0` or a significant framework refactor ¯\_(ツ)_/¯ . We can close this if everyone is satisfied.

**Closed** 2016-05-17 14:51 UTC
Labels: type: bug
