### ISSUE TITLE
[Request] Level-of-detail for scatter plots

### ISSUE THREAD

**Issue by avsdev-cw** [plotly/plotly.js#4190] opened 2019-09-16 14:37 UTC
I've been working on some data that has a LOT of lat/long scatter points in a dense area which causes a lot of lag.  about 1500-2000 points per viewport seems to work quite fluidly, but above that the click and drag/zoom tools really start to lag (click and drag is by far the worst).

There is already a "max displayed" markers parameter (which I'm putting to use), however it causes "holes" to appear until the user has zoomed in significantly and due to the way the points are organised (equal steps in lat/long) there are weird striations and patterns that occur.

It would look a lot better if I were able to have a Level-of-detail (LOD) parameter.  I have a number of thoughts on how this could be achieved.

- The simplest of which would be a parameter that takes an array of sizes at zoom levels and combined with "max displayed" could be used to grow/shrink the markers at different zooms.
- Simplest for the user might be a parameter which when active clusters the points (much like the google [marker clustering](https://developers.google.com/maps/documentation/javascript/marker-clustering)).
- More complex could be that the user supplies an array of their own data points to display at various zoom levels and the marker size for each step.
- Finally, the user could add a trace for each of the different zoom levels and specify at which level the trace should be visible.

Obviously some of these could be done 3rd party by tapping onto the events, however it would be more suitable to add to the core library I think.

**Comment by gvwilson** [comment] 2024-06-14 12:49
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-14 12:49 UTC
