### ISSUE TITLE
Add `marker.nancolor`

### ISSUE THREAD

**Issue by gilles-crealp** [plotly/plotly.js#3035] opened 2018-09-21 11:42 UTC
When you set a `marker.color` array with `null` values, these markers are black.

Shouldn't they be the same color as the line?

https://jsfiddle.net/z1asg45e/

**Comment by etpinard** [comment] 2018-09-21 19:50
Reading from line:

https://github.com/plotly/plotly.js/blob/8c3580ffb3d93c9893c16ce5b67fc7e63666a40e/src/components/colorscale/make_color_scale_func.js#L72

this is the _intended_ behavior. Granted, you can make a case that this behavior isn't optimal. But we won't consider changing it until v2.

**Comment by gilles-crealp** [comment] 2018-09-24 05:07
Sad to read that there is no way to set it up to the auto-color of the line...

**Comment by gilles-crealp** [comment] 2018-09-25 05:47
@alexcjohnson Nice, so I'm reopening this issue. 😉

**Comment by JenniferShelton** [comment] 2020-08-26 20:27
Is there any update on this feature request?

**Comment by nicolaskruchten** [comment] 2020-08-27 00:14
It's a good feature and we'd love to have it in the library but it's not on anyone's roadmap at the moment as far as I know. That said, we as maintainers would be happy to [help someone from the community to implement it in Plotly.js](https://github.com/plotly/plotly.js/blob/master/CONTRIBUTING.md), or to [accept sponsorship](https://plot.ly/products/consulting-and-oem/) to get it on to our short-term roadmap :)

**Comment by gvwilson** [comment] 2024-06-11 17:22
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson

**Closed by gvwilson** 2024-06-11 17:22 UTC
Labels: type: feature
