### ISSUE TITLE
autorange='reversed' in scatter3d

### ISSUE THREAD

**Issue by VelizarVESSELINOV** [plotly/plotly.js#3041] opened 2018-09-22 17:54 UTC
For more details, you can check the closed issue by plotly.py Collaborator pushing the ball to your project :)
https://github.com/plotly/plotly.py/issues/803

**Comment by alexcjohnson** [comment] 2018-09-22 18:33
Duplicate of #1940

**Closed by alexcjohnson** 2018-09-22 18:33 UTC
