### ISSUE TITLE
HEATMAP: Blending of Z values to fill in gaps in x value data

### ISSUE THREAD

**Issue by AndrewJohnBenjamin** [plotly/plotly.js#2167] opened 2017-11-17 09:53 UTC
Hi, I am creating a heatmap that can contain gaps in its x-axis data. For instance, my x-axis may look like this. 1, 2, 3, 4, 5, 6, 11, 12, 13, 14.

When I render my heatmap I am noticing that plotly is blending the Z values either side of this gap across the gap to fill it in. i.e. Plotly will blend the Z values for 6 and 11 together to bridge the gap in x values. Is there a way to prevent this and just have plotly render a white space or a solid colour instead?

Kind Regards,
Andy

**Comment by etpinard** [comment] 2017-11-17 17:25
Using `null`s should do the trick, unless I'm not understanding where you're looking for correctly.

Are looking for something like: https://codepen.io/etpinard/pen/RjjvLe?editors=0010 ?

**Comment by AndrewJohnBenjamin** [comment] 2017-11-20 07:33
That is exactly the type of thing I am looking for. However, the original data is very large and its not really feasible to iterate through it filling in the gaps with null values for performance reasons. Is there another way to achieve this or without manipulating the source data?

**Comment by etpinard** [comment] 2017-11-20 15:08
So if I understand correctly, you expect:

```js
{
  type: 'heatmap',
  x: [1, 2, 3, 4, 5, 6, 11, 12, 13, 14],
  z: [[1, 2, 3, 4, 5, 6, 11, 12, 13, 14]]
}
```

to give

![image](https://user-images.githubusercontent.com/6675409/33024966-95e3e79e-cdda-11e7-94cf-792f9f9efa90.png)

where each `x` item correspond to a single brick of width 1.

----

Related: https://github.com/plotly/plotly.js/issues/1117

**Comment by AndrewJohnBenjamin** [comment] 2017-11-21 09:07
Correct, this is exactly the behaviour I am looking for. At the moment plotly is bridging the gap by blending the z values either side of it. See below.

![image](https://user-images.githubusercontent.com/8436521/33063678-0d5fb6e8-ce9b-11e7-9ec2-b3ff7e94dcea.png)

Notice the area where the gap in x values is and how plotly has blended the z-values either side of it, Instead of this blending, I wish it to be whitespace, exactly as in your example above.

**Comment by etpinard** [comment] 2017-11-21 14:28
Ok @AndrewJohnBenjamin - this sounds like a fairly common use case. I don't think this constitute a bug however. To me, he best way to implement this would be adding an attribute like `brickwidth`.

**Comment by AndrewJohnBenjamin** [comment] 2017-11-23 08:23
Can you provide me with a very basic example of how to implement this please? I've checked the api docs and I cannot find a reference to 'brickwidth' in there anywhere. I can see a 'xgap' attribute that sets the width of bricks on the chart but nothing about 'brickwidth' itself. Also, if I were to set this attribute, wouldnt it effect the entire chart by manipulating the size of every brick?

**Comment by etpinard** [comment] 2017-11-23 14:13
> Can you provide me with a very basic example of how to implement this please?

By implementing, you mean adding this feature to the library, or simply fixing your graph?

If the latter then there's no easy way I'm afraid at the moment. I'd recommend adding `null`s like mentioned in https://github.com/plotly/plotly.js/issues/2167#issuecomment-345308427

**Comment by AndrewJohnBenjamin** [comment] 2017-11-23 16:30
understood. Sorry, seemed to have got our wires crossed then. If this is the only way currently then at least I can work with it; was just wondering if the library already provided a way around it; but you have answered that now. Thanks for your help on this one :)

**Comment by AndrewJohnBenjamin** [comment] 2017-11-28 12:09
Just a quick update on this, I solved this issue by ensure that the last set of values before the gap and the first set of values after the gap are all null. That when when plotly blends these values across the gap, it is blending null with null, and the gap is therefore white. This was a better solution than manually populating all the x values in the gap with nulls for obvious performance reasons

**Comment by niels-hop** [comment] 2020-08-11 05:59
Is there a solution for this problem yet? It has been almost 3 years since this question was asked and I am seeing a lot of the same questions when i search for this issue with heatmaps.

**Comment by nicolaskruchten** [comment] 2020-08-11 13:13
The solution listed above is still the recommended way to do this.

**Comment by jackparmer** [comment] 2020-09-10 19:33
This issue has been tagged with `NEEDS SPON$OR`

A [community PR](https://github.com/plotly/plotly.js/pulls?q=is%3Apr+is%3Aopen+label%3A%22type%3A+community%22) for this feature would certainly be welcome, but our experience is deeper features like this are difficult to complete without the Plotly maintainers leading the effort.

**Sponsorship range: $10k-$15k**

What Sponsorship includes:
- Completion of this feature to the Sponsor's satisfaction, in a manner coherent with the rest of the Plotly.js library and API
- Tests for this feature
- Long-term support (continued support of this feature in the latest version of Plotly.js)
- Documentation at [plotly.com/javascript](https://plotly.com/javascript/)
- Possibility of integrating this feature with Plotly Graphing Libraries (Python, R, F#, Julia, MATLAB, etc)
- Possibility of integrating this feature with Dash
- Feature announcement on [community.plotly.com](https://community.plotly.com/tag/announcements) with shout out to Sponsor (or can remain anonymous)
- Gratification of advancing the world's most downloaded, interactive scientific graphing libraries (>50M downloads across supported languages)

Please include the link to this issue when [contacting us](https://plotly.com/get-pricing/) to discuss.

**Comment by gvwilson** [comment] 2024-06-10 21:02
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson

**Closed by gvwilson** 2024-06-10 21:02 UTC
Labels: type: feature, ♥ NEEDS SPON$OR
