### ISSUE TITLE
Candlestick (OHLC) - plotly_hover returns incorrect point

### ISSUE THREAD

**Issue by cressidave** [plotly/plotly.js#2095] opened 2017-10-17 10:56 UTC
When utilising ploty_hover function on candlestick charts, the point number of the hovered point isn't correctly referenced.

**Comment by alexcjohnson** [comment] 2017-10-17 12:16
Likely duplicate of #1807 ?

**Comment by cressidave** [comment] 2017-10-17 12:39
I'm not sure- check out the pen..
Hover of each and checkout the pointNumber in console

https://codepen.io/cressidave/pen/OxadvQ?editors=1111

**Comment by etpinard** [comment] 2017-10-17 13:15
Not a duplicate in terms of symptoms, but yeah the cause is the same as in #1807 

Merging.

**Closed by etpinard** 2017-10-17 13:15 UTC

**Comment by cressidave** [comment] 2017-10-17 18:17
I'll try and look into this later..
I find it interesting that the hoverlabels display the correct data but the point data is an erroneous return.
