### ISSUE TITLE
Recolor 1 point in 3D scatter with "restyle" cause a bug due to recursive loop

### ISSUE THREAD

**Issue by Florent-Breton** [plotly/plotly.js#4369] opened 2019-11-20 08:38 UTC
Hi,
I already check different issues about the same problem, like [this one](https://github.com/plotly/plotly.js/issues/1025). But I have always the same problem, also with a csv with just 1 point.

Does my code wrong or the bug still remains?

    `setTimeout(function () {
                myPlot.on('plotly_click', function (data) {
                    console.log("data :", data)
                    var pn = data.points[0].pointNumber;
                    var tn = data.points[0].curveNumber;
                    var colors = data.points[0].data.marker.color;

                    colors[pn] = '#C54C82';
                    var update = { 'marker': { color: colors, size: 4 } };
                    Plotly.restyle('chart', update, [tn]);
                });
        }, 200)
    `

> plotly-latest.min.js:7 Uncaught RangeError: Maximum call stack size exceeded
>     at e.exports (plotly-latest.min.js:7)
>     at e.exports (plotly-latest.min.js:7)
>     at e.exports (plotly-latest.min.js:7)
>     at o.merge (plotly-latest.min.js:7)
>     at b._.plot (plotly-latest.min.js:7)
>     at Object.r.plot (plotly-latest.min.js:7)
>     at r.drawData (plotly-latest.min.js:7)
>     at Object.l.syncOrAsync (plotly-latest.min.js:7)
>     at r.plot (plotly-latest.min.js:7)
>     at Object.l.syncOrAsync (plotly-latest.min.js:7)

**Comment by etpinard** [comment] 2019-11-20 14:03
Yes, this is essentially a duplicate of https://github.com/plotly/plotly.js/issues/1025 - which we haven't resolved yet. Merging into https://github.com/plotly/plotly.js/issues/1025

Thanks for posting!

**Closed by etpinard** 2019-11-20 14:03 UTC
