### ISSUE TITLE
change line opacity, leave markers opaque

### ISSUE THREAD

**Issue by stklik** [plotly/plotly.js#2684] opened 2018-05-31 08:55 UTC
Is it possible to add an opacity to the line-attribute?change the line opacity but not the marker opacity?
I found that I can set the opacity of the entire line including markers (`opacity = .5`) and the one of the marker (e.g. `marker={"opacity":1}`). However, it is seemingly impossible to reduce the opacity of just the line.

As shown in this example:

    import plotly
    import plotly.graph_objs as go
    plotly.offline.init_notebook_mode(connected=True)  # I'm running in a jupyter notebook
    
    x = np.arange(0,10)
    ys = [np.random.rand(10) for _ in range(3)]
    
    lines = []
    for y in ys:
        line = go.Scatter(x=x, y=y, mode="markers+lines", opacity=.5, marker={'symbol': 'x', 'size': "15", "opacity":1},
            line={'opacity': 0.5}
        )
        lines.append(line)           
    fig = go.Figure(
        data=lines,
        layout=go.Layout(showlegend=True)
    )
    plotly.offline.iplot(fig)

See result here:
![image](https://user-images.githubusercontent.com/235894/40772296-dd8d0b4e-64bf-11e8-86e2-31b8b48eb459.png)

My problem is the following: My data points are important, the lines are just visual aid. I want to make the lines .5-opaque but have the markers fully opaque.  
However, when I set `opacity=.5, marker={'opacity':1}` the opacity of the marker is also reduced. (I believe that the marker-opacity is defined in the range `[0, line-opacity]`.

PS: If there is an existing solution/workaround for this issue, it might be interesting to (also) answer on my [post on Stackoverflow](https://stackoverflow.com/questions/50488894/plotly-py-change-line-opacity-leave-markers-opaque?noredirect=1#comment88249976_50488894)

**Comment by etpinard** [comment] 2018-05-31 12:58
> Is it possible to add an opacity to the line-attribute?change the line opacity but not the marker opacity?

You can set `line.color` to an rgba value like in this codepen: https://codepen.io/etpinard/pen/QxbNBO?editors=0010

**Comment by stklik** [comment] 2018-05-31 13:13
> You can set line.color to an rgba value
Thanks for your suggestion. 

I saw that possibility, but it requires to manually set the color of the line as well, rather than letting plotly do the coloring. 
In my project I'm changing the list of default colours provided by the `Colors` component, in order to avoid manually setting the colour in every plot I create.
(I therefore asked for an ''official'' solution)

**Comment by alexcjohnson** [comment] 2018-05-31 18:07
> I saw that possibility, but it requires to manually set the color of the line as well, rather than letting plotly do the coloring.

Seems like a reasonable use case... I wouldn't be opposed to adding that.

> In my project I'm changing the list of default colours provided by the `Colors` component, in order to avoid manually setting the colour in every plot I create.

Have you seen `layout.colorway` that does exactly that? https://github.com/plotly/plotly.js/pull/2156 It's still part of each figure then, but it can be a constant for every plot, and then it doesn't require you to have a custom build.

**Comment by stklik** [comment] 2018-05-31 18:20
> Seems like a reasonable use case... I wouldn't be opposed to adding that.
awesome.

> Have you seen layout.colorway that does exactly that? #2156 It's still part of each figure then, but it can be a constant for every plot, and then it doesn't require you to have a custom build.

I had not seen it, but it's exactly what I was looking for. you just made my crooked DIY solution obsolete, thanks!

**Comment by hidai** [comment] 2018-08-09 02:38
I have the same use-case.
Any plan to address the original issue (adding line.opacity)?

**Comment by corymosiman12** [comment] 2020-04-28 18:47
+1

**Comment by JanghyunJK** [comment] 2020-05-13 15:01
+2

**Comment by raffg** [comment] 2020-06-09 04:38
+3

**Comment by JPvRiel** [comment] 2021-09-24 19:56
I've found this seems to be an issue for scatter-plots as well, and the above mentioned work-around using the alpha channel with RGBA does not work. opacity at the parent marker level seems to override any alpha value set for the marker line color.

E.g. when trying to create a bubble chart with transparent fill and solid lines:

```python
import plotly.express as px

df_gap_2007 = px.data.gapminder().query('year == 2007')
fig = px.scatter(df_gap_2007, y='lifeExp', x='gdpPercap',
    size='pop', size_max=50,
    opacity=0.25, color='continent',
    hover_name='country', hover_data=['lifeExp', 'gdpPercap', 'pop']
)
for trace in fig.data:
    trace.marker.line.color = 'rgba(0, 0, 0, 1.0)'
    trace.marker.line.width = 2
fig.show()
```

Resulting plot does not have solid black lines as would be expected with `'rgba(0, 0, 0, 1.0)'`:

![image](https://user-images.githubusercontent.com/9722317/134732559-93cc2b32-3d89-4b6e-bf6f-fbd5e05c2a78.png)

Again, the marker part within `fig.data[0]`:

```
    'line': {'color': 'rgba(0, 0, 0, 1.0)', 'width': 2},
    'opacity': 0.25,
```

**Comment by gvwilson** [comment] 2024-06-11 17:09
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson

**Closed by gvwilson** 2024-06-11 17:09 UTC
Labels: type: feature
