### ISSUE TITLE
[Feature Request] Violin plots with multiple marker symbols

### ISSUE THREAD

**Issue by jshleeb** [plotly/plotly.js#4093] opened 2019-07-31 15:06 UTC
For scatter plots, we can provide "enumerated or array of enumerateds" for marker symbols https://plot.ly/javascript/reference/#scatter-marker-symbol. This allows different points within a trace to have different symbols.

For violin plots, we can plot points on top of a violin plot by setting points: "all". However, the marker symbol option only allows "enumerated", and does not allow passing an array to plot different symbols for different points. https://plot.ly/javascript/reference/#violin-marker-symbol

I would like to be able to provide an array of marker symbols, and have different points on a violin plot render with different symbols.

**Comment by gvwilson** [comment] 2024-06-14 12:48
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-14 12:48 UTC
Labels: type: feature
