### ISSUE TITLE
Add powers-of-two 'exponent base' support to axes

### ISSUE THREAD

**Issue by iustin** [plotly/plotly.js#79] opened 2015-12-05 13:50 UTC
Hi,

It seems that the current exponentformat values for showing human-friendly names are either SI or B (which I'm not sure about; is it billion?). However, these both are powers-of-10, so for computer-related values it would make sense to add a powers-of-two model (where 1024 → 1K, etc.)

**Comment by alexcjohnson** [comment] 2015-12-07 13:14
:+1:
(right, SI and B are only different in how they show 10^9 - G or B)

Binary vs decimal might need to be a separate item from `exponentformat` though - because even in binary mode, you might want to use `exponentformat` of `'none'` (512, 1024, 2048...), `'power'` (2^9, 2^10, 2^11...), or `'SI'` (512, 1K, 2K... that's not technically SI but it seems like the logical extension?). And if we're putting in binary, we might as well allow for other bases too.

So I'm thinking of `exponentbase`, which would default to 10 but you could set it to 2, 8, 16, and if we're feeling energetic `'e'` or an arbitrary (positive) number. But then only some `exponentformat`s would be allowed - `'none'` and `'power'` are always good, `'SI'` is only good for powers of 2 or 10, and `'e'`, `'E'`, and `'B'` are only valid for 10. The default is `'B'` for base 10, seems like `'SI'` would be a good default for powers of 2, and `'power'` for other bases.

@iustin @etpinard thoughts?

**Comment by etpinard** [comment] 2015-12-07 14:51
I like the sound of `exponentbase`

+1

**Comment by iustin** [comment] 2015-12-12 02:46
+1, exponentbase makes more sense than my original proposal. Thanks for considering!

**Comment by mdtusz** [comment] 2015-12-15 15:51
@etpinard @alexcjohnson how should we handle if users use `SI` and an `exponentbase` other than 2 or 10, or use `B`, `e`, `E` with bases other than 10? Throw an error, or should we just fallback to defaults?

**Comment by etpinard** [comment] 2015-12-15 15:59
Fallback to default. 

This logic should be implemented at the defaults step [here](https://github.com/plotly/plotly.js/blob/master/src/plots/cartesian/axes.js#L228).

**Comment by jonashaag** [comment] 2016-06-28 15:49
I'm interested in coding this and making a pull request. Since anything but base 2 and base 10 is definitely a corner case, and it doesn't really make sense to say base-2-SI, my suggestion is to add new options `power2` (2^1, 2^2, ..., 2^n) and `IEC` (the binary equivalent to SI)

**Comment by etpinard** [comment] 2016-06-28 15:53
@jonashaag thanks for interest.

@mdtusz made a PR (see https://github.com/plotly/plotly.js/pull/116) back in December about this. 

We noticed a few inconsistency with the approach (see comments in #116), the PR stalled and we moved on to more important things.

Feel free to give this a shot!

**Comment by jonashaag** [comment] 2016-06-28 18:42
Wow, that PR looks like a lot of work, and changes many things in many places. It would take me too many hours to rewrite/conflict-resolve this.

**Comment by mdtusz** [comment] 2016-06-28 18:55
That's part of the reason that the branch went stale. I wouldn't try to rebase if you do decide to work on it - it's probably easier to just start from scratch based on the diffs - too much has changed in the plotly.js structure since when the PR was opened.

**Comment by etpinard** [comment] 2017-01-06 22:11
See https://github.com/plotly/plotly.js/tree/exponent-base for some WIP work.

**Comment by jacobq** [comment] 2018-08-17 13:16
I agree with the [decision to close #116](https://github.com/plotly/plotly.js/pull/116#issuecomment-219738590), but I'd still love to see this feature. Is there still interest in implementing it?

**Comment by jackparmer** [comment] 2020-09-10 19:30
This issue has been tagged with `NEEDS SPON$OR`

A [community PR](https://github.com/plotly/plotly.js/pulls?q=is%3Apr+is%3Aopen+label%3A%22type%3A+community%22) for this feature would certainly be welcome, but our experience is deeper features like this are difficult to complete without the Plotly maintainers leading the effort.

**Sponsorship range: $10k-$15k**

What Sponsorship includes:
- Completion of this feature to the Sponsor's satisfaction, in a manner coherent with the rest of the Plotly.js library and API
- Tests for this feature
- Long-term support (continued support of this feature in the latest version of Plotly.js)
- Documentation at [plotly.com/javascript](https://plotly.com/javascript/)
- Possibility of integrating this feature with Plotly Graphing Libraries (Python, R, F#, Julia, MATLAB, etc)
- Possibility of integrating this feature with Dash
- Feature announcement on [community.plotly.com](https://community.plotly.com/tag/announcements) with shout out to Sponsor (or can remain anonymous)
- Gratification of advancing the world's most downloaded, interactive scientific graphing libraries (>50M downloads across supported languages)

Please include the link to this issue when [contacting us](https://plotly.com/get-pricing/) to discuss.

**Comment by gvwilson** [comment] 2024-06-05 12:40
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson

**Closed by gvwilson** 2024-06-05 12:40 UTC
Labels: type: feature, ♥ NEEDS SPON$OR
