### ISSUE TITLE
Day of Year Date Format Support

### ISSUE THREAD

**Issue by JordanBallew** [plotly/plotly.js#453] opened 2016-04-20 20:30 UTC
Is there currently a way to do day of year date formatting? I didn't see it in the documentation. If not, is there any interest in adding it? It is a popular format in the science and engineering communities, and it is already supported in D3 as %j.

https://github.com/mbostock/d3/wiki/Time-Formatting

**Comment by mdtusz** [comment] 2016-04-20 21:33
We hope to fix this soon, but it is not at the very top of our priority list. We are always open to pull requests if they come sooner though!

Duplicate of https://github.com/plotly/plotly.js/issues/380.

**Comment by JordanBallew** [comment] 2016-04-20 21:41
Do you have an guidance on where to start looking in the code base to make a change for this?

**Comment by mdtusz** [comment] 2016-04-20 21:46
I haven't worked much on the date formatting myself, but I believe [this code](https://github.com/plotly/plotly.js/blob/master/src/plots/cartesian/axes.js#L905) may be a good place to start!

The [development](https://github.com/plotly/plotly.js/blob/master/CONTRIBUTING.md#development) section of our `contributing.md` has some information on the test dashboard and some tools you may find helpful as well.

**Closed** 2016-04-21 13:56 UTC
Labels: type: duplicate
