### ISSUE TITLE
Poor resize performance

### ISSUE THREAD

**Issue by john-soklaski** [plotly/plotly.js#283] opened 2016-02-24 23:47 UTC
I have a website that contains many scatter plots which resize on the window's resize event. Each chart takes around 300ms to re-render, leaving the site feeling very sluggish (based on the "Timeline" feature of the Chrome devtools).

Here is a small repro:
http://codepen.io/john-soklaski/pen/NNKqjq

Browser: Chrome 48.0.2564.116 m
Machine: Intel Xeon CPU E5-1607 @ 3.00 GHZ
OS: Windows 10

**Comment by mdtusz** [comment] 2016-02-25 15:25
Thanks for reporting!

This isn't very high on our priority list at the moment so we won't have time to get around to it for a little while, but if you're willing to take a stab at it yourself, a good starting point to dive in may be [here](https://github.com/plotly/plotly.js/blob/master/src/plots/plots.js#L256).

**Comment by blankclemens** [comment] 2016-02-26 13:33
Hello there,

im also absolutely disappointed in the drawing performance and looked a little bit into it: On a common mid-class machine, the drawing needs for a simple scatter chart with just 5 points around 30-40ms (on Chrome, the rest looks way worse). Having 500 points increases it just by 5ms.

So the problem is not the graph data - it actually is the labels. More preciously: `Plotly.Axes.doTicks` takes most of the drawing time. While this might not be a problem for static data, it becomes one when having multiple plots with dynamic changing data.

So I wonder, is it really necessary that just doing the labels/ticks takes most of the drawing time? Probably there is a clever way of handling labels correctly behind it, but for me it stands in no relation to amount of processing time needed for it.

**Comment by john-soklaski** [comment] 2016-03-01 01:38
doAutoMargin() appears to cause the plot to be drawn twice.

![image](https://cloud.githubusercontent.com/assets/12491965/13414572/b7f529be-df08-11e5-97d4-39ffec194517.png)

I don't fully understand the implications of this change, but for my use case I get a significant speed improvement with no loss of functionality:
https://github.com/plotly/plotly.js/compare/master...john-soklaski:resize_perf

**Comment by john-soklaski** [comment] 2016-03-01 01:40
@mdtusz I would like to have resizing be an order of magnitude faster. Do you think this is possible with the current redraw everything approach? Or would it require a reworking of graph layout?

**Comment by john-soklaski** [comment] 2016-03-02 03:00
I moved `gd._replotting = true;` above the call to `plots.supplyDefaults()` so `plots.doAutoMargin()` doesn't replot. 

I'll have time to look at this more tomorrow and get some numbers (the improved performance was a one-off observation).

**Comment by marcj** [comment] 2016-08-05 21:24
@john-soklaski any news? :)

**Comment by john-soklaski** [comment] 2016-08-05 22:25
@marcj No, unfortunately I had to move on to other things. I'm hoping that @rreusser 's animation work might address some of the underlying issues though.

**Comment by rreusser** [comment] 2016-08-05 22:59
Interesting, though I'm not sure about the ability of my PR to improve this case. If I had to summarize the animation PR, it would be that it repurposes existing functionality to accomplish an optimized redraw. (Other big thing = reusing DOM elements, but I don't think that's the bottleneck in resizing.) Unfortunately, the more things change, the more parts need to be re-run, to the point that by the time you change the size of the whole plot, really you mostly just need to redraw the plot. It certainly seems possible to explicitly optimize resizing, but I don't know that the animation PR will handle this automatically.

**Comment by gvwilson** [comment] 2024-06-05 12:43
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson

**Closed by gvwilson** 2024-06-05 12:43 UTC
Labels: type: performance
