### ISSUE TITLE
3D Scatter Hover Issue with full opacity in FF on Ubuntu

### ISSUE THREAD

**Issue by Backlash1337** [plotly/plotly.js#3008] opened 2018-09-13 19:36 UTC
I've encountered an issue with the 'show closest data on hover' on 3D scatter plots, when the opacity is set to 1.

No matter which data-point you'll hover on, it will always show the information of the **first data-point**.
This only happens for the **first set of traces**, all others behave correctly on hover.
Furthermore, the bug seems to be gone, when the **opacity** of that trace set is lower than 1 (e.g. 0.9).
(Using the CDN link to ensure the newest version of plotly and Firefox 62.0 Ubuntu)

I've created an example here: 
https://codepen.io/anon/pen/yxEKvj
The green data-points (trace 0) are the ones behaving incorrectly, red (trace 1) and blue (trace 2) work fine.

![hover_bug](https://user-images.githubusercontent.com/26602599/45511332-0a93b180-b79d-11e8-9c1f-f1d7855de980.png)

**Comment by etpinard** [comment] 2018-09-13 20:28
![peek 2018-09-13 16-27](https://user-images.githubusercontent.com/6675409/45513906-f5555d80-b771-11e8-9f25-78dc5b37bbca.gif)

Confirmed in FF61 on Ubuntu 18.04. The example works fine for me in Chrome 69 though.

Thanks for the report.

**Comment by alexcjohnson** [comment] 2018-09-13 22:40
Looks like just linux+FF - works fine in both FF and Chrome on Mac

**Comment by mikk351** [comment] 2018-09-19 13:43
Same problem here, Ubuntu 16 and 18 and Chrome Version 69.0.3497.92 (64-bit) and FF 62

**Comment by etpinard** [comment] 2018-09-19 13:54
OK well I guess we'll have to start listing hardware not just OS and browser versions.

On my Lenovo t450s running Ubuntu 18.04, the examples works on Chrome 69, does not work in FF61.

**Comment by etpinard** [comment] 2018-12-19 22:32
Fixed in 1.43.0

**Closed by etpinard** 2018-12-19 22:32 UTC
Labels: type: bug
