### ISSUE TITLE
XML Parsing Error: mismatched tag. Expected: </tspan>.   [Plotly 1.18.1, Firefox]

### ISSUE THREAD

**Issue by jensb** [plotly/plotly.js#2485] opened 2018-03-20 09:01 UTC
I am encountering a weird error in Plotly 1.18.1 in my application.

Sometimes, when re-rendering the Plotly chart (calling Plotly.newPlot() with identical data in the identical DIV but different dimensions for the DIV), I get the above error message with the backtrace below.
This does not happen with every data set but so far I could not find a common denominator in the datasets where it happens.

I would be very grateful if somebody could help me debug this. I tried to produce an example but so far I could not reproduce this, it might be a browser specific race condition - it does not happen with Chrome, only with Firefox (both ESR and 58.0.1). 

**Here is the error:**
XML Parsing Error: mismatched tag. Expected: </tspan>.
Location: .....
Line Number 1, Column 173:

**Here is a backtrace:**
[695]</d3.selection.prototype.appendSVG@....lib/plotly/plotly-latest.js:99267:17
showText@....lib/plotly/plotly-latest.js:99327:18
[695]</exports.convertToTspans@....lib/plotly/plotly-latest.js:99412:10
textLayout@....lib/plotly/plotly-latest.js:89172:9
[129]</</d3_selectionPrototype.call@....lib/plotly/plotly-latest.js:16001:5
drawTexts@....lib/plotly/plotly-latest.js:89207:10
[129]</</d3_selectionPrototype.call@....lib/plotly/plotly-latest.js:16001:5
draw/<@....lib/plotly/plotly-latest.js:88932:13
[129]</</d3_selectionPrototype.each/<@....lib/plotly/plotly-latest.js:15988:7
d3_selection_each@....lib/plotly/plotly-latest.js:15994:30
[129]</</d3_selectionPrototype.each@....lib/plotly/plotly-latest.js:15987:12
draw@....lib/plotly/plotly-latest.js:88922:5
marginPushers@....lib/plotly/plotly-latest.js:100389:9
[681]</lib.syncOrAsync@....lib/plotly/plotly-latest.js:97463:15
[698]</Plotly.plot@....lib/plotly/plotly-latest.js:100538:5
[698]</Plotly.newPlot@....lib/plotly/plotly-latest.js:100726:12

Thank you!

**Comment by etpinard** [comment] 2018-03-20 13:18
Ok. Two questions for you:

- `1.18.1` is over a year old. Does the latest version `1.35.2` exhibit this bug also?
- Debugging from a call stack is almost impossible. Can you please share a reproducible example?

**Comment by jensb** [comment] 2018-03-26 09:16
I will try the most current release first and report back here, thank you.
About reproducibility, I tried but I cannot even reproduce this in our own app using exact the same input data. Much less creating a minimum example. (This is why I assumed it was a race condition...)

**Comment by etpinard** [comment] 2018-04-06 20:36
Closing due to lack of reproducible example. @jensb feel free to open up a new issue if/when you're able to reproduce this bug.

**Closed by etpinard** 2018-04-06 20:36 UTC
