### ISSUE TITLE
Heatmap space between heatmap bricks not working

### ISSUE THREAD

**Issue by hanumanthraju** [plotly/plotly.js#1226] opened 2016-12-06 13:41 UTC
Hi, 
space between heatmap bricks not working when I render graph in my page..but shows space between bricks when I view in plot cloud. Any idea? Thanks in advance.
Here is the code
 `heatMapData = [{
          x: xValues,
          y: yValues,
          z: zValues,
          type: 'heatmap',
          colorscale: colorscaleValue,
          xgap:1,
          ygap:1,
          opacity : 1,
          showscale:true,
          zsmooth:false,
          text: zText,
          hoverinfo: "text",
        }];`

**Comment by rreusser** [comment] 2016-12-06 13:45
Could you share a reproducible example, perhaps on codepen? It really helps us reproduce and debug the issues much more quickly. Here's an example of what a codepen might look like: http://codepen.io/rsreusser/pen/YpNGaY 

Thanks so much!

**Comment by hanumanthraju** [comment] 2016-12-06 13:52
Thanks!. I will try to create codepen and  #share.
Here is screenshot of the issue.
heatmap on my website:
![image1](https://cloud.githubusercontent.com/assets/6049341/20927787/1f1edc44-bbe9-11e6-91ca-cf2a7380975f.PNG)

On plotly cloud:
![img-plotly-cloud](https://cloud.githubusercontent.com/assets/6049341/20927788/1f1fe6a2-bbe9-11e6-86c9-31e1e6553539.PNG)

I'm using plotly with angularJs.

**Comment by hanumanthraju** [comment] 2016-12-06 13:57
show space between heatmap bricks is Pro feature?

**Comment by etpinard** [comment] 2016-12-06 14:44
@hanumanthraju That's probably because you're using an old version of plotly.js.

**Comment by etpinard** [comment] 2016-12-07 02:42
Closing until someone can reproduce this bug using the latest plotly.js version.

**Closed by etpinard** 2016-12-07 02:42 UTC
