### ISSUE TITLE
spikedistance=-1: lines are not drawn up to the closest bar in some cases

### ISSUE THREAD

**Issue by antoinerg** [plotly/plotly.js#4638] opened 2020-03-13 18:57 UTC
Following the introduction of https://github.com/plotly/plotly.js/pull/4637, the following edge case will need to be fixed:
![image](https://user-images.githubusercontent.com/2678795/76622512-09fde780-6508-11ea-900a-1c23e0c5e79f.gif)

See https://github.com/plotly/plotly.js/pull/4627#issuecomment-598706293 for a complete description of the issue and a suggestion on how to fix it.

**Comment by gvwilson** [comment] 2024-06-14 13:00
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-14 13:00 UTC
Labels: type: bug
