### ISSUE TITLE
Hover does not scale with growing number of traces

### ISSUE THREAD

**Issue by cameronwaterman** [plotly/plotly.js#3826] opened 2019-05-01 16:22 UTC
Hover performance degrades with growing number of traces.
1M points in one trace is 10x faster when hovering than 1M points spread across 100 traces.

- https://codepen.io/cameronwaterman/pen/jRjMxO
- Plotly Version: 1.47.4
- OS: Windows 10 Pro (10.0.17134 Build 17134)
- Browser: Chrome 73.0.3683.103

**Comment by rhamner** [comment] 2019-05-02 13:36
I'm seeing the same thing. I tried working around it by turning off auto-hover info and using the plotly_hover event, but it has the same issue. Even worse I guess...the issue is still there with a small number of points (100 traces with 100 points per trace):

https://codepen.io/rhamner/pen/rbEWjY

**Comment by etpinard** [comment] 2019-05-02 13:53
Thanks for writing @cameronwaterman . A _lot_ of things (not just hover) are slower when you have more than say 30 traces on your graph. Plotly isn't well optimized for these cases (yet). I recommend using the least number of traces possible (e.g. by setting `marker.color` as an array) whenever you can.

@rhamner Listening to `plotly_hover` won't help. It makes uses of the same picking algorithm to find which point(s) is the closest to your cursor.

**Comment by rhamner** [comment] 2019-05-02 14:04
@etpinard 

I couldn't help but notice the '(yet)'. Any info on when it might be more optimized?

**Comment by etpinard** [comment] 2019-05-02 14:20
> Any info on when it might be more optimized?

Not anytime _soon_ I'm afraid.

**Comment by cameronwaterman** [comment] 2019-05-02 15:27
Thanks for your response @etpinard 

Glad to see this was already on your radar, hopefully we can see some performance improvements in this regard sometime in the not-to-distant future, and at least there is a workaround for the time being.

**Comment by jebenois** [comment] 2021-08-10 03:13
Any updates on this one? Trying to make hover faster with ~300 traces

**Comment by gvwilson** [comment] 2024-06-14 11:56
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-14 11:56 UTC
Labels: type: performance
