### ISSUE TITLE
Tight automargins with label/title/legend clipping

### ISSUE THREAD

**Issue by wbrgss** [plotly/plotly.js#4376] opened 2019-11-21 00:22 UTC
Related: #2985, #3579, #3607 

I'm making another issue to document existing problems with text inside figures. Most of the problems have to do with tight explicit `layout.margin` + `layout.(x|y)axis.automargin = True`, but the first two examples in my codepen have no layout defined (using the default layout). Each `Plotly.newPlot` call has a comment above it describing the specific issue. Most of these examples are from our own docs.

Here is the codepen, using `plotly-latest` (`v1.51.1`): https://codepen.io/wbrgss/pen/ExxMXQP

I also have some screenshots from graphs using automargins; unfortunately I cannot easily, consistently reproduce them:

*150° and 180° labels are cut off*
![scatterpolar_labels](https://user-images.githubusercontent.com/9068290/69289332-288f4a00-0bca-11ea-9187-1e6bb88f5d26.png)

*axis labels overlap without rotating*
![splom_overlap](https://user-images.githubusercontent.com/9068290/69289333-288f4a00-0bca-11ea-99d9-7e253f9da3fb.png)

*top legend text is cut off*
![barpolar_legend](https://user-images.githubusercontent.com/9068290/69289334-288f4a00-0bca-11ea-89a3-c7d9dc95ce51.png)

If it would be helpful, I can try to create examples for these figures, but hopefully the codepen provides a good starting point. I realize that the axis labels/tick labels/legend text may be different issues, so if you'd like me to create separate issues/codepens I can do that also.

cc @nicolaskruchten @etpinard

**Comment by nicolaskruchten** [comment] 2019-11-21 00:29
Thanks Will!

A couple of notes: 

1) polar charts have no automargins and are not affected by automargin settings on x/y so that’s expected today, although fixing it would be a good feature to add!

2) axis labels never rotate today, only tick labels, so that’s also not a malfunction but a missing feature 

The legend thing seems like a bug though!

**Comment by gvwilson** [comment] 2024-06-14 12:52
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-14 12:52 UTC
