### ISSUE TITLE
Hovervalues can be shown incorrectly with a large range of values

### ISSUE THREAD

**Issue by precisesimulation** [plotly/plotly.js#1711] opened 2017-05-20 03:44 UTC
Sometimes with very small values the hoverdata shows incorrect value probably due to some truncation, rounding, or formating. Hovering over the right left point shows _10_ instead of _~0_

`Plotly.newPlot('myDiv',[{x: [0, 1],y: [1e-8, 1],type: 'scatter'}]);`

Note that it works fine with for example 

`Plotly.newPlot('myDiv',[{x: [0, 1],y: [1e-8, 2e-8],type: 'scatter'}]);`

when the _y_ values does not span a big range.

**Comment by etpinard** [comment] 2017-05-23 13:47
Probably a duplicate of https://github.com/plotly/plotly.js/issues/755

Related:

- https://github.com/plotly/plotly.js/issues/912
- https://github.com/plotly/plotly.js/issues/803
- https://github.com/plotly/plotly.js/issues/780

**Comment by etpinard** [comment] 2017-08-07 14:20
@rreusser can you confirm that https://github.com/plotly/plotly.js/pull/1932 also resolved this issue?

**Comment by rreusser** [comment] 2017-08-07 16:59
Confirmed!

<img width="150" alt="screen shot 2017-08-07 at 09 59 05" src="https://user-images.githubusercontent.com/572717/29037109-15ddb7e4-7b57-11e7-8fe9-688413343c1c.png">

**Closed** 2017-08-07 16:59 UTC
Labels: type: bug
