### ISSUE TITLE
HeatmapGL axis tick value overlap plot

### ISSUE THREAD

**Issue by ONLYstcm** [plotly/plotly.js#3998] opened 2019-06-30 16:56 UTC
I've been trying to swap out  HeatmapGL for Heatmap as it renders alot faster in my application however I've experienced quite a few bugs (most have been raised already and sorted - Thanks). One of the two bugs I still experience is that the tick values (specifically on the y-axis) overlap with the actual heatmap when they get longer. This does not happen in Heatmap however.

HeatmapGL
![image](https://user-images.githubusercontent.com/26184198/60399713-3683f600-9b69-11e9-82b7-aaebd5b9c74a.png)

Heatmap
![image](https://user-images.githubusercontent.com/26184198/60399721-4996c600-9b69-11e9-999f-fd8c144c842f.png)

Codepen link: https://codepen.io/anon/pen/EBQoRb

Code (incase the codepen link expires)
HTML
```
		<head>
		<script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
		</head>
		<body>
		<div id="mapgl"></div>
		<div id="map"></div>
</body>
```

JS
```
var data = 
  [{
    z: [[1, 1, 1],
        [1,1,1],
        [1,1,1]],
    type: 'heatmap'
  }];

var data2 = 
  [{
    z: [[1, 1, 1],
        [1,1,1],
        [1,1,1]],
    type: 'heatmapgl'
  }];


var layout = {
  title: 'Zoom into Heatmap',
  xaxis: {'title': 'Frequency [MHz]'},
}

Plotly.plot('map', data, layout);
Plotly.plot('mapgl', data2, layout);
```

**Comment by gvwilson** [comment] 2024-06-14 12:47
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-14 12:47 UTC
Labels: type: bug
