### ISSUE TITLE
Hover tooltip positioned wrong in stacked barchart when number of bar is 1

### ISSUE THREAD

**Issue by alexbyj** [plotly/plotly.js#2154] opened 2017-11-13 15:51 UTC
my macbook screen resolution : 1680x1050
browser: firefox 56.0.2 (64-bit)
reproducible jsfiddle link : https://jsfiddle.net/o9fc44pg/1/
used library : https://cdn.plot.ly/plotly-latest.min.js
Is there any limit of tooltip label character length?
screenshot 
<img width="737" alt="screen shot 2017-11-13 at 9 45 24 am" src="https://user-images.githubusercontent.com/10076271/32734491-cba72d56-c857-11e7-91d8-446aed3fc4e5.png">

**Comment by alexcjohnson** [comment] 2017-11-15 18:15
Thanks @alexbyj - specifically the problem here is with the centered label: when there isn't enough room to put the label either entirely to the right or entirely to the left of the object it's labeling, we center it; but the text is not positioned properly in this case. This situation doesn't arise very often, which is why it's not well tested I guess.

Probably duplicate of #865

**Closed** 2018-03-05 15:37 UTC
Labels: type: bug

**Comment by nishantlnmiit** [comment] 2020-09-24 10:58
I am also facing the same issue while using this with shiny ggplot2 library
Please help me out.
