### ISSUE TITLE
Firefox Latex/Mathjax Rendering Broken

### ISSUE THREAD

**Issue by j-proc** [plotly/plotly.js#5391] opened 2021-01-11 13:12 UTC
It seems that there's a latex rendering issue on firefox again... #2616 

I'm including a specific example for illustration.

Everything works fine on chrome:
![chrome](https://user-images.githubusercontent.com/47364977/104185968-b6884e80-53e3-11eb-8692-b3730db76a28.png)

On firefox:
![firefox](https://user-images.githubusercontent.com/47364977/104186029-cbfd7880-53e3-11eb-9dab-ce199fc93833.png)

By playing with the anchor points and font size I could get things to show up in bizarre ways. The degree to which things are not working seems to be very dependent on the size of the bounding box as well. A single character often at least displays with the default settings. By making a simple `a+b` statement however, I needed to change the anchor point or font. The arrow didn't work consistently either.

![Screenshot_2021-01-11 Online Graph Maker · Plotly Chart Studio(1)](https://user-images.githubusercontent.com/47364977/104186272-2eef0f80-53e4-11eb-821e-fe2a38abf377.png)
![Screenshot_2021-01-11 Online Graph Maker · Plotly Chart Studio(2)](https://user-images.githubusercontent.com/47364977/104186287-34e4f080-53e4-11eb-9296-d13b6f4fc34a.png)
![Screenshot_2021-01-11 Online Graph Maker · Plotly Chart Studio(3)](https://user-images.githubusercontent.com/47364977/104186646-b63c8300-53e4-11eb-80bb-a7d7cb32fefd.png)

**Comment by alexcjohnson** [comment] 2021-01-11 14:11
Duplicate of #5374 (which now has a more obvious title 😅 )
Thanks for the details, it seems pretty clear the problem is somewhere in the bounding box calculations.

**Closed by alexcjohnson** 2021-01-11 14:11 UTC
