### ISSUE TITLE
Different zero for xaxis in case of multiple axis with different types

### ISSUE THREAD

**Issue by ramon-ga** [plotly/plotly.js#1845] opened 2017-07-04 14:36 UTC
I'm using two y-axes in a plot with different types (bar and scatter).
With this, the zero line of the x axis is not a the same position on y and y2.

Example:
https://codepen.io/anon/pen/GEGKLm

If for y-axes the type scatter is used there's no problem (https://codepen.io/anon/pen/xrzxxb).
I think the both zero's of the x-axis should be at same level, right?

**Comment by etpinard** [comment] 2017-07-04 14:47
That's the intended behavior. We pad the axis ranges a little bit when scatter traces with markers are present. In your graphs, `yaxis` has only a bar trace (that means no axis expand), `yaxis2` has a scatter trace with markers (that the axis range is expanded a little bit).

To override the default behavior, simply add `rangemode: 'tozero'` to the `layout.yaxis2` as in:

**Comment by etpinard** [comment] 2017-07-04 14:47
This ticket won't result in a PR, so I'll close it.

**Closed by etpinard** 2017-07-04 14:47 UTC

**Comment by ramon-ga** [comment] 2017-07-04 15:16
Thank you for the fast reply and the solution.
I think i tried this, but maybe i added it at a wrong position.

**Comment by vijaygaddam190** [comment] 2019-05-10 00:55
Is there any way to achieve same zero position for multiple y-axis and with -ve values.

**Comment by GendelfLugansk** [comment] 2019-05-11 14:10
It is possible to calculate correct range for each axis with some math and then for each y-axis set `autorange` = `false` and `range` as calculated.

How to calculate ranges:

1. Calculate `rangeLength` (`max y value - min y value`) for each y-axis using your data
2. Determine which `rangeLength` is biggest. Let's say it would be `rangeLength2`
3. For each y-axis calculate coefficient by dividing maximal `rangeLength` by `rangeLength` of that axis. I.e. `coeff1 = rangeLength2/rangeLength1`
4. Take `min y value` and `max y value` for each axis, multiply by respective coefficient (i.e. multiply `y values of axis y1` by `coeff1`) and put them in array
5. Find minimum and maximum value from that array, let's call it `commonRange`
6. Now you can find `range` for each y-axis if you divide each item of `commonRange` by corresponding coefficient from step 3

I tested it with 2 y-axis, seems to work for me. Be aware about theoretically possible division by zero errors, i.e. skip calculation for axis where `rangeLength` is 0.

**Comment by vijaygaddam190** [comment] 2019-05-15 17:48
Awesome. I tried with 3 Y-Axis's it worked. Also is there any way to match 3 Y-Axis's grid lines?

**Comment by GendelfLugansk** [comment] 2019-05-15 18:17
@vijaygaddam190 I didn't try but I think that it can be done by setting `tickmode: 'array'` and calculating  [tickvals](https://plot.ly/javascript/reference/#layout-yaxis-tickvals) based on calculated ranges for each axis (i.e. if you will break each range into the same amount of intervals, they should be on the same line)

Something like this:
```
const numberOfTicks = 10;
const commonRangeBetweenTicks = (max(...commonRange) - min(...commonRange))/(numberOfTicks -1);
const commonTickVals = [];
const firstTick = min(...commonRange);
for (let i = 0; i < numberOfTicks; i++) {
  commonTickVals.push(firstTick + (commonRangeBetweenTicks * i));
}
const tickvals1 = commonTickVals.map(v => v / coeff1);
```

**Comment by vijaygaddam190** [comment] 2019-05-22 21:11
@GendelfLugansk above calculations are worked for me, but we got problem with number of ticks because we are getting no of ticks based on the number of data sets we got. With this calculation we are making tick values depend on each other which fails my requirement. 

Please check the picture in this link.
https://community.plot.ly/t/is-it-possible-to-have-multiple-y-axis-0-zero-positions-in-same-line/23236

**Comment by GendelfLugansk** [comment] 2019-05-22 21:44
@vijaygaddam190 Plotly draws grid lines on each tick. Only workaround I can propose - disable grid (`showgrid: false`) for all y-axis except one.

**Comment by vijaygaddam190** [comment] 2019-05-23 13:32
i did the same thing it looks good. But we got problem with number of ticks because we are getting no of ticks based on the number of data sets we got. With this calculation we are making tick values depend on each other which fails my requirement.

**Comment by VictorBezak** [comment] 2020-02-28 01:30
I've crafted a comprehensive solution. This was fairly rushed, so if there are any mistakes or confusions, please do let me know

https://github.com/VictorBezak/Plotly_Multi-Axes_Gridlines

**Comment by pkozul** [comment] 2020-03-18 21:53
Thanks Victor, your solution is working for me. Hopefully others can make use of it too.
