### ISSUE TITLE
Update menu buttons text not vertically centrered

### ISSUE THREAD

**Issue by jamesmudd** [plotly/plotly.js#4161] opened 2019-09-02 08:17 UTC
See for example

https://codepen.io/jamesmudd/pen/ExYwarp

This looks especially bad when using font icons like a cog for settings. It is especially noticeable with larger font sizes. Could you make it vertically centred?

**Comment by etpinard** [comment] 2019-09-03 15:20
Thanks for posting, something does appear off when large fonts are used.

Maybe we should add a `valign` attribute like we did for legend text in https://github.com/plotly/plotly.js/pull/3263

**Comment by gvwilson** [comment] 2024-06-14 12:49
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-14 12:49 UTC
Labels: type: bug, type: feature
