### ISSUE TITLE
Improve gl3d APIs to ingest regular grid volume data without inserting every vertex position

### ISSUE THREAD

**Issue by archmoj** [plotly/plotly.js#4228] opened 2019-09-26 22:13 UTC
When developing `volume` and `iso-surface` traces we tried to make their APIs similar to `streamtube` and `cone` traces. This was actually a hard thing to achieve while non-uniform grids should be supported.
However in case of having a regular grid inserting the 3d coordinates of every vertex is not easy and disk / memory efficient.
It might be a good idea to have ways of declaring such grids for example similar to `heatmap` we may have two `float` attributes of `x0` and `dx` to declare all the `x` coordinates.
https://github.com/plotly/plotly.js/blob/0ad91e443870a7ae2950c9e867ac35df015d114d/src/traces/heatmap/attributes.js#L24-L29

In addition to `volume` and `iso-surface` this option could be useful for `cone` and `streamtube`.

**Comment by etpinard** [comment] 2019-10-03 15:38
Dropping from 1.51.0

**Comment by gvwilson** [comment] 2024-06-14 12:59
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-14 12:59 UTC
Labels: type: feature
