### ISSUE TITLE
Allow heatmaps to understand line objects

### ISSUE THREAD

**Issue by cpsievert** [plotly/plotly.js#898] opened 2016-09-02 16:25 UTC
This could be used to effectively set the stroke of heatmap cells. Without it, I can't replicate this ggplot2 example -- https://github.com/ropensci/plotly/issues/699

**Comment by talgalili** [comment] 2017-04-09 11:28
BUMP.
I hope this could be resolved so that heatmaps would include the option to show cells grid.

Thanks.

**Comment by rreusser** [comment] 2017-04-09 14:32
@talgalili `xgap` and `ygap` from #868 are not an exact match to this feature, but they do accomplish padding for the cells, which may be of some help.

**Comment by talgalili** [comment] 2017-04-09 14:34
Thanks @rreusser .
@cpsievert  - could this help solve this: https://github.com/ropensci/plotly/issues/699
what do you think?

**Comment by cpsievert** [comment] 2017-04-09 16:47
@talgalili no, `xgap`/`ygap` seem to specify a _constant_ gap between each cell.

Also, for ggplot2 parity, we need each cell border to respect linetype. Just adding `lty = 4` to [your example](https://github.com/ropensci/plotly/issues/699#issue-174334503) yields:

<img width="667" alt="screen shot 2017-04-09 at 11 43 23 am" src="https://cloud.githubusercontent.com/assets/1365941/24839101/31f38ca6-1d1a-11e7-913d-5610c8d1e009.png">

**Comment by talgalili** [comment] 2017-04-09 16:59
Hi @rreusser 
Since my personal need for this is the ability to have a "grid like" look for the heatmaply R package, then actually "a constant gap between each cell" (defined on top of a ggplotly object derived from geom_tile), would be great. However, I'm not sure how to map that to the existing Aesthetics of geom_tile...

**Comment by cpsievert** [comment] 2017-04-09 21:53
@talgalili use `style()` to *modify* the attributes of existing traces:

```r
style(p, xgap = 5)
```

**Comment by talgalili** [comment] 2017-04-10 07:51
Thanks @cpsievert , this is very helpful! It would still be nice to have this issue resolved directly. But for now, this resolved the main feature I was looking for (i.e.: to add a grid of lines to heatmaply - https://github.com/talgalili/heatmaply/commit/0f9f73b254d2faf52f2c1b5ae6fbc187aac3dde2).

**Comment by adriwitek** [comment] 2021-03-01 19:15
I need to make a grid over a annotated heat map and this is very frustrating

**Comment by gvwilson** [comment] 2024-06-05 16:56
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson

**Closed by gvwilson** 2024-06-05 16:56 UTC
Labels: type: feature

**Comment by rabyj** [comment] 2025-04-28 18:03
I think this is still pertinent. This isn't the first time I try to add grid lines in-between cells, without success. I didn't find any other issue related to this, but I might have missed it (I'm working from the Python side, but I imagine it would have to be implemented here first). 

Currently, the grid lines from axes are centered on the cells, instead of at their edges.

I'm trying to reproduce something like this, and parameters `xgap` /`ygap` + `plot_bgcolor` are not enough, since I have nans that share the background color.

Should a new issue be opened?

![Image](https://github.com/user-attachments/assets/e8e8a976-09ef-4993-9bee-3d0ef6321179)
