### ISSUE TITLE
Sankey node `hovertemplate` attributes documentation

### ISSUE THREAD

**Issue by alb-erandelcastillo** [plotly/plotly.js#4240] opened 2019-10-01 20:46 UTC
I'm trying to set a customdata attribute to the nodes of a sankey diagram (i.e. percentage of node value of total value) and display that calculation when hovering over the node. I can't access the parent data customdata attribute in the node hovertemplate. 

Could there be documentation for the event data available for node hovertemplates? Also, it'd be helpful to access the x0, x1, y0, y1 of the nodes, is there a way to do this?

@matthewchan15

**Comment by matthewchan15** [comment] 2019-10-02 00:37
@alb-erandelcastillo is a member of the data science team, where I'm currently giving a workshop.

We had some challenges getting `hovertemplate` to work with `node` because the parameters were not explicitly defined in the documentation. 

See documentation here: https://plot.ly/python/reference/#sankey-node-hovertemplate

which redirects to available variables parameters here: https://plot.ly/javascript/plotlyjs-events/#event-data, where `sankey` is nowhere to be found.

It would be nice to add the properties which are accessible through `hovertempate` to the docs.

As of right now these are: `y0, y1, x0, x1, value, label, flow` according to @antoinerg

**Comment by matthewchan15** [comment] 2019-10-02 00:37
CC: @michaelbabyn

**Comment by etpinard** [comment] 2019-10-02 15:40
Thanks for posting. 

This ticket is essentially the sankey version of the more general: https://github.com/plotly/plotly.js/issues/4139

**Comment by antoinerg** [comment] 2019-10-02 15:51
> This ticket is essentially the sankey version of the more general: #4139

It is but in the case of Sankey it's not just documentation that needs improvements: Sankey's `node.hovertemplate` exposes `y0` and `y1` but not `x0` and `x1`.

**Comment by alb-erandelcastillo** [comment] 2019-10-02 15:55
> > This ticket is essentially the sankey version of the more general: #4139
> 
> It is but in the case of Sankey it's not just documentation that needs improvements: Sankey's `node.hovertemplate` exposes `y0` and `y1` but not `x0` and `x1`.

I was able to successfully call 'x0' and 'x1' in the 'node.hovertemplate'.

**Comment by martinzuba** [comment] 2019-11-15 10:37
Is there somewhere I can see what the default hovertemplate code for nodes is? This would help understanding how various info is accessed.

**Comment by gvwilson** [comment] 2024-06-14 12:52
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-14 12:52 UTC
Labels: type: documentation
