### ISSUE TITLE
Scattered3D plot loads cpu and memory up to total system freeze

### ISSUE THREAD

**Issue by kelegorm** [plotly/plotly.js#1525] opened 2017-03-29 16:42 UTC
Example: https://codepen.io/anon/pen/VpVLMN
OS X, Win 10, Chrome.

How to reproduce: run example by link above and wait some time(10-30min). While wait open a Chrome's task manager to look how many memory and cpu browser tab with example takes.

It's not usual memory leaks, it is a memory rage. Default, minimal memory is ~150Mb. Then it grows up to 170 by few seconds, then drops to default, after garbage collector have done it's  job. Max memory level grows too, I have seen tab takes more than 1Gb (comment out marker and colors in example to get 1Gb fast).

When job for GB is becoming bigger, it takes more CPU, up to 100% on my mac.

It's not a problem when you need to show charts just for few minutes, nobody notice. But for dashboards it's crutical bug.

If something isn't clear, ask me.

**Comment by rreusser** [comment] 2017-03-29 18:43
Have you edited and re-saved the codepen? It looks like most of it is commented out. I just want to be sure we're looking at the same thing.

**Comment by kelegorm** [comment] 2017-03-29 19:48
Yes, I have tried comment different things, may be they affects problem somehow. So, they just makes leaks faster.

At last time I have left it with x,y,z data only.

**Comment by rreusser** [comment] 2017-03-29 20:52
I'm not currently able to reproduce it, and I'm not sure I fully understand exactly the scenario that leads to the memory leak. I certainly would be believe there could be a memory leak, but when I run the above codepen it just sits idle. In the four minutes after the initial plot, it allocates about 700kb of memory, mostly after clicking the animate button (which to be clear just runs an action once and then does nothing further) and a bit more when moving the mouse a bit. I'm running Chrome 56.0 on Mac OS X.

The memory profile I see for that plot:

<img width="606" alt="screen shot 2017-03-29 at 16 36 12" src="https://cloud.githubusercontent.com/assets/572717/24475453/de2d8e52-149d-11e7-9808-d280e11c6c4e.png">

If possible, could you profile memory usage and confirm that it's what happens when you run the codepen with exactly the parts commented as are currently saved in that pen?

I believe there's been an effort to stamp out memory leaks in the gl code, so to anticipate what might be the problem here, one small note on animations is that if you keep adding frames, they will persist in memory. 

You don't need to add frames in order to animate though.The [python documentation for animations](https://plot.ly/python/animations/#defining-button-arguments) has [a nice tablehttps://plot.ly/python/animations/#defining-button-arguments) on the arguments for animations. [Here's a corresponding javascript example](https://plot.ly/javascript/animations/#animating-many-frames-quickly). The important thing to note is that if the changes are ephemeral (i.e. if you don't need to retain all named frames in memory permanently), then you can use the alternate inline syntax. That is, instead of writing

```javascript
Plotly.addFrames('graph', [{name: 'foo', data: {data: [...], layout: {...}}}])
Plotly.animate('graph', ['foo'])
```

You can simply write:

```javascript
Plotly.animate('graph', [{name: 'foo', data: {data: [...], layout: {...}}}])
```

The behavior is identical, except the second doesn't store a frame in memory that can be referenced by name. I'll add a note to the docs that makes this distinction slightly clearer.

(One last note: Regarding the usage of `deleteFrames`, I've filed what I think could be considered a bug (missing feature?) here: #1528 )

**Comment by kelegorm** [comment] 2017-03-29 21:56
I've recorded a video for you about that problem, I hope you can take a look (stupid flash player :)). If you won't be able to reproduce, can you tell me what to do else to show you problem.

**Comment by rreusser** [comment] 2017-03-29 21:59
The main thing I don't understand is that from the codepen, it sounds like this has nothing to do with animation since there's only a single animate call that runs once and then does nothing further. If that's the case, then this would probably still be an issue with a static gl3d plot. Do you see a memory leak on gl3d plots that are just sitting there not doing anything?

**Comment by kelegorm** [comment] 2017-03-30 08:09
No. I didn't use animation function at all. Yes, problem is with static 3d plot. My video is showing exactly memory leaks when nothing is happening,

**Comment by kelegorm** [comment] 2017-03-30 11:02
Sorry, I forgot left a link to video. I recorder one new instead, take a look: [video](https://screencast.com/t/gXzEh0vg9dSS)
Example from video: [here](https://codepen.io/kelegorm/pen/jBQpwz).

**Comment by rreusser** [comment] 2017-03-30 12:50
Thanks for the extra info. I don't happen to have flash player installed, and to be honest I'm not sure a video is the most effective way to understand it. If possible, could you provide a minimal codepen that reproduces it and a screenshot of the profiler that indicates the memory leak? By minimal, I mean exactly the code corresponding to the profiled memory leak and with no commented code. Thanks!

**Comment by kelegorm** [comment] 2017-03-30 15:33
Summary time:
![screen shot 2017-03-30 at 18 27 26](https://cloud.githubusercontent.com/assets/479866/24512285/cf9478ae-1576-11e7-98b2-6eadc7dd9459.png)

Overall snapshot:
![screen shot 2017-03-30 at 18 26 43](https://cloud.githubusercontent.com/assets/479866/24512286/cf9509c2-1576-11e7-864b-971042ef53c7.png)

Some period with big load:
![screen shot 2017-03-30 at 18 28 49](https://cloud.githubusercontent.com/assets/479866/24512287/cf99c96c-1576-11e7-9b08-8e2ea8d9b3e8.png)

JS Code tree:
![screen shot 2017-03-30 at 18 27 12](https://cloud.githubusercontent.com/assets/479866/24512284/cf923f58-1576-11e7-86bd-60e96a51eab4.png)

Example on codepen: [here](https://codepen.io/kelegorm/pen/jBQpwz)

**Comment by etpinard** [comment] 2017-03-30 16:06
@kelegorm thanks very much for this report.

If you're interested, it would be helpful for us to see if the same large memory fluxes are happenning for other 3d trace types: `surface` and `mesh3d`.

@dfcreative any thoughts on how to reduce these memory fluxes?

**Comment by rreusser** [comment] 2017-03-30 16:16
Might be obvious to those who know the code better, but I track the raf down to [gl-plot3d](https://github.com/gl-vis/gl-plot3d/blob/master/scene.js#L749) which seems to allocate about 1.5MB on the js heap per raf. All I can think of is to 🔪 large sections of that file one at a time to get a better sense for whether it's evenly distributed throughout or whether there's a hotspot that's doing something problematic.

**Comment by dfcreative** [comment] 2017-03-31 00:48
Chrome task manager draws larger and larger memory variance with very slowly increasing average, and it happens in relation with raf - inactive tab preserves the same amount of memory. It seems not depend on the input data size.
It feels like there is more and more memory required for `redraw` method with the time, though that is effectively collected every time, so the heap just increases or so.
One fast-made possible solution is redrawing only at some events rather than every frame (as used in _gl-waveform_). That would postpone the problem to indefinite time though.

**Comment by rreusser** [comment] 2017-03-31 01:09
With little knowledge of the particular code, I'd be willing to bet it's something like an 80/20 or 90/10 distribution of code causing lots of GC. That is, can probably pick of some low hanging fruit, but it's a matter of degrees since there will always be plenty to GC. A quick survey of the source might be nice.

It's not clear to me this actually leaks memory though, so I'm maybe a bit more interested in: 1) does the raf on a static plot *leak* memory? and 2) if not, then what *is* causing the leak.

**Comment by dfcreative** [comment] 2017-03-31 03:06
@rreusser I def see increase in background chrome window, but once I hover it GC triggers and cleans to static low value

**Comment by kelegorm** [comment] 2017-03-31 06:13
@dfcreative As I could see, browser tab should be present on the screen. If you switch tab or minimize browser - it's calm down, memory goes to it's lower level, cpu load - too.

I guess It depends on input data. The more data you put - the faster max level grows.

I'm not sure what is a more bug - leaks or cpu load, but for sure in some time cpu problem becomes a bad problem. Specially, if chart is using on thin client like iPad, mounted on a wall.

**Comment by kelegorm** [comment] 2017-03-31 16:03
May be this is same issue: https://community.plot.ly/t/how-to-kill-plotly/3802

**Comment by dfcreative** [comment] 2017-03-31 17:46
Ran [gl-plot3d/example/scatter](https://github.com/gl-vis/gl-plot3d/blob/master/example/scatter.js) for 1.5h. Memory consumption increased twice or more.
![image](https://cloud.githubusercontent.com/assets/300067/24560367/81a40c1e-1610-11e7-8cd7-bea04110eb09.png)
↑ started from around 17,000K

But looking at heap allocation timeline there is no signs of not-retained memory. 
![image](https://cloud.githubusercontent.com/assets/300067/24560664/91d1a604-1611-11e7-9db3-d1b56d960e95.png). Although constant reallocation does not look sane, considering static render.

Should note also that CPU load is not the less important, 15% idle load is annoying, my laptop started overheating after half an hour.

I would try to focus on reducing CPU load at first.

**Comment by rreusser** [comment] 2017-03-31 18:36
The breakdown, IMO:

1. Re: cpu usage. 👍  Would be great to have better dirty flags that avoid redrawing when static.
2. Re: static plot: I'm still not quite satisfied with the answer to whether a static plot allocates memory until the computer freezes. That would be surprising to me since the only obvious way for that to happen is either plotly retaining lots of references (which should be obvious because those references have to *go* somewhere, right?) or a browser-level memory leak (which seems unlikely though not impossible). As pointed out, fixing (1) would only delay the inevitable.
3. Re: computer freezing: If a static plot doesn't crash the computer, then I'm suspicious that the animation API might leak memory, whether internally/accidentally or through incorrect usage of the api that should be better communicated (as described above).

Fixing (1) would be great, but I wouldn't consider it an effective way to address (2) or (3). IMO next is to nail down (2).

**Comment by dfcreative** [comment] 2017-03-31 20:21
Sometimes there are uncollected allocations inside 3d-view-controls. Possibly leak.
![image](https://cloud.githubusercontent.com/assets/300067/24567984/06e77dbc-162e-11e7-9b57-b6647853fc92.png)

**Comment by dfcreative** [comment] 2017-03-31 21:00
So turns out [there](https://github.com/mikolalysenko/matrix-camera-controller/pull/1/files) is a typo.

**Comment by kelegorm** [comment] 2017-04-03 13:01
@rreusser, as I can see it's not strictly leaks, but something like that. there is two problems.
1. Static 3D plot cause intensive memory usage. But garbage collector works perfectly. Just through time plot gets more and more memory. But thankfully GB frees all that memory. I saw usage over 1Gb less in half of hour. But it is not big deal except next case.
2. CPU usage. When memory is allocated and then frees, it making job for CPU. And the bigger memory - the bigger job. So, when it comes to 1Gb CPU is loaded a lot.

About computer lags. It's just about CPU used a lot so it cause performance problems in all other applications.

**Comment by kelegorm** [comment] 2017-04-06 20:43
@dfcreative PR #2 is merged.

**Comment by dfcreative** [comment] 2017-04-06 21:04
Merged and published both gl-plot3d and matrix-camera-controller.

**Comment by kelegorm** [comment] 2017-04-07 13:40
I have tested with updated gl-plot3d 1.5.4, bug is really fixed! Thank you, guys! When is milestone release?

**Comment by cpsievert** [comment] 2017-04-07 15:25
> it would be helpful for us to see if the same large memory fluxes are happenning for other 3d trace types: surface and mesh3d.

Not totally sure if this is relevant, but -- https://github.com/ropensci/plotly/issues/483

Also, a bit off topic, as this seems to apply to all trace types, but there seems to be some issues around selfcontained HTML via pandoc -- https://github.com/ropensci/plotly/issues/721

**Comment by rreusser** [comment] 2017-04-07 16:42
@cpsievert yeah something is definitely up. Firefox just screeches to a halt in a way that makes it difficult to debug. Not sure how releases work, but I get `Plotly.version = "1.6.1"`. Seems the first thing might be to confirm whether it's the case with more recent plotly.js. It doesn't quite seem consistent with the slow, small (is it always small?) memory leak observed here though.

Also a small note that https://github.com/plotly/plotly.js/issues/1445 is very likely not relevant here.

**Closed** 2017-04-07 22:32 UTC
Labels: type: performance
