### ISSUE TITLE
Scattergl error bars not correctly place when using log scale axes

### ISSUE THREAD

**Issue by sfletc** [plotly/plotly.js#1881] opened 2017-07-14 00:05 UTC
X and Y error bares are correctly place in plotly scatter plots.

![newplot 5](https://user-images.githubusercontent.com/5491692/28192772-acbeb5da-687b-11e7-9ec2-a48aec2a8b69.png)

Same code - go.Scattergl swapped for go.Scatter - presumably a bug

![newplot 4](https://user-images.githubusercontent.com/5491692/28192680-1655d6c8-687b-11e7-8433-7d9caefc64c0.png)

**Comment by etpinard** [comment] 2017-07-14 14:15
Thanks for the report. 

As per our contributing guidelines, would you mind sharing a reproducible example?

**Comment by etpinard** [comment] 2017-07-14 18:12
https://codepen.io/etpinard/pen/ZyPrEM seems to be enough to reproduce the bug.

**Comment by etpinard** [comment] 2017-12-08 20:38
cc @dfcreative

**Comment by etpinard** [comment] 2018-01-08 18:54
This issue is **NOT** fixed on @dfcreative regl-based `scattergl` branch:

![image](https://user-images.githubusercontent.com/6675409/34686998-666affbc-f47b-11e7-914f-b893343b31f7.png)

---

@dfcreative this issue isn't a blocker for the regl release, but would be nice to fix if you have the time.

**Comment by dfcreative** [comment] 2018-01-16 11:29
Fixed in a54e70d04f1207a98bdb7d9b95b14e24eb4eb31b and added mock in https://github.com/plotly/plotly.js/commit/c6856d0b84a0a4911285afcbaf1dd5dd1c200ad4

**Comment by etpinard** [comment] 2018-01-18 22:01
fixed with https://github.com/plotly/plotly.js/pull/2258

**Closed by etpinard** 2018-01-18 22:01 UTC
Labels: type: bug
