### ISSUE TITLE
Can't export a 50m choropleth as SVG in Chrome but a 110m map works fine

### ISSUE THREAD

**Issue by Thlayli** [plotly/plotly.js#3919] opened 2019-05-28 17:20 UTC
I've tested this running Chrome 74.0.3729.169 (64-bit) and Firefox 64.0.2 (64-bit) on Windows 10.

It looks like something silently fails when using Plotly.downloadImage to get an SVG of a 50m resolution choropleth in Chrome. It works in Firefox. 

To test this I'm making two plots of the same data. One at 110 resolution and one at 50. I then try to save both plots as PNG then SVG. Only the PNG file saves for the 50m map in Chrome, but both save for the 110m. All four images save in Firefox. No errors are generated (except the ones related to my failed understanding of the promise chain, which don't seem to affect anything.)

Could it be due to the file size? 

https://codepen.io/Thlayli/pen/LoBgaZ

**Comment by etpinard** [comment] 2019-05-28 17:32
Probably a duplicate of https://github.com/plotly/plotly.js/issues/3771

Thanks for the report!

**Comment by etpinard** [comment] 2019-05-29 18:20
Merged into https://github.com/plotly/plotly.js/issues/3771

**Closed by etpinard** 2019-05-29 18:20 UTC
