### ISSUE TITLE
polar plot legend bug

### ISSUE THREAD

**Issue by djkashtan** [plotly/plotly.js#95] opened 2015-12-09 20:20 UTC
I get extraneous items in my legend if I have less than three datasets. I have a codepen example that demonstrates it.

Codepen example

If you change line 61 to:

var data = [trace1,trace2,trace3,trace4,trace5];
then you will see that the legend has no extraneous entries. I have been wrestling with this for a while but I am stumped :(

**Comment by etpinard** [comment] 2015-12-15 15:04
From v1.0.0 release [notes](https://github.com/plotly/plotly.js/releases/tag/v1.0.0): 

> Polar charts are under-developed.

**Comment by TCAllen07** [comment] 2016-09-23 19:28
Likely duplicate of [#592](https://github.com/plotly/plotly.js/issues/592)

**Comment by etpinard** [comment] 2018-01-16 22:38
fixed in `scatterpolar` after #2200

**Closed by etpinard** 2018-01-16 22:38 UTC
