### ISSUE TITLE
Odd, random changes to scattergl point color, size and visibility

### ISSUE THREAD

**Issue by brian428** [plotly/plotly.js#2890] opened 2018-08-09 19:21 UTC
We're seeing random changes to scattergl point color and size. I've set up a JSFiddle to demonstrate the problem at: http://jsfiddle.net/brian428/21t3v6xs/

(Edit: I should have noted that this is using plotly-latest, currently 1.39.4.)

As you zoom into the plot, you will see the points with circle symbols randomly turn black (they are configured to be blue), randomly drop to 1px in size (they're configured to be 9 pixels), and some points randomly disappearing.

Here are some screenshots that also show off the problem. Which problem you see seems to be random, so you can zoom in and out (I'm using the mouse selection zoom), reset the axes, and autoscale the axes to see the different problems at different times.

Circles that should be blue are black:
![black_circles](https://user-images.githubusercontent.com/140338/43920632-7a264dc2-9be7-11e8-8e32-6e9258c0bd2b.png)
 
Circles that should be 9px are 1px :
![1px_circles](https://user-images.githubusercontent.com/140338/43920672-9440086a-9be7-11e8-901d-63b760ffe78a.png)

Also probably related, missing some blue square points:
![missing_squares](https://user-images.githubusercontent.com/140338/43921033-96290702-9be8-11e8-9678-eba8473b0bb1.png)

**Comment by etpinard** [comment] 2018-08-09 22:17
Thanks for the report!

**Comment by brian428** [comment] 2018-09-17 13:27
Actually, looks like the coloring may be fixed, but I'm still seeing some oddness with the point size changing. I'll try it further and post an update shortly.

**Comment by etpinard** [comment] 2018-09-17 13:40
>  Is there a way to link to an older version of Plotly using https://cdn.plot.ly?

- https://cdn.plot.ly/plotly-1.40.0.min.js

**Comment by etpinard** [comment] 2018-10-05 16:59
Closing (for now) due to lack of reproducible example.

**Closed by etpinard** 2018-10-05 16:59 UTC
Labels: type: bug
