### ISSUE TITLE
subplots webgl bug

### ISSUE THREAD

**Issue by jackparmer** [plotly/plotly.js#1846] opened 2017-07-04 16:01 UTC
Tried to make a 5 X 7 scattergl subplot and some of the subplot panels are hidden:

https://plot.ly/~jackp/17617/#plot

![image](https://user-images.githubusercontent.com/1865834/27836940-b245ac58-60af-11e7-9608-572e0c8ec3cf.png)

The SVG version works and the "missing data" sometimes flickers on hover in the GL version. Also if you toggle the legend items you can get the missing panels to redraw and show up:

![image](https://user-images.githubusercontent.com/1865834/27837065-400735a2-60b0-11e7-81a0-b34d3685ef58.png)

Apologies if this is already a know issue, I couldn't find it anywhere.

Maybe large `scattergl` subplot trellises should be one of the image tests. 

@alishobeiri has a nice Dash app where you can play with different GL subplot layouts:

https://dash-diamonds-explorer.herokuapp.com/

**Comment by etpinard** [comment] 2017-07-04 16:02
probably a duplicate of https://github.com/plotly/plotly.js/issues/1680

**Comment by jackparmer** [comment] 2017-07-04 16:12
Ahhhh... Looks like it's related to this:
![image](https://user-images.githubusercontent.com/1865834/27837369-d0e50896-60b1-11e7-8809-36912e361be2.png)

If so, probably won't be a fix until the great regl migration: 
https://github.com/plotly/plotly.js/issues/949  😑

**Comment by etpinard** [comment] 2018-01-08 20:13
Looking sharp with @dfcreative 's regl-based `scattergl`

![image](https://user-images.githubusercontent.com/6675409/34690256-69ad72d0-f486-11e7-88a2-ddabf1423fc8.png)

**Comment by dfcreative** [comment] 2018-01-16 13:18
https://github.com/plotly/plotly.js/commit/72cc1a3958d60be1efbdc610115facce06acb1d6 adds test mock:

![image](https://user-images.githubusercontent.com/300067/34990903-ce544756-fad8-11e7-8dc3-fc31a5e2d202.png)

(pretty impressed how performant it is)

**Comment by etpinard** [comment] 2018-01-16 15:50
> (pretty impressed how performant it is)

Yep me too. Solid performance cc @jackparmer

**Comment by etpinard** [comment] 2018-01-18 22:02
I'm really happy about this one.

Done in -> https://github.com/plotly/plotly.js/pull/2258

**Closed by etpinard** 2018-01-18 22:02 UTC
Labels: type: bug
