### ISSUE TITLE
Keep ticks while sharing axes in subplots

### ISSUE THREAD

**Issue by SebsterG** [plotly/plotly.js#2772] opened 2018-07-04 12:41 UTC
This has been flagged twice in community: https://community.plot.ly/t/maintain-ticks-on-shared-axes/9343 , https://community.plot.ly/t/show-shared-axis-in-all-subplots/3696

When making subplots and sharing axes the ticks are removed from all but one axes in the subplots, example:

```
fig = tools.make_subplots(rows=2, cols=1, 
                          shared_xaxes=False/True)**, shared_yaxes=True,
                          subplot_titles=('First Subplot','Second Subplot'))

trace = go.Scatter(x=[1,2,3], y=[2,1,2])
trace2 = go.Scatter(x=[1,2,3], y=[4,0,2])

fig.append_trace(trace, col=1, row=1)
fig.append_trace(trace2, col=1, row=2)

offline.iplot(fig)
```

![newplot 1](https://user-images.githubusercontent.com/13782339/42277377-70072b98-7f97-11e8-9bf2-1153b36fcaca.png)
![newplot](https://user-images.githubusercontent.com/13782339/42277378-702ab2f2-7f97-11e8-8390-42c27020ba33.png)

I would be great to share axes and have axis ticks in all of the subplots.

**Comment by etpinard** [comment] 2018-07-04 13:04
duplicate of https://github.com/plotly/plotly.js/issues/2539

**Closed by etpinard** 2018-07-04 13:04 UTC

**Comment by yiliu-coding** [comment] 2022-10-04 19:57
Have you solved this problem, I now have the same need. Thanks in advance.
