### ISSUE TITLE
feature: let `marker.color` accept an array of categories

### ISSUE THREAD

**Issue by n-riesco** [plotly/plotly.js#2795] opened 2018-07-09 20:22 UTC
For example, see [here](https://community.plot.ly/t/cant-color-based-on-column-value/11602) a user that wants to create a scatter plot of `count` vs `date` coloured by by `host`.

If `host` was a numeric variable, then, the default `cmax`, `cmin` and `colorscale` would be used.

**Comment by etpinard** [comment] 2018-07-09 20:28
Probably a duplicate of https://github.com/plotly/plotly.js/issues/1747

**Comment by etpinard** [comment] 2018-07-10 15:32
Merging with #1747

**Closed by etpinard** 2018-07-10 15:32 UTC
