### ISSUE TITLE
histogram2dcontour with heatmap coloring loses color on responsive resize

### ISSUE THREAD

**Issue by jonmmease** [plotly/plotly.js#3894] opened 2019-05-23 10:34 UTC
Originally reported in https://github.com/plotly/plotly.py/issues/1573

When a `histogram2dcontour` trace with `contour.coloring: 'heatmap'` is displayed with a config of `responsive: true`, it loses its coloring on resize.

CodePen: https://codepen.io/jonmmease/pen/KLQWOO?editors=1010

```javascript
var x = [0, 1, 1];
var y = [0, 1, 1];

var data = [
  {
    x: x,
    y: y,
    type: 'histogram2dcontour',
    contours: {coloring: 'heatmap'}
  }
];
Plotly.newPlot('graph', data, {}, {responsive:true}); 
```
![histogram2dcontour_coloring](https://user-images.githubusercontent.com/15064365/58246332-c5108680-7d24-11e9-92f8-75f96aa08669.gif)

**Comment by etpinard** [comment] 2019-05-23 14:02
Fixed in `master` https://codepen.io/etpinard/pen/RmQMrz?editors=1010

Duplicate of https://github.com/plotly/plotly.js/issues/3858

**Closed by etpinard** 2019-05-23 14:02 UTC
