### ISSUE TITLE
Small plot height causes hover text not display

### ISSUE THREAD

**Issue by colinfang** [plotly/plotly.js#1936] opened 2017-08-07 15:43 UTC
If there are many lines in a hover text, small plot height causes hover text not display.

The hover text has a bigger chance to display if the marker is on the lower part in the plot.

https://codepen.io/anon/pen/JyWjYv

```javascript
var data =
{
    "x": [1, 2, 3],
    "y": [2, 1, 3],
    "text": 'foo</br>foo</br>foo</br>foo</br>foo</br>foo</br>foo</br>',
};

var layout =
{
  'height': 300,
};

Plotly.plot('graph', [data], layout);
```

**Comment by etpinard** [comment] 2017-08-07 15:58
duplicate of https://github.com/plotly/plotly.js/issues/527

**Closed by etpinard** 2017-08-07 15:58 UTC
