### ISSUE TITLE
sankey: clicking on nodes do not fire click events in Chrome

### ISSUE THREAD

**Issue by antoinerg** [plotly/plotly.js#3297] opened 2018-11-28 19:05 UTC
As shown in Codepen https://codepen.io/anon/pen/pQxZem

**Comment by antoinerg** [comment] 2018-12-03 22:55
The Codepen above actually works in Firefox but fails on Chromium Version 69.0.3497.100 (Developer Build) (64-bit) on Linux.

Can anybody reproduce the bug I'm seeing? Basicaly, in the Codepen https://codepen.io/anon/pen/pQxZem, clicking on a node doesn't increase the counter. Clicking links is working however :thinking:

**Comment by etpinard** [comment] 2018-12-03 22:59
Fails on Chrome 70, works ok in FF63

**Comment by Braintelligence** [comment] 2018-12-20 10:03
- MS Edge (EdgeHTML engine) 42.17134.1.0 :heavy_check_mark: 
- FireFox 64.0 :heavy_check_mark: 
- Chrome 71.0.3578.98 :heavy_check_mark: 

Everything works for me.

**Comment by kebabhans** [comment] 2020-10-09 14:37
I experience the same issue in Chrome, Edge (Chromium), but not in Internet Explorer. 
Is there a potential work-around for this (such that I can both drag nodes around, but also trigger a function on clicks)?

**Comment by gvwilson** [comment] 2024-06-11 17:36
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson

**Closed by gvwilson** 2024-06-11 17:36 UTC
Labels: type: bug
