### ISSUE TITLE
Image not showing in Edge (but Chrome) when xaxis is Date type with values as timestamp

### ISSUE THREAD

**Issue by phungthien** [plotly/plotly.js#4452] opened 2019-12-30 11:02 UTC
Hi team,

I was trying to display an image in the chart with XAxis is date type, the input values of xaxis is timestamp value and the image is pushed with the following code.

My code was written in Angular and the `timestamp` value was calculated using `new Date().getTime();`

I'm not sure why this is working in Chrome but Edge.

 
```
this.plotly.chartLayout.images.push({
             x: timestamp,
             y: 1,
             xref: 'x',
             yref: 'paper',
             xanchor: 'left',
             yanchor: 'top',
             sizex: timestamp,
             sizey: 1,
             layer: 'above',
             sizing: 'contain',
             source: 'assets/icons/FlagPole.jpg',
});
```

**Comment by antoinerg** [comment] 2019-12-31 01:02
Hello @phungthien, thanks for reporting this issue. Could you provide us with a Codepen reproducing the issue?

**Comment by phungthien** [comment] 2019-12-31 03:07
> Codepen

Hi @antoinerg, here is the Codepen to reproduce the issue. As you can see in Chrome, the Matlab icon is plotted in the chart but it's not working in Edge.

https://codepen.io/phungthien07/pen/YzPrpjo?editors=0010

**Comment by phungthien** [comment] 2020-01-02 03:38
Hi @antoinerg, has the team had a chance to look at the issue yet?

**Comment by antoinerg** [comment] 2020-01-02 16:55
Hi @phungthien, not in detail yet. I could confirm that it happens in Edge but I haven't time to find out why and come up with a fix.

**Comment by antoinerg** [comment] 2020-01-03 19:31
@phungthien Upon second inspection, the problem you see in Edge arises from the huge `sizex`. Changing it to say `20` gives: https://codepen.io/antoinerg/pen/LYEOmRN?editors=0010 which shows the logo in both Edge and Chrome.

**Comment by antoinerg** [comment] 2020-01-06 18:17
I think we can close this one since it's not clear there really is an issue with Edge (as shown in https://github.com/plotly/plotly.js/issues/4452#issuecomment-570674460).

**Closed by antoinerg** 2020-01-06 18:17 UTC
Labels: type: bug

**Comment by phungthien** [comment] 2020-01-07 09:59
> @phungthien Upon second inspection, the problem you see in Edge arises from the huge `sizex`. Changing it to say `20` gives: https://codepen.io/antoinerg/pen/LYEOmRN?editors=0010 which shows the logo in both Edge and Chrome.

So it looks like I set a wrong value of sizex property. Can you advise of how I can calculate the correct number of this property?
