### ISSUE TITLE
Filled line option for error_y

### ISSUE THREAD

**Issue by lucgiffon** [plotly/plotly.js#4702] opened 2020-03-22 14:24 UTC
Hello, thank you for plotly.py it is a life changing library compared to pyplot from matplotlib.

Feature request:

I think that allowing us to pass argument `filled=True` argument inside the `error_y` attribute of `go.Scatter` would be very handy. 

Indeed, I often make use of error bars in my plot but sometimes I want it to be simple [error bars](https://plot.ly/python/error-bars/) and sometimes I want to have a ["ribbon-like" design](https://plot.ly/python/line-charts/#filled-lines). I feel it weird that the two behaviors are so different to implement and I believe a simple boolean option would be nice. Also, it seems to me that having Filled lines is pretty difficult and obscure to implement compared to everything in plotly.

See you
Luc

**Comment by gvwilson** [comment] 2024-06-14 13:01
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-14 13:01 UTC
