### ISSUE TITLE
(3-D) Get datapoints in currently zoomed view (3-D)

### ISSUE THREAD

**Issue by AniWar** [plotly/plotly.js#3981] opened 2019-06-25 09:05 UTC
Hi ,
Is there any way I can get data points info when I zoom into 3-D Scatter plots .
Like when I zoom in , if I can get handle of some object which can help know how many data points are present in current view/scene .

Relayout gives me handle of camera object , I tried altering the return (in library file) and sent the whole object instead of just ‘camera’ , but no joy .

Thanks .

**Comment by etpinard** [comment] 2019-06-25 13:55
Duplicate of https://community.plot.ly/t/3-d-get-datapoints-in-currently-zoomed-view-3-d/24966

**Closed by etpinard** 2019-06-25 13:55 UTC
