### ISSUE TITLE
Trace legend error on Bar chart when updating color of first bar

### ISSUE THREAD

**Issue by r1z1a** [plotly/plotly.js#1634] opened 2017-04-28 08:45 UTC
I have hit an issue, I can recolor a single bar for multiple traces, the problem arises when you recolor the first bar, it seems to make whole legend that one color.
EDIT: Added Some code to show, the variable is passed in which corresponds to single x value, colors sets new array of color for each trace.

Feels like the legend is working of the color for first element in the trace, in my case in first element there is '0' value bars, but I made a test with 0 on second bar, and tested a bar that is not part of all traces, (where some trace value for bar is null) Show here
![plotlybar1](https://cloud.githubusercontent.com/assets/14272971/25430427/e94f39da-2a7c-11e7-83c1-2fe26715099e.png)
![plotlybar3](https://cloud.githubusercontent.com/assets/14272971/25430428/e94f627a-2a7c-11e7-932d-577d296e0d5c.png)
![plotlybar2](https://cloud.githubusercontent.com/assets/14272971/25430426/e94e962e-2a7c-11e7-8336-389a007198b5.png)

```
     for (var j = 0; j < plotDiv.data.length; j++) {
        var colors = plotDiv.data[j].marker.color;
        for (var i = 0; i < plotDiv.data[j].x.length; i++) {
          if (plotDiv.data[j].x[i].indexOf(variable)===1) {
            colors[i]='red';
          }
        }
        Plotly.restyle(plotDiv, {'marker':{color: colors}}, [j]);
      }
```

**Comment by etpinard** [comment] 2017-04-28 14:15
I think this is a duplicate of https://github.com/plotly/plotly.js/issues/1560 

Can you share a fully reproducible example, with data array and all to help us confirm? Thanks.

**Comment by r1z1a** [comment] 2017-04-28 17:29
Here is simplified example that i just made for you, wrote it real quick, but i think the idea should be the same :)
[Codepen](https://codepen.io/anon/pen/QvpQzG?editors=0010)

The issue here is not that it makes a legend per trace, that's exactly what I expect and need.

It feels like the colors of the legend traces are derived from the first bar per each trace, so when I restyle them, the legend gets re-styled too
An Ideal would be to store legend color when you first time plot it and pass data in, and after that the restyle shouldn't take effect if you are re-styling just single bars. 

Although I can see an issue that if some one needs to re-style whole trace then it wouldn't update that trace legend color. This is possibly the problem since there seems to be a lot of issues to just change color of one element in a trace, you have to update whole trace, which can be rather hard process when you have like 10+ traces each with 100+ bars.

**Comment by alexcjohnson** [comment] 2017-05-04 07:40
Yes, definitely duplicate of #1560 - lets continue this discussion over there.

**Closed by alexcjohnson** 2017-05-04 07:40 UTC
