### ISSUE TITLE
Allow PDF and SVG download

### ISSUE THREAD

**Issue by yichaoS** [plotly/plotly.js#156] opened 2016-01-04 16:22 UTC
Right now there's only a "download as png" button in the hidden mode bar. Maybe it could be good if we could add the PDF and SVG download options? Thanks. Yichao

**Comment by etpinard** [comment] 2016-01-04 16:31
Marked as duplicate of https://github.com/plotly/plotly.js/issues/83

**Comment by etpinard** [comment] 2016-01-26 23:27
closed in favour of #83

**Closed by etpinard** 2016-01-26 23:27 UTC
Labels: duplicate
