### ISSUE TITLE
webgl dashed lines don't display correctly

### ISSUE THREAD

**Issue by dsmmcken** [plotly/plotly.js#2946] opened 2018-08-27 19:09 UTC
![screen shot 2018-08-27 at 2 49 39 pm](https://user-images.githubusercontent.com/1576283/44679253-7ab5df80-aa08-11e8-92b9-51afa0f4e739.png)

The blue scattergl dashed line spacing is broken. The dashes are inconsistently spaced.
Orange is the same data as svg for comparison (expected result).

Sample: https://codepen.io/anon/pen/oPxOgJ

Checked in firefox and chrome on mac with similar results.

**Comment by etpinard** [comment] 2018-09-14 14:40
cc @dy

**Comment by dy** [comment] 2018-09-25 15:03
Oh! That is an issue of the old [gl-line2d](https://github.com/gl-vis/gl-line2d) too:
![image](https://user-images.githubusercontent.com/300067/46023456-59bada00-c0ed-11e8-80e0-eab2e738bd76.png)

**Comment by dy** [comment] 2018-09-26 10:55
That seems to be non-trivial to implement fast version of it. A segment pattern offset depends on previous segment's length, which depends on previous segment length etc, ie. patterns are linked.
When it comes to rescaling - every dataRange change we have to recalculate all segments lengths. That is ok for short lines, but heavy for thousands of points.

**Comment by archmoj** [comment] 2018-10-31 13:55
The image below & this [demo](https://codepen.io/MojtabaSamimi/pen/YJoJyM) could be used to illustrate the differences between dash lines in `scatter` & `scattergl`. 
Also to mention when using various line `width` parameters it affects `scattergl` dashes.
![newplot 52](https://user-images.githubusercontent.com/33888540/47792670-e52e1900-dcf2-11e8-9cc5-248ec5b15e7d.png)

**Comment by alexcjohnson** [comment] 2018-10-31 14:10
Since you mentioned line width, if we're truly going for parity check out the logic used in SVG-land, in `Drawing.dashLine`: the length scale of the built-in dash patterns `'dot', 'dash', 'longdash', 'dashdot', 'longdashdot'` is based on `max(lineWidth, 3)`

https://github.com/plotly/plotly.js/blob/f0f9a867ef5f3e155adc24dfd8865f3255dd860f/src/components/drawing/index.js#L168-L185

**Comment by mitja-p** [comment] 2020-01-02 11:20
Is there any progress on this bug? Currently using anything except solid line is pretty unusable in webgl.

**Comment by gvwilson** [comment] 2024-06-11 17:21
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson

**Closed by gvwilson** 2024-06-11 17:21 UTC
Labels: type: bug
