### ISSUE TITLE
Hovertext doesn't display correct text on current point when both points have the same x coordinate

### ISSUE THREAD

**Issue by m2jobe** [plotly/plotly.js#1245] opened 2016-12-11 20:23 UTC
As seen in the image below, when two points have the same x coordinate (in this case -110) the hover text for the first generated point is displayed rather than the correct hover text for said point

<img width="163" alt="screen shot 2016-12-11 at 3 22 42 pm" src="https://cloud.githubusercontent.com/assets/9561974/21083033/b3d8c5dc-bfb5-11e6-8910-51d06d5e7528.png">

**Comment by m2jobe** [comment] 2016-12-11 20:25
when moving the initial point to x coord -100, since they are no longer on the same point we can now  see the correct hover text for the point we were hovering over.
<img width="169" alt="screen shot 2016-12-11 at 3 24 14 pm" src="https://cloud.githubusercontent.com/assets/9561974/21083054/058bb0c4-bfb6-11e6-893d-2ecac721648d.png">

**Comment by etpinard** [comment] 2016-12-11 22:04
Probably duplicate of https://github.com/plotly/plotly.js/issues/720 

Can you share a reproducible codePen / jsFiddle / jsBin example - as per our contributing guidelines.

**Comment by m2jobe** [comment] 2016-12-12 00:52
Hi I was able to solve this by adding  hovermode:'closest' to the layout of the graph

**Closed** 2016-12-12 00:52 UTC
Labels: type: duplicate
