### ISSUE TITLE
Add option to render scattergl charts in Web Worker using OffscreenCanvas

### ISSUE THREAD

**Issue by joshua-gould** [plotly/plotly.js#4623] opened 2020-03-11 13:30 UTC

**Comment by gvwilson** [comment] 2024-06-14 12:59
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-14 12:59 UTC

**Comment by vadimkantorov** [comment] 2025-03-29 10:02
Any advancement here?

In https://plotly.com/python/performance/ OffscreenCanvas is not mentinoed
