### ISSUE TITLE
Rotated & shifted hover labels on bars

### ISSUE THREAD

**Issue by archmoj** [plotly/plotly.js#3838] opened 2019-05-06 21:07 UTC
The hover boxes are not positioned properly on bars.
[Codepen](https://codepen.io/MojtabaSamimi/pen/byNLBj?editors=0010).

![hover](https://user-images.githubusercontent.com/33888540/57254920-85595780-7020-11e9-92fa-c250ce67ab31.gif)

**Comment by gvwilson** [comment] 2024-06-14 11:57
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-14 11:57 UTC
Labels: type: bug
