### ISSUE TITLE
Customize brush color

### ISSUE THREAD

**Issue by basix86** [plotly/plotly.js#2124] opened 2017-10-26 07:57 UTC
Hi, I would want the possibility to change the default appearance of the brush, in particular i would like to change the default color magenta to another one (maybe with some opacity).

Thanks

**Comment by etpinard** [comment] 2017-10-26 13:20
duplicate of https://github.com/plotly/plotly.js/issues/1961

**Closed by etpinard** 2017-10-26 13:20 UTC
