### ISSUE TITLE
y-range and extreme outliers: traces vanish progressively

### ISSUE THREAD

**Issue by czellweg** [plotly/plotly.js#1660] opened 2017-05-10 13:07 UTC
When enabling `yaxis.range` and the data contains extreme outliers, the traces vanish, i.e. they will progressively vanish. See the following codepens that demonstrates this behaviour:

* http://codepen.io/czellweg/pen/rmJvzW (OK)
* http://codepen.io/czellweg/pen/pPaVWj (trace with outlier shown only as markers, no more lines)
* http://codepen.io/czellweg/pen/MmQGEy (all traces gone)

It seems that it depends on the magnitude the outlier is outside the `yaxis.range` values, e.g. if `yaxis.range=[0,20]` and the outlier is 20'000'000, only markers are shown. If `yaxis.range=[0,20]` and the outlier is 2'000'000'000, all traces are gone.

Expected behaviour would be:

* traces are shown, including markers and lines if `markers+lines` has been configured

**Comment by etpinard** [comment] 2017-05-10 14:31
Thanks very much for this report.

Looks like your pens are working ok using `v1.7.0` -> http://codepen.io/etpinard/pen/gWvjBv

I suspect the same issue as in https://github.com/plotly/plotly.js/issues/403 caused by https://github.com/plotly/plotly.js/pull/353 which unfortunately is a little hard to solve as mentioned in https://github.com/plotly/plotly.js/issues/403#issuecomment-247362096

**Comment by czellweg** [comment] 2017-05-11 07:17
Ok, good to know. `v1.7.0` is a bit far back (March 22, 2016) but I will follow the developments on the mentioned issues. Thanks.

**Comment by alexcjohnson** [comment] 2017-10-05 20:05
closed by #2060

**Closed by alexcjohnson** 2017-10-05 20:05 UTC
Labels: type: bug
