### ISSUE TITLE
[Request] Hexagonal heatmap / binning

### ISSUE THREAD

**Issue by mafar** [plotly/plotly.js#4368] opened 2019-11-20 06:57 UTC
**Dear Devs,**
Is it poosible to make [SOM ](https://en.wikipedia.org/wiki/Self-organizing_map)plots in plotly 

https://en.wikipedia.org/wiki/Self-organizing_map

**D3 References :** 
1. https://gist.github.com/nbremer/6052814#file-thumbnail-png
2. http://bl.ocks.org/nbremer/raw/6052681/

**Matlab References :** 
1. https://www.mathworks.com/help/deeplearning/ref/plotsomplanes.html
2. https://www.mathworks.com/help/deeplearning/self-organizing-maps.html?s_tid=CRUX_lftnav

**R References :** 
1. https://www.shanelynn.ie/self-organising-maps-for-customer-segmentation-using-r/
1. https://clarkdatalabs.github.io/soms/SOM_NBA

![thumbnail](https://user-images.githubusercontent.com/4101480/69215938-bcdabc00-0b8c-11ea-9a4b-7983f54020f7.png)

**Comment by alexcjohnson** [comment] 2019-11-20 15:49
My first impression is the "self-organizing" part involves more analysis / nuance / judgment than we want to include in plotly.js - leaving that part to a data preparation step prior to sending us the form to be displayed. But if your question is about adding a hexagonal heatmap / binning variant, that's definitely something we'd consider adding - I've added a comment to this effect to the master "new charts wishlist" issue #2221

**Comment by mafar** [comment] 2019-11-21 05:17
hexagonal heatmap / binning variant  is what needed.
ANd yes I would suggest to keep analysis part separate since it is more scientifc in nature and plotly should not deal with such calculations

**Comment by alexcjohnson** [comment] 2019-11-21 05:47
Great, thanks for clarifying. Updated the title to reflect this.

**Comment by gvwilson** [comment] 2024-06-14 12:53
Hi - we are currently trying to tidy up Plotly's public repositories to help us focus our efforts on things that will help users most. Since this issue has been sitting for several years, I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our backlog. Thanks for your help - @gvwilson

**Closed by gvwilson** 2024-06-14 12:53 UTC
Labels: type: new trace type
